### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

### ISSUE THREAD

**Issue by xiaoheiNLP** [google/jax#16082] opened 2023-05-22 10:12 UTC
Please:

- [ ] Check for duplicate requests.
- [ ] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by hawkinsp** [comment] 2023-05-22 12:58
You have not provided enough information to diagnose the problem.

* What version of `jax` and `jaxlib` do you have and how did you install it?
* What version of CUDA and CUDNN do you have and how did you install them?
* What GPU do you have? Share the output of `nvidia-smi`. Are there any other processes using the same GPU

**Comment by xiaoheiNLP** [comment] 2023-05-24 06:20
Thanks
1.What version of jax and jaxlib do you have and how did you install it?
jax                           0.4.10
jaxlib                        0.4.10+cuda11.cudnn86
whisper-jax                   0.0.1

2.What version of CUDA and CUDNN do you have and how did you install them?
CUDA Version: 11.6
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

What GPU do you have? Share the output of nvidia-smi. Are there any other processes using the same GPU
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:31:00.0 Off |                  N/A |
|  0%   32C    P8    16W / 220W |      5MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:4B:00.0 Off |                  N/A |
|  0%   32C    P8    18W / 220W |      5MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:B1:00.0 Off |                  N/A |
| 30%   31C    P8    27W / 350W |      5MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:CA:00.0 Off |                  N/A |
| 30%   32C    P8    26W / 350W |      5MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by xiaoheiNLP** [comment] 2023-05-24 06:56
> You have not provided enough information to diagnose the problem.
> 
> * What version of `jax` and `jaxlib` do you have and how did you install it?
> * What version of CUDA and CUDNN do you have and how did you install them?
> * What GPU do you have? Share the output of `nvidia-smi`. Are there any other processes using the same GPU

**Comment by jakevdp** [comment] 2023-06-01 08:21
I'm going to close this as a duplicate of #16167. Feel free to re-open if it turns out to be a different issue!

**Closed by jakevdp** 2023-06-01 08:21 UTC
Labels: bug, needs info
