### ISSUE TITLE
take_along_axis with dim > 2 throws IndexError with sharding 

### ISSUE THREAD

**Issue by tran-khoa** [google/jax#17587] opened 2023-09-13 09:31 UTC
### Description

`jax.numpy.take_along_axis` works with sharding on 2D arrays, but throws an IndexError with 3D arrays, e.g.

```python
import jax.numpy as jnp
from jax.experimental import mesh_utils
from jax.sharding import PositionalSharding

sharding = PositionalSharding(mesh_utils.create_device_mesh((4,)))

x = jnp.zeros((4,10))
y = jnp.ones((4,), jnp.int32)
x = jax.device_put(x, sharding.reshape(4, 1))
y = jax.device_put(y, sharding)

out = jnp.take_along_axis(x, y[..., None], -1)
# works as expected: 
# Array([[0.],
#        [0.],
#        [0.],
#        [0.]], dtype=float32)

x2 = jnp.tile(x, (2, 1, 1))
y2 = jnp.tile(y, (2, 1))

out2 = jnp.take_along_axis(x2, y2[..., None], -1)
# throws IndexError, see below

x3 = jax.device_put(x2, jax.devices()[0])
y3 = jax.device_put(y3, jax.devices()[0])

out3 = jnp.take_along_axis(x3, y3[..., None], -1)
# works as expected: 
# Array([[[0.],
#        [0.],
#        [0.],
#        [0.]],
#
#       [[0.],
#        [0.],
#        [0.],
#        [0.]]], dtype=float32)
```

For `out2`, the following exception is thrown.:
```
    [... skipping hidden 14 frame]

File /p/project/jinm60/users/tran4/env_llfs/lib/python3.11/site-packages/jax/_src/dispatch.py:464, in backend_compile(backend, module, options, host_callbacks)
    459   return backend.compile(built_c, compile_options=options,
    460                          host_callbacks=host_callbacks)
    461 # Some backends don't have `host_callbacks` option yet
    462 # TODO(sharadmv): remove this fallback when all backends allow `compile`
    463 # to take in `host_callbacks`
--> 464 return backend.compile(built_c, compile_options=options)

IndexError: `InlinedVector::at(size_type) const` failed bounds check
```

### What jax/jaxlib version are you using?

jax v0.4.14, jaxlib 0.4.14+cuda12.cudnn89

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.11, Rocky Linux 8.8, cf. https://apps.fz-juelich.de/jsc/hps/jureca/configuration.html

### NVIDIA GPU info

```
Wed Sep 13 11:15:39 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          On  | 00000000:03:00.0 Off |                    0 |
| N/A   45C    P0              67W / 400W |  31584MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-40GB          On  | 00000000:44:00.0 Off |                    0 |
| N/A   45C    P0              68W / 400W |  31602MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM4-40GB          On  | 00000000:84:00.0 Off |                    0 |
| N/A   45C    P0              65W / 400W |  31602MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM4-40GB          On  | 00000000:C4:00.0 Off |                    0 |
| N/A   45C    P0              70W / 400W |  31578MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     21742      C   ...60/users/tran4/env_llfs/bin/python3    31566MiB |
|    1   N/A  N/A     21742      C   ...60/users/tran4/env_llfs/bin/python3    31584MiB |
|    2   N/A  N/A     21742      C   ...60/users/tran4/env_llfs/bin/python3    31584MiB |
|    3   N/A  N/A     21742      C   ...60/users/tran4/env_llfs/bin/python3    31560MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by rajasekharporeddy** [comment] 2024-04-19 14:22
Hi @tran-khoa 

Looks like this issue appears to be resolved in later versions of JAX. I tried to reproduce the error with JAX version 0.4.26 on Cloud VM with 4 Tesla T4 GPUs. The code executes without any error and working as expected. Please find the following screenshot for reference.

<img width="883" alt="image" src="https://github.com/google/jax/assets/153593711/a6b2ea75-b6f1-4f28-be38-c2b4d37f5083">
<img width="883" alt="image" src="https://github.com/google/jax/assets/153593711/d11f5266-85ef-40b5-9856-45fbdacbf4d6">

Thank you.

**Comment by jakevdp** [comment] 2024-04-19 17:07
Thanks for following-up!

**Closed by jakevdp** 2024-04-19 17:07 UTC
Labels: bug
