### ISSUE TITLE
Parallel operators fail with >2 GPUs

### ISSUE THREAD

**Issue by EmptyJackson** [google/jax#14560] opened 2023-02-17 17:28 UTC
### Description

Hi, when running parallel operations across more than 2 GPUs, JAX is failing silently. Using the example from the [pmean documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.pmean.html):
```python
>>> import jax
>>> import jax.numpy as jnp
>>> x = jnp.arange(2)
>>> jax.pmap(lambda x: jax.lax.pmean(x, 'i'), axis_name='i')(x)
ShardedDeviceArray([0.5, 0.5], dtype=float32)
>>> y = jnp.arange(3)
>>> jax.pmap(lambda x: jax.lax.pmean(x, 'i'), axis_name='i')(y)
Bus error (core dumped)
```
The same behavior is observed when substituting `pmean` for `psum` or `pmax` (and presumably other parallel operators).

When using `pmap` without parallel operators, the program executes without issue on any number of GPUs.

I've tested this on two servers (1080Ti and 2080Ti) with the same Docker container and replicated the behavior.

Thanks in advance for any help with this!

### What jax/jaxlib version are you using?

jax==0.3.25 jaxlib==0.3.25+cuda11.cudnn82

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.8.10, Ubuntu Docker container

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:04:00.0 Off |                  N/A |
| 28%   33C    P0    59W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:05:00.0 Off |                  N/A |
| 26%   38C    P0    60W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:08:00.0 Off |                  N/A |
| 27%   26C    P0    59W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:09:00.0 Off |                  N/A |
| 27%   32C    P0    62W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce ...  Off  | 00000000:83:00.0 Off |                  N/A |
| 27%   33C    P0    60W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce ...  Off  | 00000000:84:00.0 Off |                  N/A |
| 26%   31C    P0    61W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA GeForce ...  Off  | 00000000:87:00.0 Off |                  N/A |
| 26%   34C    P0    60W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA GeForce ...  Off  | 00000000:88:00.0 Off |                  N/A |
| 23%   31C    P0    61W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by hawkinsp** [comment] 2023-05-19 19:30
Hmm. It looks like this issue was not answered. Sorry about that.

However, all of the versions involved here (e.g. jax 0.3.25) are pretty old, so I think this might well have been fixed by now. Please reopen if you can reproduce this with a current JAX release.

We routinely run JAX tests on multiple GPUs in a docker container in our CI, so my guess is this issue must have something to do with your setup.

One hint is that you need to configure adequate SHM space to the container to use NCCL (multiGPU collectives) under docker. Hope that helps!

**Closed by hawkinsp** 2023-05-19 19:30 UTC
Labels: bug, NVIDIA GPU
