### ISSUE TITLE
jax.lax.scan tries to access empty array

### ISSUE THREAD

**Issue by ThomasMiconi** [google/jax#20399] opened 2024-03-22 19:13 UTC
### Description

Apologies if I'm just very confused.

When `jax.lax.scan(f, init, xs)` is fed an empty array as `xs` and `init`, it will still start the loop, and try to apply the scanning function`f` to the empty carry `init` and non-existent `xs`. Since the carry itself is also empty, this will result in a crash.

```
import jax
import jax.numpy as jnp

def foo(carry, j):
    c=carry.at[j].set(j)
    return c, None

myarray = jnp.array([])                                                                                                                     

carry, _ = jax.lax.scan( foo, myarray, jnp.arange(myarray.shape[0]) )

print(carry)
```

Result:

```
Traceback (most recent call last):
  File "/home/thomas/craftax/Craftax/test.py", line 10, in <module>
    carry, _ = jax.lax.scan( foo, myarray, jnp.arange(myarray.shape[0]) )
  File "/home/thomas/craftax/Craftax/test.py", line 5, in foo
    c=carry.at[j].set(j)
  File "/home/thomas/craftax/craftax/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 490, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "/home/thomas/craftax/craftax/lib/python3.10/site-packages/jax/_src/ops/scatter.py", line 80, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "/home/thomas/craftax/craftax/lib/python3.10/site-packages/jax/_src/ops/scatter.py", line 104, in _scatter_impl
    indexer = jnp._index_to_gather(jnp.shape(x), idx,
  File "/home/thomas/craftax/craftax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4817, in _index_to_gather
    raise IndexError(f"index is out of bounds for axis {x_axis} with size 0")
IndexError: index is out of bounds for axis 0 with size 0

```

The expected behavior is that scanning on an empty array `xs` should do nothing at all. It should not start the loop, should not try to apply the function, and should return the unmodified `init` as carry.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.25
jaxlib: 0.4.25
numpy:  1.26.4
python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
jax.devices (8 total, 8 local): [cuda(id=0) cuda(id=1) ... cuda(id=6) cuda(id=7)]
process_count: 1
platform: uname_result(system='Linux', node='g088.voltagepark.net', release='5.15.0-100-generic', version='#110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024', machine='x86_64')


$ nvidia-smi
Fri Mar 22 18:58:18 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA H100 80GB HBM3          Off | 00000000:19:00.0 Off |                  Off |
| N/A   37C    P0             125W / 700W |   1066MiB / 81559MiB |      1%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          Off | 00000000:3B:00.0 Off |                  Off |
| N/A   30C    P0             115W / 700W |   1066MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          Off | 00000000:4C:00.0 Off |                  Off |
| N/A   28C    P0             117W / 700W |   1066MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          Off | 00000000:5D:00.0 Off |                  Off |
| N/A   35C    P0             120W / 700W |  45292MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA H100 80GB HBM3          Off | 00000000:9B:00.0 Off |                  Off |
| N/A   37C    P0             123W / 700W |  62484MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA H100 80GB HBM3          Off | 00000000:BB:00.0 Off |                  Off |
| N/A   31C    P0             122W / 700W |   1066MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA H100 80GB HBM3          Off | 00000000:CB:00.0 Off |                  Off |
| N/A   34C    P0             122W / 700W |   1066MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA H100 80GB HBM3          Off | 00000000:DB:00.0 Off |                  Off |
| N/A   28C    P0             113W / 700W |   1066MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   1069146      C   python3                                     526MiB |
|    0   N/A  N/A   1169846      C   python3                                     526MiB |
|    1   N/A  N/A   1069146      C   python3                                     526MiB |
|    1   N/A  N/A   1169846      C   python3                                     526MiB |
|    2   N/A  N/A   1069146      C   python3                                     526MiB |
|    2   N/A  N/A   1169846      C   python3                                     526MiB |
|    3   N/A  N/A    852127      C   python                                    44218MiB |
|    3   N/A  N/A   1069146      C   python3                                     526MiB |
|    3   N/A  N/A   1169846      C   python3                                     526MiB |
|    4   N/A  N/A   1069146      C   python3                                   61944MiB |
|    4   N/A  N/A   1169846      C   python3                                     526MiB |
|    5   N/A  N/A   1069146      C   python3                                     526MiB |
|    5   N/A  N/A   1169846      C   python3                                     526MiB |
|    6   N/A  N/A   1069146      C   python3                                     526MiB |
|    6   N/A  N/A   1169846      C   python3                                     526MiB |
|    7   N/A  N/A   1069146      C   python3                                     526MiB |
|    7   N/A  N/A   1169846      C   python3                                     526MiB |
+---------------------------------------------------------------------------------------+

```

**Comment by clemisch** [comment] 2024-03-25 09:50
What would you expect from the code snippet?

**Comment by ThomasMiconi** [comment] 2024-03-25 17:06
Since `myarray` is empty in this case, I would expect it to print `[]`, i.e. the final carry should be identical to `init` (because the scan call would do nothing).

Most importantly I would expect it not to cause an error by trying to start a loop that should not be started. If the array is empty, I would expect it to behave exactly like `for _ in range(0)`.

Note that if `myarray` is any non-empty array, then the snippet currently does the right thing, i.e. print `[0, 1, 2...]` with the same length as `myarray`.

**Comment by mattjj** [comment] 2024-03-26 16:21
Thanks for raising this and fo the thoughtful analysis! I agree.

**Comment by mattjj** [comment] 2024-03-27 00:54
Ah, I just looked more carefully at the code in the OP, and I see the issue: we need to produce some scanned-over output, and to figure out its type we need to be able to stage out the body function. But we can't stage out this body function because there's statically an out-of-bounds error, namely we know statically that `carry.at[j].set(j)` must fail. (Indeed we can see from reading the Python source that the scanned-over output is just `None`, but JAX doesn't read source code; it just gets an opaque Python callable, and can do nothing but run it...)

I think this is working as intended, and there's not much else we can do here other than raise a better error message.

**Comment by mattjj** [comment] 2024-03-27 05:04
I think the best thing to do is to recommend that you write the original code with a fori_loop, since you aren't using the scanned-over inputs or outputs much:

```python
import jax
import jax.numpy as jnp

def foo(j, carry):
  return carry.at[j].set(j)

myarray = jnp.array([])
carry = jax.lax.fori_loop(0, 0, foo, myarray)
print(carry)
```

That would've also crashed from running the body, but #20448 makes it not run anymore.

I realize that your example may have been a distilled toy example, and perhaps in your real one you do want to use scanned-over inputs, or something. But still I think this is our best option, for the reasons mentioned above.

**Comment by ThomasMiconi** [comment] 2024-03-28 19:01
FWIW, the reason for this post is [Craftax](https://github.com/MichaelTMatthews/Craftax/), a 2D Minecraft-like game implemented entirely in Jax.

It has a lot of passages that use `jax.lax.scan` to loop over all enemies / mobs / plants, etc., like this:

```
def _move_zombies(rng_and_state, zombie_index):
    random_move_proposed_position = (
        zombies.position[zombie_index] + random_move_direction
    )
    ...

rng, _rng = jax.random.split(rng)
(rng, new_state), _ = jax.lax.scan(
    _move_zombie, (rng, state), jnp.arange(static_params.max_zombies)
)
```

If you try to set `max_zombies` to 0, this crashes (because `zombies.position` is an empty array but it still tries to access it). I've managed to make it work with a lot of `if` statements. 

If this behaviour is not going to change, maybe it should be specified in the documentation that `scan` should not be applied to empty arrays, at least if the function accesses them?

**Comment by alonfnt** [comment] 2024-03-29 19:02
How is checking if `length == 0` in a `for_loop` different than checking if `len(xs)==0` in a `scan`? Is it the fact that a compiled `scan` does not recompile for different lengths of `xs`? 

Sorry if it is a stupid question, but I was just wondering...

**Comment by mattjj** [comment] 2024-03-29 19:35
@ThomasMiconi super cool project!

> How is checking if length == 0 in a fori_loop different than checking if len(xs)==0 in a scan? Is it the fact that a compiled scan does not recompile for different lengths of xs?

@alonfnt `scan` has to produce empty versions of the scanned-over outputs. That is, if you write `carry, ys = scan(f, carry, xs)` and `xs` have length 0, we still need to produce something for `ys`. To know what to produce, we need to know the output type of `f`: for example, if we had `f = lambda c, x: (c, x)` then we need `ys` to be an empty array that looks just like `xs`, but if we had `f = lambda c, x: (c, (x, x))` then we need `ys` to be a pair like `(xs, xs)`, or if we had `f = lambda c, x: (c, jnp.zeros(3, 'int32'))` then we need `ys` to be something like `jnp.zeros((0, 3), 'int32')`. (In general, 'the output type of `f`' means knowing its pytree structure and the shapes/dtypes of its leaves.)

But `scan` is just given `f`, and has to infer its output type. The only thing we can do (robustly) with a Python callable is run it, so we run it and build a jaxpr for `f`, in the process discovering its output type.

But what if `f` can't be run, e.g.
```python
def f(c, x):
  assert False
  ...
```

Then we can't infer its output type!

That's the issue here: we have a loop body that can never run, for _any_ length of `xs` (basically like the `assert False` example), because the carry is (statically) empty and can never be indexed.

If we didn't have an empty carry, but still had length-0 xs, everything would've worked fine:

```python
def foo(carry, j):
  c=carry.at[j].set(j)
  return c, None

myarray = jnp.array([1])
carry, _ = jax.lax.scan( foo, myarray, jnp.arange(0))
print(carry)
```

> If this behaviour is not going to change, maybe it should be specified in the documentation that scan should not be applied to empty arrays, at least if the function accesses them?

Well, the issue isn't exactly empty arrays or accessing them, as the example above shows; it's that the scan body can't always (i.e. statically) error, given the shapes of the arguments passed to scan, because we run the body for output type inference. That's the issue in the body function in the OP, but we'd have the same issue with a body function that just has an `assert False` at the top (and has nothing to do with empty arrays).

> It has a lot of passages that use jax.lax.scan to loop over all enemies / mobs / plants, etc., like this:

```python
def _move_zombies(rng_and_state, zombie_index):
    random_move_proposed_position = (
        zombies.position[zombie_index] + random_move_direction
    )
    ...

rng, _rng = jax.random.split(rng)
(rng, new_state), _ = jax.lax.scan(
    _move_zombie, (rng, state), jnp.arange(static_params.max_zombies)
)
```

For code that fits this pattern, I suggest `fori_loop` instead of scanning over a `jnp.arange`. That is, wherever you have

```python
carry, _ = scan(f, carry, jnp.arange(N))  # e.g. f = _move_zombie, carry = (rng, state)
```

where you ignore the scanned-over output anyway, you can instead write

```python
carry, _ = fori_loop(0, N, lambda i, carry: f(carry, i), carry)
```

and you'll get the behavior you want.

---

Another option we have is we could add an optional `out_type` argument to `scan`: if you provide the output type of the body, then we won't have to run it to infer the output type. Then you'd also get the behavior you want, i.e. you can write

```python
carry, ys = scan(lambda c, x: assert_false(), carry, xs, out_type=...)
```

and when xs has length 0 that would not error.

But if your examples all fit the `fori_loop` pattern, it seems reasonable just to use that...

WDYT?

**Comment by alonfnt** [comment] 2024-03-29 21:09
Thanks for the explanation @mattjj! And just to be sure, if during compilation you where to check `len(xs)` and just set `ys` to `None` when it is 0, that would not work because that would create a representation of `f` that has different output pytrees depending on `xs`? -- which is a no go -- since e.g. `ys` shape does depend on `xs` length, but not its pytree structure which is found out by running `f`. Is that correct? Does recompilation happen when changing the length of `xs`?

Thank you for your work and feel free to ignore this! :)

**Comment by jakevdp** [comment] 2024-03-31 22:39
Late comment, but this has come up several times in the past and we've always answered that it's working as intended; see e.g. https://github.com/google/jax/issues/3285 and in particular https://github.com/google/jax/issues/3285#issuecomment-638120124

We also have places in the code where we account for this fact; for example here https://github.com/google/jax/blob/81c3d51deff4e947f9c708ab4191540711f4f80c/jax/_src/lax/linalg.py#L1213-L1214

**Comment by mattjj** [comment] 2024-07-20 17:36
> And just to be sure, if during compilation you where to check len(xs) and just set ys to None when it is 0, that would not work because that would create a representation of f that has different output pytrees depending on xs?

That's right.

> Does recompilation happen when changing the length of xs?

Yes, any given program we generate and compile is for fixed shapes.

I think we resolved things here well enough to close this issue. Please correct me if I'm mistaken!

Thanks, all.

**Closed by mattjj** 2024-07-20 17:36 UTC
Labels: better_errors
