### ISSUE TITLE
Cholesky crashes with bus error on Mac OS X

### ISSUE THREAD

**Issue by bayerj** [google/jax#1684] opened 2019-11-14 10:36 UTC
I am running jax revision 0981e75 (currently master) which I compiled for Python 3.7.3 installed with homebrew. This crash also happens with a pip installable jax.

The issue can be reproduced with the following piece of code:

```
from jax import np

for i in range(15, 20):
    print(i)
    np.linalg.cholesky(np.eye(i))
```

The program crashes after the `i==17`.

```
15
/Users/bayerj/.virtualenvs/try-jax/lib/python3.7/site-packages/jax/lib/xla_bridge.py:114: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
16
17
[1]    81997 bus error  python3 bug.py
```

**Comment by bayerj** [comment] 2019-11-14 10:47
Some additional info. The GP example [1] runs fine with `numpts==19`, but crashes at `numpts==20` as well.

**Comment by bkayalibay** [comment] 2019-11-14 11:56
I tested the snippet on Ubuntu 16.04, Python 3.6.0 and it went through without error (both on GPU and CPU).

**Comment by hawkinsp** [comment] 2019-11-14 13:48
I think this is a duplicate of https://github.com/google/jax/issues/432 .

This seems to be a problem with SciPy on Mac. Downgrading Scipy to 1.1.0 should fix it, but I haven't had time to look more closely. The issue doesn't reproduce on Linux, only Mac.

One possibility is that we may need to move away from using the SciPy-provided LAPACK kernels in favor of something else.

**Closed by hawkinsp** 2019-11-14 13:48 UTC

**Comment by bayerj** [comment] 2019-11-14 14:18
I can confirm, downgrading to scipy 1.1.0 fixed the issue.
