### ISSUE TITLE
JAX never destroys compiled executables

### ISSUE THREAD

**Issue by ezhulenev** [google/jax#16778] opened 2023-07-18 16:19 UTC
```
def add(a, b):
  x0 = jnp.dot(a, b)
  x1 = jnp.dot(x0, a)
  x2 = jnp.dot(x1, a)
  x3 = jnp.dot(x2, a)
  x = x0 + x1 + x2 + x3
  return a, x


def main(argv: Sequence[str]) -> None:
  print('Foo')

  add_jit = jit(add)

  for i in range(2, 1000):
    print(f'i: {i}')
    a = np.array(np.arange(i*i), dtype=np.float32).reshape((i, i))
    b = np.array(np.arange(i*i), dtype=np.float32).reshape((i, i))
    c = add_jit(a, b)
```

This program keeps compiling new executables and never destroys them. This was not a big problem for XLA:GPU before, but now we have CUDA graphs, and each executable in addition to host memory in standby state allocates device memory, which leads to OOMs.

Should JAX have an LRU cache for compiled programs?

OOM example:

```
 XLA_FLAGS=--xla_gpu_cuda_graph_level=2 blaze run --config=cuda ${TEST} --
   --alsologtostderr --suppress_failure_output --vmodule=cuda_graph=10,graph_launch=10
```

**Comment by ezhulenev** [comment] 2023-07-18 16:36
Ok, then it's probably WAI. I added cuda graphs eviction to XLA:GPU in https://github.com/openxla/xla/pull/4304.

Why 4096 as the default value? Seems too large. Do you have any statistics about average number of alive executables in the process?

**Comment by hawkinsp** [comment] 2023-07-18 16:41
The size of the cache is backend-independent, and might contain many small programs like `+`.

IIRC, I chose 4096 as a compromise between "gives a performance improvement on our test suite on CPU" and "doesn't OOM the test runners". But fundamentally host memory is cheap and we assume abundant.

Is the problem resolved with the XLA PR?

**Comment by hawkinsp** [comment] 2023-07-18 19:55
Sounds like things are working as intended. Closing.

**Closed by hawkinsp** 2023-07-18 19:55 UTC
Labels: enhancement
