### ISSUE TITLE
np.linalg.inv() on GPU

### ISSUE THREAD

**Issue by minaskar** [google/jax#1440] opened 2019-10-04 09:37 UTC
Hi all,

I was expecting to see a difference in terms of performance when running the np.linalg.inv() on a GPU with respect to the CPU case but I see no difference.

Isn't GPU acceleration supported for np.linalg.inv()?

Cheers,

**Comment by shoyer** [comment] 2019-10-06 04:35
Yes, a GPU should be capable of being significantly faster, at least for sufficiently large matrices and/or batches of matrices. JAX does use GPU acceleration for solve. Keep in mind that sometimes it can be hard to realize the full speed of GPUs with XLA, due to some per-operation overhead.

Can you share what your benchmark looks like? Don't forget about the overhead of asynchronous dispatch: https://jax.readthedocs.io/en/latest/async_dispatch.html

**Comment by hawkinsp** [comment] 2019-10-07 18:39
Yes, @shoyer is correct: matrix inversion should be accelerated on GPU. Please share a benchmark that reproduces the problem. Please also read the async dispatch documentation; otherwise you may not be measuring the right timing.

**Comment by hawkinsp** [comment] 2020-04-16 19:36
Closing since we don't have a benchmark. Feel free to reopen with a benchmark!

**Closed by hawkinsp** 2020-04-16 19:36 UTC
Labels: question
