### ISSUE TITLE
index_update shape error not caught before reaching XLA

### ISSUE THREAD

**Issue by froystig** [google/jax#1403] opened 2019-09-26 17:40 UTC
```python
import jax.numpy as np
import jax.ops as jo

f = lambda x, X: jo.index_update(X, jo.index[0], x)
x = np.zeros(2)
X = np.zeros(2)

# RuntimeError: Invalid argument: Updates tensor must be of rank 0; got 1.: 
# This is a bug in JAX's shape-checking rules; please report it!
print(f(x, X))
```

The jaxpr for `f` in context of `x, X` is:
```
{ lambda c ;  ; a b.
  let d = broadcast[ sizes=() ] a
      e = scatter[ updates_shape=(2,)
                   update_jaxpr={ lambda  ;  ; a b.
                                  let 
                                  in [b] }
                   dimension_numbers=ScatterDimensionNumbers(update_window_dims=(), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,))
                   update_consts=() ] b c d
  in [e] }
```

**Comment by xysun** [comment] 2019-09-27 09:29
seems duplicate of #1380 ?

**Comment by SIben** [comment] 2020-08-28 15:24
The error is now thrown by JAX as expected, closing the issue :)

**Closed by SIben** 2020-08-28 15:24 UTC
Labels: bug
