### ISSUE TITLE
bfloat16 error from NumPy when combining TensorFlow + JAX

### ISSUE THREAD

**Issue by shoyer** [google/jax#4426] opened 2020-09-30 19:07 UTC
```python
import jax
from jax import lax, random
from jax import numpy as jnp
import tensorflow as tf

# convert a tf tensor via _numpy() and do a Conv in bfloat16.
train_batch = tf.ones((8, 512, 512, 4), dtype=tf.bfloat16)
train_batch = jax.tree_map(lambda x: x._numpy(), train_batch)
w = random.uniform(random.PRNGKey(0), (3, 3, 4, 64), jnp.float32)

y = lax.conv_general_dilated(
             lhs=jnp.asarray(train_batch, jnp.bfloat16),
             rhs=jnp.asarray(w, jnp.bfloat16),
             window_strides=(1, 1),
             lhs_dilation=None,
             rhs_dilation=None,
             padding='SAME',
             precision=jax.lax.Precision.DEFAULT,
             dimension_numbers=('NHWC','HWIO','NHWC'))

totally_separate_test_data = jnp.ones((10, 10), dtype=jnp.bfloat16)
output = jnp.sum(totally_separate_test_data)  # Throws a TypeError!!
```

Results in the error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-49a6eda64422> in <module>()
     23 
     24 totally_separate_test_data = jnp.ones((10, 10), dtype=jnp.bfloat16)
---> 25 output = jnp.sum(totally_separate_test_data)  # Throws a TypeError!!

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in reduction(a, axis, dtype, out, keepdims)
   1746     a = preproc(a) if preproc else a
   1747     dims = _reduction_dims(a, axis)
-> 1748     result_dtype = dtype or _dtype(np_fun(np.ones((), dtype=_dtype(a))))
   1749     if upcast_f16_for_computation and issubdtype(result_dtype, inexact):
   1750       computation_dtype = promote_types(result_dtype, float32)

<__array_function__ internals> in sum(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in sum(a, axis, dtype, out, keepdims, initial, where)
   2227 
   2228     return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
-> 2229                           initial=initial, where=where)
   2230 
   2231 

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     88                 return reduction(axis=axis, out=out, **passkwargs)
     89 
---> 90     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     91 
     92 

TypeError: No loop matching the specified signature and casting was found for ufunc add
```

The error only occurs if `totally_separate_test_data` is evaluated _after_ the convolution. If it's evaluated first, then there is no error.

**Comment by tomhennigan** [comment] 2020-09-30 19:22
Unclear to me wrt why ordering matters but internal bug 156125812 might have some useful context and discussion (as to TF and JAX having different bfloat16 NumPy dtypes).

Also not a fix for the issue but perhaps as a work around I've found `x = x.view(jnp.bfloat16)` a useful way to move from TF NumPy bfloat16 to JAX's bf16 without a copy (I use this for tf datasets when combined with `tfds.as_numpy`).

**Comment by lgeiger** [comment] 2021-04-22 20:14
Looks like this has been fixed. At least it doesn't reproduce with TensorFlow 2.4.1 anymore. For reference checkout [this notebook](https://colab.research.google.com/drive/1RpJ32ApTskyxepjHBWyelgrXjpCjTql1?usp=sharing).

**Comment by hawkinsp** [comment] 2021-04-23 00:27
We've made two changes:
* both TF and JAX check to see if someone has already registered a `bfloat16` type, and if so, they prefer to use the existing one. (Ideally we would add the type to upstream numpy or to a package both can depend on, but this is enough for now.)
* TF now has a much more complete implementation of the `bfloat16` type. So I agree, we can probably declare this fixed with current JAX and TF.

**Closed by hawkinsp** 2021-04-23 00:27 UTC
