### ISSUE TITLE
Deprecation warning when parsing nightly packages

### ISSUE THREAD

**Issue by stellaraccident** [google/jax#15476] opened 2023-04-07 22:17 UTC
### Description

When running `pip` with `-f https://storage.googleapis.com/jax-releases/jaxlib_nightly_releases.html` to install nightlies, I'm getting this deprecation warning:

```
DEPRECATION: The HTML index page being used (https://storage.googleapis.com/jax-releases/jaxlib_nightly_releases.html) is not a proper HTML 5 document. This is in violation of PEP 503 which requires these pages to be well-formed HTML 5 documents. Please reach out to the owners of this index page, and ask them to update this index page to a valid HTML 5 document. pip 22.2 will enforce this behaviour change. Discussion can be found at https://github.com/pypa/pip/issues/10825
```

I'm using pip 22.0.2.

Probably best to fix whatever it is angry about soon.

**Comment by jakevdp** [comment] 2023-04-07 23:01
Thanks for the report – this looks like a duplicate of #5410, but is still something we need to address.

**Comment by yashk2810** [comment] 2023-11-03 03:28
Closing in favor of https://github.com/google/jax/issues/5410

**Closed by yashk2810** 2023-11-03 03:28 UTC
Labels: bug
