### ISSUE TITLE
Problem with gradient for jax installed with pip, but working for jax install from git

### ISSUE THREAD

**Issue by jeammimi** [google/jax#2505] opened 2020-03-25 08:22 UTC
Hello,
I don't have a minimal example, but for the same code on the same machine,
if I install jax from pip:

```
conda list | grep jax
jax                       0.1.62                   pypi_0    pypi
jaxlib                    0.1.42                   pypi_0    pypi
```

And I run my code I have nan in my gradient.
Here is the error that I catch with the flag jax_debug_nans set to true

```
Invalid value encountered in the output of a jit function. Calling the de-optimized version.
Invalid value encountered in the output of a jit function. Calling the de-optimized version.
Invalid value encountered in the output of a jit function. Calling the de-optimized version.
Invalid value encountered in the output of a jit function. Calling the de-optimized version.
Traceback (most recent call last):
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 459, in _xla_call_impl
    return compiled_fun(*args)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 565, in _execute_compiled
    if FLAGS.jax_debug_nans: check_nans(xla_call_p, out_bufs)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 272, in check_nans
    _check_nans(prim.name, buf.shape(), buf)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 279, in _check_nans
    raise FloatingPointError(msg.format(name))
FloatingPointError: invalid value (nan) encountered in xla_call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 459, in _xla_call_impl
    return compiled_fun(*args)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 565, in _execute_compiled
    if FLAGS.jax_debug_nans: check_nans(xla_call_p, out_bufs)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 272, in check_nans
    _check_nans(prim.name, buf.shape(), buf)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 279, in _check_nans
    raise FloatingPointError(msg.format(name))
FloatingPointError: invalid value (nan) encountered in xla_call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 459, in _xla_call_impl
    return compiled_fun(*args)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 565, in _execute_compiled
    if FLAGS.jax_debug_nans: check_nans(xla_call_p, out_bufs)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 272, in check_nans
    _check_nans(prim.name, buf.shape(), buf)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 279, in _check_nans
    raise FloatingPointError(msg.format(name))
FloatingPointError: invalid value (nan) encountered in xla_call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 459, in _xla_call_impl
    return compiled_fun(*args)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 565, in _execute_compiled
    if FLAGS.jax_debug_nans: check_nans(xla_call_p, out_bufs)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 272, in check_nans
    _check_nans(prim.name, buf.shape(), buf)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 279, in _check_nans
    raise FloatingPointError(msg.format(name))
FloatingPointError: invalid value (nan) encountered in xla_call

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/mathmodrep/fit.py", line 152, in <module>
    g = grad(lossv)(chs0)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/api.py", line 362, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/api.py", line 428, in value_and_grad_f
    g = vjp_py(onp.ones((), dtype=dtype))
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/api.py", line 1283, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 113, in vjp_
    arg_cts = backward_pass(jaxpr, consts, dummy_args, dummy_primals_and_cts)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 205, in backward_pass
    params, call_jaxpr, invals, cts_in)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 549, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/core.py", line 895, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 463, in _xla_call_impl
    return fun.call_wrapped(*args)  # probably won't return
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 205, in backward_pass
    params, call_jaxpr, invals, cts_in)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 549, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/core.py", line 895, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 463, in _xla_call_impl
    return fun.call_wrapped(*args)  # probably won't return
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 205, in backward_pass
    params, call_jaxpr, invals, cts_in)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 549, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/core.py", line 895, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 463, in _xla_call_impl
    return fun.call_wrapped(*args)  # probably won't return
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 205, in backward_pass
    params, call_jaxpr, invals, cts_in)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 549, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/core.py", line 895, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 463, in _xla_call_impl
    return fun.call_wrapped(*args)  # probably won't return
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 207, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(cts_in, *invals, **eqn.params)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/ad.py", line 503, in bilinear_transpose
    out = zero if cotangent is zero else lhs_rule(cotangent, y, **kwargs)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/lax/lax.py", line 282, in mul
    return mul_p.bind(x, y)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/core.py", line 199, in bind
    return self.impl(*args, **kwargs)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 170, in apply_primitive
    return compiled_fun(*args)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 258, in _execute_compiled_primitive
    check_nans(prim, out_bufs)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 272, in check_nans
    _check_nans(prim.name, buf.shape(), buf)
  File "/home/jeanmichel/miniconda3/envs/mathmodrep_pip/lib/python3.7/site-packages/jax/interpreters/xla.py", line 279, in _check_nans
    raise FloatingPointError(msg.format(name))
FloatingPointError: invalid value (nan) encountered in mul
```

But if I clone jax and install jaxlib from pip:

```
conda list | grep jax
jax                       0.1.62                    dev_0    <develop>
jaxlib                    0.1.42                   pypi_0    pypi

```
The same code works perfectly.

Do you have any idea what is happening?

**Comment by gnecula** [comment] 2020-03-25 11:15
Hello! My first thought is that there is a relevant difference between the version 1.62 and the github HEAD. [These](https://github.com/google/jax/compare/jax-v0.1.62...master) are the commits since then (perhaps your clone is somewhere in the middle).

Can you please try to set your local clone to version 1.62: `git co jax-v0.1.62` and see if you can reproduce the problem? If you can, then you problem has been solved already in commits after 1.62. If however, the clone at 1.62 and the conda version behave different we have to look deeper into what is different.

**Comment by jeammimi** [comment] 2020-03-25 12:59
Hi, I just cloned it this morning and the commit is here:
a4922ceda29091981c4d49c78110dcdc5c5b1e40

**Comment by gnecula** [comment] 2020-03-26 14:28
Were you able to check out the version jax-v0.1.62 to see if it reproduces the error? Or, perhaps you are not suffering from this problem, and then we can close the issue?

**Comment by jeammimi** [comment] 2020-03-26 15:28
My local clone was version 0.1.62 at the commit a4922ce
I tried to execute git co jax-v0.1.62 in the jax repertory but it does not work.

**Comment by organic-chemistry** [comment] 2020-04-08 14:26
If you think it was introduced by a previous commit we can close it indeed.

**Closed** 2020-04-08 14:28 UTC
