### ISSUE TITLE
fill_diagonal not yet implemented

### ISSUE THREAD

**Issue by dpfau** [google/jax#2680] opened 2020-04-11 13:24 UTC
Just a feature request to implement `jnp.fill_diagonal`, mainly for consistency with NumPy. Though is the reason this hasn't been implemented yet that it isn't pure in NumPy? I don't see an issue with having a non-pure version that returns a new array.

**Comment by dpfau** [comment] 2020-04-11 14:22
Should be easy to implement:

```
fill_diagonal = lambda x: jax.ops.index_updat(x, jnp.diag_indices(x.shape[0]), 0)
```

Just need to make sure it works for batches, etc.

**Comment by hawkinsp** [comment] 2020-04-14 13:15
My main hesitation here is that `np.fill_diagonal` is specified to update its input in-place. We can't do that in JAX. We could provide an alternate API that returns an updated array, although that wouldn't satisfy the "consistent with NumPy" constraint. What do you think?

**Comment by dpfau** [comment] 2020-04-14 14:25
Well, this connects with PR #2684 on syntactic sugar for pure array updating. Maybe instead of implementing fill diagonal, we do something like `x = x.update.diag(y)` or `x = x.setdiag(y)`, something consistent with whatever syntax we settle on in #2684. Only question is how far we want to diverge from the NumPy interface.

**Comment by geoHeil** [comment] 2021-03-07 15:43
After the PR being merged - what is the suggested syntax now? For me (just getting started with JAX) this is still confusing.

**Comment by geoHeil** [comment] 2021-03-07 15:55
```
diag_elements = jnp.diag_indices_from(jax_array)
new_jax_array = index_update(jax_array, diag_elements, 1.)

```
seems to work though.

**Comment by jakevdp** [comment] 2021-03-07 15:58
Slightly more concise is
```
new_jax_array = jax_array.at[diag_elements].set(1)
```

**Comment by geoHeil** [comment] 2021-03-07 21:50
The concise version was distorting the shape of the matrix. Perhaps I was using it wrong.

**Comment by jakevdp** [comment] 2021-03-07 22:41
`arr.at[idx].set(y)` is identical to `index_update(arr, idx, y)`: https://github.com/google/jax/blob/39a7158cb6aad6a927b314c4aae5ba22ff29b0d7/jax/_src/numpy/lax_numpy.py#L5477-L5489

**Comment by fehiepsi** [comment] 2021-03-20 05:13
I am a bit confused. What is a convenient way to convert a batch of vectors to a batch of diagonal matrices? Currently, I use
```
# given x is a batch of vectors
x_matrix = x[..., None] * jnp.eye(x.shape[-1])
```
but I guess it is slower than using `index_update` option. I guess we can reshape `x` to (-1, x.shape[-1]), then perform `vmap(ops.index_update(...))` then reshape the output back to `x.shape + x.shape[-1:]`?

**Comment by jakevdp** [comment] 2021-03-22 13:23
I'm not sure if it's the fastest way, but here's an approach to creating a batched diagonal based on `index_update` that avoids any reshapes and multiplications:
```python
from jax import vmap
import jax.numpy as jnp

@vmap
def fill_diagonal(x):
  (N,) = x.shape
  i, j = jnp.diag_indices(N)
  return jnp.zeros_like(x, shape=(N, N)).at[i, j].set(x)

x = jnp.arange(6).reshape(2, 3)
print(fill_diagonal(x))
# [[[0 0 0]
#   [0 1 0]
#   [0 0 2]]

#  [[3 0 0]
#   [0 4 0]
#   [0 0 5]]]
```

**Comment by hawkinsp** [comment] 2021-03-22 13:27
This is a case where the best approach will probably depend on both hardware and the matrix size. On CPU and GPU, @jakevdp 's approach is probably close to optimal. On TPU your original computation that multiplies by `np.eye` is probably better for small to moderate matrix sizes. For larger matrices on TPU I suspect a hybrid between the two is best: use `np.eye` to form diagonal blocks, and then use a `.at[...]` to update diagonal blocks.

**Comment by fehiepsi** [comment] 2021-03-22 15:14
Thanks! The extra reshapes are used to make sure that we have 1 batch dimension, so we can vmap over it and cast the result back to match the original shape. If this is a better approach than matmul in CPU then I'll go with this solution. It would be nice to have a batching version of fill_diagonal by the way. :)

**Comment by jakevdp** [comment] 2021-03-22 16:09
The problem is that numpy's `fill_diagonal` modifies the array in-place. We've generally avoided JAX wrappers of numpy inplace operations to avoid user confusion.

**Comment by fehiepsi** [comment] 2021-03-22 17:33
Understood, I just thought that it would be nice to have a utility like fill_diagonal that works for a batch (can have arbitrary shape: (10, 3, 4, 5) e.g.) of vectors and incorporates the best practice. Based on the above discussions, it seems that I can just make a utility by my own and either using matmul or index_update. Except for the creation of eye or zeros, the cost of matmul (which has shorter code but requires some math) is O(N^2) while the cost of index update (which has longer code and requires reshape, vmap) is O(N) I guess.

**Comment by jakevdp** [comment] 2021-03-22 17:52
I see; here's a quick implementation similar to `np.fill_diagonal` that should work without reshapes:
```python
import jax.numpy as jnp

def fill_diagonal(a, val):
  assert a.ndim >= 2
  i, j = jnp.diag_indices(min(a.shape[-2:]))
  return a.at[..., i, j].set(val)

a = jnp.zeros((2, 3, 4, 4))

# works for scalars
a1 = fill_diagonal(a, 2)

# or for batched vectors
a2 = fill_diagonal(a, jnp.arange(24).reshape(2, 3, 4))
```

**Comment by carlosgmartin** [comment] 2023-10-15 05:06
@jakevdp How about the following?

```python3

def fill_diagonal(array, value, inplace=True):
    if inplace:
        raise NotImplementedError("JAX arrays are immutable")
    return array.at[jnp.diag_indices_from(array)].set(value)
```
This ensures that no user confusion can take place, since they must consciously specify `inplace=False`. (Precedent for the use of the `inplace` argument can be found in [`numpy.ndarray.byteswap`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.byteswap.html).)

**Comment by carlosgmartin** [comment] 2023-11-23 20:25
@jakevdp Given https://github.com/google/jax/pull/18180, I think this issue can be closed now.

**Closed** 2023-11-24 13:07 UTC
Labels: question
