### ISSUE TITLE
Significant numerical differences of dot_general on TPU

### ISSUE THREAD

**Issue by sbl1996** [google/jax#16349] opened 2023-06-11 16:18 UTC
### Description

```python
import jax
import jax.numpy as jnp
from jax import random

n = 4
key = random.PRNGKey(0)
key, subkey1, subkey2 = jax.random.split(key, 3)
x = random.normal(subkey1, shape=(1,2,n))
k = random.normal(subkey2, shape=(n,2))

o1 = jax.lax.dot_general(x, k, (((2,), (0,)), ((), ())))
o2_1 = jax.lax.dot_general(x[:, 0:1], k, (((2,), (0,)), ((), ())))
o2_2 = jax.lax.dot_general(x[:, 1:2], k, (((2,), (0,)), ((), ())))
o2 = jnp.concatenate([o2_1, o2_2], axis=1)

print(o1)
# [[[0.31184387 5.3089447 ]
#   [0.5985794  3.6086464 ]]]

print(o2)
# [[[0.31908777 5.3246055 ]
#   [0.60039854 3.6162388 ]]]
```

It is expected that `o1` and `o2` have exactly the same value or negligible difference. These significant numerical differences appear only on TPU, not on CPU or GPU.

### What jax/jaxlib version are you using?

jax v0.4.12, jaxlib v0.4.12, libtpu-nightly v0.1.dev20230608

### Which accelerator(s) are you using?

TPU v3-8

### Additional system info

Python 3.8.10, Ubuntu 20.04, Cloud TPU VM

**Comment by hawkinsp** [comment] 2023-06-12 12:46
I strongly suspect this is working as intended. Try setting `jax.default_matmul_precision` to `float32`, see https://github.com/google/jax/issues/2161

If you perform a matrix-vector multiplication, it is performed in full `float32` precision on TPU. If you perform a matrix-matrix multiplication, it uses the lower precision matrix hardware which rounds its inputs to `bfloat16` precision. You can opt into a higher precision for a specific matmul using the `precision` flag on a particular matmul, or by using, e.g., the `default_matmul_precision` decorator.

Something very similar happens on modern GPUs with TensorCores, as it happens; this is not TPU specific.

Does that fix the problem?

**Comment by hawkinsp** [comment] 2023-06-12 12:46
Closing, but feel free to comment and I'll reopen if there's an action item.

**Closed by hawkinsp** 2023-06-12 12:46 UTC
Labels: bug
