### ISSUE TITLE
JAX should not create duplicate HLO computations for reductions

### ISSUE THREAD

**Issue by cheshire** [google/jax#7654] opened 2021-08-18 01:32 UTC
@hawkinsp when generating HLO with many reductions, JAX duplicates reduction computations. Despite that not affecting codegen much, the resulting HLO dumps get overly huge and hard to work with due to such computations. Similarly to tf2xla it would be very difficult if JAX could deduplicate such computations.
![unnamed](https://user-images.githubusercontent.com/348959/129822274-a74cb97d-474f-41d4-98ee-c2829c7c3d87.png)

**Comment by skye** [comment] 2021-08-23 21:54
@hawkinsp (when you're back) can you reassign this or mark P2 as necessary? I'm not sure what the context on this is. Thanks.

**Comment by jekbradbury** [comment] 2021-08-29 23:55
I believe the issue is that the XLA builder API duplicates subcomputations even if JAX makes an effort to share them. But once it stops doing that JAX should probably try to share subcomputations as much as possible.

**Comment by hawkinsp** [comment] 2022-08-19 14:16
This particular issue is moot on the JAX side, because JAX now emits MHLO and in MHLO the reducer is emitted inline:

```
In [1]: import jax

In [2]: import jax.numpy as jnp

In [3]: def f(x, y): return jnp.sum(x) + jnp.sum(y)

In [4]: print(jax.jit(f).lower(jnp.arange(10), jnp.arange(15)).compiler_ir())
module @jit_f.2 {
  func.func public @main(%arg0: tensor<10xi32>, %arg1: tensor<15xi32>) -> tensor<i32> {
    %0 = mhlo.constant dense<0> : tensor<i32>
    %1 = mhlo.reduce(%arg0 init: %0) across dimensions = [0] : (tensor<10xi32>, tensor<i32>) -> tensor<i32>
     reducer(%arg2: tensor<i32>, %arg3: tensor<i32>)  {
      %5 = mhlo.add %arg2, %arg3 : tensor<i32>
      "mhlo.return"(%5) : (tensor<i32>) -> ()
    }
    %2 = mhlo.constant dense<0> : tensor<i32>
    %3 = mhlo.reduce(%arg1 init: %2) across dimensions = [0] : (tensor<15xi32>, tensor<i32>) -> tensor<i32>
     reducer(%arg2: tensor<i32>, %arg3: tensor<i32>)  {
      %5 = mhlo.add %arg2, %arg3 : tensor<i32>
      "mhlo.return"(%5) : (tensor<i32>) -> ()
    }
    %4 = mhlo.add %1, %3 : tensor<i32>
    return %4 : tensor<i32>
  }
}
```

Of course, when the MHLO is converted to HLO, we end up duplicating the reducers:
```
In [6]: print(jax.jit(f).lower(jnp.arange(10), jnp.arange(15)).compiler_ir(dialect="hlo").as_hlo_text())
HloModule jit_f.4, entry_computation_layout={(s32[10]{0},s32[15]{0})->s32[]}

region_0.4 {
  Arg_0.5 = s32[] parameter(0)
  Arg_1.6 = s32[] parameter(1)
  ROOT add.7 = s32[] add(Arg_0.5, Arg_1.6)
}

region_1.9 {
  Arg_0.10 = s32[] parameter(0)
  Arg_1.11 = s32[] parameter(1)
  ROOT add.12 = s32[] add(Arg_0.10, Arg_1.11)
}

ENTRY main.15 {
  Arg_0.1 = s32[10]{0} parameter(0)
  constant.3 = s32[] constant(0)
  reduce.8 = s32[] reduce(Arg_0.1, constant.3), dimensions={0}, to_apply=region_0.4
  Arg_1.2 = s32[15]{0} parameter(1)
  reduce.13 = s32[] reduce(Arg_1.2, constant.3), dimensions={0}, to_apply=region_1.9
  ROOT add.14 = s32[] add(reduce.8, reduce.13)
}
```

There's nothing we can do about that on the JAX end; closing. We could open an issue about this for the MHLO->HLO conversion.

**Closed by hawkinsp** 2022-08-19 14:16 UTC
Labels: enhancement

**Comment by cheshire** [comment] 2022-08-19 14:24
> This particular issue is moot on the JAX side, because JAX now emits MHLO
and in MHLO the reducer is emitted inline:

Is it actually good? Do we want to duplicate the code for addition with
every reduction, of which we can potentially have hundreds? Is it a
fundamental MHLO limitation that different operations can not share regions?

**Comment by hawkinsp** [comment] 2022-08-19 14:30
Nothings stop us from emitting a function call as the reducer, if the reducer is large and deduplicating it is important. That isn't often the case for JAX right now: they are mostly single instructions. (Personally I think I prefer the inline reducers for IR readability if nothing else.)

**Comment by hawkinsp** [comment] 2022-08-19 19:36
Filed https://github.com/tensorflow/mlir-hlo/issues/48

**Comment by never-to-never** [comment] 2023-07-27 08:47
```
xla_comp = jax.xla_computation(fun)(inputs)
xla_text = xla_comp.as_serialized_hlo_module_proto()

from tensorflow.compiler.xla.service import hlo_pb2
module = hlo_pb2.HloModuleProto() module.ParseFromString(xla_text)
```
The module obtained in this way contains many instructions, and each instruction corresponds to an opcode. Where can I get all the opcode lists used by the jax program? @hawkinsp

**Comment by jakevdp** [comment] 2023-07-27 13:42
See https://github.com/google/jax/discussions/16859

**Comment by never-to-never** [comment] 2023-07-31 04:54
> See #16859

hello, What I want to ask is a list of all opcodes that may be generated by any jax program?
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/hlo/ir/hlo_opcode.h](https://github.com/google/jax/discussions/url)
I saw a HLO_OPCODE_LIST from the source code of tensorflow, I don't know if this is the list of all opcodes that the jax program may generate?

**Comment by hawkinsp** [comment] 2023-07-31 13:39
Note that JAX doesn't generate HLO directly any more. JAX emits `stablehlo`, which is an MLIR dialect, which later gets translated to XLA HLO. So JAX doesn't deal directly with the opcode list.

If you're writing a compiler that consumes JAX IR, you should consume `stablehlo` MLIR not the HLO protobuf.

We don't have a list of exactly which `stablehlo` opcodes JAX uses, but the answer is almost certainly "just about all of them".
