### ISSUE TITLE
Jax Einsum Implementation Error

### ISSUE THREAD

**Issue by YANYZP** [google/jax#23159] opened 2024-08-20 23:20 UTC
### Description

I ran colab on TPU and Jax einsum has an obvious error and inconsistent result with Numpy einsum:

```
B, T, A, R, D  = 4, 1, 8, 4, 10

x = jnp.arange(B * T * D).reshape(B, T, D).astype(jnp.float32)
y = jnp.arange(A * D * R).reshape(A, D, R).astype(jnp.float32)
expected = jnp.einsum('btd,adr->brta', x, y)

x1 = np.arange(B * T * D).reshape(B, T, D).astype(jnp.float32)
y1 = np.arange(A * D * R).reshape(A, D, R).astype(jnp.float32)
expected1 = np.einsum('btd,adr->brta', x1, y1)
print(expected)
print(expected1)
np.testing.assert_array_equal(expected, expected1)
```

Receive:
```
AssertionError:
Arrays are not equal

Mismatched elements: 16 / 128 (12.5%)
Max absolute difference: 345.
Max relative difference: 0.00333382
 x: array([[[[  1140.,   2940.,   4740.,   6540.,   8340.,  10140.,
           11940.,  13740.]],
...
 y: array([[[[  1140.,   2940.,   4740.,   6540.,   8340.,  10140.,
           11940.,  13740.]],
...
```

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.32
jaxlib: 0.4.32
numpy:  1.26.3
python: 3.11.8 (stable, redacted, redacted) [Clang google3-trunk (a0a9bf5152507beacd2a72dda42d054391494c4a)]
jax.devices (8 total, 8 local): [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0) TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1) ... TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0) TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
process_count: 1
platform: uname_result(system='Linux', node='d00ef52addb6d6c9-52c77f7d560.borgtask.google.com', release='5.10.0-smp-1103.32.0.0', version='#1 [v5.10.0-1103.32.0.0] SMP @1721941885', machine='x86_64')

**Comment by dfm** [comment] 2024-08-21 05:34
As discussed on the internal issue tracker, this is the expected behavior: the TPU will multiply with bf16 precision and accumulate in f32 precision, so some numerical differences are expected due to the bf16 truncation.

I'll close this!

**Closed by dfm** 2024-08-21 05:34 UTC
Labels: bug
