### ISSUE TITLE
illegal memory access while two GPUs is used

### ISSUE THREAD

**Issue by EyalRozenberg1** [google/jax#3518] opened 2020-06-22 17:29 UTC
Hi @skye , this is a continuation of our discussion at issue #3158 

I am have implemented an optimization program with JAX.
The program works great on a single GPU (TITAN RTX 24GB), but problems occur while multiple multiple GPUs are given. With the error that suggests "illegal memory access".

Below is the full error description. Please let me know what else can be handy to crack this issue.
Thanks, Eyal
```
2020-06-22 21:17:03.780428: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_blas.cc:426] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
2020-06-22 21:17:03.780492: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1484] Execution of replica 0 failed: Internal: Failed to launch CUDA kernel: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2020-06-22 21:17:03.780554: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1484] Execution of replica 1 failed: Internal: Unable to launch fft for thunk 0x55def2e06330 with type IFFT
Traceback (most recent call last):
  File "/home/name/sp/sp.py", line 201, in <module>
    batch_loss, opt_state = update(opt_state, idx, x, At, Bt)
  File "/home/name/anaconda3/envs/sp/lib/python3.7/site-packages/jax/api.py", line 1165, in f_pmapped
    donated_invars=tuple(donated_invars))
  File "/home/name/anaconda3/envs/sp/lib/python3.7/site-packages/jax/core.py", line 1085, in _call_bind
    outs = primitive.impl(f, *args, **params)
  File "/home/name/anaconda3/envs/sp/lib/python3.7/site-packages/jax/interpreters/pxla.py", line 653, in xla_pmap_impl
    return compiled_fun(*args)
  File "/home/name/anaconda3/envs/sp/lib/python3.7/site-packages/jax/interpreters/pxla.py", line 1092, in execute_replicated
    out_bufs = compiled.execute_on_local_devices(list(input_bufs))
RuntimeError: Internal: Failed to launch CUDA kernel: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered: while running replica 0 and partition 0 of areplicated computation (other replicas may have failed as well).
2020-06-22 21:17:03.869297: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:940] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***
	PyDict_SetItem
	_PyModule_ClearDict
	PyImport_Cleanup
	Py_FinalizeEx
	_Py_UnixMain
	__libc_start_main
	
*** End stack trace ***

2020-06-22 21:17:03.869484: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_executable.cc:88] Check failed: pair.first->SynchronizeAllActivity() 

Process finished with exit code 134
```

**Comment by EyalRozenberg1** [comment] 2020-06-22 18:04
If I run on a much smaller array I also get an error, but this time its a different one:

2020-06-22 20:51:53.466568: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_fft.cc:502] failed to run cuFFT routine: 6
2020-06-22 20:51:53.466727: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1484] Execution of replica 1 failed: Internal: Unable to launch fft for thunk 0x5571695c0090 with type IFFT
2020-06-22 20:51:58.997204: E external/org_tensorflow/tensorflow/compiler/xla/service/collective_ops_utils.h:142] This thread has been waiting for 5000ms for and may be stuck: participant for device ordinal 0, stream 0x55712f163960 waiting for all participants to arrive at rendezvous RendezvousKey{run_id=RunId: 285265, global_devices=[0,1], num_local_participants=2, collective_op_kind=1, op_id=75}
2020-06-22 20:52:03.466890: F external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1665] Replicated computation launch failed, but not all replicas terminated. Aborting process to work around deadlock. Failure message (there may have been multiple failures, see the error log for all failures): 

Unable to launch fft for thunk 0x5571695c0090 with type IFFT

Process finished with exit code 134

**Comment by skye** [comment] 2020-06-22 20:31
Just to clarify: when you run with multiple GPUs, are they all the same model?

The first few lines are a best hint I think:
```
failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
Execution of replica 1 failed: Internal: Unable to launch fft for thunk 0x555b1b7f0060 with type IFFT
failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
Execution of replica 0 failed: Internal: Unable to launch fft for thunk 0x555b1b7f0060 with type IFFT
```

Seems like something went wrong executing an `ifft` on the GPUs, although it's hard to say what... @hawkinsp do you have any ideas?

@EyalRozenberg1 two things to try:
1) Are you able to create a minimal repro of the error? It seems like pmap + ifft is the issue here, but maybe other ingredients are necessary to repro.
2) Turning on more logging might reveal more clues. Try this env var: `TF_CPP_MIN_LOG_LEVEL=0`

**Comment by EyalRozenberg1** [comment] 2020-06-23 08:09
Thank you for your response,
Yes, the GPUs are the same.

1. It is problematic for me to share the core of the code but I can share the general structure:
``

2. with `TF_CPP_MIN_LOG_LEVEL=0`, it seems like I get a very similar error (running with a small array output):

`2020-06-23 10:45:52.144388: I external/org_tensorflow/tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2900170000 Hz
2020-06-23 10:45:52.150796: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e99d8443b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-23 10:45:52.150886: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-23 10:45:52.154396: I external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-23 10:45:53.464944: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e99d75a3c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-23 10:45:53.465059: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN RTX, Compute Capability 7.5
2020-06-23 10:45:53.465085: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): TITAN RTX, Compute Capability 7.5
2020-06-23 10:45:53.466863: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/nvidia_gpu_device.cc:109] XLA backend allocating 22692652646 bytes on device 0 for BFCAllocator.
2020-06-23 10:45:53.466990: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/nvidia_gpu_device.cc:109] XLA backend allocating 22692652646 bytes on device 1 for BFCAllocator.
2020-06-23 10:53:44.362150: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:55] 
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
********************************
2020-06-23 11:02:37.601927: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_fft.cc:502] failed to run cuFFT routine: 6
2020-06-23 11:02:37.602059: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1484] Execution of replica 1 failed: Internal: Unable to launch fft for thunk 0x55e9f0aada50 with type FFT
2020-06-23 11:02:42.977732: E external/org_tensorflow/tensorflow/compiler/xla/service/collective_ops_utils.h:142] This thread has been waiting for 5000ms for and may be stuck: participant for device ordinal 0, stream 0x55e99dad2060 waiting for all participants to arrive at rendezvous RendezvousKey{run_id=RunId: 285265, global_devices=[0,1], num_local_participants=2, collective_op_kind=1, op_id=75}
2020-06-23 11:02:47.602219: F external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1665] Replicated computation launch failed, but not all replicas terminated. Aborting process to work around deadlock. Failure message (there may have been multiple failures, see the error log for all failures): 

Unable to launch fft for thunk 0x55e9f0aada50 with type FFT

Process finished with exit code 134
`

**Comment by skye** [comment] 2020-06-24 22:10
Enabling `TF_CPP_MIN_LOG_LEVEL=0` just turns out more logging, so it makes sense you'd get the same error. It did produce this new error: `cuda_fft.cc:502] failed to run cuFFT routine: 6` But it looks like 6 means `CUFFT_EXEC_FAILED` "cuFFT failed to execute the transform on the GPU" ([nvidia cuFFT docs](https://docs.nvidia.com/cuda/cufft/index.html)), which isn't very informative. @brianwa84 do you happen to know what could cause this error?

I'm not sure we'll be able to make progress on this without being able to reproduce the problem. If you could remove parts of the code and simplify it while still producing the error, that'd be extremely useful (even if the code no longer produces meaningful results).

Alternatively, it might be enough to collect the HLO produced by your computation. (HLO is the input language to the XLA compiler that jax uses, so sometimes having the raw HLO is enough to reproduce a bug in compiled code.) You can get the HLO by setting the env var `XLA_FLAGS="--xla_dump_to=/tmp/hlo"` (or whatever path you want, just make sure the directory exists), then running the failing code. You should see a bunch of files in that directory, you can zip them up and share them somewhere or email them to me.

One more question I just thought of: does the error reproduce if you run exactly the same code but only on a single GPU? Basically set `num_devices = 1`, but still use `pmap`, `psum`, etc.

**Comment by EyalRozenberg1** [comment] 2020-06-25 05:58
On single GPU the very same code works perfectly fine (on the small or larger arrays).

**Comment by skye** [comment] 2020-06-25 17:10
This is a very elusive problem! I tried writing a simple pmap involving ifft on a multi-GPU machine, but wasn't able to repro. I think to make progress we need either code we can run, or possibly the HLO would be sufficient (see my previous comment). Sorry this is such a pain!

**Comment by skye** [comment] 2020-06-25 17:13
Also, this appears to be a temperamental bug, so it's possible you can find a workaround by arbitrarily changing your code (e.g. maybe breaking up the one big pmap into multiple smaller pmaps called in sequence will help?). This could also give us clues as to what's causing it.

**Comment by hawkinsp** [comment] 2020-06-26 13:42
One thing I'd like to double check: you aren't *also* using TensorFlow in the same process? There's some sort of multigpu interactions between the two that I haven't yet tracked down. https://github.com/google/jax/issues/2742

**Comment by EyalRozenberg1** [comment] 2020-06-28 15:08
TensorFlow is not used within the process. I will create a small running version with the bug and send it over.

**Comment by brianwa84** [comment] 2020-06-29 14:59
If I had to guess, I'd start looking for a bug in/around fft_thunk:
https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/xla/service/gpu/fft_thunk.cc;l=117?q=tensorflow%2Fcompiler%2Fxla%2Fservice%2Fgpu%2Ffft_thunk.cc
Maybe a wrong device ordinal on the temp allocation? I'm not familiar with
how pmap interacts with XLA (or how XLA handles multi-GPU at all).

**Comment by EyalRozenberg1** [comment] 2020-07-08 09:04
@skye , I sent you a running version of the code to your email 10 days ago. Have you received it? Any other thing I can do to help solve the issue?

**Comment by skye** [comment] 2020-07-09 20:10
Hi, sorry for the delay! I received your email and am able to repro the error, woohoo. Now to debug it...

@brianwa84 thanks for the pointer. I'm not familiar with the internals of XLA multi-GPU execution either, so your guess sounds as plausible as any :) I'll see if I can verify the device ordinal.

**Comment by skye** [comment] 2020-11-06 01:47
Hey, sorry for the delay AGAIN. @hawkinsp has finally cracked this bug and it should be fixed in the next jaxlib release! (Fixed via https://github.com/tensorflow/tensorflow/commit/7d185bb63ba346ac955b787540518f732e2ffb53)

@EyalRozenberg1 is this still affecting you? If so I can cut a new jaxlib sooner rather than later.

**Comment by EyalRozenberg1** [comment] 2020-11-08 18:40
Thanks @skye that's encouraging. I will be happy to have it asap. At the moment it limits my development. 
Much appreciated!

**Comment by skye** [comment] 2020-11-11 23:21
Hey @EyalRozenberg1 , I just uploaded jaxlib 0.1.57 wheels (I haven't updated the README yet because we still need to build the mac wheels, but the linux ones should be there). Note that I dropped CUDA 10.0 support due to some build issues, please lemme know if this is an issue for you. Give the new release a shot and let us know how it goes?

**Comment by hawkinsp** [comment] 2020-11-13 02:48
Closing, because the new jaxlib wheels should have fixed this. Feel free to reopen if it isn't fixed!

**Closed by hawkinsp** 2020-11-13 02:48 UTC
Labels: bug

**Comment by EyalRozenberg1** [comment] 2020-11-13 14:14
> Hey @EyalRozenberg1 , I just uploaded jaxlib 0.1.57 wheels (I haven't updated the README yet because we still need to build the mac wheels, but the linux ones should be there). Note that I dropped CUDA 10.0 support due to some build issues, please lemme know if this is an issue for you. Give the new release a shot and let us know how it goes?

Works great!
thanks
