### ISSUE TITLE
Question about stax batch dimension

### ISSUE THREAD

**Issue by christopher-hesse** [google/jax#931] opened 2019-06-26 19:35 UTC
Should it be possible to define a network in stax without setting a non-batch dimension?

```
import jax.numpy as np
from jax import random
from jax.experimental import stax
from jax.experimental.stax import Dense, Relu, Flatten, LogSoftmax

# Use stax to set up network initialization and evaluation functions
net_init, net_apply = stax.serial(Dense(128), Relu, Dense(10), LogSoftmax)

rng = random.PRNGKey(0)
# Initialize parameters, not committing to a batch shape

# works
in_shape = (-1, 1)
out_shape, net_params = net_init(rng, in_shape)

# doesn't work (fails with ValueError: all elements of broadcast shape must be non-negative)
in_shape = (-1,)
out_shape, net_params = net_init(rng, in_shape)
```

As a workaround, I can of course add a fake 1 dimension on the end, and then remove it later, but I was a little surprised that this doesn't automatically work.

**Comment by mattjj** [comment] 2019-06-26 21:10
We'd like something like that to be possible, but it isn't right now. (Actually it's because stax predates the existence of vmap, and we haven't really updated it in a while.) I think this might be a duplicate of #381 though.

You'd still need to provide a nonemtpy input shape tuple with positive elements to `init_fun` to specify the example size (i.e. `in_shape` won't be just `(-1,)` because that doesn't provide any shape information, but maybe it'd be e.g. `(28 * 28,)`), but we'd like it not to be necessary to specify a batch size.

**Comment by mattjj** [comment] 2019-06-26 21:11
Can you check #381 and see if you think this is a duplicate?

**Comment by cshesse** [comment] 2019-06-27 00:50
I saw that issue when I filed this one, this could be a duplicate, but I also think I worded this confusingly.

If my inputs is a list of scalars, I could consider that of shape `(batchsize,)` or `(batchsize, 1)`.  The second one seems to work with stax but not the first.  I could of course, wrap the stax model with `jp.expand_dims(input, axis=-1)` but wanted to make sure I wasn't missing something.

**Comment by hawkinsp** [comment] 2021-05-11 01:18
We've decided to keep stax as an example rather than evolving it any further. These days, we would point users to one of the great neural network libraries built on top of JAX, such as Haiku or Flax.

**Closed by hawkinsp** 2021-05-11 01:18 UTC
Labels: question
