### ISSUE TITLE
Error when importing jax

### ISSUE THREAD

**Issue by itsjaytime** [google/jax#15403] opened 2023-04-05 05:18 UTC
### Description

Error message when importing jax. How can I solve it?
<img width="879" alt="image" src="https://user-images.githubusercontent.com/50226927/229987382-9951175c-51c4-4338-8d9d-4cc0111424f0.png">

Below is the result of "pip show jax jaxlib".
<img width="472" alt="image" src="https://user-images.githubusercontent.com/50226927/229987472-02b3f63b-059f-4031-8ac4-a29027ca2dd0.png">

### What jax/jaxlib version are you using?

jax 0.4.8, jaxlib 0.4.7

### Additional system info

python - 3.9.16, MacOS 13.0, M1 Pro

**Comment by jakevdp** [comment] 2023-04-05 15:29
Duplicate of #15402

**Closed by jakevdp** 2023-04-05 15:29 UTC
Labels: bug
