### ISSUE TITLE
Wrong `vjp` of `ops.segment_sum` with negative entries in `segment_ids`

### ISSUE THREAD

**Issue by romanngg** [google/jax#7538] opened 2021-08-06 18:40 UTC
Example:
https://colab.research.google.com/gist/romanngg/13156dc441aa14dd20aebb6df8a3337b/vjp_segment_sum_wrong.ipynb

Above I define two identical functions `f1` and `f2`, but `f2` has a dummy negative `segment_id`.

For both functions the output does not depend on `x[1]` (due to negative `segment_id` assigned to it in `f2`). 

`jacfwd` is the same `[[1., 0.]]` (and seems correct to me) for both `f1` and `f2`.
`jacrev(f1) = [[1., 0.]]` as well.
`jacrev(f2) = [[1., 1.]]`, implying dependence on `x[1]`, which I think is wrong.

**Comment by hawkinsp** [comment] 2021-08-11 16:29
The issue is that XLA scatter and XLA gather have slightly different semantics for out-of-bounds indices, and gather is the gradient of scatter. I filed an XLA feature request to modify the semantics of gather, but I think we can work around this in `segment_sum` for now.

**Comment by hawkinsp** [comment] 2021-08-12 00:00
#7595 fixes this, but it's going to take a while to get it checked in, because it will involve some cleaning up of other code, and not least because I'm going on vacation...

**Comment by hawkinsp** [comment] 2021-08-12 00:01
As a workaround you could probably replace the out-of-bounds indices with the index of an dummy array element that you throw away afterwards.

**Comment by hawkinsp** [comment] 2021-11-30 19:05
This should be fixed! `segment_sum` and its cousins now drops updates to out of bounds indices. The gradient for those indices will be zeros.

**Closed by hawkinsp** 2021-11-30 19:05 UTC
Labels: bug
