### ISSUE TITLE
JAX C++ jit path pulls SDA back to host

### ISSUE THREAD

**Issue by rsepassi** [google/jax#8501] opened 2021-11-09 22:12 UTC
```
import jax
import jax.numpy as jnp
f = lambda x: jnp.add(x, 1)
x = jax.pmap(f)(jnp.array([1]))  # x is a SDA

# jnp.add will use the JAX C++ jit path which has SDA handling falling back to numpy-like handling
x = jnp.add(x, 1)
```

Handling: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/py_values.cc#L220-L223

**Comment by jekbradbury** [comment] 2021-11-09 22:50
This is true for both the C++ and Python paths, and in both is due to `device_put(x: ShardedDeviceArray)` involving a copy to host. Instead we should (at least!) special case the path where the SDA is fully replicated and we can just take the buffer on the desired device and wrap it in a `DeviceArray`...

**Comment by jekbradbury** [comment] 2021-11-09 22:58
Duplicate of https://github.com/google/jax/issues/4885

**Closed** 2021-11-30 20:54 UTC
Labels: bug
