### ISSUE TITLE
Document experimental.jet

### ISSUE THREAD

**Issue by thisiscam** [google/jax#3730] opened 2020-07-13 00:29 UTC
Hi all,

From a lot of discussion in issues, it seems like jet is able to "compute higher order derivatives efficiently". 
This functionality is particularly of my interest, but I can't seem to find any more documentation than those discussion and a few tests.
Could someone explain very shortly what is the arguments to `jet(f, primals, series)`, in particular, what `series` represents? 

Thanks!

**Comment by jekbradbury** [comment] 2020-07-13 05:51
I believe `series` is a list of arrays representing the first, second, third, etc.-order differentials to be propagated through the function (the generalization of the `tangents` argument in `jax.jvp`). So the equivalent of `jvp(f, p, t)` is `jet(f, p, [t])`.

**Comment by thisiscam** [comment] 2020-07-14 05:03
Thanks @jekbradbury. It worked for me, though I realized it was a bit lower level than I wanted (i.e. jet doesn't support pytrees yet), so I rolled my own hack for a function `value_jac_and_hessian`. 

My primary use case was for implementing a Newton-Raphson optimizer, so calculating just three orders works for me.

It will be great if at some point computing orders of derivatives all at once can get into main feature set of Jax.

**Comment by mattjj** [comment] 2020-07-24 03:53
cc @duvenaud @jacobjinkelly @jessebett 

I think @jessebett and @jacobjinkelly planned to write some kind of a post and/or docs for `jet`. In the meantime, there is the preprint [Learning Differential Equations that are Easy to Solve](https://arxiv.org/abs/2007.04504), though that's mostly about an application and doesn't offer a ton in the way of documentation. I also wrote up [some notes on the math](https://github.com/google/jax/files/4970131/jet.1.pdf) and Sec 3 might help explain the reason the `jet` API looks how it does, but actually the most important bit is Sec 4 and it's a bit hand-wavey.

I think `jet` only becomes more efficient at third and higher orders though, so it might not be relevant to the Newton-Raphson application.

**Comment by mattjj** [comment] 2021-06-25 15:23
@fedelebron noticed some typos in the "some notes on the math" note linked above, specifically a couple places where ∂g(x) was supposed to be ∂g(h(x)). Here's [an updated pdf with notes on the math](https://github.com/google/jax/files/6717197/jet.pdf). Thanks, @fedelebron!

**Comment by pnkraemer** [comment] 2022-02-11 16:23
Hi! I agree that it would be great to have some extra documentation for jet and would be willing to help. I started a corresponding discussion in #9536, because I wasn't sure how good a place this issue here is to discuss details :)

**Comment by rajasekharporeddy** [comment] 2024-02-12 04:58
Hi @thisiscam 

The details and functionality of `jax.experimental.jet` are added to JAX documentation here https://jax.readthedocs.io/en/latest/jax.experimental.jet.html with the PR #9546.

Could you please verify and confirm the same

Thank you.

**Comment by thisiscam** [comment] 2024-02-12 06:41
> Hi @thisiscam
> 
> The details and functionality of `jax.experimental.jet` are added to JAX documentation here https://jax.readthedocs.io/en/latest/jax.experimental.jet.html with the PR #9546.
> 
> Could you please verify and confirm the same
> 
> Thank you.

It's been a while since I opened this and last looked at it!
LGTM

**Comment by rajasekharporeddy** [comment] 2024-02-12 06:51
Hi @thisiscam 

If the issue is resolved, please feel free to close the issue.

Thank you.

**Closed** 2024-02-15 20:17 UTC
Labels: documentation
