### ISSUE TITLE
Rule for `jtu.Partial`, `None` in tree_util_with_path

### ISSUE THREAD

**Issue by ASEM000** [google/jax#15310] opened 2023-03-30 13:53 UTC
Hello, 

If I'm not mistaken, I think the `flatten_with_keys` rule for `None` and `Partial` are missing.

```python

import jax.tree_util as jtu

paths_leaves, _ = jtu.tree_flatten_with_path((jtu.Partial(lambda x:x)))

paths, leaves = zip(*paths_leaves)

leaves  # (Partial(<function <lambda> at 0x1266eea70>),)

leaves, _ = jtu.tree_flatten((jtu.Partial(lambda x:x)))
leaves  # []
```

**Comment by mattjj** [comment] 2023-03-30 14:55
Thanks for raising this!

What version did you test on? I think this may have been fixed at github HEAD by #15071, as I was unable to reproduce at HEAD.

**Comment by ASEM000** [comment] 2023-03-30 15:28
My mistake, This was on 0.4.6, 

I upgraded to 0.4.8 and tried again, the new result is 

```python
import jax.tree_util as jtu

paths_leaves, _ = jtu.tree_flatten_with_path((jtu.Partial(lambda x:x)))

# paths_leaves = zip(*paths_leaves)

print(paths_leaves)  # ([])
```

One question still, for consistency, do not you think the output of `paths_leaves` should be (),() for empty path and empty leaves instead of a single tuple?

for example, the following contains an empty tuple for no path

```python

import jax.tree_util as jtu

paths_leaves, _ = jtu.tree_flatten_with_path(1)

# paths_leaves = zip(*paths_leaves)

print(paths_leaves)  # [((), 1)]

leaves, _ = jtu.tree_flatten((jtu.Partial(lambda x:x)))
print(leaves)  # []

```

**Comment by mattjj** [comment] 2023-03-30 16:17
I think `len(jtu.tree_flatten_with_path(x)[0])` should be equal to `len(jtu.tree_flatten(x)[0])`, and I think that's the case now. That is, the value of `paths_leaves` here is `[]` because there are no leaves.

Using `zip(*x)` often works for list transposition but it's fundamentally ambiguous when `x` is empty. That's why we often use `jax._src.util.unzip2` instead.

**Comment by mattjj** [comment] 2023-03-30 16:17
Since this bug is fixed at HEAD, I think we can close the issue!

**Closed by mattjj** 2023-03-30 16:17 UTC
Labels: enhancement

**Comment by ASEM000** [comment] 2023-03-30 16:20
Sounds great, thanks 🙏
