### ISSUE TITLE
Implement all of scipy.linalg matrix functions

### ISSUE THREAD

**Issue by oleg-kachan** [google/jax#5024] opened 2020-11-27 15:20 UTC
- [x] lu
- [ ] polar
- [x] expm
- [ ] logm
- [ ] sqrtm
- [ ] fractional_matrix_power

**Comment by hawkinsp** [comment] 2020-12-02 16:49
Hey you already filed this issue! :-) 

Duplicate of https://github.com/google/jax/issues/2478 .

**Closed by hawkinsp** 2020-12-02 16:49 UTC
Labels: contributions welcome, enhancement
