### ISSUE TITLE
Segfaults on MacOs Github Actions with jaxlib 0.1.68

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#7198] opened 2021-07-06 12:01 UTC
I started seeing a few weeks ago a spurious (~25-50% of the time) CI failure in GithubActions on MacOs runners.
I have been unable to reproduce it on my local (Mac) computer.

I have been able to pinpoint this to `jaxlib==0.1.68`. Downgrading to `jaxlib==0.1.67` with current jax==0.2.16` makes the issue disappear.

I have been able to produce the following MWE:
```python
bash-3.2$ cat tests/prova.py 
import jax

a  = jax.random.PRNGKey(123)

bash-3.2$ pytest tests/prova.py                                                                                                                                                                                     
=============================================================================================== test session starts ================================================================================================
platform darwin -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/runner/work/mpi4jax/mpi4jax
collecting ... Fatal Python error: Segmentation fault

Current thread 0x0000000107dbfdc0 (most recent call first):
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jaxlib/xla_client.py", line 67 in make_cpu_client
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/lib/xla_bridge.py", line 206 in backends
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/lib/xla_bridge.py", line 242 in get_backend
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/lib/xla_bridge.py", line 263 in get_device_backend
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/interpreters/xla.py", line 138 in _device_put_array
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/interpreters/xla.py", line 133 in device_put
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 1596 in _device_put_raw
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3025 in array
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3064 in asarray
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jax/_src/random.py", line 66 in PRNGKey
  File "/Users/runner/work/mpi4jax/mpi4jax/tests/prova.py", line 3 in <module>
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 170 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1030 in _gcd_import
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/importlib/__init__.py", line 127 in import_module
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/pathlib.py", line 524 in import_path
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/python.py", line 578 in _importtestmodule
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/python.py", line 500 in _getobj
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/python.py", line 291 in obj
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/python.py", line 516 in _inject_setup_module_fixture
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/python.py", line 503 in collect
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py", line 341 in <lambda>
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py", line 311 in from_call
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py", line 341 in pytest_make_collect_report
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py", line 458 in collect_one_node
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/main.py", line 808 in genitems
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/main.py", line 634 in perform_collect
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/main.py", line 333 in pytest_collection
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/main.py", line 322 in _main
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/Users/runner/hostedtoolcache/Python/3.9.5/x64/bin/pytest", line 8 in <module>
Segmentation fault: 11
```

though in interactive mode it segfaults even less often.

Noticed here: https://github.com/mpi4jax/mpi4jax/runs/2997837419?check_suite_focus=true#step:8:31 and then I debugged by using a ssh shell into github actions.

**Comment by hawkinsp** [comment] 2021-07-07 15:37
Duplicate of #7128 

There's a workaround in https://github.com/google/jax/issues/7128#issuecomment-875693010

**Comment by hawkinsp** [comment] 2021-07-07 15:38
(Thanks for the tip about ssh-ing into the action, by the way, I didn't know that was possible and it made it much easier to identify the problem.)

**Closed by hawkinsp** 2021-07-07 15:37 UTC
Labels: bug

**Comment by PhilipVinc** [comment] 2021-07-07 15:52
Ops. Sorry I missed the previous issue.

**Comment by matthewfeickert** [comment] 2021-07-07 22:41
> (Thanks for the tip about ssh-ing into the action, by the way, I didn't know that was possible and it made it much easier to identify the problem.)

Ah, sorry about that @hawkinsp. I should have drawn your attention to `tmate` in my comment on my original Issue https://github.com/scikit-hep/pyhf/issues/1501#issuecomment-870071961.
