### ISSUE TITLE
Stuck Threads with Multi-GPU Programming

### ISSUE THREAD

**Issue by TheAppleTucker** [google/jax#6896] opened 2021-06-04 16:35 UTC
The error message is as follows.

`2021-06-01 12:09:19.912475: E external/org_tensorflow/tensorflow/compiler/xla/service/collective_ops_utils.h:209] This thread has been waiting for 5000ms for and may be stuck: participant for device ordinal 1, stream 0x5594682cb160 waiting for all participants to arrive at rendezvous RendezvousKey{run_id=RunId: 85034, global_devices=[0,1,2,3], num_local_participants=4, collective_op_kind=cross_replica, op_id=534}`

`2021-06-01 12:09:19.977384: E external/org_tensorflow/tensorflow/compiler/xla/service/collective_ops_utils.h:209] This thread has been waiting for 5000ms for and may be stuck: participant for device ordinal 0, stream 0x559467f49ab0 waiting for all participants to arrive at rendezvous RendezvousKey{run_id=RunId: 85034, global_devices=[0,1,2,3], num_local_participants=4, collective_op_kind=cross_replica, op_id=534}`

`2021-06-01 12:09:20.260798: E external/org_tensorflow/tensorflow/compiler/xla/service/collective_ops_utils.h:209] This thread has been waiting for 5000ms for and may be stuck: participant for device ordinal 3, stream 0x559467d0ae10 waiting for all participants to arrive at rendezvous RendezvousKey{run_id=RunId: 85034, global_devices=[0,1,2,3], num_local_participants=4, collective_op_kind=cross_replica, op_id=534}`

The code for this is quite involved and it would be quite difficult to give a minimal example that reproduces the error, so I figure that I'd first see if anyone had seen this error before. I'll also do my best to describe the error in the context of the program and when it occurs.

I am doing some adversarial training on a machine with 4 gpus using pmap. The code itself is written entirely in Jax and a small amont of native numpy (no TF or Pytorch). The training loop is under a pmap, and within this pmap, there's a fairly large amount of computation being done under a vmap (done to generate a certain type of adversarial examples). The error normally occurs at arbitrary epochs/stages of training. When it occurs, the program will not necessarily crash/terminate, but further progress will be abnormally slow. I'd speculate that perhaps a solution is to somehow increase the thread timeout time, but I am not terribly familiar with XLA programming.

![image](https://user-images.githubusercontent.com/47281632/120832698-f08ef400-c52e-11eb-9d3f-fc72a404f0dc.png)

Here's a screenshot of the GPU utilization, with the different colors indicating the different gpus. The first dip is normal as I do some nonparallel work in between epochs. After the error occurs, devices 0, 1, and 3 seem to stop being used. In different runs, the devices that stop working are not consistent, and oftentimes, all 4 devices will experience this issue.

Have tried googling this error, but haven't seen anything about it. Would appreciate any help, and happy to provide more information if needed.

**Comment by hawkinsp** [comment] 2021-06-07 19:50
The `This thread has been waiting for 5000ms for and may be stuck` message means that one of the other participants in `pmap` didn't show up to a collective operation like `psum` after a thread had been waiting for 5s. Now, this is sometimes benign: threads/GPUs are slow sometimes. The part that makes me think it's a real bug is that the GPU utilization then drops to 0 and stays there.

The question is: why is one device (presumably device `2`) getting stuck? One way this might happen if some computation before the collective is not terminating. Another way that it might happen is if you put collectives like `psum` in control flow, and not all participants are taking the same branches.

If nothing like that rings a bell, I think we'd need a reproduction to make further progress.

**Comment by hawkinsp** [comment] 2021-06-23 13:11
Closing since there's no way we can reproduce the problem. Please feel free to reopen if you have a reproduction we can debug.

**Closed by hawkinsp** 2021-06-23 13:11 UTC
Labels: bug, needs info
