### ISSUE TITLE
jax.experimental.enable_x64 does not work under jax.jit

### ISSUE THREAD

**Issue by botev** [google/jax#7336] opened 2021-07-20 16:11 UTC
The following code:
```
@functools.partial(jax.custom_vjp, nondiff_argnums=(1,))
def _precise_mean(x, axis):
  with jax.experimental.enable_x64():
    return jnp.mean(x.astype("float64"), axis=axis).astype(x.dtype)


def _precise_mean_fwd(x, axis):
  return _precise_mean(x, axis), (x,)
  
def _precise_mean_bwd(axis, res, g):
  x, = res
  dims = tuple(i for i in range(x.ndim) if i not in axis)
  factor = 1
  for a in axis:
    factor *= x.shape[a]
  g = g / factor
  print(g.dtype)
  return lax.broadcast_in_dim(g.astype(x.dtype), x.shape, dims),

_precise_mean.defvjp(_precise_mean_fwd, _precise_mean_bwd)


def precise_mean(x, axis=None):
  if axis is None:
    axis = tuple(range(x.ndim))
  elif isinstance(axis, int):
    axis = (axis,)
  # Take care of negative values
  axis = tuple((x.ndim + a) % x.ndim for a in axis)
  if not all(isinstance(a, int) for a in axis):
    raise ValueError("All axis must be integers.")
  return _precise_mean(x, axis)

@jax.jit
def f(x, a, b):
  x = jnp.matmul(x, a) + b[None]
  y = jnp.sum(x, axis=-1)
  return precise_mean(y, axis=0)
  
x = jnp.ones([5000, 100])
a = jnp.ones([100, 100])
b = jnp.zeros([100])
print(f(x, a, b).dtype)
```
Throws out the following error:
```
UnfilteredStackTrace: RuntimeError: Internal: Seen floating point types of different precisions in %reduce.23 = f32[] reduce(f64[5000]{0} %convert.17, f32[] %constant.18), dimensions={0}, to_apply=%primitive_computation_add.19, metadata={op_type="reduce_sum" op_name="jit(f)/custom_vjp_call_jaxpr/reduce_sum[ axes=(0,) ]" source_file="<ipython-input-219-aea426c526ae>" source_line=13}, but mixed precision is disallowed.

Failed after pipeline-start

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
```
It is unclear at the moment how to use the `enable_x64` contest when using `jax.jit`.

**Comment by james-martens** [comment] 2021-07-21 15:35
I have an example of using float64 in Jax to compute more precise inner products that seems to work, but has a bunch of reasonable variants which don't work (presumably due to bugs). These variants are described in the comments of the code block below:
```
def inner_product(obj1, obj2):
  if jax.tree_structure(obj1) != jax.tree_structure(obj2):
    raise ValueError("The two structures are not identical.")

  def array_ip(x, y):

    x = jnp.array(jnp.reshape(x, [-1]), dtype=jnp.float64)
    y = jnp.array(jnp.reshape(y, [-1]), dtype=jnp.float64)

    #return jnp.sum(x * y)  # doesn't work
    #return jnp.dot(x, y)  # works
    return jnp.dot(x, y, precision=lax.Precision.HIGHEST)  # works

  with jax.experimental.enable_x64():
    elements_product = jax.tree_multimap(array_ip, obj1, obj2)

    print(jax.tree_flatten(elements_product)[0])

    # Doesn't work:
    # r = sum(jax.tree_flatten(elements_product)[0])

    # Doesn't work:
    # r = jnp.array(0.0, dtype=jnp.float64)
    # for e in jax.tree_flatten(elements_product)[0]:
    #   r += e

    # Works:
    flat_list = jax.tree_flatten(elements_product)[0]
    r = flat_list[0]
    for e in flat_list[1:]:
      r += e

  return jnp.array(r)  # convert back to default Jax dtype (usually float32)

ji = jax.jit(inner_product)

a = jnp.array([[1.1, 2.2, 3.5]])
b = jnp.array([[5.5, 0.12, 4.8]])

print(jax.make_jaxpr(inner_product)([a, b], [b, b]))

c = ji([a, b], [b, b])
```

**Comment by james-martens** [comment] 2021-07-21 19:54
Here's a simple example of counter-intuitive behavior with float64. Not sure if it's working as intended.
```
def f():
  return np.array([2, 3, 4], dtype=jnp.float64)

jf = jax.jit(f)

f().dtype == jnp.float64  # True

jf().dtype == jnp.float32  # True
```

**Comment by skye** [comment] 2021-07-21 22:11
@mattjj are you a good person to look at this given Jake's out? Can you triage if not?

**Comment by jakevdp** [comment] 2021-08-02 18:45
duplicate of #5982

**Closed** 2021-08-02 18:46 UTC
Labels: duplicate

**Comment by jakevdp** [comment] 2021-08-02 18:47
(for what it's worth, this is a difficult bug to fix and is one of the primary reasons this feature is still only experimentally supported)
