### ISSUE TITLE
Improve error message when use has_aux=True

### ISSUE THREAD

**Issue by zhongwen** [google/jax#1105] opened 2019-08-03 17:32 UTC
Minimal repro:
```
from jax import jit, grad
import jax.numpy as jnp

def f(x):
  return 2 * x
g = grad(f, has_aux=True)
x = jnp.ones([])
g(x)
```

The error message raised is:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-248f07c6c8ba> in <module>()
      6 g = grad(f, has_aux=True)
      7 x = jnp.ones([])
----> 8 g(x)

9 frames
/usr/local/lib/python3.6/dist-packages/jax/api.py in grad_f(*args, **kwargs)
    239       return g
    240     else:
--> 241       (_, aux), g = value_and_grad_f(*args, **kwargs)
    242       return g, aux
    243 

/usr/local/lib/python3.6/dist-packages/jax/api.py in value_and_grad_f(*args, **kwargs)
    282       ans, vjp_py = vjp(f_partial, *dyn_args)
    283     else:
--> 284       ans, vjp_py, aux = vjp(f_partial, *dyn_args, has_aux=True)
    285     _check_scalar(ans)
    286     dtype = onp.result_type(ans)

/usr/local/lib/python3.6/dist-packages/jax/api.py in vjp(fun, *primals, **kwargs)
    898     out_primal, out_vjp = ad.vjp(jaxtree_fun, primals_flat)
    899   else:
--> 900     out_primal, out_vjp, aux = ad.vjp(jaxtree_fun, primals_flat, has_aux=True)
    901   out_tree = out_tree()
    902   if has_aux:

/usr/local/lib/python3.6/dist-packages/jax/interpreters/ad.py in vjp(traceable, primals, has_aux)
    105     out_primal, pval, jaxpr, consts = linearize(traceable, *primals)
    106   else:
--> 107     out_primal, pval, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)
    108   def vjp_(ct):
    109     ct = ignore_consts(ct, pval)

/usr/local/lib/python3.6/dist-packages/jax/interpreters/ad.py in linearize(traceable, *primals, **kwargs)
     92   in_pvals = (pe.PartialVal((None, pack(primals))),
     93               pe.PartialVal((core.AbstractTuple(tangent_avals), core.unit)))
---> 94   jaxpr, out_pval, consts = pe.trace_to_jaxpr(jvpfun, in_pvals)
     95   pval_primal, pval_tangent = unpair_pval(out_pval)
     96   aval_primal, const_primal = pval_primal

/usr/local/lib/python3.6/dist-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr(fun, pvals, **kwargs)
    399   with new_master(JaxprTrace) as master:
    400     fun = trace_to_subjaxpr(fun, master, instantiate)
--> 401     jaxpr, (out_pval, consts, env) = fun.call_wrapped(pvals)
    402     assert not env
    403     del master

/usr/local/lib/python3.6/dist-packages/jax/linear_util.py in call_wrapped(***failed resolving arguments***)
    149     while stack:
    150       gen, out_store = stack.pop()
--> 151       ans = gen.send(ans)
    152       if out_store is not None:
    153         ans, side = ans

/usr/local/lib/python3.6/dist-packages/jax/interpreters/ad.py in jvp_subtrace_aux(instantiate, master, primals, tangents)
     69     if isinstance(x, Tracer):
     70       assert x.trace.level < trace.level
---> 71   ans, aux = yield map(partial(JVPTracer, trace), primals, tangents), {}
     72   out_tracer, aux_tracer = map(trace.full_raise, (ans, aux))
     73   out_primal, out_tangent = out_tracer.primal, out_tracer.tangent

/usr/local/lib/python3.6/dist-packages/jax/core.py in __iter__(self)
    292 
    293   def __iter__(self):
--> 294     return iter(self.aval._iter(self))
    295 
    296   def __len__(self):

/usr/local/lib/python3.6/dist-packages/jax/lax/lax.py in _iter(tracer)
   1368 def _iter(tracer):
   1369   if tracer.ndim == 0:
-> 1370     raise TypeError("iteration over a 0-d array")  # same as numpy error
   1371   else:
   1372     n = tracer.shape[0]

TypeError: iteration over a 0-d array
```

colab can be found here: https://colab.research.google.com/drive/1VZj9iloWOgZRcSeSkoIwu9G-W4kdq-s1

It would be great if it could say it's due to `has_aux=True` but no `aux` return in the function `f`.

**Comment by zhongwen** [comment] 2019-08-03 17:33
Or provide a checker for `has_aux=True`.

**Comment by hawkinsp** [comment] 2023-10-04 17:09
I think the error message at head isn't bad these days:

```
TypeError: expected function with aux output to return a two-element tuple, but got type <class 'jax._src.interpreters.ad.JVPTracer'> with value Traced<ConcreteArray(2.0, dtype=float32)>with<JVPTrace(level=2/0)> with
  primal = Array(2., dtype=float32)
  tangent = Traced<ShapedArray(float32[])>with<JaxprTrace(level=1/0)> with
    pval = (ShapedArray(float32[]), None)
    recipe = JaxprEqnRecipe(eqn_id=<object object at 0x14fa0d4e0>, in_tracers=(Traced<ShapedArray(float32[]):JaxprTrace(level=1/0)>, Traced<ConcreteArray(2.0, dtype=float32):JaxprTrace(level=1/0)>), out_tracer_refs=[<weakref at 0x14ffe2b10; to 'JaxprTracer' at 0x14ffe2fd0>], out_avals=[ShapedArray(float32[])], primitive=pjit, params={'jaxpr': { lambda ; a:f32[] b:f32[]. let c:f32[] = mul b a in (c,) }, 'in_shardings': (UnspecifiedValue, UnspecifiedValue), 'out_shardings': (UnspecifiedValue,), 'resource_env': None, 'donated_invars': (False, False), 'name': 'fn', 'keep_unused': False, 'inline': True}, effects=set(), source_info=SourceInfo(traceback=<jaxlib.xla_extension.Traceback object at 0x14fe3bfb0>, name_stack=NameStack(stack=(Transform(name='jvp'),))))
```

Closing because I think the problem is solved!

**Closed by hawkinsp** 2023-10-04 17:09 UTC
Labels: enhancement
