### ISSUE TITLE
Can't sample maximum dtype value with random.randint

### ISSUE THREAD

**Issue by juliuskunze** [google/jax#6389] opened 2021-04-09 12:24 UTC
I want to sample `uint8`s uniformly including the maximum value of 255, but this doesn't work:

```python
from jax import random, numpy as jnp
random.randint(random.PRNGKey(0), (10,), 0, 256, jnp.uint8) # [0 0 0 0 0 0 0 0 0 0]
```

The reason is that maxval is converted into the `uint8`. This is in contrast to

```python
import numpy as np
np.random.randint(0, 256, (10,), np.uint8) # [197 133 228 202 216 177 116  78 244 176]
```

The same happens for all integer datatypes. (Workaround is of course to use a larger type and then cast.)

**Comment by jakevdp** [comment] 2021-04-09 12:33
Thanks for the report! This appears to be a duplicate of #5785, and was fixed by #5868. If you upgrade to JAX version 0.2.12 or higher, your code should work correctly. Let us know if you see any remaining issues.

**Closed** 2021-04-09 13:15 UTC
Labels: bug
