### ISSUE TITLE
Extending JAX with CUDA: cstdint: error: the global scope has no "..."

### ISSUE THREAD

**Issue by bsaoptima** [google/jax#22946] opened 2024-08-08 14:37 UTC
### Description

Hi there,

I am trying to extend the capabilities of JAX with my own kernels and I have been following both the official documentation the the ̀dfm/extending-jax` repo. Here is my issue:

When I run this (do I even need to have all of these parameters?):

```
nvcc --threads 4 -Xcompiler -Wall -ldl --expt-relaxed-constexpr -O3 -DNDEBUG -Xcompiler -O3 --generate-code=arch=compute_70,code=[compute_70,sm_70]  --generate-code=arch=compute_75,code=[compute_75,sm_75] --generate-code=arch=compute_80,code=[compute_80,sm_80] --generate-code=arch=compute_86,code=[compute_86,sm_86] -Xcompiler=-fPIC -Xcompiler=-fvisibility=hidden -x cu -c lib/kernel.cu -o build/dia_kernel.cu.o
```

I get the following error:

```
/usr/include/c++/11/cstdint(52): error: the global scope has no "int_fast8_t"

/usr/include/c++/11/cstdint(53): error: the global scope has no "int_fast16_t"

/usr/include/c++/11/cstdint(54): error: the global scope has no "int_fast32_t"

/usr/include/c++/11/cstdint(55): error: the global scope has no "int_fast64_t"

/usr/include/c++/11/cstdint(57): error: the global scope has no "int_least8_t"

/usr/include/c++/11/cstdint(58): error: the global scope has no "int_least16_t"

/usr/include/c++/11/cstdint(59): error: the global scope has no "int_least32_t"

/usr/include/c++/11/cstdint(60): error: the global scope has no "int_least64_t"

/usr/include/c++/11/cstdint(62): error: the global scope has no "intmax_t"

/usr/include/c++/11/cstdint(63): error: the global scope has no "intptr_t"

/usr/include/c++/11/cstdint(65): error: the global scope has no "uint8_t"

/usr/include/c++/11/cstdint(66): error: the global scope has no "uint16_t"

/usr/include/c++/11/cstdint(67): error: the global scope has no "uint32_t"

/usr/include/c++/11/cstdint(68): error: the global scope has no "uint64_t"

/usr/include/c++/11/cstdint(70): error: the global scope has no "uint_fast8_t"

/usr/include/c++/11/cstdint(71): error: the global scope has no "uint_fast16_t"

/usr/include/c++/11/cstdint(72): error: the global scope has no "uint_fast32_t"

/usr/include/c++/11/cstdint(73): error: the global scope has no "uint_fast64_t"

/usr/include/c++/11/cstdint(75): error: the global scope has no "uint_least8_t"

/usr/include/c++/11/cstdint(76): error: the global scope has no "uint_least16_t"

/usr/include/c++/11/cstdint(77): error: the global scope has no "uint_least32_t"

/usr/include/c++/11/cstdint(78): error: the global scope has no "uint_least64_t"

/usr/include/c++/11/cstdint(80): error: the global scope has no "uintmax_t"

/usr/include/c++/11/cstdint(81): error: the global scope has no "uintptr_t"

/usr/include/c++/11/exception(53): error: not a class or struct name

/usr/include/c++/11/typeinfo(190): error: not a class or struct name

/usr/include/c++/11/typeinfo(207): error: not a class or struct name

/usr/include/c++/11/bits/nested_exception.h(99): error: identifier "true_type" is undefined

/usr/include/c++/11/bits/nested_exception.h(108): error: identifier "false_type" is undefined

/usr/include/c++/11/bits/nested_exception.h(108): error: function template "dia_jax::std::__throw_with_nested_impl" has already been defined

/usr/include/c++/11/bits/nested_exception.h(134): error: enable_if is not a template

/usr/include/c++/11/bits/nested_exception.h(135): error: identifier "__and_" is undefined

/usr/include/c++/11/bits/nested_exception.h(135): error: identifier "is_polymorphic" is undefined

/usr/include/c++/11/bits/nested_exception.h(135): error: type name is not allowed

/usr/include/c++/11/bits/nested_exception.h(135): error: expected a ";"

/usr/include/c++/11/bits/stringfwd.h(79): error: basic_string is not a template

/usr/include/c++/11/bits/stringfwd.h(83): error: basic_string is not a template

/usr/include/c++/11/bits/stringfwd.h(93): error: basic_string is not a template

/usr/include/c++/11/bits/stringfwd.h(96): error: basic_string is not a template

/usr/include/c++/11/cwchar(64): error: the global scope has no "mbstate_t"

/usr/include/c++/11/cwchar(141): error: the global scope has no "wint_t"

/usr/include/c++/11/cwchar(143): error: the global scope has no "btowc"

/usr/include/c++/11/cwchar(144): error: the global scope has no "fgetwc"

/usr/include/c++/11/cwchar(145): error: the global scope has no "fgetws"

/usr/include/c++/11/cwchar(146): error: the global scope has no "fputwc"

/usr/include/c++/11/cwchar(147): error: the global scope has no "fputws"

/usr/include/c++/11/cwchar(148): error: the global scope has no "fwide"

/usr/include/c++/11/cwchar(149): error: the global scope has no "fwprintf"

/usr/include/c++/11/cwchar(150): error: the global scope has no "fwscanf"

/usr/include/c++/11/cwchar(151): error: the global scope has no "getwc"

/usr/include/c++/11/cwchar(152): error: the global scope has no "getwchar"

/usr/include/c++/11/cwchar(153): error: the global scope has no "mbrlen"

/usr/include/c++/11/cwchar(154): error: the global scope has no "mbrtowc"

/usr/include/c++/11/cwchar(155): error: the global scope has no "mbsinit"

/usr/include/c++/11/cwchar(156): error: the global scope has no "mbsrtowcs"

/usr/include/c++/11/cwchar(157): error: the global scope has no "putwc"

/usr/include/c++/11/cwchar(158): error: the global scope has no "putwchar"

/usr/include/c++/11/cwchar(160): error: the global scope has no "swprintf"

/usr/include/c++/11/cwchar(162): error: the global scope has no "swscanf"

/usr/include/c++/11/cwchar(163): error: the global scope has no "ungetwc"

/usr/include/c++/11/cwchar(164): error: the global scope has no "vfwprintf"

/usr/include/c++/11/cwchar(166): error: the global scope has no "vfwscanf"

/usr/include/c++/11/cwchar(169): error: the global scope has no "vswprintf"

/usr/include/c++/11/cwchar(172): error: the global scope has no "vswscanf"

/usr/include/c++/11/cwchar(174): error: the global scope has no "vwprintf"

/usr/include/c++/11/cwchar(176): error: the global scope has no "vwscanf"

/usr/include/c++/11/cwchar(178): error: the global scope has no "wcrtomb"

/usr/include/c++/11/cwchar(179): error: the global scope has no "wcscat"

/usr/include/c++/11/cwchar(180): error: the global scope has no "wcscmp"

/usr/include/c++/11/cwchar(181): error: the global scope has no "wcscoll"

/usr/include/c++/11/cwchar(182): error: the global scope has no "wcscpy"

/usr/include/c++/11/cwchar(183): error: the global scope has no "wcscspn"

/usr/include/c++/11/cwchar(184): error: the global scope has no "wcsftime"

/usr/include/c++/11/cwchar(185): error: the global scope has no "wcslen"

/usr/include/c++/11/cwchar(186): error: the global scope has no "wcsncat"

/usr/include/c++/11/cwchar(187): error: the global scope has no "wcsncmp"

/usr/include/c++/11/cwchar(188): error: the global scope has no "wcsncpy"

/usr/include/c++/11/cwchar(189): error: the global scope has no "wcsrtombs"

/usr/include/c++/11/cwchar(190): error: the global scope has no "wcsspn"

/usr/include/c++/11/cwchar(191): error: the global scope has no "wcstod"

/usr/include/c++/11/cwchar(193): error: the global scope has no "wcstof"

/usr/include/c++/11/cwchar(195): error: the global scope has no "wcstok"

/usr/include/c++/11/cwchar(196): error: the global scope has no "wcstol"

/usr/include/c++/11/cwchar(197): error: the global scope has no "wcstoul"

/usr/include/c++/11/cwchar(198): error: the global scope has no "wcsxfrm"

/usr/include/c++/11/cwchar(199): error: the global scope has no "wctob"

/usr/include/c++/11/cwchar(200): error: the global scope has no "wmemcmp"

/usr/include/c++/11/cwchar(201): error: the global scope has no "wmemcpy"

/usr/include/c++/11/cwchar(202): error: the global scope has no "wmemmove"

/usr/include/c++/11/cwchar(203): error: the global scope has no "wmemset"

/usr/include/c++/11/cwchar(204): error: the global scope has no "wprintf"

/usr/include/c++/11/cwchar(205): error: the global scope has no "wscanf"

/usr/include/c++/11/cwchar(206): error: the global scope has no "wcschr"

/usr/include/c++/11/cwchar(207): error: the global scope has no "wcspbrk"

/usr/include/c++/11/cwchar(208): error: the global scope has no "wcsrchr"

/usr/include/c++/11/cwchar(209): error: the global scope has no "wcsstr"

/usr/include/c++/11/cwchar(210): error: the global scope has no "wmemchr"

/usr/include/c++/11/cwchar(251): error: the global scope has no "wcstold"

/usr/include/c++/11/cwchar(260): error: the global scope has no "wcstoll"

/usr/include/c++/11/cwchar(261): error: the global scope has no "wcstoull"

Error limit reached.
100 errors detected in the compilation of "lib/kernel.cu".
Compilation terminated.
```

Any ideas ?

### System info (python version, jaxlib version, accelerator, etc.)

```
import jax 
jax.print_environment_info()

jax:    0.4.25
jaxlib: 0.4.25
numpy:  1.26.4
python: 3.11.8 (main, Feb 22 2024, 16:59:22) [GCC 12.2.0]
jax.devices (1 total, 1 local): [cuda(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='morbier', release='6.1.0-13-amd64', version='#1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)', machine='x86_64')


$ nvidia-smi
Thu Aug  8 16:36:35 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  Off |
| 30%   42C    P2    87W / 450W |  15114MiB / 24564MiB |     57%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   2331728      C   ...imulations/bin/python3.11     9300MiB |
|    0   N/A  N/A   2384088      C   ...ons/3.11.9/bin/python3.11     3110MiB |
|    0   N/A  N/A   2389131      C   ...vs/simulations/bin/python     1286MiB |
|    0   N/A  N/A   2390527      C   ...vs/simulations/bin/python     1028MiB |
|    0   N/A  N/A   2391125      C   ...ons/3.11.8/bin/python3.11      386MiB |
+-----------------------------------------------------------------------------+

```

**Comment by dfm** [comment] 2024-08-08 14:43
We have recently updated the recommended approach for implementing custom calls like this and the new docs are here: https://jax.readthedocs.io/en/latest/ffi.html

You'll need to update to the most recent version of JAX to get that working, but how about you give that a try first.

If that doesn't work, please try to put together a minimal reproducible example that demonstrates the issue. At a high level this doesn't really seem like a JAX issue since the errors are raised when compiling your library, but I'm happy to try to help if you can isolate the minimal scope problem.

**Comment by bsaoptima** [comment] 2024-08-09 09:06
Thank you for this information, it is really helpful. Just a small question before I can make a minimal example that is relevant. The CMakeLists.txt works for a `.cc` file but does it also work as it is for a `.cu` file because it seems like it cannot detect the language.

**Comment by bsaoptima** [comment] 2024-08-09 09:46
Thank for this information, this is really helpful. I am trying to reproduce the tutorial for my own kernel in CUDA and I have a conversion error. Here is the `.cu` file:

```
namespace ffi = xla::ffi;

__global__ void matmul(int64_t N, int64_t diag_number, const float *A, const float *offsets, const float *B, float *C){
    int row = blockIdx.y * blockDim.y + threadIdx.y;
    int col = blockIdx.x * blockDim.x + threadIdx.x;

    if (row < N && col < N){
        for (int i = 0; i < diag_number; i++){
            int offset = static_cast<int>(offsets[i]);
            bool isOffsetPositive = (offset > 0);
            if (isOffsetPositive){
                if (row < N - offset){
                    C[row * N + col] += A[row+i*N+offset] * B[row*N+col+offset*N];
                }
            } else {
                if (row < N + offset) {
                    C[row*N+col-offset*N] += A[row+i*N] * B[row*N+col];
                }
            }
        }
    }
}

template <ffi:: DataType T>
std::pair<int64_t, int64_t> GetDims(const ffi::Buffer<T> &buffer){
    auto dims = buffer.dimensions();
    if (dims.size() == 0){
        return std::make_pair(0, 0);
    }
    return std::make_pair(buffer.element_count(), dims.back());
}

ffi::Error MatmulDIAImpl(
    cudaStream_t stream, 
    int64_t diag_number,
    ffi::Buffer<ffi::DataType::F32> A,
    ffi::Buffer<ffi::DataType::F32> offsets,
    ffi::Buffer<ffi::DataType::F32> B,
    ffi::Result<ffi::Buffer<ffi::DataType::F32>> C
){
    auto [totalSize, lastDim] = GetDims(A);
    
    const int block_size = 32;

    dim3 block(block_size * block_size);
    dim3 grid(lastDim/block_size, lastDim/block_size);
    
    matmul<<<grid, block, 0, stream>>>(lastDim, diag_number, A, offsets, B, C);

    return ffi::Error::Success();
}
```

And when I run the command :  ̀cmake --build ffi/_build`, I will get the following error:
```
error: no suitable conversion function from "xla::ffi::Buffer<xla::ffi::DataType::F32, 18446744073709551615UL>" to "const float *" exists
```

I don't know if this is the best minimal reproductible example but it is pretty minimal in what I am trying to do :)

**Comment by superbobry** [comment] 2024-08-09 10:50
It looks like you are passing an `ffi::Buffer` to `matmul` directly instead of its `.typed_data()`.

**Comment by dfm** [comment] 2024-09-03 10:13
@bsaoptima — I'm going to close this issue because I think we got to the bottom of it for now. Please open new issues if you run into further problems!

**Closed by dfm** 2024-09-03 10:13 UTC
Labels: bug
