### ISSUE TITLE
Build failure during bazel/cuda configuration step

### ISSUE THREAD

**Issue by CharlesJQuarra** [google/jax#2222] opened 2020-02-13 21:41 UTC
I am getting some hard to understand CUDA configuration errors when trying to build a docker image with gpu support for JAX:

```
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/user/jax/.bazelrc:
  Inherited 'build' options: --repo_env PYTHON_BIN_PATH=/home/user/miniconda/envs/py37/bin/python --python_path=/home/user/miniconda/envs/py37/bin/python --repo_env TF_NEED_CUDA=1 --distinct_host_configuration=false --copt=-Wno-sign-compare -c opt --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --spawn_strategy=standalone --strategy=Genrule=standalone --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --action_env CUDA_TOOLKIT_PATH=/home/user/miniconda/envs/py37/pkgs/cudatoolkit-dev/ --action_env CUDNN_INSTALL_PATH=/home/user/miniconda/envs/py37/
INFO: Found applicable config definition build:mkl_open_source_only in file /home/user/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/user/jax/.bazelrc: --crosstool_top=@local_config_cuda//crosstool:toolchain --define=using_cuda=true --define=using_cuda_nvcc=true
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at /home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1171:18):
 - /home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/tensorflow/workspace.bzl:87:5
 - /home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/tensorflow/workspace.bzl:77:5
 - /home/user/jax/WORKSPACE:46:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1169
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 990, in _create_local_cuda_repository
		find_cc(repository_ctx)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 231, in find_cc
		which(repository_ctx, cc_name)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/remote_config/common.bzl", line 202, in execute
		fail(<1 more arguments>)
Repository command failed

ERROR: Skipping ':install_xla_in_source_tree': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1169
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 990, in _create_local_cuda_repository
		find_cc(repository_ctx)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 231, in find_cc
		which(repository_ctx, cc_name)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/remote_config/common.bzl", line 202, in execute
		fail(<1 more arguments>)
Repository command failed

WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1169
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 990, in _create_local_cuda_repository
		find_cc(repository_ctx)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 231, in find_cc
		which(repository_ctx, cc_name)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/user/.cache/bazel/_bazel_root/978affdf8ff894b13b5d5eb8bc6c5fdc/external/org_tensorflow/third_party/remote_config/common.bzl", line 202, in execute
		fail(<1 more arguments>)
Repository command failed

INFO: Elapsed time: 81.543s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)
``` 

Here is the Dockerfile:

```
FROM nvidia/cuda:10.2-base-ubuntu16.04

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
 && rm -rf /var/lib/apt/lists/*

# Create a working directory
RUN mkdir /app
WORKDIR /app

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /app
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user

# All users can use /home/user as their home directory
ENV HOME=/home/user

RUN chown -R user:user /home/user && ls -ltah /home/user/ && chmod 770 /home/user

# Install Miniconda
RUN curl -so ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh
ENV PATH=/home/user/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false


# Create a Python 3.7 environment
RUN /home/user/miniconda/bin/conda create -y --name py37 python=3.7.2 \
 && /home/user/miniconda/bin/conda clean -ya



ENV CONDA_DEFAULT_ENV=py37
ENV CONDA_PREFIX=/home/user/miniconda/envs/$CONDA_DEFAULT_ENV
ENV PATH=$CONDA_PREFIX/bin:$PATH
RUN /home/user/miniconda/bin/conda info
RUN /home/user/miniconda/bin/conda install conda-build=3.18.11=py37_0 \
 && /home/user/miniconda/bin/conda clean -ya

# CUDA 9.2-specific steps

RUN conda config --set unsatisfiable_hints True \
 && conda search -c conda-forge cudnn \
 && conda install -c conda-forge cudatoolkit=9.2 cudatoolkit-dev=9.2 \
 && conda install -c conda-forge cudnn=7.6.5 \
 && conda clean -ya

RUN pip install numpy scipy cython pytest-xdist pytest-benchmark


RUN cd /home/user && git clone https://github.com/google/jax && cd /home/user/jax \
 && python build/build.py --enable_cuda --cuda_path /home/user/miniconda/envs/py37/pkgs/cudatoolkit-dev/ --cudnn_path ~/miniconda/envs/py37/ \
 && pip install -e build \
 && pip install -e . \
 && pytest -n auto tests \
 && rm -rf /home/user/jax



# Set the default command to python3
CMD ["python3"]
```

**Comment by hawkinsp** [comment] 2021-11-29 15:56
Sorry we never looked into this! Closing because it's probably not worth trying to reproduce it now: too many things have changed, so if we see something like this again we'd probably do best to open a new issue. Thanks!

**Closed by hawkinsp** 2021-11-29 15:56 UTC
Labels: build

**Comment by saisurbehera** [comment] 2022-08-17 21:43
Did you get it working? I have the same error!

**Comment by hawkinsp** [comment] 2022-08-17 21:44
@saisurbehera Please open a new bug with a complete description of your problem.
