### ISSUE TITLE
NotImplementedError: Forward-mode differentiation rule for 'svd' not implemented

### ISSUE THREAD

**Issue by jkitchin** [google/jax#647] opened 2019-04-28 00:35 UTC
I tried getting the inverse (related to issue #646), and it worked fine sort of. Here is some pseudocode of what I was trying to do.

```
def get_distances(...):
  svd code here to get inverse matrix
  return distances

def energy(params, positions, cell):
   get distances, do calculation
   return energy

def forces(params, positions, cell):
    dedr = grad(energy, 1)
    return -dedr(...)  # works fine

def stress(params, position, cell):
   def e0(params, positions, cell, strain):
       modify positions and cell with strain
       return energy(params, newpositions, newcell)

   deds = grad(e0, 3)
   return deds(params, positions, cell, np.zeros(3)) 
```

The last function gave me this error:
`NotImplementedError: Forward-mode differentiation rule for 'svd' not implemented`

I guess the issue is that the strain modifies the cell, which is the array I need an inverse of, and this triggers the need for a derivative through the svd, and it is evidently not implemented.

It seems like a clear error, so this is mostly a report I guess that it is not implemented. It isn't obvious where that would be done. Any hints?

**Comment by mattjj** [comment] 2019-04-28 01:20
Thanks for the report!

I think this might be a duplicate of #508. What do you think?

We haven't written documentation on how to implement differentiation rules in JAX (it's on the TODO list!), but [here's the analogous rule for Cholesky](https://github.com/google/jax/blob/5edb23679f2605654949156da84e330205840695/jax/lax_linalg.py#L80-L91). Another set of clues might be [the Autograd reverse-mode rules for SVD](https://github.com/HIPS/autograd/blob/e3b525302529d7490769d5c0bcfc7457e24e3b3e/autograd/numpy/linalg.py#L134), though the hints from Jamie in #508 might be more useful.

**Comment by mattjj** [comment] 2019-04-28 01:21
We prioritize features based on user demand, so requests are super helpful. Is this blocking your work?

**Comment by jkitchin** [comment] 2019-04-28 16:16
It is issue #646 that is more problematic for me. For this particular project I need something equivalent to a differentiable inverse.  I was trying this as a workaround to that issue. At the moment I have a hard coded solution for a 3x3 matrix that works, and an approach using LU decomposition but it is a specific hack on this problem.

**Comment by hawkinsp** [comment] 2019-04-30 14:22
I wouldn't say using an LU decomposition is a hack; LU decomposition requires fewer FLOPs than QR decomposition, so we should probably just use that LU implementation instead of the current `inv` implementation. The main reason we don't is that we only have an LU implementation on CPU at the moment (not, say, GPU).

**Comment by jkitchin** [comment] 2019-04-30 15:19
I meant the hard coded solution for the 3x3 was the specific hack on this problem. Specific in the sense that it only works for a 3x3 case. The LU solution is fine. The whole exercise has been a reminder on why it is often good there is more than one way to do it!

**Comment by mattjj** [comment] 2019-04-30 23:20
Let's close this issue as a duplicate of #508.

**Closed by mattjj** 2019-04-30 23:20 UTC
Labels: enhancement
