### ISSUE TITLE
pmap with different types of GPUs

### ISSUE THREAD

**Issue by neon5d** [google/jax#1509] opened 2019-10-15 16:03 UTC
I tested spmd_mnist_classifier_fromscratch.py.
It seems pmap doesn't support parallelization among different types of GPUs:
Tesla <-> Quadro <-> Gtx
Nvidia NCCL can support this configuration.
Do you have any plan to support parallelization among different types of GPUs?

**Comment by mattjj** [comment] 2019-10-15 22:40
AIUI this is a question best fielded by the XLA:GPU team, since JAX just exposes XLA's multi-GPU support. However, my guess is that the answer is probably "no, there are no plans to support this in the near future" because the XLA (and hence JAX / `pmap`) programming model is to compile one program and replicate it over identical devices.

I'll ping the XLA:GPU team to see what they think.

**Comment by mattjj** [comment] 2019-10-18 23:12
I confirmed with the XLA team that my above summary is roughly accurate.

I also don't know the details, but luckily [all of XLA:GPU is open-source](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/xla/service/gpu) (under the TensorFlow repository), so if you'd like to dig into the details you should start there!

I'll close the issue here because we've confirmed that JAX's `pmap` won't work with different types of GPUs (until XLA does).

**Closed by mattjj** 2019-10-18 23:12 UTC
Labels: question
