### ISSUE TITLE
Cannot jit np.cumsum

### ISSUE THREAD

**Issue by EddieCunningham** [google/jax#3084] opened 2020-05-13 19:28 UTC
There seems to be a bug in np.cumsum.  I get this error message when I run
`jit(np.cumsum)(np.arange(5))`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:

TypeError: cumulative_reduction() got an unexpected keyword argument 'out'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-10-4a4ec31680bb> in <module>
----> 1 jit(np.cumsum)(np.arange(5))

/opt/conda/lib/python3.7/site-packages/jax/api.py in f_jitted(*args, **kwargs)
    152     flat_fun, out_tree = flatten_fun(f, in_tree)
    153     out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend,
--> 154                        name=flat_fun.__name__)
    155     return tree_unflatten(out_tree(), out)
    156 

/opt/conda/lib/python3.7/site-packages/jax/core.py in _call_bind(processor, post_processor, primitive, f, *args, **params)
   1019   if top_trace is None:
   1020     with new_sublevel():
-> 1021       outs = primitive.impl(f, *args, **params)
   1022   else:
   1023     tracers = map(top_trace.full_raise, args)

/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py in _xla_call_impl(fun, device, backend, name, *args)
    519 
    520 def _xla_call_impl(fun: lu.WrappedFun, *args, device, backend, name):
--> 521   compiled_fun = _xla_callable(fun, device, backend, name, *map(arg_spec, args))
    522   try:
    523     return compiled_fun(*args)

/opt/conda/lib/python3.7/site-packages/jax/linear_util.py in memoized_fun(fun, *args)
    219       fun.populate_stores(stores)
    220     else:
--> 221       ans = call(fun, *args)
    222       cache[key] = (ans, fun.stores)
    223     return ans

/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py in _xla_callable(fun, device, backend, name, *arg_specs)
    536   pvals: Sequence[pe.PartialVal] = [pe.PartialVal.unknown(aval) for aval in abstract_args]
    537   jaxpr, pvals, consts = pe.trace_to_jaxpr(
--> 538       fun, pvals, instantiate=False, stage_out=True, bottom=True)
    539   jaxpr, uses_outfeed = apply_outfeed_rewriter(jaxpr)
    540   _map(prefetch, it.chain(consts, jaxpr_literals(jaxpr)))

/opt/conda/lib/python3.7/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr(fun, pvals, instantiate, stage_out, bottom, trace_type)
    436   with new_master(trace_type, bottom=bottom) as master:
    437     fun = trace_to_subjaxpr(fun, master, instantiate)
--> 438     jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
    439     assert not env
    440     del master

/opt/conda/lib/python3.7/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    148     gen = None
    149 
--> 150     ans = self.f(*args, **dict(self.params, **kwargs))
    151     del args
    152     while stack:

<__array_function__ internals> in cumsum(*args, **kwargs)

~/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py in cumsum(a, axis, dtype, out)
   2468 
   2469     """
-> 2470     return _wrapfunc(a, 'cumsum', axis=axis, dtype=dtype, out=out)
   2471 
   2472 

~/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     68         # Call _wrapit from within the except clause to ensure a potential
     69         # exception has a traceback chain.
---> 70         return _wrapit(obj, method, *args, **kwds)
     71 
     72 

~/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     45     except AttributeError:
     46         wrap = None
---> 47     result = getattr(asarray(obj), method)(*args, **kwds)
     48     if wrap:
     49         if not isinstance(result, mu.ndarray):

~/.local/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

/opt/conda/lib/python3.7/site-packages/jax/core.py in __array__(self, *args, **kw)
    372 
    373   def __array__(self, *args, **kw):
--> 374     raise Exception("Tracer can't be used with raw numpy functions. "
    375                     "You might have\n"
    376                     "  import numpy as np\n"

Exception: Tracer can't be used with raw numpy functions. You might have
  import numpy as np
instead of
  import jax.numpy as jnp

This was run with jax version 0.1.67 with jaxlib version 0.1.47.

**Comment by jakevdp** [comment] 2020-05-13 19:44
It appears that you're trying to jit ``numpy.cumsum`` rather than ``jax.numpy.cumsum``. Only jax functions can be jitted. Try the following:
```python
from jax import jit
import jax.numpy as jnp
jit(jnp.cumsum)(jnp.arange(5))
```

**Comment by hawkinsp** [comment] 2020-05-13 19:48
Closing, since this seems to be working as intended. The exception correctly describes the problem; perhaps there is a way to improve the wording that might have helped uncover the problem sooner? Suggestions welcome!

**Closed by hawkinsp** 2020-05-13 19:48 UTC

**Comment by EddieCunningham** [comment] 2020-05-13 19:50
I found that I had imported jax.numpy as np and later, through an import *, imported numpy as np.  That was a dumb mistake, thanks for the help!
