### ISSUE TITLE
Extending jax.checkpoint

### ISSUE THREAD

**Issue by sriharikrishna** [google/jax#4285] opened 2020-09-14 20:41 UTC
I would like to extend the `jax.checkpoint` aprroach to implement [binomial checkpointing](https://dl.acm.org/doi/10.1145/347837.347846) for computing the `vjp` of a time stepping loop the performs computation in step():
```
  def timestep(A,N):
    for i in range(N):
      A = step(A,i)
```
The`remat` approach, as I understand it, generates a version of a function that stores inputs of the function and none of the linearization points. For the `vjp` calculation, it reruns the function calculation thereby regenerating the intermediate linearization points.  

If I use `remat` for `step(A,i), then for each `i`, the arguments to `step(A,i)` will be stored. This is not what I want, because in my test case, `A` is very large. 

An alternate scheme such as binomial checkpointing can use some criterion to decide for which `i` to store the inputs instead of storing each them for each `i`. This allows for different tradeoffs between storage and recomputation. To implement such a checkpointing scheme, the following actions will need to be performed:

1. Store argument of step(A,i)
2. Restore arguments of step(Ai,)
3. Run step(i) without storing/restoring arguments based on step(A,i-1)’s completion.
4. Compute jvp for step(i) assuming that output of jvp(A,i+1)  and is available

Does this seem feasible to implement on top of the existing remat approach? 
Are there any suggestions on how to go about it?

**Comment by jekbradbury** [comment] 2020-09-15 01:26
Remat itself can apply to general JAX functions that might not be straightforwardly broken down into steps, or for which estimating the costs of steps might be difficult. But JAX loop primitives like `lax.scan` and `lax.while_loop` will typically have similar cost per step, so implementing a binomially-checkpointed scan might be a good place to start? (Although scan itself is among the more complicated parts of the JAX codebase.)
See also https://github.com/google/jax/issues/2139.

**Comment by apaszke** [comment] 2020-09-21 17:30
This seems like a reasonable thing to have, so I started hacking on an implementation which I submitted as #4363. Right now the cost model is overly simple and it won't be able to handle loops that are not unrolled in jaxprs (i.e. your program is fine, but `lax.scan` will be counted as a single instruction). But this should not be very difficult to fix. I'll try do get that working tomorrow.

**Comment by mattjj** [comment] 2020-09-21 18:10
Tangentially, take a look at Example 5 in the PR message of #1749, which shows how you can use `jax.remat` recursively to manually implement divide-and-conquer / bisection checkpointing. I'll also copy it below for posterity.

That approach is "manual" in that you need to organize your code a certain way. (Also it only exists buried in a PR comment!) Adam's #4363 is superior in that you can just apply it to a function and it will do the program slicing for you. And over time we could make it smart about that slicing.

One detail is the difference between "binomial checkpointing" in the Griewank and Walther sense and divide-and-conquer / bisection / recursive checkpointing. I think the former may involve an explicit cost model for selecting the checkpoints.

In any case, great idea to start improving and flexing our AD capabilities here!

Copied from #1749:

### Example 5: recursive checkpointing

```python
def recursive_checkpoint(funs):
  if len(funs) == 1:
    return funs[0]
  elif len(funs) == 2:
    f1, f2 = funs
    return lambda x: f1(f2(x))
  else:
    f1 = recursive_checkpoint(funs[:len(funs)//2])
    f2 = recursive_checkpoint(funs[len(funs)//2:])
    return lambda x: f1(remat(f2)(x))

# forward pass
f = recursive_checkpoint([np.cos, np.sin, np.cos, np.sin])
print(make_jaxpr(f)(4.))

# forward and backward pass
f = recursive_checkpoint([np.sin, np.sin, np.sin, np.sin])
print(make_jaxpr(value_and_grad(f))(4.))

# longer forward pass
f = recursive_checkpoint([np.cos, np.sin, np.cos, np.sin,
                          np.cos, np.sin, np.cos, np.sin])
print(make_jaxpr(f)(4.))
```

```
# forward pass
{ lambda  ;  ; a.
  let b = remat_call[ concrete=False ] a
        { lambda  ;  ; a.
          let b = sin a
              c = cos b
          in [c] } [  ;  ]
      c = sin b
      d = cos c
  in [d] }

# forward and backward pass
{ lambda  ;  ; a.
  let b = sin a
      c = sin b
      d = sin c
      e = sin d
      f = cos d
      g = mul 1.0 f
      h = cos c
      i = mul g h
      j = remat_call[ concrete=False ] a i
        { lambda  ;  ; a b.
          let c = sin a
              d = cos c
              e = mul b d
              f = cos a
              g = mul e f
          in [g] } [  ;  ]
  in [e, j] }

# longer forward pass
{ lambda  ;  ; a.
  let b = remat_call[ concrete=False ] a
        { lambda  ;  ; a.
          let b = remat_call[ concrete=False ] a
                { lambda  ;  ; a.
                  let b = sin a
                      c = cos b
                  in [c] } [  ;  ]
              c = sin b
              d = cos c
          in [d] } [  ;  ]
      c = remat_call[ concrete=False ] b
        { lambda  ;  ; a.
          let b = sin a
              c = cos b
          in [c] } [  ;  ]
      d = sin c
      e = cos d
  in [e] }
```

**Comment by patrick-kidger** [comment] 2023-02-22 02:09
For anyone following this old thread: I put together an efficient implementation of (online) recursive checkpointing, see also [this comment](https://github.com/google/jax/issues/2139#issuecomment-1439334364).

**Comment by apaszke** [comment] 2023-02-22 10:23
Thanks, Patrick. I think we can close it as a duplicate of #2139 too.

**Closed by apaszke** 2023-02-22 10:23 UTC
