### ISSUE TITLE
jax 0.4.6 does not provide the extra 'cuda12_pip' | No GPU/TPU found, falling back to CPU

### ISSUE THREAD

**Issue by mriamnobody** [google/jax#17634] opened 2023-09-17 10:12 UTC
### Description

I came to Jax's repository looking for a solution because I was facing an issue with another repository. Jax was one of the dependencies of that repository. No matter what I try or do, I get the following error.
```
 C:\Users\rosha\Downloads\Compressed\appp>pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Collecting jax[cuda12_pip]
  Using cached jax-0.4.14-py3-none-any.whl
Collecting ml-dtypes>=0.2.0
  Using cached ml_dtypes-0.2.0-cp310-cp310-win_amd64.whl (938 kB)
Collecting opt-einsum
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting numpy>=1.22
  Using cached numpy-1.26.0-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting scipy>=1.7
  Using cached scipy-1.11.2-cp310-cp310-win_amd64.whl (44.0 MB)
Collecting nvidia-cufft-cu12
  Using cached nvidia_cufft_cu12-11.0.8.103-py3-none-win_amd64.whl (99.0 MB)
Collecting nvidia-cublas-cu12
  Using cached nvidia_cublas_cu12-12.2.5.6-py3-none-win_amd64.whl (450.5 MB)
Collecting nvidia-cuda-cupti-cu12
  Using cached nvidia_cuda_cupti_cu12-12.2.142-py3-none-win_amd64.whl (9.9 MB)
Collecting nvidia-cuda-runtime-cu12
  Using cached nvidia_cuda_runtime_cu12-12.2.140-py3-none-win_amd64.whl (842 kB)
Collecting nvidia-cudnn-cu12>=8.9
  Using cached nvidia_cudnn_cu12-8.9.4.25-py3-none-win_amd64.whl (734.8 MB)
Collecting nvidia-cusolver-cu12
  Using cached nvidia_cusolver_cu12-11.5.2.141-py3-none-win_amd64.whl (122.2 MB)
Collecting nvidia-cuda-nvcc-cu12
  Using cached nvidia_cuda_nvcc_cu12-12.2.140-py3-none-win_amd64.whl (15.9 MB)
Collecting jax[cuda12_pip]
  Using cached jax-0.4.13.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached jax-0.4.12.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached jax-0.4.11.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached jax-0.4.10.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached jax-0.4.9.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached jax-0.4.8.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached jax-0.4.7.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached jax-0.4.6.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
WARNING: jax 0.4.6 does not provide the extra 'cuda12_pip'
Using legacy 'setup.py install' for jax, since package 'wheel' is not installed.
Installing collected packages: numpy, scipy, opt-einsum, jax
  Running setup.py install for jax ... done
Successfully installed jax-0.4.6 numpy-1.26.0 opt-einsum-3.3.0 scipy-1.11.2
```

And at the end, jax with cuda is not being installed. I have tried the workarounds provided in the issues section of the repository but no success. 

Edit 1: I made a mistake. Without carefully reading the installation guide, I installed CUDA V12.2 but as the installation guide says:

```
JAX currently ships two CUDA wheel variants:

CUDA 12.0 and CuDNN 8.9.
CUDA 11.8 and CuDNN 8.6.
```

so I removed the CUDA V12.2 and installed V12.0. I also downloaded `cudnn` files and placed them in `lib`, `include` and `bin` folder but still the same output.

Edit 2: I made a change to `pip` command `pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` and remove `_pip` after `cuda12` and the installed completed though not successfully. Instead, the v0.4.14 was installed in one go rather than cycling though the older versions and trying to install them.

Edit 3: I used the following script to check whether GPU is present [cuda is installed]:

```
import jax

devices = jax.devices()

gpu_present = any(device.device_kind == 'gpu' for device in devices)

if gpu_present:
    print("GPU is present.")
else:
    print("No GPU detected.")
```
and the output is:

```
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
No GPU detected.
```

Edit 4: Below is the output of `pip list` after installing `jax` and others packages (there was no conflict of packages),

![Screenshot (2579)](https://github.com/google/jax/assets/14347205/19470da6-a8de-464b-a02b-dde8499f7a1c)

### What jax/jaxlib version are you using?

jax v04.14, jaxlib v0.4.14

### Which accelerator(s) are you using?

Nvidia 3090 Ti

### Additional system info

Python: 3.10.7, OS(Windows 11)

### NVIDIA GPU info

![Screenshot (2577)](https://github.com/google/jax/assets/14347205/6fd4e126-6579-41ed-afb1-8738b51c7970)

**Comment by hawkinsp** [comment] 2023-09-17 16:49
JAX does not provide CUDA-enabled wheels on Windows (https://github.com/google/jax#installation).

Closing, since this is working as intended: pip will not succeed because there aren't any wheels to install.

**Closed by hawkinsp** 2023-09-17 16:49 UTC
Labels: bug

**Comment by mriamnobody** [comment] 2023-09-17 16:55
Thanks @hawkinsp for clarifying. I opened another issue due to the error I'm receiving while building jax (cuda enabled) for Windows. https://github.com/google/jax/issues/17635. So does it mean that there is no official support for the Cuda-enabled builds for Windows?

**Comment by hawkinsp** [comment] 2023-09-17 19:25
Correct, there is no support from us (the JAX core team) for CUDA enabled builds on Windows. We release CPU-only wheels on Windows, and even those are best effort. But we welcome PRs to fix things!
