### ISSUE TITLE
Jax saves forward-pass intermediate values under lax.stop_gradient

### ISSUE THREAD

**Issue by C-J-Cundy** [google/jax#4853] opened 2020-11-10 08:48 UTC
The following code illustrates the problem:

```
import jax
import jax.numpy as jnp
from jax import jit, grad

num_iters = 10_000
dim = 1_000

def long_scan(X):
  def scan_inner(carry, _):
    return carry @ X, None
  
  carry, _ = jax.lax.scan(scan_inner, X, None, length=num_iters)
  return carry

@jit
def outer(x):
  scan_out = long_scan(x)
  scan_out = jax.lax.stop_gradient(scan_out)
  return jnp.sum(x @ scan_out)

input_matrix = jax.random.normal(jax.random.PRNGKey(0), shape=(dim, dim))
outer(input_matrix).block_until_ready()
print('Does forward pass OK')
grad(outer)(input_matrix).block_until_ready()
```

When run on the colab GPU we get `RuntimeError: Resource exhausted: Out of memory while trying to allocate 40004000128 bytes.` More generally, the memory usage scales with the length of the scan. As far as I understand, normally that makes sense--the intermediate values have to be saved for the reverse pass of the grad. But here, those intermediate values are never used because of the `stop gradient`. 

I think we can avoid the memory growth by using `remat(scan_inner)` instead of `scan_inner` inside the scan (like in #3186), but it would be great if jax could automatically do this, since we should never need the intermediate values. 

The actual use-case is adversarial training, where the `long_scan` computes adversarial inputs for a model but we don't take the gradient wrt the model parameters through the process of computing those inputs.

**Comment by shoyer** [comment] 2020-11-10 17:00
Have you tried `long_scan(stop_gradient(x))` instead?

`stop_gradient()` actually get applied during the JVP calculation from the forward pass

**Comment by C-J-Cundy** [comment] 2020-11-10 17:46
`long_scan(stop_gradient(x))` also runs out of memory.
I can get it to not save intermediate values by using a version of `long_scan` with `scan_inner` stopping the gradient in each iteration:

```
def long_scan_stopped(X):
  def scan_inner(carry, _):
    return jax.lax.stop_gradient(carry @ X), jax.lax.stop_gradient(None)
  
  carry, _ = jax.lax.scan(scan_inner, X, None, length=num_iters)
  return carry
```

It would be nice if jax could do this automatically though, since it seems like a bug if it's storing intermediate values that we know are never used.

**Comment by mattjj** [comment] 2020-11-10 20:43
Are you willing to put a `jit` on the outside, as in `jit(grad(outer))(input_matrix)`? That way XLA will do the memory pruning for you.

**Comment by mattjj** [comment] 2020-11-10 21:59
It's really surprising to me that @shoyer's suggestion didn't work!

Here's a look at the forward and backward passes of the original code as jaxprs (I tweaked the jaxpr pretty-printing to show us shapes of jaxpr invars and outvars):

```python
import jax
import jax.numpy as jnp
from jax import jit, grad

num_iters = 10_000
dim = 1_000

def long_scan(X):
  def scan_inner(carry, _):
    return carry @ X, None
  
  carry, _ = jax.lax.scan(scan_inner, X, None, length=num_iters)
  return carry

@jit
def outer(x):
  scan_out = long_scan(x)
  scan_out = jax.lax.stop_gradient(scan_out)
  return jnp.sum(x @ scan_out)

input_matrix = jax.random.normal(jax.random.PRNGKey(0), shape=(dim, dim))
outer(input_matrix).block_until_ready()
print('Does forward pass OK')
grad(outer)(input_matrix).block_until_ready()
```

```
=== forward pass ===
{ lambda  ; a:float32[1000,1000].
  let b _ c = xla_call[ backend=None
                        call_jaxpr={ lambda  ; a:float32[1000,1000] b:*.
                                     let c _ _ _ =
                                           scan[ jaxpr={ lambda  ; e:float32[1000,1000] a:* b:* c:float32[1000,1000] d:*.
                                                         let f = dot_general[ dimension_numbers=(((1,), (0,)), ((), ()))
                                                                              precision=None ] c e
                                                         in (f:float32[1000,1000] *:* *:* c:float32[1000,1000]) }
                                                 length=10000
                                                 linear=(False, True, True, False, True)
                                                 num_carry=2
                                                 num_consts=3
                                                 reverse=False
                                                 unroll=1 ] a * * a *
                                         d = stop_gradient c
                                         e = dot_general[ dimension_numbers=(((1,), (0,)), ((), ()))
                                                          precision=None ] a d
                                         f = reduce_sum[ axes=(0, 1) ] e
                                     in (f:float32[] *:* d:float32[1000,1000]) }
                        device=None
                        donated_invars=(False, False)
                        name=jvp(outer) ] a *
  in (b:float32[] c:float32[1000,1000]) }

=== backward pass ===
{ lambda a ; b:float32[].
  let c = xla_call[ backend=None
                    call_jaxpr={ lambda  ; a:float32[1000,1000] b:float32[].
                                 let c = broadcast_in_dim[ broadcast_dimensions=(  )
                                                           shape=(1000, 1000) ] b
                                     d = dot_general[ dimension_numbers=(((1,), (1,)), ((), ()))
                                                      precision=None ] c a
                                 in (d:float32[1000,1000]) }
                    device=None
                    donated_invars=(False, False)
                    name=transpose(jvp(outer)) ] a b
  in (c:float32[1000,1000]) }
```

It's a bit subtle to read, but the fourth `scan` output is going to be of shape `(10000, 1000, 1000)` here. It's unused in the outer jaxpr (which is why it is assigned to an underscore) but it'll still be computed in the forward pass.

Applying @shoyer's suggestion:

```python
import jax
import jax.numpy as jnp
from jax import jit, grad

num_iters = 10_000
dim = 1_000

def long_scan(X):
  def scan_inner(carry, _):
    return carry @ X, None

  carry, _ = jax.lax.scan(scan_inner, X, None, length=num_iters)
  return carry

@jit
def outer(x):
  scan_out = long_scan(jax.lax.stop_gradient(x))
  return jnp.sum(x @ scan_out)

input_matrix = jax.random.normal(jax.random.PRNGKey(0), shape=(dim, dim))

fwd_jaxpr = jax.make_jaxpr(lambda x: jax.vjp(outer, x))(input_matrix)
print('=== forward pass ===')
print(fwd_jaxpr)

output, outer_vjp = jax.vjp(outer, input_matrix)
bwd_jaxpr = jax.make_jaxpr(outer_vjp)(output)
print('=== backward pass ===')
print(bwd_jaxpr)
```

```
=== forward pass ===
{ lambda  ; a:float32[1000,1000].
  let b _ c = xla_call[ backend=None
                        call_jaxpr={ lambda  ; a:float32[1000,1000] b:*.
                                     let c = stop_gradient a
                                         d = scan[ jaxpr={ lambda  ; a:float32[1000,1000] b:float32[1000,1000].
                                                           let c = dot_general[ dimension_numbers=(((1,), (0,)), ((), ()))
                                                                                precision=None ] b a
                                                           in (c:float32[1000,1000]) }
                                                   length=10000
                                                   linear=(False, False)
                                                   num_carry=1
                                                   num_consts=1
                                                   reverse=False
                                                   unroll=1 ] c c
                                         e = dot_general[ dimension_numbers=(((1,), (0,)), ((), ()))
                                                          precision=None ] a d
                                         f = reduce_sum[ axes=(0, 1) ] e
                                     in (f:float32[] *:* d:float32[1000,1000]) }
                        device=None
                        donated_invars=(False, False)
                        name=jvp(outer) ] a *
  in (b:float32[] c:float32[1000,1000]) }

=== backward pass ===
{ lambda a ; b:float32[].
  let c = xla_call[ backend=None
                    call_jaxpr={ lambda  ; a:float32[1000,1000] b:float32[].
                                 let c = broadcast_in_dim[ broadcast_dimensions=(  )
                                                           shape=(1000, 1000) ] b
                                     d = dot_general[ dimension_numbers=(((1,), (1,)), ((), ()))
                                                      precision=None ] c a
                                 in (d:float32[1000,1000]) }
                    device=None
                    donated_invars=(False, False)
                    name=transpose(jvp(outer)) ] a b
  in (c:float32[1000,1000]) }
```

It sure looks to me like the issue is gone: the scan has no scanned-over outputs whatsoever now, and only outputs the final value of the carry.

@C-J-Cundy maybe the OOM issue with `long_scan(stop_gradient(x))` is some other OOM issue? Is it worth double-checking?

**Comment by C-J-Cundy** [comment] 2020-11-10 22:39
@mattjj, you're completely right, @shoyer's suggestion did work. 
I misread the suggestion as ` scan_out = jax.lax.stop_gradient(long_scan(x))` (which didn't work) instead of 
`long_scan(jax.lax.stop_gradient(x))`. My mistake! 🤦‍♀️

Interestingly, it seems like the memory pruning doesn't get done at the XLA level with jit-of-grad.
If I take the initial example and change the last line to 
`jit(grad(outer)((input_matrix).block_until_ready()` then I still get an OOM error.

**Comment by mattjj** [comment] 2020-11-11 05:51
Hrm interesting, I wonder if somehow XLA is missing the optimization.

Glad to hear that putting stop_gradient earlier fixes things! I think that's the best solution; to notice this optimization automatically is tricky in the grad-of-jit situation, basically because grad thinks it's operating eagerly (i.e. it lives in a "dynamic graph" world and doesn't do any compiler-y optimizations). When doing jit-of-grad (or jit-of-grad-of-jit) I'd expect XLA to take care of this optimization for us, but it sounds like it's missing it, at least on the backend you're using.

In general it seems it's a good idea to put stop_gradient as early as possible.

If it's alright with you, I'll close this issue, but let me know if we should reopen it, and don't hesitate to open new issues!

**Closed by mattjj** 2020-11-11 05:51 UTC
Labels: question
