### ISSUE TITLE
Disabling jit for small subsection of code

### ISSUE THREAD

**Issue by proteneer** [google/jax#5041] opened 2020-11-29 16:32 UTC
Is there an easy way to disable jitting for a part of the code only?

``` python
# can't @jax.jit because it contains a non-jittable section
def foo(a):
   b = bar(a) # jittable
   c = scipy.bfgs.minimize(b) # non-jittable
   d = zar(c) # jittable
   return d

```
This can be manually split into two different jit sections
``` python
bar = jax.jit(bar)
zar = jax.jit(zar)
def foo(a):
   b = bar(a)
   c = scipy.bfgs.minimize(b) # non-jittable
   d = zar(c)
   return d
```
However I often have an extremely long call-stack that explicit jitting is very tedious (especially through compositions and custom_vjps) and it would be nice to be able to specify something like ```@jax.nojit```. Not sure how the implementation detail would work though, maybe automatically generate two sets of jaxprs/HLOs that sandwich the non-jittable part?

(and yes, I've tried tfp's bfgs optimizers and unfortunately it is very deficient compared to that of scipy's bfgs)

**Comment by hawkinsp** [comment] 2020-11-30 14:36
We've talked about adding such a feature, but nothing of that form exists at the moment. There's no way to "escape" from a JIT computation and call back into Python at the moment.

**Comment by hawkinsp** [comment] 2020-11-30 21:27
I'm going to close this as a duplicate of #766

**Closed by hawkinsp** 2020-11-30 21:27 UTC
Labels: enhancement

**Comment by proteneer** [comment] 2020-11-30 21:29
Thanks for the follow-up, closing makes sense.
