### ISSUE TITLE
ImportError: cannot import name 'get_metadata' from 'jax._src.cloud_tpu_init' (anaconda3/lib/python3.8/site-packages/jax/_src/clout_tpu_init.py)

### ISSUE THREAD

**Issue by ckc5800** [google/jax#20159] opened 2024-03-11 05:18 UTC
### Description

i just import jax
`import jax` or `from jax import xla_bridge` 

```
Cell In[11], [line 1](vscode-notebook-cell:?execution_count=11&line=1)
----> [1](vscode-notebook-cell:?execution_count=11&line=1) from jax.lib import xla_bridge

File [~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:64](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:64)
     [62](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:62) from .core import eval_context as ensure_compile_time_eval
     [63](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:63) from jax._src.environment_info import print_environment_info as print_environment_info
---> [64](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:64) from jax._src.api import (
     [65](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:65)   ad,  # TODO(phawkins): update users to avoid this.
     [66](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:66)   effects_barrier,
     [67](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:67)   block_until_ready as block_until_ready,
     [68](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:68)   checkpoint as checkpoint,
     [69](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:69)   checkpoint_policies as checkpoint_policies,
     [70](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:70)   clear_backends as clear_backends,
     [71](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:71)   closure_convert as closure_convert,
     [72](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:72)   curry,  # TODO(phawkins): update users to avoid this.
     [73](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:73)   custom_gradient as custom_gradient,
     [74](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:74)   custom_jvp as custom_jvp,
     [75](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:75)   custom_vjp as custom_vjp,
     [76](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:76)   default_backend as default_backend,
     [77](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:77)   device_count as device_count,
     [78](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:78)   device_get as device_get,
     [79](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:79)   device_put as device_put,
     [80](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/__init__.py:80)   device_put_sharded as device_put_sharded,
...
     [20](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/_src/clusters/cloud_tpu_cluster.py:20) class TpuCluster(ClusterEnv):
     [21](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/_src/clusters/cloud_tpu_cluster.py:21)   @classmethod
     [22](https://vscode-remote+ssh-002dremote-002b218-002e232-002e78-002e62.vscode-resource.vscode-cdn.net/home/ys/NLP/~/anaconda3/envs/env1/lib/python3.8/site-packages/jax/_src/clusters/cloud_tpu_cluster.py:22)   def is_env_present(cls) -> bool:

ImportError: cannot import name 'get_metadata' from 'jax._src.cloud_tpu_init' (/anaconda3/envs/env1/lib/python3.8/site-packages/jax/_src/cloud_tpu_init.py)
```

### System info (python version, jaxlib version, accelerator, etc.)

`nvcc -V
`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

`nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
```

`conda list`
```
jax                       0.4.6                    pypi_0    pypi
jaxlib                    0.3.25           py38h6a678d5_1  
```

**Comment by jakevdp** [comment] 2024-03-11 16:08
It looks like you're using mutually incompatible jax & jaxlib packages. jax version 0.4.6 requires at least jaxlib v0.4.4 (see https://github.com/google/jax/blob/jax-v0.4.6/jax/version.py#L19)

I would suggest uninstalling jax & jaxlib, and then starting over with the installation instructions at https://jax.readthedocs.io/en/latest/installation.html to ensure you get mutually-compatible versions.

**Comment by mattjj** [comment] 2024-03-12 19:30
Could you share instructions to reproduce? If not, I agree that the steps to take are just to check versions / reinstall, and we should close the issue.

**Comment by mattjj** [comment] 2024-03-13 22:26
I'm going to close this for lack of a reproducer, but if the problem persists even after following the above advice, please reopen.

**Closed by mattjj** 2024-03-13 22:26 UTC
Labels: bug

**Comment by ckc5800** [comment] 2024-03-18 00:55
> It looks like you're using mutually incompatible jax & jaxlib packages. jax version 0.4.6 requires at least jaxlib v0.4.4 (see https://github.com/google/jax/blob/jax-v0.4.6/jax/version.py#L19)
> 
> I would suggest uninstalling jax & jaxlib, and then starting over with the installation instructions at https://jax.readthedocs.io/en/latest/installation.html to ensure you get mutually-compatible versions.
> 
> After you install new versions, be sure to restart your jupyter/ipython/colab runtime (if applicable) to make sure you are not cacheing the old versions in the runtime.


What you said was the answer. Thank you
Have a nice day.
