### ISSUE TITLE
Incorrect cost_analysis() Flop Count on GPU for Dense layer/Dot product

### ISSUE THREAD

**Issue by m-schier** [google/jax#22249] opened 2024-07-03 10:31 UTC
### Description

When analysing costs of a basic Dense Layer, JAX currently seems to report incorrect FLOPs on GPU. This happens also with `flax.linen.Dense`, however I have eliminated all `flax` references to keep the example minimal and manually implemented the forward:

```python
import jax
import jax.numpy as jnp


@jax.jit
def dense_forward(state, inp):
    k, b = state
    return jnp.squeeze(inp[..., None, :] @ k, -2) + b


rng = jax.random.key(0)  # Reusing for simplicity
dense_state = jax.random.normal(rng, (73, 256)), jax.random.uniform(rng, (256,), minval=-1., maxval=1.)
single_arg = jax.random.normal(jax.random.key(0), shape=(1, 73))

for n in range(1, 10):
    arg = jnp.repeat(single_arg, n, 0)
    compiled = dense_forward.lower(dense_state, arg).compile()
    cost, = compiled.cost_analysis()
    result = compiled(dense_state, arg)
    print(f"{n = }, flops = {cost['flops']}, {result.shape = }")
```

I would expect the (naive) flops to be n * 2 * output_dim * input_dim, which would be 37376 for n=1, however output on GPU is:

```
n = 1, flops = 37376.0, result.shape = (1, 256)
n = 2, flops = 511.0, result.shape = (2, 256)
n = 3, flops = 767.0, result.shape = (3, 256)
n = 4, flops = 1023.0, result.shape = (4, 256)
n = 5, flops = 1279.0, result.shape = (5, 256)
n = 6, flops = 1535.0, result.shape = (6, 256)
n = 7, flops = 1791.0, result.shape = (7, 256)
n = 8, flops = 2047.0, result.shape = (8, 256)
n = 9, flops = 2303.0, result.shape = (9, 256)
```

which only fits for n=1 and gives unreasonable analysis for larger values.
When running with `JAX_PLATFORMS=CPU`, output is:
```
n = 1, flops = 37632.0, result.shape = (1, 256)
n = 2, flops = 75264.0, result.shape = (2, 256)
n = 3, flops = 112896.0, result.shape = (3, 256)
n = 4, flops = 150528.0, result.shape = (4, 256)
n = 5, flops = 188160.0, result.shape = (5, 256)
n = 6, flops = 225792.0, result.shape = (6, 256)
n = 7, flops = 263424.0, result.shape = (7, 256)
n = 8, flops = 301056.0, result.shape = (8, 256)
n = 9, flops = 338688.0, result.shape = (9, 256)
```

For some reason the FLOPS at n=1 is increased by 256, but the output for n>1 is much more reasonable.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.30
jaxlib: 0.4.30
numpy:  2.0.0
python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
jax.devices (1 total, 1 local): [cuda(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='XXX', release='5.14.21-150500.55.68-default', version='#1 SMP PREEMPT_DYNAMIC Wed Jun 5 21:39:05 UTC 2024 (40e256a)', machine='x86_64')


$ nvidia-smi
Wed Jul  3 12:28:29 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:01:00.0 Off |                  N/A |
| 35%   31C    P2              44W / 260W |    159MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     28490      C   python                                      156MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by mattjj** [comment] 2024-07-09 22:41
Thanks for raising this.

I think this may be a duplicate of https://github.com/openxla/xla/issues/10479. That is, the `cost_analysis()` API is just binding an XLA feature into Python. But that XLA feature basically doesn't work, for the reasons cited in that thread.

What do you think?

**Comment by mattjj** [comment] 2024-07-20 17:18
I'm going to close this as a duplicate of https://github.com/openxla/xla/issues/10479, so that we don't split the discussion in multiple places. Thanks for raising it, though.

**Closed by mattjj** 2024-07-20 17:18 UTC
Labels: bug
