### ISSUE TITLE
ImportError: ..... ____chkstk_darwin

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#3867] opened 2020-07-26 19:20 UTC
I got the same issue as #1782 after upgrading jaxlib from `0.1.51` to `0.1.52`.

My system information
+ Mac OS 10.12
+ CPU
+ Python 3.8
+ Install using `pip`

This issue does not happen in previous jaxlib releases in my systems.

**Comment by sebamenabar** [comment] 2020-07-30 19:20
Have the same problem with Mac OS 10.12.6 and Python 3.7.7. First time installed version 0.1.52, raised that exception, downgraded to 0.1.51 and it worked.

**Comment by jemisjoky** [comment] 2020-11-30 03:19
I'm having the same issue with Mac OS 10.13.6 and Python 3.7.3, after upgrading from Jaxlib 0.1.43 to 0.1.57

**Comment by louis925** [comment] 2020-12-08 06:10
Same issue on macOS 10.13.6 and Python 3.6 with the latest jax 0.2.7

**Comment by hawkinsp** [comment] 2021-01-14 14:30
We just pushed jaxlib 0.1.58 wheels, and we verified they do not import this symbol (and added a test to our wheel build that verifies this). Please try them out!

**Comment by moellenh** [comment] 2021-02-05 18:40
I'm trying to build the lastest version of jax from source on macOS 11.2 and am getting the following error:

  File "/private/var/tmp/_bazel_thomas/1ed0249ab046a9ff46b71d477efc0615/execroot/__main__/bazel-out/darwin-opt/bin/build/build_wheel.runfiles/__main__/build/build_wheel.py", line 121, in verify_mac_libraries_dont_reference_chkstack
    raise RuntimeError(
RuntimeError: Mac wheel incorrectly depends on symbol ____chkstk_darwin, which means that it isn't compatible with older MacOS versions.

Could it be related to this issue?

**Comment by hawkinsp** [comment] 2021-02-05 19:07
Yes, it sure is: it's the check we put in to make sure this issue didn't reoccur on our released wheels.

We haven't entirely figured out why that symbol ends up in the binary in some build configurations; the check is a stop gap to make sure we don't regress and break things.

If you are building locally for your own machine, you can just comment out the check (this line: https://cs.opensource.google/jax/jax/+/master:build/build_wheel.py;drc=599d65c5c6054db1b74ee232303c4a6adc5c9009;l=132 ). The only downside is that the wheel won't be portable to older Mac OS releases.

**Comment by hawkinsp** [comment] 2021-05-11 00:40
Closing, because we have a check in our wheel builds that verifies that we don't include this symbol any more.

(We don't yet know the root cause, but it not a user-facing bug any more hopefully!)

**Closed by hawkinsp** 2021-05-11 00:40 UTC
Labels: build

**Comment by giljerard** [comment] 2024-01-31 17:22
FYI: Building jaxlib from source on Mac M2 for use in Rosetta per: https://github.com/google/jax/issues/9580.
Ran into this same issue, commenting out the verify_mac_libraries_dont_reference_chkstack() function call as hawkinsp recommended and rerunning bazel command fixed the issue for me. Though my build_wheel.py was in a different location than referenced in the older version. Thanks!
