### ISSUE TITLE
Failing lax_numpy_indexing_test.py tests on Python 3.7

### ISSUE THREAD

**Issue by alexbw** [google/jax#228] opened 2019-01-11 20:28 UTC
`python tests/lax_numpy_indexing_test.py --num_generated_cases=1` on Python 3.7 (fresh Anaconda install on a macOS 10.13.6). Numpy version 1.15.4.

**Comment by hawkinsp** [comment] 2019-01-11 20:55
Duplicate of #227

**Closed by hawkinsp** 2019-01-11 20:55 UTC
