### ISSUE TITLE
pip install jaxlib==version+cuda is not found: metadata does not match name

### ISSUE THREAD

**Issue by j-bernardi** [google/jax#6932] opened 2021-06-09 20:17 UTC
- [x] Check for duplicate issues.
I searched `is:issue is:open pip install jaxlib metadata`
- [x] Provide a complete example of how to reproduce the bug:

```bash
pip install --upgrade jax==0.2.0 jaxlib==0.1.55+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

- [x] If applicable, include full error messages/tracebacks. Returns:

> Looking in links: https://storage.googleapis.com/jax-releases/jax_releases.html
Requirement already satisfied: jax==0.2.0 in /home/jb/anaconda3/envs/cuda111/lib/python3.8/site-packages (0.2.0)
Collecting jaxlib==0.1.55+cuda110
  Using cached https://storage.googleapis.com/jax-releases/cuda110/jaxlib-0.1.55%2Bcuda110-cp38-none-manylinux2010_x86_64.whl (155.2 MB)
> WARNING: Discarding https://storage.googleapis.com/jax-releases/cuda110/jaxlib-0.1.55%2Bcuda110-cp38-none-manylinux2010_x86_64.whl (from https://storage.googleapis.com/jax-releases/jax_releases.html). Requested jaxlib==0.1.55+cuda110 from https://storage.googleapis.com/jax-releases/cuda110/jaxlib-0.1.55%2Bcuda110-cp38-none-manylinux2010_x86_64.whl has inconsistent version: filename has '0.1.55+cuda110', but metadata has '0.1.55'
ERROR: Could not find a version that satisfies the requirement jaxlib==0.1.55+cuda110 (from versions: 0.1, 0.1.1, 0.1.32, 0.1.33, 0.1.34, 0.1.35, 0.1.36, 0.1.37, 0.1.38, 0.1.39, 0.1.40, 0.1.41, 0.1.42, 0.1.43, 0.1.44, 0.1.45, 0.1.46, 0.1.47, 0.1.48, 0.1.50, 0.1.51, 0.1.52, 0.1.52+cuda100, 0.1.52+cuda101, 0.1.52+cuda102, 0.1.52+cuda110, 0.1.55, 0.1.55+cuda100, 0.1.55+cuda101, 0.1.55+cuda102, 0.1.55+cuda110, 0.1.56, 0.1.56+cuda100, 0.1.56+cuda101, 0.1.56+cuda102, 0.1.56+cuda110, 0.1.56+cuda111, 0.1.57, 0.1.57+cuda101, 0.1.57+cuda102, 0.1.57+cuda110, 0.1.57+cuda111, 0.1.58, 0.1.58+cuda101, 0.1.58+cuda102, 0.1.58+cuda110, 0.1.58+cuda111, 0.1.59, 0.1.59+cuda101, 0.1.59+cuda102, 0.1.59+cuda110, 0.1.59+cuda111, 0.1.60, 0.1.60+cuda101, 0.1.60+cuda102, 0.1.60+cuda110, 0.1.60+cuda111, 0.1.61, 0.1.61+cuda101, 0.1.61+cuda102, 0.1.61+cuda110, 0.1.61+cuda111, 0.1.61+cuda112, 0.1.62, 0.1.62+cuda101, 0.1.62+cuda102, 0.1.62+cuda110, 0.1.62+cuda111, 0.1.62+cuda112, 0.1.63, 0.1.63+cuda101, 0.1.63+cuda102, 0.1.63+cuda110, 0.1.63+cuda111, 0.1.63+cuda112, 0.1.64, 0.1.64+cuda101, 0.1.64+cuda102, 0.1.64+cuda110, 0.1.64+cuda111, 0.1.64+cuda112, 0.1.65, 0.1.65+cuda101, 0.1.65+cuda102, 0.1.65+cuda110, 0.1.65+cuda111, 0.1.65+cuda112, 0.1.66, 0.1.66+cuda101, 0.1.66+cuda102, 0.1.66+cuda110, 0.1.66+cuda111, 0.1.67, 0.1.67+cuda101, 0.1.67+cuda102, 0.1.67+cuda110, 0.1.67+cuda111)
ERROR: No matching distribution found for jaxlib==0.1.55+cuda110

Conda env at time of install:
[env.txt](https://github.com/google/jax/files/6626643/tmp.txt)

Notable: my cuda toollkit version is 11.1 (to use with torch). I am pinned back on jax 0.1.55 due to DeepMind GLN implementation, if curious.

Edit: Using GTX 1070

**Comment by jakevdp** [comment] 2021-06-09 20:21
What version of `pip` are you using? I suspect you need to update to a more recent version of `pip` that knows how to handle package version annotations.

**Comment by j-bernardi** [comment] 2021-06-09 20:29
Hi @jakevdp 
apologies for omitting this. I did pip upgrade right before running the command. Not sure if pip got more strict recently..
```bash
pip --version
```
> pip 21.1.2 from /home/jb/anaconda3/envs/cuda111/lib/python3.8/site-packages/pip (python 3.8)

**Comment by jakevdp** [comment] 2021-06-09 20:33
Thanks - I can reproduce this error with pip 20.X and 21.X, but the installation is successful with pip 19.X.

Perhaps this is something that should be reported on the pip issue tracker?

**Comment by j-bernardi** [comment] 2021-06-09 20:35
Perhaps - though I'd first consider whether it's good behaviour to reject metadata that doesn't match the name of a package? Or is this a standard pattern, having "+"-separated distribution naems? I'm relatively unfamiliar with package distribution.

Thanks for the workaround. I didn't mention, but jaxlib 0.1.55+cuda111 seems compatible so I'm progressing with that, but will do if any discrepencies arise.

**Comment by jakevdp** [comment] 2021-06-09 20:37
Using a `+` in an identifier is a standard pattern in pip repositories.

**Comment by jakevdp** [comment] 2021-06-09 20:39
Here is a similar issue - not sure if related: https://github.com/google/jax/issues/5148

**Comment by j-bernardi** [comment] 2021-06-09 21:22
Good find. It looks like that user was not pointing at https://storage.googleapis.com/jax-releases/jax_releases.html. You can see that none of the versions listed by pip have "cuda" in them, as a result. I would err on unrelated. 
I think I got it:
```python
>>> from zipfile import ZipFile as Z
>>> path_works = "jaxlib-0.1.56+cuda111-cp38-none-manylinux2010_x86_64.whl"
>>> path_broke = "jaxlib-0.1.55+cuda110-cp38-none-manylinux2010_x86_64.whl"
>>> zip_works = Z(path_works)
>>> zip_broke = Z(path_broke)

>>> zip_works.namelist()
['jaxlib/__init__.py', 'jaxlib/cublas_kernels.so', 'jaxlib/cuda_prng.py', 'jaxlib/cuda_prng_kernels.so', 'jaxlib/cusolver.py', 'jaxlib/cusolver_kernels.so', 'jaxlib/lapack.so', 'jaxlib/tpu_client.py', 'jaxlib/tpu_client_extension.so', 'jaxlib/version.py', 'jaxlib/xla_client.py', 'jaxlib/xla_extension.so', 'jaxlib-0.1.56+cuda111.dist-info/METADATA', 'jaxlib-0.1.56+cuda111.dist-info/WHEEL', 'jaxlib-0.1.56+cuda111.dist-info/top_level.txt', 'jaxlib-0.1.56+cuda111.dist-info/RECORD']
>>> with zip_works.open("jaxlib-0.1.56+cuda111.dist-info/METADATA") as f:
...     print(f.read().decode("utf-8"))
... 
Metadata-Version: 2.1
Name: jaxlib
Version: 0.1.56+cuda111
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Platform: UNKNOWN
Requires-Python: >=3.6
Requires-Dist: scipy
Requires-Dist: numpy (>=1.12)
Requires-Dist: absl-py

UNKNOWN

>>> zip_broke.namelist()
['jaxlib/__init__.py', 'jaxlib/cublas_kernels.so', 'jaxlib/cuda_prng.py', 'jaxlib/cuda_prng_kernels.so', 'jaxlib/cusolver.py', 'jaxlib/cusolver_kernels.so', 'jaxlib/lapack.so', 'jaxlib/tpu_client.py', 'jaxlib/tpu_client_extension.so', 'jaxlib/version.py', 'jaxlib/xla_client.py', 'jaxlib/xla_extension.so', 'jaxlib-0.1.55.dist-info/METADATA', 'jaxlib-0.1.55.dist-info/WHEEL', 'jaxlib-0.1.55.dist-info/top_level.txt', 'jaxlib-0.1.55.dist-info/RECORD']

Metadata-Version: 2.1
Name: jaxlib
Version: 0.1.55
Summary: XLA library for JAX
Home-page: https://github.com/google/jax
Author: JAX team
Author-email: jax-dev@google.com
License: Apache-2.0
Platform: UNKNOWN
Requires-Python: >=3.6
Requires-Dist: scipy
Requires-Dist: numpy (>=1.12)
Requires-Dist: absl-py

UNKNOWN

```

Issue: there is no file called "jaxlib-0.1.55+cuda110.dist-info/METADATA", whereas that does exist for 0.1.56 cuda111 release
And the metadata inside the METADATA file that does exist is for the 0.1.55 release (without cuda).

**Comment by jakevdp** [comment] 2021-06-09 21:28
Thanks for digging in. It looks like the issue is limited to the 0.1.55 release, then, and is fixed in later releases - perhaps @skye might remember some context on that?

If it's fixed for newer releases, I think this issue can be closed.

**Closed** 2021-06-09 21:30 UTC
Labels: bug

**Comment by skye** [comment] 2021-06-09 23:07
It looks like the 0.1.55 release was the first one to use the +cudaXXX modifier: https://github.com/google/jax/commit/cacb01753a2fca73fba8972db5391438699f52ef
So I probably just screwed it up :) As a workaround for 0.1.55, you can pip install directly from the storage bucket URL (something like https://storage.googleapis.com/jax-releases/cuda110/jaxlib-0.1.55%2Bcuda110-cp38-none-manylinux2010_x86_64.whl, which I got from your error message). Lemme know if I should dig up the exact command.

**Comment by j-bernardi** [comment] 2021-06-09 23:54
Thanks both - I'm satisfied that the workarounds I have already are absolutely fine for my purposes, and have a comprehensive list of other possibilities!

Closed the bug as it seems it's not anything that's likely to persist. Thanks for your time and rapid responses, glad we got to the bottom of it.
