### ISSUE TITLE
Mish activation Function

### ISSUE THREAD

**Issue by joaogui1** [google/jax#2842] opened 2020-04-25 14:20 UTC
Is there interest in adding the [mish](https://arxiv.org/abs/1908.08681) activation function to `jax.nn`?

> It has a much smoother curve vs relu, and in theory, that drives information more deeply through the network. It is slower than ReLU, but on average adds about 1-3% improvement vs ReLU. - LessW2020, Fastai forums

**Comment by mattjj** [comment] 2020-04-25 16:08
Thanks for the question! We considered this in #1676 and decided against it. Things can always change in the future, but our general principle is we want to keep things minimal.

Hope you don't mind if I close this issue, since in some ways it's a duplicate of #1676, but don't take it as shutting down the conversation. If you have any strong feelings here, we want to hear them!

**Closed by mattjj** 2020-04-25 16:08 UTC

**Comment by joaogui1** [comment] 2020-04-25 17:32
Wow sorry, I searched before posting, must have written it wrong
