### ISSUE TITLE
jnp.dtype is not idempotent

### ISSUE THREAD

**Issue by SiegeLordEx** [google/jax#3857] opened 2020-07-24 21:54 UTC
```python
import jax.numpy as np

print(np.dtype(np.int32))
# int32
print(np.int32)
# <class 'jax.numpy.lax_numpy.int32'>
```

This is a minor annoyance when writing tests and verifying that the expected dtype via the `is` operator.

**Comment by jakevdp** [comment] 2020-07-24 21:57
JAX follows Numpy on this:
```python
import numpy as np
print(np.int32)
# <class 'numpy.int32'>
print(np.dtype(np.int32))
# int32
```
I've found it a bit annoying as well, but I think there's not much chance of Numpy changing its API at this point.

**Comment by mattjj** [comment] 2020-07-24 22:12
@jakevdp @SiegeLordEx given we're following NumPy behavior here, should we close this issue?

**Comment by SiegeLordEx** [comment] 2020-07-24 22:21
JAX certainly could choose to improve upon NumPy here, but given the relatively minor impact of this and the consistency with NumPy, closing seems reasonable.

**Comment by mattjj** [comment] 2020-07-24 22:50
You're right; I wonder if this is something we should consider deviating on. I defer to @jakevdp and @shoyer for wisdom on that.

**Comment by jakevdp** [comment] 2020-07-24 23:14
The issue is that dtype objects don't have a constructor. So if you do this, you get an error:
```python
>>> dt = np.dtype('int32')
>>> type(dt)
numpy.dtype
>>> dt(1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-91945648777b> in <module>
----> 1 dt(1)

TypeError: 'numpy.dtype' object is not callable
```
Numpy exposes python types that are associated with the dtypes:
```python
>>> np.int32(1)
1
>>> np.int32 is np.dtype('int32')                                                                                                                        
False
>>> np.int32 is np.dtype('int32').type                                                                                                                   
True
```
I don't think we can deviate from this in JAX without substantially redefining what a dtype is, and I think that would probably lead to more issues that it would be worth.

**Comment by mattjj** [comment] 2020-07-24 23:34
Good call, thanks for explaining!

**Closed by mattjj** 2020-07-24 23:34 UTC
Labels: question
