### ISSUE TITLE
Wrong values on second GPU when distributing the data SPMD [Tesla K80]

### ISSUE THREAD

**Issue by T-Almeida** [google/jax#12527] opened 2022-09-27 11:49 UTC
### Description

Hi, I'm a newcomer to jax (previously, I used tensorflow). While I was learning jax, I found a strange behaviour when testing the single-process multiple-data (SPMD) programs on my local Tesla K80 (I believe this is a single board with two GPU chips). When I ran the _pmap_ function I found that the data that was stored on (sent to?) the second GPU was different from the first one. To demonstrate the problem I build a simple script around the _jax.device_put_ and _jax.device_put_replicated_ methods (which have the same wrong behaviour as observed in the _pmap_, I suppose they use the same low-end method for data replication).  

To better understand these issues, I made three simple experiences:

- In the first experience, I use _jax.device_put_replicated_ to replicate a two-by-two matrix of ones in both GPUs. However, on the second one, I got a two-by-two matrix with zeros.

```
Jax visible devices:  [GpuDevice(id=0, process_index=0), GpuDevice(id=1, process_index=0)] 

--- Local values ---
gpu:0 
 [[1. 1.]
 [1. 1.]] 


--- Distributed values ---
Device: gpu:0 
Values:
 [[1. 1.]
 [1. 1.]]

Device: gpu:1 
Values:
 [[0. 0.]
 [0. 0.]]

```
 - In the second experience, I replace _jax.device_put_replicated_ with _jax.device_put_ (where I select each GPU individually), and as expected, the same wrong behaviour was observed.

```
--- Second experiment ---

--- Local values ---
gpu:0 
 [[1. 1.]
 [1. 1.]] 


--- Distributed values ---
Device: gpu:0 
Values:
 [[1. 1.]
 [1. 1.]]

Device: gpu:1 
Values:
 [[0. 0.]
 [0. 0.]]

```

 - Finally, I tried to execute the code directly on GPU 1 (with help of jit) since by default the values are being allocated to GPU 0. Then made the replication using _jax.device_put_ and _jax.device_put_replicated_.

```
--- Third experiment ---

--- Locally create on GPU: 1 ---
gpu:1 
 [[1. 1.]
 [1. 1.]] 


--- Distributed values with device_put ---
Device: gpu:0 
Values:
 [[1. 0.]
 [0. 0.]]

Device: gpu:1 
Values:
 [[1. 1.]
 [1. 1.]]


--- Distributed values with device_put_replicated ---
Device: gpu:0 
Values:
 [[1. 1.]
 [1. 1.]]

Device: gpu:1 
Values:
 [[0. 0.]
 [0. 0.]]

```

As observable, when directly running the instruction on GPU 1, it seems to work. However, when I share it from that GPU (GPU 1) to the other one (GPU 0), the replicated values are still wrong.

Other info, I run the program with this env: CUDA_VISIBLE_DEVICES=0,1. If I  run the normal code on each GPU (like CUDA_VISIBLE_DEVICES=1) I did not find any strange behaviour. **I also run the code on a desktop with two rtx 2070 and there I had no issues. I also used the same base container to perform these experiences.**

The script I run for checking the previously described jax behaviour:
```python

## DEBUG of K80 multi GPU setup
import jax
import jax.numpy as jnp

def first_experiment():
    local = jnp.ones((2,2))
    print("--- Local values ---")
    print(local.device(),"\n", local, "\n\n")
    
    print("--- Distributed values ---")
    out = jax.device_put_replicated(local, jax.devices()).block_until_ready()
    print("\n\n".join([f"Device: {buf.device()} \nValues:\n {buf}" for buf in out.device_buffers]))    
    
def second_experiment():
    local = jnp.ones((2,2))
    print("--- Local values ---")
    print(local.device(),"\n", local, "\n\n")

    print("--- Distributed values ---")
    out_0 = jax.device_put(local, jax.devices()[0]).block_until_ready()
    # manually select gpu 1
    out_1 = jax.device_put(local, jax.devices()[1]).block_until_ready()
    print("\n\n".join([f"Device: {out.device()} \nValues:\n {out}" for out in [out_0, out_1]]))    

def third_experiment():
    print("--- Locally create on GPU: 1 ---")
    local = jax.jit(lambda x: jnp.ones((2,2)), device=jax.devices()[1])(0).block_until_ready()
    print(local.device(),"\n", local, "\n\n")
    
    # put on gpu 0
    print("--- Distributed values with device_put ---")
    out = jax.device_put(local, jax.devices()[0]).block_until_ready()
    print("\n\n".join([f"Device: {buf.device()} \nValues:\n {buf}" for buf in [out, local]])) 
    print("\n")
    print("--- Distributed values with device_put_replicated ---")
    out = jax.device_put_replicated(local, jax.devices()).block_until_ready()
    print("\n\n".join([f"Device: {buf.device()} \nValues:\n {buf}" for buf in out.device_buffers]))  
    

if __name__ == "__main__":
    
    print("\nJax visible devices: ", jax.devices(), "\n")
    
    first_experiment()
    print("\n--- Second experiment ---\n")
    second_experiment()
    
    print("\n--- Third experiment ---\n")
    third_experiment()
```

### What jax/jaxlib version are you using?

0.3.15+cuda11.cudnn82

### Which accelerator(s) are you using?

GPU - Tesla K80 (single board two GPU chips)

### Additional system info

Everything runs inside a container that uses as base image: nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04 | python 3.9.14 | Ubuntu 20.04.4 LTS

### NVIDIA GPU info

nvidia-smi
```
Tue Sep 27 11:00:52 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:86:00.0 Off |                    0 |
| N/A   51C    P0    60W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:87:00.0 Off |                    0 |
| N/A   41C    P0    72W / 149W |      0MiB / 11441MiB |     96%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

nvidia-smi topo -m
```
        GPU0    GPU1    CPU Affinity    NUMA Affinity
GPU0     X      PIX     10-19,30-39     1
GPU1    PIX      X      10-19,30-39     1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by hawkinsp** [comment] 2022-09-27 15:14
I can't reproduce this behavior. I used a GCP VM with 2 K80 GPUs, using the same `jaxlib` as you.

Your script produces for me:
```
Jax visible devices:  [GpuDevice(id=0, process_index=0), GpuDevice(id=1, process_index=0)]

--- Local values ---
gpu:0
 [[1. 1.]
 [1. 1.]]


--- Distributed values ---
Device: gpu:0
Values:
 [[1. 1.]
 [1. 1.]]

Device: gpu:1
Values:
 [[1. 1.]
 [1. 1.]]

--- Second experiment ---

--- Local values ---
gpu:0
 [[1. 1.]
 [1. 1.]]


--- Distributed values ---
Device: gpu:0
Values:
 [[1. 1.]
 [1. 1.]]

Device: gpu:1
Values:
 [[1. 1.]
 [1. 1.]]

--- Third experiment ---

--- Locally create on GPU: 1 ---
gpu:1
 [[1. 1.]
 [1. 1.]]


--- Distributed values with device_put ---
Device: gpu:0
Values:
 [[1. 1.]
 [1. 1.]]

Device: gpu:1
Values:
 [[1. 1.]
 [1. 1.]]


--- Distributed values with device_put_replicated ---
Device: gpu:0
Values:
 [[1. 1.]
 [1. 1.]]

Device: gpu:1
Values:
 [[1. 1.]
 [1. 1.]]
```


My `nvidia-smi` outputs are:

```
phawkins@phawkins-k80-2:~$ nvidia-smi
Tue Sep 27 15:09:18 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:00:05.0 Off |                    0 |
| N/A   54C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
phawkins@phawkins-k80-2:~$ nvidia-smi topo -m
	GPU0	GPU1	CPU Affinity	NUMA Affinity
GPU0	 X 	PHB	0-7		N/A
GPU1	PHB	 X 	0-7		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

This is a bit of a long shot, but can you try running with `TF_CPP_MIN_LOG_LEVEL=0` and share the output?

**Comment by T-Almeida** [comment] 2022-09-27 15:28
Hi, thanks for the prompt response.

Here is the output @hawkinsp 
```
$ CUDA_VISIBLE_DEVICES=0,1 TF_CPP_MIN_LOG_LEVEL=0 python spmd.py 
2022-09-27 15:21:50.037724: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:173] XLA service 0x2e41cc0 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2022-09-27 15:21:50.037772: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): Interpreter, <undefined>
2022-09-27 15:21:50.055260: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/tfrt_cpu_pjrt_client.cc:181] TfrtCpuClient created.
2022-09-27 15:21:55.494818: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:173] XLA service 0x2da1530 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-09-27 15:21:55.494904: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2022-09-27 15:21:55.494934: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (1): Tesla K80, Compute Capability 3.7
2022-09-27 15:21:55.496529: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:284] Using BFC allocator.
2022-09-27 15:21:55.496639: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:240] XLA backend allocating 10740223180 bytes on device 0 for BFCAllocator.
2022-09-27 15:21:55.496727: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/gpu_device.cc:240] XLA backend allocating 10740223180 bytes on device 1 for BFCAllocator.

Jax visible devices:  [GpuDevice(id=0, process_index=0), GpuDevice(id=1, process_index=0)] 

2022-09-27 15:21:55.864654: I external/org_tensorflow/tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
--- Local values ---
gpu:0 
 [[1. 1.]
 [1. 1.]] 


--- Distributed values ---
Device: gpu:0 
Values:
 [[1. 1.]
 [1. 1.]]

Device: gpu:1 
Values:
 [[0. 0.]
 [0. 0.]]

--- Second experiment ---

--- Local values ---
gpu:0 
 [[ 0.62481064  2.168414  ]
 [-0.89830905 -0.26842144]] 


--- Distributed values ---
Device: gpu:0 
Values:
 [[ 0.62481064  2.168414  ]
 [-0.89830905 -0.26842144]]

Device: gpu:1 
Values:
 [[0. 0.]
 [0. 0.]]

--- Third experiment ---

--- Locally create on GPU: 1 ---
gpu:1 
 [[1. 1.]
 [1. 1.]] 


--- Distributed values with device_pu ---
Device: gpu:0 
Values:
 [[ 1.3300115e-05 -4.5944925e+08]
 [ 0.0000000e+00  0.0000000e+00]]

Device: gpu:1 
Values:
 [[1. 1.]
 [1. 1.]]


--- Distributed values with device_put_replicated ---
Device: gpu:0 
Values:
 [[ 0.62481064  2.168414  ]
 [-0.89830905 -0.26842144]]

Device: gpu:1 
Values:
 [[0. 0.]
 [0. 0.]]
2022-09-27 15:21:57.649477: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/tfrt_cpu_pjrt_client.cc:184] TfrtCpuClient destroyed.
```

Furthermore, I noticed that your topology uses PHB and mine PIX (any chance this to be related? also when I run on desktop with two 2070 it is also PHB). Additionally I also updated the nvidia drive to 470.141.03 (latest, same as yours).

**Comment by hawkinsp** [comment] 2022-09-27 17:14
I think if the simplep2p program fails, that means that this is almost certainly not a JAX bug. It seems like either a CUDA bug or a hardware failure. Peer-to-peer transfers are exactly what JAX is doing under the hood also!

This is a great tip: I'll make sure to ask anyone reporting a similar issue in the future to try simpleP2P as well.

Closing since there's no action we can take. I hope that helps!

**Closed by hawkinsp** 2022-09-27 17:14 UTC
Labels: bug, NVIDIA GPU

**Comment by kefirski** [comment] 2022-11-30 08:55
I've faced the same issue.

```python
>>> x
DeviceArray([[ 0.12536795,  1.001624  , -1.1135612 ,  0.5008104 ,
              -0.47558996],
             [-1.5486398 ,  1.0566913 , -0.7010289 ,  1.6805717 ,
               0.03403701],
             [ 1.2229952 ,  0.90688646, -0.6866566 , -1.3204749 ,
               0.04500131],
             [-1.0343889 , -0.72855705, -0.05964825,  0.3477782 ,
               0.25304395],
             [-0.02247168, -0.8256811 ,  0.56739944,  0.05135848,
              -0.93779516]], dtype=float32)
              
>>> jax.device_put_replicated(x, jax.local_devices())
ShardedDeviceArray([[[ 0.12536795,  1.001624  , -1.1135612 ,
                       0.5008104 , -0.47558996],
                     [-1.5486398 ,  1.0566913 , -0.7010289 ,
                       1.6805717 ,  0.03403701],
                     [ 1.2229952 ,  0.90688646, -0.6866566 ,
                      -1.3204749 ,  0.04500131],
                     [-1.0343889 , -0.72855705, -0.05964825,
                       0.3477782 ,  0.25304395],
                     [-0.02247168, -0.8256811 ,  0.56739944,
                       0.05135848, -0.93779516]],

                    [[ 0.        ,  0.        ,  0.        ,
                       0.        ,  0.        ],
                     [ 0.        ,  0.        ,  0.        ,
                       0.        ,  0.        ],
                     [ 0.        ,  0.        ,  0.        ,
                       0.        ,  0.        ],
                     [ 0.        ,  0.        ,  0.        ,
                       0.        ,  0.        ],
                     [ 0.        ,  0.        ,  0.        ,
                       0.        ,  0.        ]],

                    [[ 0.12536795,  1.001624  , -1.1135612 ,
                       0.5008104 , -0.47558996],
                     [-1.5486398 ,  1.0566913 , -0.7010289 ,
                       1.6805717 ,  0.03403701],
                     [ 1.2229952 ,  0.90688646, -0.6866566 ,
                      -1.3204749 ,  0.04500131],
                     [-1.0343889 , -0.72855705, -0.05964825,
                       0.3477782 ,  0.25304395],
                     [-0.02247168, -0.8256811 ,  0.56739944,
                       0.05135848, -0.93779516]],

                    [[ 0.12536795,  1.001624  , -1.1135612 ,
                       0.5008104 , -0.47558996],
                     [-1.5486398 ,  1.0566913 , -0.7010289 ,
                       1.6805717 ,  0.03403701],
                     [ 1.2229952 ,  0.90688646, -0.6866566 ,
                      -1.3204749 ,  0.04500131],
                     [-1.0343889 , -0.72855705, -0.05964825,
                       0.3477782 ,  0.25304395],
                     [-0.02247168, -0.8256811 ,  0.56739944,
                       0.05135848, -0.93779516]]], dtype=float32)
                       
>>> jax.local_devices()
[StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0), StreamExecutorGpuDevice(id=1, process_index=0, slice_index=0), StreamExecutorGpuDevice(id=2, process_index=0, slice_index=0), StreamExecutorGpuDevice(id=3, process_index=0, slice_index=0)]
```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   34C    P0    36W / 300W |  29370MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:8B:00.0 Off |                    0 |
| N/A   33C    P0    37W / 300W |  29322MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:9C:00.0 Off |                    0 |
| N/A   35C    P0    37W / 300W |  29322MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:9D:00.0 Off |                    0 |
| N/A   33C    P0    35W / 300W |  29322MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

```
jax                        0.3.25
jaxlib                     0.3.25+cuda11.cudnn82
```

**Comment by kefirski** [comment] 2022-11-30 09:44
It definitely feels like an CUDA/etc issue, since I could not reproduce that with different host with A100 GPU and a newer CUDA version. Though, still don't understand what is the issue itself
