### ISSUE TITLE
ops.index_add double precision performance on GPUs

### ISSUE THREAD

**Issue by bnwebcode** [google/jax#3270] opened 2020-06-01 06:43 UTC
It appears that double precision performance of ```jax.ops.index_add``` is far slower (maybe around 400x times) than single precision when running on gpu. I used the following code to benchmark:

```
# Precision to use. Configure: config.update("jax_enable_x64", True)
T=jnp.float64
# Compare to:
T=jnp.float32

# Setup the data
i=jax.device_put(numpy.random.randint(0,12, size=10_000_000))
v=jax.device_put(jnp.array(numpy.random.normal(size=i.shape), dtype=T))
g=jnp.zeros(12, dtype=T)

# Actual timing 
%timeit jax.ops.index_add(g, i, v).block_until_ready()
```
On Google Colab I find double precision is 400 times slower, even when running on an P100 instance.

To speculate: maybe this is due to lack of atomic double precision add on earlier compute capabilities? However I think this was added from Pascal onward.

**Comment by jekbradbury** [comment] 2020-06-02 00:38
I can reproduce (it's more than 1000x slower for me). Filed an internal bug for the XLA:GPU team.

**Comment by jekbradbury** [comment] 2020-06-03 21:56
The XLA:GPU team confirmed your diagnosis: "The bug is that we don't use atomic add for f64 (available since sm_50)." I think they're working on a fix.

**Comment by jekbradbury** [comment] 2020-06-04 00:13
Fixed in https://github.com/tensorflow/tensorflow/commit/e0769309642b8547d9b720b5d42b35db87031dcd. You'll need to either rebuild from source or wait until we update jaxlib binaries.

**Comment by mattjj** [comment] 2020-06-04 01:07
@jekbradbury I'm going to mark you as "assigned" since you already followed up on this issue, but IMO there's no additional action to take here.

@bnwebcode thanks for finding this, leading to a fix! Even though we haven't updated the jaxlib wheels yet, I'm going to close this issue as fixed (since otherwise it's tricky to remember which issues to close when we update jaxlib). I suspect we'll push new jaxlib wheels in the next week.

**Closed by mattjj** 2020-06-04 01:07 UTC

**Comment by bnwebcode** [comment] 2020-06-09 09:51
Excellent, many thanks! Good to hear the diagnosis was helpful.
