### ISSUE TITLE
Inscrutable custom VJP error

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#13099] opened 2022-11-03 21:27 UTC
### Description

Here's my MWE.  I left in the type annotations and the docstring in case they help with making sense of the code.
```python
from functools import partial
from typing import Any, Callable, Tuple, TypeVar, cast

import jax.numpy as jnp
from jax import custom_vjp, vjp
from jax.tree_util import tree_map

XT = TypeVar('XT', bound=Tuple[Any, ...])
Y = TypeVar('Y')

@partial(custom_vjp, nondiff_argnums=(0,))
def cotangent_combinator(f: Callable[..., Tuple[XT, Y]],
                         args_tuples: Tuple[Tuple[Any, ...], ...]) -> Tuple[XT, Y]:
    """
    Args:
        f: A function that accepts positional arguments and returns xs, y where xs is a tuple of
            length n.
        args_tuples: n copies of the same tuple of positional arguments accepted by f.
    Returns: The pair (xs, y).

    The purpose of the cotangent combinator is to take cotangents of each of the elements of x, and
    send them back through to each of the corresponding argument tuples.
    """
    return f(*args_tuples[0])


def _cotangent_combinator_fwd(f: Callable[..., Tuple[XT, Y]],
                              args_tuples: Tuple[Tuple[Any, ...], ...]
                              ) -> Tuple[Tuple[XT, Y], Callable[[XT, Y], Tuple[Any, ...]]]:
    return vjp(f, *args_tuples[0])


def _cotangent_combinator_bwd(f: Callable[..., Tuple[XT, Y]],
                              f_vjp: Callable[[XT, Y], Tuple[Any, ...]],
                              xy_bar: Tuple[XT, Y]
                              ) -> Tuple[Any, ...]:
    xs_bar, y_bar = xy_bar
    n = len(xs_bar)
    xs_zero = tuple(tree_map(jnp.zeros_like, x_bar)
                    for x_bar in xs_bar)
    all_args_bar = []
    for i, x_bar in enumerate(xs_bar):
        this_xs_bar = cast(XT, (xs_zero[:i]
                                + (x_bar,)
                                + xs_zero[i + 1:]))
        print_generic(this_xs_bar, y_bar)
        this_args_bar = f_vjp(this_xs_bar, y_bar)
        all_args_bar.append(this_args_bar)
    return tuple(all_args_bar)


cotangent_combinator.defvjp(_cotangent_combinator_fwd, _cotangent_combinator_bwd)


def f(x: Any) -> Tuple[Any, None]:
    return (x ** 2, x ** 2), None
o = jnp.ones(())

result, f_vjp = vjp(partial(cotangent_combinator, f), ((-1.0,), (-1.0,)))
result_bar = (2 * o, 3 * o), None
from tjax import print_generic
print_generic(result=result)
print_generic(result_bar=result_bar)
f_vjp(result_bar)
```
gives
```
TypeError: _vjp_pullback_wrapper() takes 5 positional arguments but 6 were given
```
I have no idea where this is coming from since I don't have anything like that in my code.  What am I doing wrong?

### What jax/jaxlib version are you using?

jax 0.3.23; jaxlib 0.3.22

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10

**Comment by mattjj** [comment] 2022-11-03 21:51
A terrible error message indeed!

In the original repro (before edit, sorry that's just when I copied it) that we were calling

```python
f_vjp((2.0, 0.0), None)
```

when we actually needed

```python
f_vjp(((2.0, 0.0), None))
```

Notice the extra parentheses. I think `f_vjp` always takes a single argument (corresponding to how Python functions always return a single value, though that value might be a tuple or pytree or whatever).

Let me try the new repro... but if the issue is the same, then at least we know how to fix the code, though it's still a TODO to improve the error message here.

**Comment by mattjj** [comment] 2022-11-03 21:53
The callable returned by `jax.vjp` is a `Partial` over a function which takes 5 arguments (named `_vjp_pullback_wrapper`) where all but the last argument is supplied by the `Partial`. Because of the `Partial`, we don't error quite as early as you might expect (and apparently tracebacks are messed up, because we subclass `functools.partial` perhaps?).

**Comment by mattjj** [comment] 2022-11-03 21:54
I think in the new repro we have a repeat of the same issue on this line:

```python
        this_args_bar = f_vjp(this_xs_bar, y_bar)
```

where we instead want

```python
        this_args_bar = f_vjp((this_xs_bar, y_bar))
```

**Comment by NeilGirdhar** [comment] 2022-11-03 22:00
Yeah, you got it!  Thank you.  Please let me know if/when I should close this.

**Comment by mattjj** [comment] 2022-11-03 22:04
I'll send a PR with an improved error message momentarily. Let's let the PR close the issue. (Please review the PR if you feel like it!)

**Closed** 2022-11-03 22:47 UTC
Labels: better_errors
