### ISSUE TITLE
ImportError issued when importing jax in macOS Big Sur

### ISSUE THREAD

**Issue by lucchem** [google/jax#6118] opened 2021-03-18 14:49 UTC
Hello,

I just installed jax and jaxlib under macOS 11.1 (Big Sur) and Python 3.8.5, and issued a ```pip install --upgrade pip tensorflow jax jaxlib``` to start playing around with jax. At first attempt, ```import jax``` fails:
```python
ImportError: dlopen(/Users/lucchem/opt/miniconda3/lib/python3.8/site-packages/jaxlib/xla_extension.so, 2): Symbol not found: __ZN10tensorflow8profiler11MonitorGrpcERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_14MonitorRequestEPNS_15MonitorResponseE
  Referenced from: /Users/lucchem/opt/miniconda3/lib/python3.8/site-packages/jaxlib/xla_extension.so
  Expected in: flat namespace
 in /Users/lucchem/opt/miniconda3/lib/python3.8/site-packages/jaxlib/xla_extension.so
```
```pip show pip jax jaxlib tensorflow``` outputs:
```
Name: pip
Version: 21.0.1
...
---
Name: jax
Version: 0.2.10
...
---
Name: jaxlib
Version: 0.1.63
...
---
Name: tensorflow
Version: 2.4.1
...
```
is there any fix? Thank you in advance.

**Comment by joschu** [comment] 2021-03-18 14:58
Same problem on Catalina, Python 3.7

**Comment by hawkinsp** [comment] 2021-03-18 15:02
Duplicate of #6111 

Use 0.1.62 for now until we push a new release.

**Closed by hawkinsp** 2021-03-18 15:02 UTC
Labels: bug

**Comment by omauryIRD** [comment] 2024-04-01 15:27
Hello,

I just installed jax and jaxlib on MacOS 10.12.6 and Python 3.8 using ANACONDA and I get:

ImportError: dlopen(/Users/lucchem/opt/miniconda3/lib/python3.8/site-packages/jaxlib/xla_extension.so, 2): Symbol not found: __ZN10tensorflow8profiler11MonitorGrpcERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_14MonitorRequestEPNS_15MonitorResponseE
  Referenced from: /Users/lucchem/opt/miniconda3/lib/python3.8/site-packages/jaxlib/xla_extension.so
  Expected in: flat namespace
 in /Users/lucchem/opt/miniconda3/lib/python3.8/site-packages/jaxlib/xla_extension.so

Any clue how to fix that?

Thanks,
Olivier
