### ISSUE TITLE
jaxlib.mlir._mlir_libs._mlir overrides python's logging module config.

### ISSUE THREAD

**Issue by hajarmitage** [google/jax#12526] opened 2022-09-27 10:26 UTC
### Description

Importing `jaxlib.mlir._mlir_libs._mlir` (and by extension any modules depending on these, including `jaxlib` and `jax`), seems to render python's logging module unable to work.

I have a script `test.py`:
```
import logging
import importlib
import sys

logger = logging.getLogger(__name__)

import jax
logging.basicConfig(level=logging.INFO)
# import jax

logger.info('Test')
```
Running `python -m test` results in no logging output. If the second import statement, after the `logging.basicConfig`, is used instead of the first, then the expected `INFO:__main__:Test` line appears. If another module e.g. `numpy` is used instead of `jax`, the log line appears. I also do see the log line when using `jax==0.3.14, jaxlib==0.3.14` - it disappears on version 0.3.15-0.3.18.

By looking at `sys.modules` before and after the import, the module that replicates this behaviour with the smallest number of dependencies appears to be `jaxlib.mlir._mlir_libs._mlir.`

### What jax/jaxlib version are you using?

jax >=0.3.14, jaxlib >=0.3.14

### Which accelerator(s) are you using?

CPU

### Additional system info

Linux

**Comment by hawkinsp** [comment] 2022-09-27 14:00
It turns out all the MLIR module in question is doing is: 
https://github.com/llvm/llvm-project/blob/1b7089fe67b924bdd5ecef786a34bdba7a88778f/mlir/python/mlir/_mlir_libs/__init__.py#L66

If you replace the MLIR or JAX import with just:
```
import logging
logging.debug("hello")
```

you get the same failure.

I think the issue is that `logging.debug` will implicitly call `logging.basicConfig` on first call:
https://docs.python.org/3/library/logging.html#logging.basicConfig
and a second call to `logging.basicConfig` will not override it.

I'm not sure what the best practice is here: perhaps the MLIR Python code should not use the root logger? If that's the case, you/we should send a PR to upstream LLVM changing it to use a non-root logger.

What do you think?

**Comment by hawkinsp** [comment] 2022-09-28 13:33
I'm an expert on Python logging :-)

Do you want to send the PR to LLVM? If it's fixed upstream, the fix will be merged into the next jaxlib release whenever we do one.

**Comment by hawkinsp** [comment] 2022-09-28 14:03
(I missed a very key "not" in that last sentence...)

**Comment by hawkinsp** [comment] 2022-09-28 18:46
Closing because we'll automatically get this fix when the MLIR change is merged, so there's no further action for us to take here.

**Comment by hawkinsp** [comment] 2022-11-28 23:09
I guess we're still waiting for the MLIR fix to be merged...

**Comment by hawkinsp** [comment] 2022-12-06 01:59
The upstream LLVM fix was merged. This should be fixed as part of the next jaxlib release.

**Closed by hawkinsp** 2022-12-06 01:59 UTC
Labels: bug
