### ISSUE TITLE
cuSolver internal error during QR decomposition on GPU

### ISSUE THREAD

**Issue by janosg** [google/jax#4497] opened 2020-10-08 12:44 UTC
## Problem

QR decomposition fails on GPU but runs on CPU. 

## Minimal Example

The example is taken from the [documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.qr.html) of `jax.numpy.linalg.qr`

```python
import jax.numpy as jnp
A = jnp.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = jnp.linalg.qr(A)
```
## Error Message

```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-5d57dd84237a> in <module>
      1 import jax.numpy as jnp
      2 A = jnp.array([[0, 1], [1, 1], [1, 1], [2, 1]])
----> 3 q, r = jnp.linalg.qr(A)

/home/skanehealth/jax/jax/numpy/linalg.py in qr(a, mode)
    438     raise ValueError("Unsupported QR decomposition mode '{}'".format(mode))
    439   a = _promote_arg_dtypes(jnp.asarray(a))
--> 440   q, r = lax_linalg.qr(a, full_matrices)
    441   if mode == "r":
    442     return r

/home/skanehealth/jax/jax/lax_linalg.py in qr(x, full_matrices)
     62 
     63 def qr(x, full_matrices=True):
---> 64   q, r = qr_p.bind(x, full_matrices=full_matrices)
     65   return q, r
     66 

/home/skanehealth/jax/jax/core.py in bind(self, *args, **params)
    264     top_trace = find_top_trace(args)
    265     tracers = map(top_trace.full_raise, args)
--> 266     out = top_trace.process_primitive(self, tracers, params)
    267     return map(full_lower, out) if self.multiple_results else full_lower(out)
    268 

/home/skanehealth/jax/jax/core.py in process_primitive(self, primitive, tracers, params)
    572 
    573   def process_primitive(self, primitive, tracers, params):
--> 574     return primitive.impl(*tracers, **params)
    575 
    576   def process_call(self, primitive, f, tracers, params):

/home/skanehealth/jax/jax/lax_linalg.py in qr_impl(operand, full_matrices)
    806 
    807 def qr_impl(operand, full_matrices):
--> 808   q, r = xla.apply_primitive(qr_p, operand, full_matrices=full_matrices)
    809   return q, r
    810 

/home/skanehealth/jax/jax/interpreters/xla.py in apply_primitive(prim, *args, **params)
    222 def apply_primitive(prim, *args, **params):
    223   """Impl rule that compiles and runs a single primitive 'prim' using XLA."""
--> 224   compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args), **params)
    225   return compiled_fun(*args)
    226 

/home/skanehealth/jax/jax/interpreters/xla.py in xla_primitive_callable(prim, *arg_specs, **params)
    255         f"replicas, but only {xb.device_count(backend)} XLA devices are "
    256         f"available on backend {backend.platform}.")
--> 257   built_c = primitive_computation(prim, AxisEnv(nreps, (), (), None), backend,
    258                                   tuple_args, *avals, **params)
    259   options = xb.get_compile_options(

/home/skanehealth/jax/jax/interpreters/xla.py in primitive_computation(prim, axis_env, backend, tuple_args, *avals, **params)
    296   if prim in backend_specific_translations[platform]:
    297     rule = backend_specific_translations[platform][prim]
--> 298     ans = rule(c, *xla_args, **params)
    299   elif prim in translations:
    300     rule = translations[prim]

/home/skanehealth/jax/jax/lax_linalg.py in _qr_cpu_gpu_translation_rule(geqrf_impl, orgqr_impl, c, operand, full_matrices)
    858   m, n = dims[-2:]
    859   batch_dims = dims[:-2]
--> 860   r, tau, info_geqrf = geqrf_impl(c, operand)
    861   if m < n:
    862     q = xops.Slice(r, [0] * len(dims), list(batch_dims) + [m, m],

/home/skanehealth/jax/build/jaxlib/cusolver.py in geqrf(c, a)
    192   batch = _prod(batch_dims)
    193 
--> 194   lwork, opaque = cusolver_kernels.build_geqrf_descriptor(
    195       np.dtype(dtype), batch, m, n)
    196   workspace = _Shape.array_shape(dtype, (lwork,), (0,))

RuntimeError: cuSolver internal error
```
## Environment

- jax 0.2.0
- jaxlib 0.1.55
- cuda version 11.0
- GPU model: Tesla P100 PCIe 12GB

**Comment by janosg** [comment] 2020-10-09 16:08
The error does not occur with `jax=0.2.1` installed from pip. The previous install was from source. I would be fine with closing this issue but leave it open in case someone wants to look into it.

**Comment by hawkinsp** [comment] 2020-10-12 19:07
Can you give an example that fails? I can't reproduce your problem with the example above.

**Comment by janosg** [comment] 2020-10-13 16:57
The problem seems to be related to the fact that I ran the example in jupyter notebooks and it occurs if multiple notebooks running jax are open at the same time. The following caused the error consistently on two different machines:

1. Open a notebook with the following code and run it
```python
import jax.numpy as jnp
a = jnp.arange(900).reshape(30, 30)
a @ a
```
2. Without shutting down the kernel of the first notebook, open a second one with the following code and run it:
```python
import jax.numpy as jnp
A = jnp.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = jnp.linalg.qr(A)
```
It seems not to matter what happens in the first notebook (as long as it uses jax on a GPU).

**Comment by janosg** [comment] 2020-10-13 17:20
Thanks a lot! Yes, that solved it. 

Do you think it would be possible to check in the pre-allocation step how much memory is available and warn the User if this is much less than what jax tries to pre-allocate? Ideally, with the link you just sent me in the warnings text.

**Comment by hawkinsp** [comment] 2020-10-13 17:56
Since you are trying things out, could you try restarting your colab kernels (with none of the environment variables above), and try setting the environment variable`TF_FORCE_UNIFIED_MEMORY=1` instead?

I'm thinking it will solve your problem in a better way and that we should make it the default.

**Comment by janosg** [comment] 2020-10-13 18:54
Yes, this also works. Thanks!

**Comment by hawkinsp** [comment] 2020-10-15 13:23
I'm going to close this bug since there's no immediate action (beyond a longer term desire to improve the GPU memory allocator) and the workaround is documented.

**Closed by hawkinsp** 2020-10-15 13:23 UTC
Labels: question
