### ISSUE TITLE
Segfault with `jax.clear_caches`

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#15973] opened 2023-05-11 19:05 UTC
### Description

Calling `jax.clear_caches`:
```
Fatal Python error: Segmentation fault

Current thread 0x00007cb4dbcbd180 (most recent call first):
  File ".../jax/_src/util.py", line 309 in clear_all_weakref_lru_caches
  File ".../jax/_src/api.py", line 2894 in clear_caches
...
```
Notably I also had to exclude the weakref stuff from my previous manual equivalent:
```
for module_name, module in sys.modules.copy().items():
    if module_name.startswith("jax"):
        if module_name not in ["jax.interpreters.partial_eval"]:
            for obj_name in dir(module):
                obj = getattr(module, obj_name)
                if hasattr(obj, "cache_clear"):
                    try:
                        print(f"Clearing {obj}")
                        if "Weakref" not in type(obj).__name__:
                            obj.cache_clear()
                    except Exception:
                        pass
```
so it's probably something to do with that.

I can probably set up a repro using the Diffrax test suite if that'd be helpful.

### What jax/jaxlib version are you using?

JAX 0.4.9, jaxlib 0.4.7

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.9

**Comment by patrick-kidger** [comment] 2023-05-11 19:09
Possibly related: #14212

**Comment by hawkinsp** [comment] 2023-07-14 17:53
Please add a repro...

**Comment by hawkinsp** [comment] 2023-07-14 18:03
Closing because we don't have a repro. Please reopen if we have a way to recreate the problem!

**Comment by hawkinsp** [comment] 2023-09-29 18:02
@patrick-kidger will reopen if/when he can tell us how to reproduce it...

**Closed** 2023-09-29 18:02 UTC
Labels: bug, needs info

**Comment by stefanocortinovis** [comment] 2023-10-13 08:51
If that's useful, this can be reproduced using Diffrax, as per patrick-kidger/diffrax#306.
