### ISSUE TITLE
KeyError: 'CUDA'

### ISSUE THREAD

**Issue by AntoinePlumerault** [google/jax#5302] opened 2021-01-02 11:03 UTC
Hi, I built jax from source but when importing jax, I get this error:
```
/usr/local/lib/python3.8/dist-packages/jaxlib/cusolver.py in <module>
     24   from jaxlib import cublas_kernels
     25   for _name, _value in cublas_kernels.registrations().items():
---> 26     xla_client.register_custom_call_target(_name, _value, platform="CUDA")
     27 except ImportError:
     28   pass

/usr/local/lib/python3.8/dist-packages/jaxlib/xla_client.py in register_custom_call_target(name, fn, platform)
    432     platform: the target platform.
    433   """
--> 434   _xla.register_custom_call_target(name, fn, xla_platform_names[platform])
    435 
    436 

KeyError: 'CUDA'
```
After looking at the source code, it seems that line 26 and 34 in `jaxlib/cusolver.py` should be:
```python
 xla_client.register_custom_call_target(_name, _value, platform="gpu")
```
to match the xla_platform_names dict in xla_client. When fixed another error is raised:
```
  File "/usr/local/lib/python3.8/dist-packages/jaxlib/cuda_prng.py", line 27, in <module>
    xla_client.register_custom_call_target(_name, _value, platform="CUDA")
  File "/usr/local/lib/python3.8/dist-packages/jaxlib/xla_client.py", line 434, in register_custom_call_target
    _xla.register_custom_call_target(name, fn, xla_platform_names[platform])
KeyError: 'CUDA'
```
line 434 in `jaxlib/xla_client.py` should be:
```python
xla_client.register_custom_call_target(_name, _value, platform="gpu")
```
Let me know if I'm right or if I missed something.

**Comment by jakevdp** [comment] 2021-01-02 14:43
Possibly related to #5238

**Comment by hawkinsp** [comment] 2021-01-05 20:16
Duplicate of #5238

**Closed by hawkinsp** 2021-01-05 20:16 UTC
