### ISSUE TITLE
jax.numpy.linalg.inv causes segfault on macOS

### ISSUE THREAD

**Issue by odiak** [google/jax#1866] opened 2019-12-16 05:01 UTC
maybe related to #432.

# example code

```python
import jax.numpy as np

N = 80
np.linalg.inv(np.eye(N))
```

output:
```
/path/to/project/.venv/lib/python3.7/site-packages/jax/lib/xla_bridge.py:120: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
zsh: bus error  python -m misc.jax
```

If N is smaller than 80, it works correctly on my machine.

# my environment

macOS 10.14.6
Python 3.7.0 (pyenv)

jax 0.1.55
jaxlib 0.1.37
numpy 1.17.4
scipy 1.3.3

**Comment by hawkinsp** [comment] 2019-12-16 16:23
I'm pretty sure this is a duplicate of https://github.com/google/jax/issues/432

The workaround is to downgrade your scipy release to 1.1.0, but I admit that's not a great answer.

**Closed by hawkinsp** 2019-12-16 16:23 UTC
