### ISSUE TITLE
Successfully built with Cuda, no errors on pip install, but cannot import jax

### ISSUE THREAD

**Issue by jessebett** [google/jax#1377] opened 2019-09-19 21:37 UTC
I am unable to build jax with GPU support.

I have cloned the repo and am running:
```
python build/build.py --enable_cuda --cuda_path path/to/cuda-10.0 --cudnn_path path/to/cudnn-10.0-v7.4.2
pip install -e build  
pip install -e .  
```

After about an hour of building I get `Build completed successfully`
Then run the `pip` installs and get `successfully installed jax`.

However, when I run `import jax` I get the following error:
```
---> 37 from . import xla_extension as _xla
     38 from .xla_extension import ops
     39

ImportError: libcusolver.so.10.0: cannot open shared object file: No such file or directory
```

Further, if I try to run `import jax` again I get a different error:
```
In [2]: import jax
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-cb15c4215ef7> in <module>()
----> 1 import jax

/h/jessebett/pensieve/JetAD/src/jax/jax/__init__.py in <module>()
     17
     18 from jax.version import __version__
---> 19 from jax.api import *
     20 from jax import random
     21 import jax.numpy as np  # side-effecting import sets up operator overloads

/h/jessebett/pensieve/JetAD/src/jax/jax/api.py in <module>()
     41 from six.moves import reduce
     42
---> 43 from . import core
     44 from . import linear_util as lu
     45 from . import ad_util

ImportError: cannot import name core
```

What am I missing? Why was it able to build successfully without being able to access `libcusolver.so.10.0`?

**Comment by hawkinsp** [comment] 2019-09-19 21:40
That error means the dynamic linker can't find that `.so` file at run time, but the compiler found everything it needed at build time.

Try setting `LD_LIBRARY_PATH=/path/to/cuda/lib` where the directory is the one containing `libcusolver.so.10.0` on your machine. Does that work?

**Comment by jacobjinkelly** [comment] 2019-10-01 14:56
I have the same issue. Setting `LD_LIBRARY_PATH` doesn't solve it. For what it's worth, my code still runs even after throwing the above error, just not on the GPU.

**Comment by jessebett** [comment] 2019-11-13 20:15
@hawkinsp I tried your suggestion with `LD_LIBRARY_PATH` and it did not work.

Here is what I have:
`python build/build.py --enable_cuda --cuda_path $CUDA_HOME --cudnn_path $CUDNN_PATH`

where `python` is a fresh `python 2.7` anaconda environment. Those CUDA env variables point to the parent folder for those libraries:
```
export CUDA_HOME=/pkgs/cuda-10.1
export CUDNN_PATH=/pkgs/cudnn-10.1-v7.6.3.30
```

When I execute the above command it spends 5 minutes or so saying `Loading: 0 packages loaded` then throws the error which results in 
```
Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib'
        '/lib/x86_64-linux-gnu'
        '/lib32'
        '/libx32'
        '/usr'
        '/usr/lib'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'
        '/usr/lib32'
        '/usr/libx32'
```

What is it doing? Why is it unable to find `$CUDA_HOME/include/cublas_api.h` which definitely exists?

**Comment by jessebett** [comment] 2019-11-13 20:27
If I try a different version of CUDA, dropping down to `/pkgs/cuda-10.0` I get a completely different error:
```
│Cuda Configuration Error: BUILD.tpl template is missing these variables: ["linker_bin_path"].
```

By the way, these are standard shared installs of cuda for a cluster, which work for other using pytorch and tensorflow, so nothing shady should be happening as long as I'm pointing to them correctly. Not sure how I'm not.

**Comment by jessebett** [comment] 2019-11-13 20:51
`cuda-10.1` issue seems to be related to https://devtalk.nvidia.com/default/topic/1047981/cuda-setup-and-installation/cublas-for-10-1-is-missing/

**Comment by skye** [comment] 2019-11-14 00:15
@jessebett with cuda 10, pull the latest changes and try again. That "linker_bin_path" problem was recently fixed in TF: https://github.com/tensorflow/tensorflow/commit/d55375021a36e404015abb3439e631f9fac59838

I just updated jax's WORKSPACE to include this fix.

**Comment by skye** [comment] 2019-11-14 00:21
For cuda 10.1, make sure you have cublas_api.h installed somewhere (try `locate cublas_api.h`). You might need to install some more stuff from Nvidia -- I still haven't figured out which header file comes from which Nvidia package, so I just keep installing them until the right one appears :)

**Comment by jessebett** [comment] 2019-11-14 17:54
@skye thanks for the reply. Trying to build a custom fork so I'll do a rebase with master now and hopefully the CUDA 10.0 `linker_bin_path` issue will also work out. I'll report back once I get to it.

**Comment by jessebett** [comment] 2019-11-14 19:49
Possibly related to @skye 's comment on tensorflow fix, but I also can't build jax master without cuda support either. #1689

**Comment by skye** [comment] 2019-11-14 22:50
@hawkinsp is working on a fix for that, stay tuned!

**Comment by jessebett** [comment] 2019-11-20 15:58
@hawkinsp can I get a status update on this? Also, is it related to #1689? I'd like to rebase my fork to current master before continuing with some stuff but since I'm unable to build on any of my machines I'm stopped. If there's a semi-recent commit that doesn't have these issues could you point me to it (even if it is just getting me past the #1689 macOS build would let me keep working on rebasing). Thanks.

**Comment by hawkinsp** [comment] 2019-11-20 17:36
I'm not actually working on this, since no build failures reproduce for me on any platform. So it's hard for me to make progress here.

Can you clarify why the `LD_LIBRARY_PATH` approach didn't work? What exact command line did you run? Where is `libcusolver.so.10.0` located on your machine?

**Comment by hawkinsp** [comment] 2020-04-16 18:57
Do you still experience this problem? We've made quite a few jaxlib releases since then.

**Comment by hawkinsp** [comment] 2020-04-16 18:57
(Closing, feel free to reopen.)

**Closed by hawkinsp** 2020-04-16 18:57 UTC
Labels: question

**Comment by choltz95** [comment] 2020-04-22 16:42
Still have this problem - installed via pip instructions in the readme. 

Have cudnn installed via conda.

Any hints?

<img width="735" alt="Screen Shot 2020-04-22 at 9 42 12 AM" src="https://user-images.githubusercontent.com/5779125/80009180-8f68a600-847d-11ea-8c61-f7d37cf51981.png">

**Comment by choltz95** [comment] 2020-04-22 16:49
Resolved by verifying correct jaxlib wheel + cuda version
