### ISSUE TITLE
Difference between jit and non-jit output on CPU, but not on GPU and TPU

### ISSUE THREAD

**Issue by sinjax** [google/jax#6566] opened 2021-04-26 16:24 UTC
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
import jax
import jax.numpy as jnp
import numpy as np
def apply(mask, scores):
  attention_mask = -1. * 1e30 * (1.0 - mask)
  scores += attention_mask
  unnormalized = scores - scores.max()
  return unnormalized 
mask = np.array(1.0)
scores = jax.numpy.array([0.7, 0.5])
apply(mask, scores), jax.jit(apply)(mask, scores)
```

- [x] If applicable, include full error messages/tracebacks.

The code above produces:

```
(DeviceArray([ 0.        , -0.19999999], dtype=float32),
 DeviceArray([0., 0.], dtype=float32))
```

on a CPU machine but correctly produces:

```
(DeviceArray([ 0.        , -0.19999999], dtype=float32),
 DeviceArray([ 0.        , -0.19999999], dtype=float32))
```

on GPU and TPU
The issue seems to be around `-0.0` and adding it to the score. 
If the key part of the code snippet that adds the `-0.0` is rephrased as the equivalent:

 ```
  attention_mask = 1. * 1e30 * (1.0 - mask)
  scores -= attention_mask
```

Then the CPU produces the same results as GPU and TPU

**Comment by hawkinsp** [comment] 2021-04-26 16:37
I think this might be coming from a fast math optimization in LLVM, most likely algebraic reassociation. With `XLA_FLAGS=--xla_cpu_enable_fast_math=false`, the problem no longer reproduces.

Unfortunately we currently need to allow LLVM reassociation for performance on CPU, although nothing stops you from disabling it locally.

**Comment by jakevdp** [comment] 2021-04-26 17:01
Here's a repro that more directly illustrates what peter is talking about: re-ordering float expressions can change the results due to float roundoff error:
```python
import jax.numpy as jnp
from jax import jit

def result(x, y):
  return (x + y) - y

x = jnp.array(0.2)
y = jnp.array(1E30)
result(x, y), jit(result)(x, y)
```

**Comment by sinjax** [comment] 2021-04-27 08:01
I think the outputs in your example are reversed @jakevdp but I think you're right

**Comment by skye** [comment] 2021-06-08 23:59
@hawkinsp can this conceivably be fixed and we should file an internal XLA issue, or should we close this if there's no reasonable way to fix the default behavior?

**Comment by hawkinsp** [comment] 2021-06-09 00:06
It's a long-known XLA issue, and in principle it is fixable, but it's not an easy fix. So it's not something we're likely to make progress on any time soon.

**Comment by hawkinsp** [comment] 2022-08-12 18:49
This bug has been fixed for a while now!

**Closed by hawkinsp** 2022-08-12 18:49 UTC
Labels: bug, XLA, P3 (no schedule)
