### ISSUE TITLE
segmentation fault when runing unit test 

### ISSUE THREAD

**Issue by jyizheng** [google/jax#9929] opened 2022-03-17 03:05 UTC
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```bach
python3  tests/lax_numpy_test.py --num_generated_cases=5
```

- [x] If applicable, include full error messages/tracebacks.

[ RUN      ] LaxBackedNumpyTests.testOpIscomplex_bfloat16[3,4]
Fatal Python error: Segmentation fault

Current thread 0x00007f19ad5eb740 (most recent call first):
  File "/data00/home/xxx/jax/jax/_src/dispatch.py", line 537 in backend_compile
  File "/data00/home/xxx/jax/jax/_src/profiler.py", line 206 in wrapper
  File "/data00/home/xxx/jax/jax/_src/dispatch.py", line 583 in compile_or_get_cached
  File "/data00/home/xxx/jax/jax/_src/dispatch.py", line 614 in from_xla_computation
  File "/data00/home/xxx/jax/jax/_src/dispatch.py", line 529 in compile
  File "/data00/home/xxx/jax/jax/_src/dispatch.py", line 170 in _xla_callable_uncached
  File "/data00/home/xxx/jax/jax/linear_util.py", line 272 in memoized_fun
  File "/data00/home/xxx/jax/jax/_src/dispatch.py", line 143 in _xla_call_impl
  File "/data00/home/xxx/jax/jax/core.py", line 614 in process_call
  File "/data00/home/xxx/jax/jax/core.py", line 1720 in call_bind
  File "/data00/home/xxx/jax/jax/core.py", line 1708 in bind
  File "/data00/home/xxx/jax/jax/_src/api.py", line 435 in cache_miss
  File "/data00/home/xxx/jax/jax/_src/traceback_util.py", line 162 in reraise_with_filtered_traceback
  File "/data00/home/xxx/jax/jax/_src/test_util.py", line 1072 in _CheckAgainstNumpy
  File "tests/lax_numpy_test.py", line 589 in testOp
  File "/usr/lib/python3.7/contextlib.py", line 74 in inner
  File "/home/xxx/.local/lib/python3.7/site-packages/absl/testing/parameterized.py", line 314 in bound_param_test
  File "/usr/lib/python3.7/unittest/case.py", line 615 in run
  File "/usr/lib/python3.7/unittest/case.py", line 663 in __call__
  File "/usr/lib/python3.7/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.7/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.7/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.7/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.7/unittest/runner.py", line 176 in run
  File "/home/yizhengjiao/.local/lib/python3.7/site-packages/absl/testing/_pretty_print_reporter.py", line 86 in run
  File "/usr/lib/python3.7/unittest/main.py", line 271 in runTests
  File "/usr/lib/python3.7/unittest/main.py", line 101 in __init__
  File "/home/yizhengjiao/.local/lib/python3.7/site-packages/absl/testing/absltest.py", line 2537 in _run_and_get_tests_result
  File "/home/xxx/.local/lib/python3.7/site-packages/absl/testing/absltest.py", line 2569 in run_tests
  File "/home/xxx/.local/lib/python3.7/site-packages/absl/testing/absltest.py", line 2164 in main_function
  File "/home/xxx/.local/lib/python3.7/site-packages/absl/app.py", line 258 in _run_main
  File "/home/xxx/.local/lib/python3.7/site-packages/absl/app.py", line 312 in run
  File "/home/xxx/.local/lib/python3.7/site-packages/absl/testing/absltest.py", line 2166 in _run_in_app
  File "/home/xxx/.local/lib/python3.7/site-packages/absl/testing/absltest.py", line 2049 in main
  File "tests/lax_numpy_test.py", line 6317 in <module>
Segmentation fault (core dumped)

**Comment by aarmey** [comment] 2022-05-19 14:33
I am also seeing a segmentation fault in backend_compile using python 3.10, but only when running the code across multiple processes. This doesn't occur with Jax v0.2.28 and jaxlib v0.1.76, but does with the most recent release and the couple other versions I tried among the v0.3 releases.

**Comment by hawkinsp** [comment] 2022-08-15 17:09
I tried reproducing this at head but it works for me. Closing because I"m going to guess the bug is fixed. If you can still reproduce it, please reopen with instructions on how I can reproduce it!

**Closed by hawkinsp** 2022-08-15 17:09 UTC
Labels: bug
