### ISSUE TITLE
BUG: missing batching rule error with custom call and xmap manual sharding

### ISSUE THREAD

**Issue by seanprime7** [google/jax#11948] opened 2022-08-16 19:58 UTC
### Description

While testing a custom call that I have been working on, I have run into an error `NotImplementedError: Batching rule for 'scale_mask_softmax_fwd' not implemented`

I didn't have to specify a batching rule for other custom calls I worked on and this is the first time running into it.

This custom call takes two input arrays `x` and `mask`.  The shape of `x` and the shape of the output array match.

Here is the traceback
```
Traceback (most recent call last):
  File "tests/test_pjit_softmax.py", line 119, in <module>
    pjitted.lower(x, mask).compiler_ir().dump()
  File "/jax_home/jax/jax/experimental/pjit.py", line 394, in lower
    lowering = _pjit_lower(
  File "/jax_home/jax/jax/experimental/pjit.py", line 868, in _pjit_lower
    return _pjit_lower_cached(jaxpr, in_shardings, out_shardings, *args, **kwargs)
  File "/jax_home/jax/jax/_src/util.py", line 273, in wrapped
    result = call(weak_arg, *args, **kwargs)
  File "/jax_home/jax/jax/experimental/pjit.py", line 913, in _pjit_lower_cached
    return pxla.lower_mesh_computation(
  File "/jax_home/jax/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/jax_home/jax/jax/interpreters/pxla.py", line 2762, in lower_mesh_computation
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/jax_home/jax/jax/interpreters/mlir.py", line 637, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/jax_home/jax/jax/interpreters/mlir.py", line 900, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/jax_home/jax/jax/interpreters/mlir.py", line 1027, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/jax_home/jax/jax/experimental/maps.py", line 1320, in _xmap_lowering_rule
    return _xmap_lowering_rule_spmd_manual(ctx, *args, **kwargs)
  File "/jax_home/jax/jax/experimental/maps.py", line 1501, in _xmap_lowering_rule_spmd_manual
    vectorized_jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_dynamic(f, global_in_avals)
  File "/jax_home/jax/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/jax_home/jax/jax/interpreters/partial_eval.py", line 2088, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/jax_home/jax/jax/interpreters/partial_eval.py", line 2105, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/jax_home/jax/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/jax_home/jax/jax/core.py", line 193, in jaxpr_as_fun
    return eval_jaxpr(closed_jaxpr.jaxpr, closed_jaxpr.consts, *args)
  File "/jax_home/jax/jax/core.py", line 390, in eval_jaxpr
    ans = eqn.primitive.bind(*subfuns, *map(read, eqn.invars), **bind_params)
  File "/jax_home/jax/jax/core.py", line 2344, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/jax_home/jax/jax/core.py", line 327, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/jax_home/jax/jax/interpreters/batching.py", line 211, in process_primitive
    val_out, dim_out = batcher_primitive(vals_in, dims_in, **params)
  File "/jax_home/jax/jax/_src/custom_derivatives.py", line 747, in _custom_vjp_call_jaxpr_vmap
    batched_fun_jaxpr, out_batched = batching.batch_jaxpr(
  File "/jax_home/jax/jax/interpreters/batching.py", line 473, in batch_jaxpr
    return _batch_jaxpr(closed_jaxpr, axis_size, tuple(in_batched), inst,
  File "/jax_home/jax/jax/interpreters/batching.py", line 485, in _batch_jaxpr
    return batch_jaxpr_axes(closed_jaxpr, axis_size, in_axes, out_axes_dest,
  File "/jax_home/jax/jax/interpreters/batching.py", line 490, in batch_jaxpr_axes
    return _batch_jaxpr_axes(closed_jaxpr, axis_size, tuple(in_axes),
  File "/jax_home/jax/jax/_src/util.py", line 273, in wrapped
    result = call(weak_arg, *args, **kwargs)
  File "/jax_home/jax/jax/interpreters/batching.py", line 501, in _batch_jaxpr_axes
    jaxpr_out, _, consts = pe.trace_to_jaxpr_dynamic(f, avals_in)
  File "/jax_home/jax/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/jax_home/jax/jax/interpreters/partial_eval.py", line 2088, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/jax_home/jax/jax/interpreters/partial_eval.py", line 2105, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/jax_home/jax/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/jax_home/jax/jax/core.py", line 193, in jaxpr_as_fun
    return eval_jaxpr(closed_jaxpr.jaxpr, closed_jaxpr.consts, *args)
  File "/jax_home/jax/jax/core.py", line 390, in eval_jaxpr
    ans = eqn.primitive.bind(*subfuns, *map(read, eqn.invars), **bind_params)
  File "/jax_home/jax/jax/core.py", line 324, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/jax_home/jax/jax/core.py", line 327, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/jax_home/jax/jax/interpreters/batching.py", line 216, in process_primitive
    batched_primitive = self.get_primitive_batcher(primitive, frame)
  File "/jax_home/jax/jax/interpreters/batching.py", line 189, in get_primitive_batcher
    raise NotImplementedError(msg.format(primitive))
```

Here is the jaxpr
```
{ lambda ; a:f16[32,16,512,512] b:bool[32,1,512,512]. let
    c:f16[32,1,16,512,512] = reshape[
      dimensions=None
      new_sizes=(32, 1, 16, 512, 512)
    ] a
    d:bool[32,1,1,512,512] = reshape[
      dimensions=None
      new_sizes=(32, 1, 1, 512, 512)
    ] b
    e:f16[32,1,16,512,512] = xmap[
      axis_resources=FrozenDict({'a': ('a',)})
      backend=None
      call_jaxpr={ lambda ; f:f16[1,16,512,512;a:32] g:bool[1,1,512,512;a:32]. let
          h:f16[1,16,512,512] = custom_vjp_call_jaxpr[
            bwd=Wrapped function:

Core: <lambda>

            fun_jaxpr={ lambda ; i:f16[1,16,512,512;a:32] j:bool[1,1,512,512;a:32]. let
                k:f16[1,16,512,512] = scale_mask_softmax_fwd[scale_factor=1.0] i
                  j
              in (k,) }
            fwd_jaxpr_thunk=<function _memoize.<locals>.memoized at 0x7f07be644f70>
            num_consts=0
            out_trees=<function transformation_with_aux.<locals>.<lambda> at 0x7f07be644b80>
          ] f g
        in (h,) }
      donated_invars=(False, False)
      global_axis_sizes=FrozenDict({'a': 32})
      in_axes=(FrozenDict({'a': 0}), FrozenDict({'a': 0}))
      in_positional_semantics=(<_PositionalSemantics.LOCAL: 0>, <_PositionalSemantics.LOCAL: 0>)
      name=<unnamed function>
      out_axes=(FrozenDict({'a': 0}),)
      out_positional_semantics=_PositionalSemantics.LOCAL
      resource_env=ResourceEnv(Mesh(array([0, 1, 2, 3]), ('a',)), ())
      spmd_in_axes=None
      spmd_out_axes=None
    ] c d
    l:f16[32,16,512,512] = reshape[dimensions=None new_sizes=(32, 16, 512, 512)] e
  in (l,) }
```

This is the test code and `fused_scale_mask_softmax` is a custom call
```python
jax.config.update('experimental_xmap_spmd_lowering', True)
jax.config.update('experimental_xmap_spmd_lowering_manual', True)
attn_mask = AttnMaskType.padding
jitted_out = jax.jit(partial(jax_apex.fused_scale_mask_softmax, attn_mask_type=attn_mask, scale_factor=scale))(x, mask)
with Mesh(numpy.array(jax.devices()).reshape(4), ("a")):
    def xmap_softmax(x, mask):
        x_sharded = x.reshape(x.shape[0], 1, x.shape[1], x.shape[2], x.shape[3])
        mask_sharded = mask.reshape(mask.shape[0], 1, mask.shape[1], mask.shape[2], mask.shape[3])
        axes = ("a", None, None, None, None)
        xmapped = xmap(partial(jax_apex.fused_scale_mask_softmax, attn_mask_type=attn_mask, scale_factor=scale),
                       in_axes=(axes, axes), out_axes=axes, axis_resources={"a": "a"})
        xmapped_out = xmapped(x_sharded, mask_sharded)
        return xmapped_out.reshape(x.shape)

    pjitted = pjit(xmap_softmax,
                   in_axis_resources=(PartitionSpec("a", None, None, None),
                                      PartitionSpec("a", None, None, None)),
                   out_axis_resources=PartitionSpec("a", None, None, None))
    print(jax.make_jaxpr(xmap_softmax)(x, mask))
    pjitted.lower(x, mask).compiler_ir().dump()
    pjitted_out = pjitted(x, mask)

print(numpy.allclose(jitted_out, pjitted_out))
```

### What jax/jaxlib version are you using?

0.3.17

### Which accelerator(s) are you using?

GPU

**Comment by jakevdp** [comment] 2022-08-16 22:28
Can you say more about how `fused_scale_mask_softmax` is implemented? You said it's a custom call... that makes me think that you've created a custom `core.Primitive` representing this opertaions and in the translation rule you've used `custom_call`. If so, the issue is that you don't get the batching rule for free when you create a custom primitive: you have to define it if you want your primitive to be compatible with `vmap`. There's a good example of this in the docs here: https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html#batching

**Comment by seanprime7** [comment] 2022-08-16 22:32
@jakevdp It's a custom `core.Primitive`.

```
_scale_mask_softmax_fwd_p = core.Primitive("scale_mask_softmax_fwd")
_scale_mask_softmax_fwd_p.multiple_results = False
_scale_mask_softmax_fwd_p.def_impl(
    partial(xla.apply_primitive, _scale_mask_softmax_fwd_p)
)
_scale_mask_softmax_fwd_p.def_abstract_eval(_scale_mask_softmax_fwd_abstract)
```

And we provide mlir lowering like below:
```
mlir.register_lowering(
    _scale_mask_softmax_fwd_p,
    _scale_mask_softmax_fwd_cuda_lowering,
    platform="gpu",
)
```

**Comment by seanprime7** [comment] 2022-08-16 22:33
And.. I am not using `vmap`  I am only using `pjit` and `xmap` if that matters.

**Comment by jakevdp** [comment] 2022-08-16 22:35
Thanks - that makes sense. You'll have to define a batching rule for your primitive if you want to use it with `pjit`/`xmap`.

**Comment by seanprime7** [comment] 2022-08-16 22:36
hm.. the thing is I didn't have to for other custom calls I've been working on.  Can you tell me when I need to define a batching rule and when I don't?  It's confusing.

**Comment by seanprime7** [comment] 2022-08-16 22:39
@jekbradbury @apaszke

**Comment by jakevdp** [comment] 2022-08-16 22:40
I believe you need to define a batching rule for your primitive any time you use your primitive in a non-trivial `pmap`, `vmap`, or `xmap` transform.

**Comment by jakevdp** [comment] 2022-08-16 22:44
(actually, I may be wrong, batching may not always come into play for `pmap` and `xmap`)

**Comment by apaszke** [comment] 2022-08-17 07:50
The batching rules are needed whenever the size of the xmapped dimension is unequal (but a multiple) to the mesh dimension size you've assigned to it. Perhaps in your previous tests this condition did hold. It is perfectly reasonable for xmap to require a batching rule from primitives inside it, so this is not a bug.

**Closed** 2022-08-17 07:51 UTC
Labels: bug, P0 (urgent), NVIDIA GPU
