### ISSUE TITLE
ImportError: initialization failed

### ISSUE THREAD

**Issue by ma-sadeghi** [google/jax#10071] opened 2022-03-29 19:19 UTC
- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

Here's how to reproduce (Ubuntu 20.04, Intel Xeon 1650 CPU):

```bash
# Create a fresh virtual env
conda create -n venv python=3.9
conda activate venv

# Install `jax` from conda
conda install jax

# Since I wanted GPU support, next line only removes `jaxlib`, not other deps
conda remove jaxlib --force

# Now I install GPU-compatible `jaxlib`
pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

Now, just enter Python REPL, and import `jax`:

```python
>>> import jax
```

- [x] If applicable, include full error messages/tracebacks.

```python
Traceback (most recent call last):
  File "/home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/scipy/linalg/__init__.py", line 210, in <module>
    from ._matfuncs import *
  File "/home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/scipy/linalg/_matfuncs.py", line 21, in <module>
    from ._matfuncs_sqrtm import sqrtm
  File "/home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/scipy/linalg/_matfuncs_sqrtm.py", line 24, in <module>
    from ._matfuncs_sqrtm_triu import within_block_loop
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-39-x86_64-linux-gnu.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/jax/__init__.py", line 37, in <module>
    from jax import config as _config_module
  File "/home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 101, in <module>
    import jaxlib.lapack as lapack
  File "/home/anaconda/mambaforge/envs/gpu/lib/python3.9/site-packages/jaxlib/lapack.py", line 21, in <module>
    from . import _lapack
ImportError: initialization failed
```

The reason that in the script above I initially install `jax` from `conda` although it's not GPU-compatible is because I want the packages to mostly come from `conda-forge` (for compatibility reasons) and only if that's not possible, get them from `pypi`. In this case, I only want to install GPU-compatible `jaxlib` from PyPI and the rest from `conda-forge`.

If it helps debugging the issue, I tried getting all dependencies from `pypi` (essentially installing `jax` from `pypi` right off the bat after creating a new virtual env), and it works fine. so there must be some package from `conda-forge` that causes the `ImportError`.

To further illustrate the issue, here's the output of `conda list` when everything comes from `pypi`:

```bash
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
absl-py                   1.0.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
flatbuffers               2.0                      pypi_0    pypi
jax                       0.3.4                    pypi_0    pypi
jaxlib                    0.3.2+cuda11.cudnn82          pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgomp                   11.2.0              h1d223b6_14    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
numpy                     1.22.3                   pypi_0    pypi
openssl                   3.0.2                h166bdaf_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
python                    3.9.12          h2660328_1_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scipy                     1.8.0                    pypi_0    pypi
setuptools                61.2.0           py39hf3d152e_1    conda-forge
six                       1.16.0                   pypi_0    pypi
sqlite                    3.37.1               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.1.1                    pypi_0    pypi
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

and here's its output when only `jaxlib` is coming from `pypi`:

```bash
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20211102.0           h27087fc_1    conda-forge
absl-py                   1.0.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
grpc-cpp                  1.44.0               h1021d7f_1    conda-forge
jax                       0.3.4              pyhd8ed1ab_0    conda-forge
jaxlib                    0.3.2+cuda11.cudnn82          pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgfortran-ng            11.2.0              h69a702a_14    conda-forge
libgfortran5              11.2.0              h5c6108e_14    conda-forge
libgomp                   11.2.0              h1d223b6_14    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libprotobuf               3.19.4               h780b84a_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
numpy                     1.22.3           py39h18676bf_0    conda-forge
openssl                   3.0.2                h166bdaf_1    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
python                    3.9.12          h2660328_1_cpython    conda-forge
python-flatbuffers        2.0                pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
re2                       2022.02.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scipy                     1.8.0            py39hee8e79c_1    conda-forge
setuptools                61.2.0           py39hf3d152e_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.1               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

and here's the diff between the two:
```bash
 # Name                    Version                   Build  Channel
 _libgcc_mutex             0.1                 conda_forge    conda-forge
 _openmp_mutex             4.5                       1_gnu    conda-forge
-abseil-cpp                20211102.0           h27087fc_1    conda-forge
-absl-py                   1.0.0              pyhd8ed1ab_0    conda-forge
+absl-py                   1.0.0                    pypi_0    pypi
 bzip2                     1.0.8                h7f98852_4    conda-forge
-c-ares                    1.18.1               h7f98852_0    conda-forge
 ca-certificates           2021.10.8            ha878542_0    conda-forge
-grpc-cpp                  1.44.0               h1021d7f_1    conda-forge
-jax                       0.3.4              pyhd8ed1ab_0    conda-forge
+flatbuffers               2.0                      pypi_0    pypi
+jax                       0.3.4                    pypi_0    pypi
 jaxlib                    0.3.2+cuda11.cudnn82          pypi_0    pypi
 ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
-libblas                   3.9.0           13_linux64_openblas    conda-forge
-libcblas                  3.9.0           13_linux64_openblas    conda-forge
 libffi                    3.4.2                h7f98852_5    conda-forge
 libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
-libgfortran-ng            11.2.0              h69a702a_14    conda-forge
-libgfortran5              11.2.0              h5c6108e_14    conda-forge
 libgomp                   11.2.0              h1d223b6_14    conda-forge
-liblapack                 3.9.0           13_linux64_openblas    conda-forge
 libnsl                    2.0.0                h7f98852_0    conda-forge
-libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
-libprotobuf               3.19.4               h780b84a_0    conda-forge
-libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
 libuuid                   2.32.1            h7f98852_1000    conda-forge
 libzlib                   1.2.11            h166bdaf_1014    conda-forge
 ncurses                   6.3                  h9c3ff4c_0    conda-forge
-numpy                     1.22.3           py39h18676bf_0    conda-forge
+numpy                     1.22.3                   pypi_0    pypi
 openssl                   3.0.2                h166bdaf_1    conda-forge
-opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
+opt-einsum                3.3.0                    pypi_0    pypi
 pip                       22.0.4             pyhd8ed1ab_0    conda-forge
 python                    3.9.12          h2660328_1_cpython    conda-forge
-python-flatbuffers        2.0                pyhd8ed1ab_0    conda-forge
 python_abi                3.9                      2_cp39    conda-forge
-re2                       2022.02.01           h9c3ff4c_0    conda-forge
 readline                  8.1                  h46c0cb4_0    conda-forge
-scipy                     1.8.0            py39hee8e79c_1    conda-forge
+scipy                     1.8.0                    pypi_0    pypi
 setuptools                61.2.0           py39hf3d152e_1    conda-forge
-six                       1.16.0             pyh6c4a22f_0    conda-forge
+six                       1.16.0                   pypi_0    pypi
 sqlite                    3.37.1               h4ff8645_0    conda-forge
 tk                        8.6.12               h27826a3_0    conda-forge
-typing_extensions         4.1.1              pyha770c72_0    conda-forge
+typing-extensions         4.1.1                    pypi_0    pypi
 tzdata                    2022a                h191b570_0    conda-forge
 wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
 xz                        5.2.5                h516909a_1    conda-forge
```

**Comment by hawkinsp** [comment] 2022-03-29 19:46
I think this might be the issue described here: https://github.com/google/jax/issues/9218#issuecomment-1016949739

Did you activate your conda environment?

**Comment by ma-sadeghi** [comment] 2022-03-29 19:57
Thank you for your quick reply.



> From the traceback, it appears the error happens on `import scipy.linalg`. Can you check whether the error occurs on `import scipy.linalg` if you do not install JAX? If so, it may be better to report the error elsewhere.

`import scipy.linalg` works fine even after I install `jax`.

> I think this might be the issue described here: [#9218 (comment)](https://github.com/google/jax/issues/9218#issuecomment-1016949739)
> 
> Did you activate your conda environment?

Yes, I did activate the environment.

However, the link you referenced contained a crucial piece of information! So, it turns out, if I import `scipy.linalg` before importing `jax`, then the problem is gone!

So, the workaround is to run `import scipy.linalg` before `import jax`. @jakevdp Do you think this can be added to `jax`'s `__init__`?

**Comment by hawkinsp** [comment] 2022-03-29 20:02
@ma-sadeghi No, this is a bug in your environment (well, conda's environment, I guess), not in JAX. You have two C++ libraries and you need to arrange that only Conda's version is used.

**Comment by ma-sadeghi** [comment] 2022-03-29 20:08
@hawkinsp Oh, I see. Based on the output of `conda list` I posted, do you know which ones might be conflicting? I'm not very familiar with C libraries.

On another note, do you know if there's any ongoing effort to publish GPU-compatible `jax` on `conda-forge` so it can all be installed in one go?

Thank yo so much!

**Comment by hawkinsp** [comment] 2022-03-29 21:47
The issue is described in https://github.com/google/jax/issues/9218#issuecomment-1016949739 fairly completely.

You most likely have libstdc++ in /lib (or similar) as well as in your conda installation. When using conda, you *must* arrange that conda's libstdc++ is the one found first, or you will get bugs like the one you have. I don't personally use conda, but my belief is that the way to do this is by activating a conda virtual environment. If that isn't happening, I would ask the conda folks. (You can probably do this manually by setting `LD_LIBRARY_PATH` to point to Conda's library path, but I would think that Conda should be doing this for you.)

(We don't distribute Conda binaries ourselves, the conda-forge binaries are community supported.)

(There's no action for us to take here, so I'm closing the bug.)

**Closed by hawkinsp** 2022-03-29 21:47 UTC
Labels: bug
