### ISSUE TITLE
`psum` will fail when using `value_and_grads`

### ISSUE THREAD

**Issue by Doraehhh** [google/jax#10917] opened 2022-06-01 15:04 UTC
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

`psum` will fail when using `value_and_grads` but it will succeed if call it directly

```python
import jax
def fn(arg_0):
    return jax.lax.psum(arg_0, [-1]).sum()

mykey = jax.random.PRNGKey(21847582)
array = jax.random.uniform(mykey, [2], jax.numpy.float32, minval=-8, maxval=64)

arg_0 = array.clone()
print(fn(arg_0))
# 25.462376

arg_0 = array.clone()
jax.value_and_grad(fn, (0))(arg_0)
# ValueError: reduction axes (-1,) contains out-of-bounds indices for ShapedArray(float32[2]).
```

- [x] If applicable, include full error messages/tracebacks.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-c6dfa3d16c05> in <module>
     11 
     12 arg_0 = array.clone()
---> 13 jax.value_and_grad(fn, (0))(arg_0)

    [... skipping hidden 8 frame]

<ipython-input-22-c6dfa3d16c05> in fn(arg_0)
      2 results = dict()
      3 def fn(arg_0):
----> 4     return jax.lax.psum(arg_0, [-1]).sum()
      5 
      6 mykey = jax.random.PRNGKey(21847582)

    [... skipping hidden 14 frame]

/usr/local/lib/python3.9/site-packages/jax/_src/lax/lax.py in _reduce_op_shape_rule(***failed resolving arguments***)
   3488     raise ValueError(f"duplicate value in 'axes' of reduction: {axes}")
   3489   if not all(0 <= a < operand.ndim for a in axes):
-> 3490     raise ValueError(f"reduction axes {axes} contains out-of-bounds indices for {operand}.")
   3491   axes = frozenset(axes)
   3492   return tuple(d for i, d in enumerate(operand.shape) if i not in axes)

ValueError: reduction axes (-1,) contains out-of-bounds indices for ShapedArray(float32[2]).
```

**Comment by jakevdp** [comment] 2022-06-01 15:24
Thank you for the report. Perhaps you can combine all the issues you're reporting into one, to avoid DDOSing the issue tracker? 😀

**Comment by jakevdp** [comment] 2022-06-01 15:24
Closing as a duplicate of #10916

**Closed by jakevdp** 2022-06-01 15:24 UTC
Labels: bug
