### ISSUE TITLE
Check GPU usage

### ISSUE THREAD

**Issue by lightningholt** [google/jax#1266] opened 2019-08-29 18:39 UTC
This is a very basic comment, but I'm new to the GPU game and want to make sure I'm doing things right. Is there a jax command to check that it's using the GPU? I currently have jax installed on my laptop, and a workstation. My laptop does not have a compatible GPU and the first time I run some jax code, I get the following error

 `UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')`

Which makes a lot of sense. And jax runs fairly slow on my laptop because there is no GPU i think [equivalent [autograd](https://github.com/HIPS/autograd) code runs in less than a second, jax takes minutes]. So I expected to see a speed up of my code when I installed [following the steps [here](https://github.com/google/jax#installation)], and indeed when I run a line of jax code on the workstation, I do not see the above error leading me to believe it is utilizing the GPU. But the code still takes a long time to run, so I was wondering if there's a simple command I could run to ensure the GPU is being used correctly.

**Comment by mattjj** [comment] 2019-08-29 18:43
> equivalent autograd code runs in less than a second, jax takes minutes

That sounds like a performance bug! Could you give us a repro so we can attempt to squash it?

It may be that there's some performance bug causing the slowness that affects both CPU and GPU. But it's hard for us to say much more than that without a repro :)

**Comment by lightningholt** [comment] 2019-08-29 18:56
Absolutely! Like I said, I'm new to this GPU game though, what does repro mean?

**Comment by mattjj** [comment] 2019-08-29 22:56
Ah, for posterity, by "repro" I mean "reproduction", i.e. a self-contained bit of code that we can run ourselves to study its behavior.

We just noticed a big performance regression on GPU (mentioned briefly in #1267, but we're following up much more thoroughly internally). It might be related, or it might not! Just thought I'd mention it; we think we know how to fix that one.

**Comment by lightningholt** [comment] 2019-08-30 18:06
I created a jaxVsAutograd [repo](https://github.com/lightningholt/jaxVsAutograd/blob/master/Demo_AutoJax.ipynb) with a ipynb displaying what's happening on my computer. It's a simple example of some rates (r's) being updated by some weight array (W's) with some input (I's), and obeying a reLU input output function.  You can see that jax takes several orders of magnitude longer to run according to %timeit.

**Comment by lightningholt** [comment] 2019-08-30 18:20
And actually the problem seems more specific to how jax deals with @ multiplication in python. 

<img width="824" alt="image" src="https://user-images.githubusercontent.com/12179113/64043038-290ecc00-cb18-11e9-97ef-a03c0ecb05cf.png">

**Comment by hawkinsp** [comment] 2022-01-28 17:08
JAX's `jit` dispatch time has gotten much faster since we last looked at this issue. e.g., the matrix multiplication example is now around 8us on CPU in Colab.

(These matrices are so small that this kind of benchmark is mostly exercising dispatch time.)

Closing because hopefully this issue is fixed; feel free to reopen if there's something new to look at.

**Closed by hawkinsp** 2022-01-28 17:08 UTC
