### ISSUE TITLE
Convolutions leak host memory on Colab GPU runtimes

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#10949] opened 2022-06-02 11:27 UTC
Example:

```python
import jax
import jax.numpy as jnp
import flax.linen as nn

import os, psutil
memusage = lambda: psutil.Process(os.getpid()).memory_info().rss

class CNN(nn.Module):
    @nn.compact
    def __call__(self, x):
        x = nn.Conv(features=32, kernel_size=(5, 5))(x)
        x = nn.Conv(features=3, kernel_size=(5, 5))(x)
        return x

SIZE = 32

@jax.jit
def predict(params):
    model_inputs = jnp.zeros((1, SIZE, SIZE, 3))
    correction = jnp.squeeze(model.apply(params, model_inputs))
    return correction

model = CNN()
batch = jnp.ones((1, SIZE, SIZE, 3))  # (batch, height, width, channels)
params = model.init(jax.random.PRNGKey(0), batch)

for i in range(1000):
    _ = predict(params)

    if i % 100 == 0:
        print(f"i={i} {memusage() / 1e6:.2f} MB")
```

Output:

```
i=0 3721.99 MB
i=100 3724.69 MB
i=200 3727.12 MB
i=300 3729.56 MB
i=400 3731.99 MB
i=500 3734.69 MB
i=600 3737.12 MB
i=700 3739.55 MB
i=800 3742.26 MB
i=900 3744.69 MB
```

[Reproducer on Colab](https://colab.research.google.com/drive/1MUYN9pFuVeKBrh7OqLpgenHy_L3XjT9a?usp=sharing)

**Comment by pschuh** [comment] 2022-07-13 01:18
Colab is still on ubuntu18 and python3.7. I'm not sure if these are a problem, but it makes it hard to work on this. Here is the colab tracking bug for this: https://github.com/googlecolab/colabtools/issues/1880 .  I was unable to reproduce this on a cloud instance with a matching GPU. I can check back on this when they finish their update to 20.04.

**Comment by andylolu2** [comment] 2022-07-26 19:28
I have ran into the same problem as well. I boiled down the example to (the most minimal I can get it to, with help from @jheek from google/flax#2327):
```python
import resource

import jax
import jax.numpy as jnp

kernel1 = jnp.zeros((16,16,3,3))
bias = 0
x = jnp.zeros((1,16,32,32))

@jax.jit
def apply(k, b, x):
    x = jax.lax.conv_general_dilated(x, k, (1, 1), "SAME")
    x = jax.lax.conv_general_dilated(x, k, (1, 1), "SAME")
    x += b
    return x

def mem_snapshot():
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / (1024 ** 2)

print(f"Before: {mem_snapshot():.6f}GB")
for i in range(5000):
    if i % 1000 == 999:
        print(f"Iter {i+1}: {mem_snapshot():.6f}GB")
    _ = apply(kernel1, bias, x)
print(f"After: {mem_snapshot():.6f}GB")
```

Output:
```
Before: 4.486221GB
Iter 1000: 4.502346GB
Iter 2000: 4.517956GB
Iter 3000: 4.533566GB
Iter 4000: 4.549175GB
Iter 5000: 4.564785GB
After: 4.564785GB
```

Colab notebook to reproduce: https://colab.research.google.com/drive/1oWSDpYIDUgFfAe26XqsX9Ufa-Pe_nF4d?usp=sharing

Any help would be appreciated! 🚀

**Comment by pschuh** [comment] 2022-07-27 02:24
Thanks for the minimized reproducer.

I'm seeing leaks from inside cudnn::fusion::ConvBiasActPatternMatchingEngine<cudnn::cnn::EngineContainer>.
Looks like it is the same underlying bug as this: https://github.com/microsoft/onnxruntime/issues/9643 It is fixed in newer cudnn versions.

Indeed, if I upgrade to 11.2 in colab, I get this:
```
!sudo apt-get install libcudnn8=8.1.1.33-1+cuda11.2 cuda-11-2 -y --allow-change-held-packages
```

```
Before: 0.756866GB
Iter 1000: 2.323483GB
Iter 2000: 2.323483GB
Iter 3000: 2.323483GB
Iter 4000: 2.323483GB
Iter 5000: 2.323483GB
After: 2.323483GB
```

**Comment by andylolu2** [comment] 2022-07-27 13:36
Thanks for the fix @pschuh!

**Closed** 2022-07-27 13:38 UTC
Labels: bug
