### ISSUE TITLE
Train ensemble neural networks in a for loop using JAX on GPU and got "RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory"

### ISSUE THREAD

**Issue by ybyangpku** [google/jax#8521] opened 2021-11-11 18:14 UTC
Please:

```python

from models import ensembleNeuralNetworks
from pyDOE import lhs

layers = [1, 128, 128, 128, 128, 128, 1]
for k in range(10000000000):

     model = ensembleNeuralNetworks(layers)
     model.train(iteration = 10000)

     X = lhs(1000000)
     prediction = model.predict(X)

```

The ensembleNeuralNetworks is a class we defined in JAX which trains multiple neural networks at the same time. 
We run a for loop where in each iteration we initialize a new model ensembleNeuralNetworks, train the model and make predictions on the testing locations X which are sampled randomly from Latin Hypercube sampling. After hundreds of iterations within this for loop, we observed the CUDA memory issue as following:

Error that we got:

RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory

Solutions that we have tried to resolve this issue:

Following the suggestion from this link we tried to reduce the pre-allocation of JAX:
https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

This partially solves the problem (we can run much more iterations for this for loop: 300 -> 3,000). 

We are wondering if someone has encountered a similar issue before? Appreciate any suggestions!

**Comment by ybyangpku** [comment] 2021-11-12 19:38
Just to elaborate more about the error message:

jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 32, in <module>
    results, rng_key = run_single_trial(rng_key, i, nIter)
  File "/mnt/castor/seas_home/y/ybyang/NN_BO/Trials/single_trial_function.py", line 109, in run_single_trial
    new_X = acq_model.next_best_point(q = q, num_restarts = 300)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/rpn/acquisitions.py", line 128, in next_best_point
    pos, val = minimize_lbfgs(objective, x0[i,:,:].flatten(), bnds = dom_bounds)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/rpn/optimizers.py", line 26, in minimize_lbfgs
    callback=callback_fn, options = {'maxfun':maxfun})
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/_minimize.py", line 618, in minimize
    callback=callback, **options)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 308, in _minimize_lbfgsb
    finite_diff_rel_step=finite_diff_rel_step)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/optimize.py", line 262, in _prepare_scalar_function
    finite_diff_rel_step, bounds, epsilon=epsilon)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/rpn/acquisitions.py", line 117, in objective
    value, grads = self.acq_value_and_grad(x)
  File "/scratch/ybyang/PythonEnvelope/lib64/python3.6/site-packages/jax/interpreters/xla.py", line 893, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory

**Comment by apaszke** [comment] 2021-11-17 13:42
Based on this code my best guess would be that you might be hitting a memory leak somewhere. Is there a self-contained snippet (ideally with no dependencies other than JAX) that we could use to reproduce your issue?

**Comment by zhangqiaorjc** [comment] 2021-11-17 19:41
We do need a repro (simple code that reproduces this "leak") in order to debug this.

**Comment by apaszke** [comment] 2021-12-08 13:19
I'm going to close this since we cannot reproduce it without more information. But please do reopen the issue if you find time to prepare a self-contained example we could debug! Thanks!

**Closed by apaszke** 2021-12-08 13:19 UTC
Labels: bug, needs info
