### ISSUE TITLE
Allow compilation cache to be saved from process indices that are not process index 0

### ISSUE THREAD

**Issue by simonster** [google/jax#18819] opened 2023-12-05 07:47 UTC
At present, [this check](https://github.com/google/jax/blob/7a3e2140fbda4674da855f611f515d271adba1a1/jax/_src/compiler.py#L387) stops the compilation cache from being written on any process that is not process index 0. This makes sense if the compilation cache directory resides on shared storage. However, in our case, we do not wish to put this directory on shared storage and would instead prefer to save it on every process. WDYT of having an enum state `jax_persistent_cache_write` with values `['always', 'never', 'on_process_0']` to control this behavior?

**Comment by ayaka14732** [comment] 2024-07-02 16:34
This behaviour is supposed to be controlled by the `jax_share_binary_between_hosts` flag: https://github.com/google/jax/blob/42724ebc73e2bd06d5fc9c803c79e33377c7d93f/jax/_src/config.py#L1242-L1249

However, the code is currently written in a way that this flag would be disregarded if `is_multi_process` is true.

**Comment by ayaka14732** [comment] 2024-09-10 16:05
I've tested on TPU v3-32 and the compiled programs are indeed saved on all hosts. Seems that the issue is fixed now.

**Closed by ayaka14732** 2024-09-10 16:05 UTC
Labels: enhancement
