### ISSUE TITLE
How to Run JAX on multi-host GPU platforms

### ISSUE THREAD

**Issue by yxd886** [google/jax#5143] opened 2020-12-09 03:58 UTC
Hi, Currently I found the step to JAX on multi-host TPU Cloud, but I do not find the step to Run JAX on multi-host GPU platforms. Does anyone can help?

**Comment by brettkoonce** [comment] 2020-12-09 04:28
see also #2731

**Comment by hawkinsp** [comment] 2020-12-10 16:23
Closing as a duplicate of #2731 

(The current state is: this actually works, but we don't yet expose a Python API for it, and we don't yet overlap communication with compute, which limits scalability.)

**Closed by hawkinsp** 2020-12-10 16:23 UTC
