### ISSUE TITLE
A nasty bug it seems

### ISSUE THREAD

**Issue by gms-dm** [google/jax#4909] opened 2020-11-16 17:01 UTC
I am getting a crash with an error below. Adding a line
print('compiler error') makes it go away!

Error message:
third_party/tensorflow/stream_executor/lib/statusor.cc:34 - Attempting to fetch value instead of handling error Unimplemented: Unimplemented MHLO -> HloOpcode: %s%19 = "mhlo.broadcast_in_dim"(%18) {broadcast_dimensions = dense<[0, 2]> : tensor<2xi64>} : (tensor<64x16xf32>) -> tensor<64x16x16xf32>

**Comment by hawkinsp** [comment] 2020-11-16 17:06
You're missing the code to reproduce the problem. Could you provide it, please?

I'm also assuming this is on GPU? What jax/jaxlib versions are you using?

**Comment by hawkinsp** [comment] 2020-11-17 03:15
Closing in lieu of internal bug b/173408588, since the bug reproduction involves research code that the author does not want to share on Github.

**Closed by hawkinsp** 2020-11-17 03:16 UTC
