### ISSUE TITLE
Is it always okay to nest jitted functions?

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#2884] opened 2020-04-29 14:55 UTC
Are nested jitted functions supposed to always work?  I've spent two days chasing "escaped tracers" and can't seem to find the problem.  However, removing the jit decorator on the outer function seems to solve the problem.

**Comment by hawkinsp** [comment] 2020-04-29 15:26
You should be able to nest `jit` functions fine. If you had a reproduction, we can look into it.

Two things to be careful of with `jit` are:
a) be careful about side effects
b) don't use tracer values as `static_argnums`. (In fact, we should probably test for that case and fail.)

**Comment by NeilGirdhar** [comment] 2020-04-29 15:52
I have been trying to avoid `static_argnums`.  In fact, this whole problem started when I converted from passing values statically to making everything pytree-like.

I totally agree with your point about testing that all static argnums are free from tracers.

If you have time to look into it, that  would be really awesome!  Here's the [link](https://github.com/NeilGirdhar/fax_suggestions/).  It relies on my pull request for jax that enables custom derivatives on methods (which is fairly minor), so you would have to temporarily [install it](https://github.com/NeilGirdhar/jax).  All of the tests pass except those [here](https://github.com/NeilGirdhar/fax_suggestions/blob/master/cmm/fixed_point/test_use_classes.py).  Unless I remove the `jit` decorator.

**Comment by NeilGirdhar** [comment] 2020-04-29 16:20
@hawkinsp Maybe if there were a way to name the tracers, I could debug this more easily.   Something like

```python
@partial(jit, name_tracers("f_x", "f_y")
def f(x, y): ...
```
and similarly for `grad`, `vjp`, and `jvp`.

Then, at least the error messages and display could far less cryptic.

What do you think?

**Comment by hawkinsp** [comment] 2020-04-29 18:15
@mattjj what do you think about the idea of annotating tracers somehow?

**Comment by NeilGirdhar** [comment] 2020-04-30 18:24
@hawkinsp Is there any documentation about what tracer levels mean?  I see things like "level=-1/1", "level=1/0", "level=0/1".

**Comment by mattjj** [comment] 2020-04-30 18:30
No docs on that, sorry. It's pretty deep internals that I don't think we'd ever want to document, because it's all subject to change and it wouldn't be good to rely on.

I think the only way to get escaped tracer errors (without doing side effects) involves `custom_jvp` rules, because we don't catch and raise errors clearly there. 

I think [this use](https://github.com/NeilGirdhar/fax_suggestions/blob/e71f433b24654fc9f48331a5e41577acc0f8bd13/cmm/fixed_point/combinator.py#L43) of `custom_vjp` is dangerous because tracers could leak in through `self`. I'd guess some kind of trace leakage like that is causing the issue. (It's a requirement of `custom_jvp` and `custom_vjp` that no closures leak in via closure or by being smuggled in through an opaque object.)

**Comment by mattjj** [comment] 2020-04-30 18:32
> b) don't use tracer values as static_argnums. (In fact, we should probably test for that case and fail.)

@hawkinsp I don't think that's a problem, because `static_agnums` is identical to lexical closure (modulo how caching works) and `jit` handles lexical closure fine.

**Comment by mattjj** [comment] 2020-04-30 18:34
> what do you think about the idea of annotating tracers somehow?

That seems doable, especially if we're only talking about annotating _some_ tracers (like those that correspond to function inputs, since lots of other tracers are created and might not correspond to any named values in user code). It wouldn't be trivial plumbing, and we'd want to make it as lightweight as possible.

**Comment by NeilGirdhar** [comment] 2020-04-30 18:44
> No docs on that, sorry. It's pretty deep internals that I don't think we'd ever want to document, because it's all subject to change and it wouldn't be good to rely on.

Fair enough. I'm trying to understand the error "Different traces at the same level".  I don't know what levels mean and why it's a problem for different traces at the same level.

> I think the only way to get escaped tracer errors (without doing side effects) involves custom_jvp rules, because we don't catch and raise errors clearly there.

Okay, good tip.  I'll focus my attention there, thank you.

> I think this use of custom_vjp is dangerous because tracers could leak in through self

Thanks, I'll focus on that.  I've been trying to heed your (or maybe it was shoyer's) warning of no mutable state.   My goal was to treat self as just another parameter.  But it's obvious, I got it wrong somewhere.

> by being smuggled in through an opaque object.

Right, and by opaque object, you mean something that's not registered as a PyTree?  I think I'm registering everything, so there are no opaque objects, but I'll double-check.

> That seems doable, especially if we're only talking about annotating some tracers (like those that correspond to function inputs, since lots of other tracers are created and might not correspond to any named values in user code). It wouldn't be trivial plumbing, and we'd want to make it as lightweight as possible.

Just a comment on this, as I've started debugging this, I temporarily changed the repr in JAX to this:
```python
class Trace:
  def __repr__(self):
    return '{}({}:{}/{})'.format(
        self.__class__.__name__, hex(id(self) & 0xffff)[-4:], self.level, self.sublevel)

class JaxprTracer(Tracer):
  def __repr__(self):
      return 'Traced<{}:{}>'.format(hex(id(self) & 0xffff)[-4:], self._trace)
```
With these modifications, I get a much more useful error:
```
E       jax.core.UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
E       The functions being transformed should not save traced values to global state.
E       Details: Different traces at same level: Traced<3180:JaxprTrace(4e50:-1/1)>, JaxprTrace(7730:-1/1).
```
Now I'm trying to print out every tracer that's created to find out what those correspond to.  
It would be much more useful to get actual names from the inspection, but I didn't want to devote the time to deciphering the JAX internals.

**Comment by NeilGirdhar** [comment] 2020-04-30 20:03
Sorry to bother you with this, but if either of you have a moment, I think I might have a guess as to what's going on, although I'm not sure there's anything wrong with my code.

The collision is happening between the memos received [here](https://github.com/NeilGirdhar/fax_suggestions/blob/e71f433b24654fc9f48331a5e41577acc0f8bd13/cmm/fixed_point/combinator.py#L84), and new tracers created when this jitted function is called [here](https://github.com/NeilGirdhar/fax_suggestions/blob/e71f433b24654fc9f48331a5e41577acc0f8bd13/cmm/fixed_point/combinator.py#L92), which is defined [here](https://github.com/NeilGirdhar/fax_suggestions/blob/e71f433b24654fc9f48331a5e41577acc0f8bd13/cmm/fixed_point/iterated_function.py#L79).

Do these memos count as global state?

**Comment by mattjj** [comment] 2020-04-30 21:12
> Sorry to bother you with this

No worries at all! It's what we're here for. I'm just extremely underwater right now, and responding super slowly and erratically. 

I think I need to find time to run the code and poke at it, but some general advice is only use `custom_vjp` on top-level functions, meaning fully-dedented code (and not an instance method).

> If I know more about the levels, I could maybe bump the level somehow to see if that fixes the problem?

It's not the level values that are the problem (i.e. changing the levels manually won't help), it's the tracer mixup that the level numbers are there to check against. The only way to solve the tracer mixup is to prevent the leak.

I think the leak is happening because of tracers sneaking into the `custom_vjp` function or its rules not through their arguments (i.e. through closure or an opaque container).

Try factoring out the code into top-level functions!

**Comment by NeilGirdhar** [comment] 2020-04-30 21:19
Okay, thanks, I will rewrite it as a top-level function.

**Comment by NeilGirdhar** [comment] 2020-04-30 22:08
Found it!  Apparently, the tracers were sneaking in through the `nondiff_argnums`.  Are those not allowed to be tracers?

**Comment by mattjj** [comment] 2020-04-30 22:11
That should be okay! Sounds like a bug.

Are you working from GitHub master, or the lastest pypi release? I vaguely recall fixing a bug here, but the fix might not have made it up to pypi yet.

**Comment by mattjj** [comment] 2020-04-30 23:22
@hawkinsp 

> b) don't use tracer values as static_argnums.

I just realized what was on Peter's mind when he wrote this. It will essentially never get a `jit` cache hit in this case, though we shouldn't get tracer errors (and incorrect values won't be computed). I think #2813 would raise an error in this case.

**Comment by NeilGirdhar** [comment] 2020-05-01 00:04
> That should be okay! Sounds like a bug in JAX.
>
> Are you working from GitHub master, or the lastest pypi release? I vaguely recall fixing a bug here, but the fix might not have made it up to pypi yet.

[I'm pretty bleeding edge.](https://github.com/NeilGirdhar/jax/commits/master)  Do you remember where your fix was?

>  I think #2813 would raise an error in this case.

Yes, it would!  Since tracer's aren't hashable, then just blocking non-hashables would be enough to get that behaviour.

**Comment by mattjj** [comment] 2020-05-01 00:20
It was from like a week ago, so you'd have it. This sounds like a new bug.

**Comment by NeilGirdhar** [comment] 2020-05-01 00:35
I think I have a MWE.  I'll submit it now.

**Comment by mattjj** [comment] 2020-05-01 01:11
Shall we close this issue in favor of that one?

**Closed** 2020-05-01 01:11 UTC
Labels: question
