### ISSUE TITLE
Unimplemented primitive in Pallas: slice

### ISSUE THREAD

**Issue by bsaoptima** [google/jax#20010] opened 2024-02-28 14:24 UTC
### Description

```
import functools
import jax
from jax.experimental import pallas as pl
import jax.numpy as jnp
import numpy as np
from jaxtyping import Array
from jax.experimental import sparse

key = jax.random.PRNGKey(52)
other = jax.random.normal(key, (10, 10))
diags = jax.random.normal(key, (3, 10))
offsets = (-2, 1, 2)

def dia_matmul_kernel(diags_ref, other_ref, o_ref):
    global offsets
    diags, other = diags_ref[...], other_ref[...]
    N = other.shape[0]
    out = jnp.zeros((N, N))
    for offset, diag in zip(offsets, diags):
        start = max(0, offset)
        end = min(N, N + offset)
        top = max(0, -offset)
        bottom = top + end - start
        out = out.at[top:bottom, :].add(
            diag[start:end, None] * other[start:end, :]
        )
    o_ref[...] = out

def dia_matmul(diags: Array, other:Array) -> Array:    
    return pl.pallas_call(
        dia_matmul_kernel,
        out_shape=jax.ShapeDtypeStruct(other.shape, other.dtype)
    )(diags, other)
dia_matmul(diags, other)
```

The error is:
```
NotImplementedError: Unimplemented primitive in Pallas GPU lowering: slice. Please file an issue on https://github.com/google/jax/issues.
```

I'm not even sure that my code is correct (99% sure it isn't I can't seem to make this simple sparse matrix multiplication work, if anyone has an idea why this is happening, please let me know :)

### System info (python version, jaxlib version, accelerator, etc.)

python=3.11.8
jax=0.4.25
jaxlib=0.4.25+cuda11.cudnn86
jaxtyping=0.2.25

**Comment by sharadmv** [comment] 2024-02-29 00:46
I think this is a duplicate of #19214 . Closing for now.

**Closed by sharadmv** 2024-02-29 00:46 UTC
Labels: bug, pallas
