### ISSUE TITLE
JAX 0.4.1 with Rocm tensorflow-upstream for AMD GPUs

### ISSUE THREAD

**Issue by jigo3635** [google/jax#16997] opened 2023-08-07 10:00 UTC
### Description

Hi, 

We have similar system as LUMI and used the EasyBuild configuration file **jax-0.4.1-cpeGNU-22.08-rocm5.3.eb**

[https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/j/jax/jax-0.4.1-cpeGNU-22.08-rocm5.3/](https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/j/jax/jax-0.4.1-cpeGNU-22.08-rocm5.3/)

where, JAX _v0.4.1_ is built with Rocm tensorflow-upstream _463c9aeff2f52e7988c869b15e1c3876d311b578_ using rocm _v5.3_

However, we are unable to build Jax with this config. If using tensorflow _463c9aeff2f52e7988c869b15e1c3876d311b578_, there is one bug with **c++ unique_ptr** in the submission. So we have to use bug fixed version, e.g. **ed2e564e9944c70a6274f61d7ef6c0c537a458a7** but there are other compiler errors likes

> In file included from external/org_tensorflow/tensorflow/compiler/xla/service/gpu/am
> dgpu_compiler_registration.cc:16:0:
> external/org_tensorflow/tensorflow/compiler/xla/service/gpu/amdgpu_compiler.h: At gl
> obal scope:
> external/org_tensorflow/tensorflow/compiler/xla/service/gpu/amdgpu_compiler.h:36:10:
>  error: 342200230tsl::Status xla::gpu::AMDGPUCompiler::OptimizeHloConvolutionCanonicalizatio
> n(xla::HloModule*, stream_executor::StreamExecutor*, stream_executor::DeviceMemoryAl
> locator*)342200231 marked 342200230override342200231, but does not override
>    Status OptimizeHloConvolutionCanonicalization(
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

though the function looks like to be declaimed as virtual function in the superclass _GpuCompiler_ while it is overrided in subclass _AMDGPUCompiler_. so principally it should be fine.

There are two versions of rocm 5.0.2 and 5.3.3 available on our system.  Do you have any recommendation to install JAX (any versions) with compatible version of Rocm tensorflow-upstream ?

Thanks. /Jing

### What jax/jaxlib version are you using?

jax v0.4.1

### Which accelerator(s) are you using?

AMD GPU

### Additional system info

python 3.9, Cray system

**Comment by hawkinsp** [comment] 2023-08-08 17:18
Please try the *latest* version (0.4.14). Anything older and we can't help you.

**Comment by rahulbatra85** [comment] 2023-08-09 02:59
@jigo3635  We have started releasing jax/jaxlib for ROCm here https://github.com/ROCmSoftwarePlatform/jax/releases. Can you try one of these? 

Also, you can find docker images here https://hub.docker.com/r/rocm/jax/tags.

**Comment by jigo3635** [comment] 2023-08-09 14:37
Hi @rahulbatra85 

Unfortunately the versions of rocm installed on the cluster are too old, v5.0 and v5.3, this is also the reason why I tried to install older version of jax. 

The docker image  **rocm5.6.0-jax0.4.13-py3.9.0** has been installed using singularity.

```

singularity shell --rocm rocm5.6.0-jax0.4.13-py3.9.0
Singularity> python 
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 

# import jax is fine
>>> import jax 

>>> import jax.numpy as jnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jax.numpy'

>>> import jax.grad
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'grad' from 'jax'
...
```

It seems to me that only _jax_ is available but not any submodules such as _jax.numpy_,  _jax.random_ etc.  Is the installation of docker image correct? Thanks /Jing

**Comment by SarthakYadav** [comment] 2023-08-11 11:57
I tried the above, and had the same error.
@rahulbatra85  The pip installation from releases you linked seems to only installs jaxlib, not jax. (Even under the "Install jax", the URL points to the same jaxlib .whl file). Maybe that's the issue.

**Comment by rahulbatra85** [comment] 2023-08-14 01:19
@SarthakYadav As you can see, jaxlib 0.4.13 wheels are released for ROCm 5.5 and 5.6.  

Instead of running baremetal, have you tried using the docker images mentioned on this page? They already have jax and jaxlib installed, so you don't even have to install the wheels. Also, the right ROCm version is already available in the docker images.

https://github.com/ROCmSoftwarePlatform/jax/releases

**Comment by SarthakYadav** [comment] 2023-08-14 14:19
@rahulbatra85 I pulled the following docker image (to build a singularity image): rocm/jax:rocm5.5.0-jax0.4.12-py3.9.0

Upon running the singularity container, the correct rocm (5.5.0) is found in path, but the default python version is only 3.8, not 3.9, same as @jigo3635

I found the problem: when we run it as a singularity container, the following error is received:

`source: /.singularity.d/env/10-docker2singularity.sh:2:8: invalid var name`

It might be unrelated, but I think this results in python3.9 (which is at `/pyenv/shims/python` in the container) not being added to the path.

Once manually added it works, I can initialize arrays and run dot products on the GPU. Will report back once I get more complex examples going.

Can you recommend which paths can we explicitly add to paths to ensure everything works right?

**Comment by rahulbatra85** [comment] 2023-08-14 15:23
@SarthakYadav You shouldn't need to add any paths explicitly. 

When I run/start the docker container using this image rocm/jax:rocm5.5.0-jax0.4.12-py3.9.0, the python version is 3.9. 

To verify on your end, is it possible for you run the container just using docker and not use singularity? May be the problem is how singularity image is built.

**Comment by rahulbatra85** [comment] 2023-08-17 14:39
@jigo3635 Can you confirm which JAX python packages are installed?
`python3[or python] -m pip list | grep jax`

Also, what's the ROCm installation path? Is it /opt/rocm?

**Comment by jigo3635** [comment] 2023-08-17 14:48
@rahulbatra85 , 

Here is the output
```
singularity shell --rocm jax0.4.13_rocm5.5.0_python3.9.0

Singularity> ls /opt/rocm
rocm/       rocm-5.5.0/ 
Singularity> ls /opt/rocm/
amdgcn		 hipfft		     lib      rocalution   rocsolver
bin		 hiprand	     libexec  rocblas	   rocsparse
hip		 hipsolver	     llvm     rocfft	   rocthrust
...

Singularity> /pyenv/shims/python  -m pip list | grep jax
jax                  0.4.1
jaxlib               0.4.1
```

The version of jax/jaxlib  (0.4.1) seems not to be correct.   Perhaps it is the issue to use  

**/pyenv/shims/python** !?

**Comment by rahulbatra85** [comment] 2023-08-17 15:40
ROCm jaxlib wheels will have ROCm in the name. The Jaxlib that you have installed is what Google releases on PyPI. To my understanding that only supports CPU(https://github.com/google/jax#pip-installation-cpu). And obviously, it  doesn't have ROCm support in it. For ROCm support you have to specifically install ROCm jaxlib from the releases page that I shared with you above(https://github.com/ROCmSoftwarePlatform/jax/releases). It's similar even for CUDA. See https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier. 

By the way, to my knowledge JAX team is working on a plugin mechanism where the same Jaxlib wheel can support different HW backends. Unfortunately, it's not available yet.

**Comment by jigo3635** [comment] 2023-08-17 18:04
@rahulbatra85,

Thanks for the explanation. So, I need to do one more step with singularity
```

# build a singularity sandbox of jax0.4.13 from the docker
$ singularity build --sandbox jax0.4.13-rocm5.6.0-py3.9.0 docker://rocm/jax:rocm5.6.0-jax0.4.13-py3.9.0

# login the writeable sandbox  
$ sudo singularity shell -w jax0.4.13-rocm5.6.0-py3.9.0 
Singuarlity >

# install jaxlib-v0.4.13 with rocm
# /usr/bin/python version is 3.8 while pyenv/shims/python is 3.9
Singularity > /pyenv/shims/python -m pip install https://github.com/ROCmSoftwarePlatform/jax/releases/download/jaxlib-v0.4.13-rocm560/jaxlib-0.4.13+rocm560-cp39-cp39-manylinux2014_x86_64.whl

```
If I understand correctly from the previous conversations,  the last step to installation **jaxlib-v0.4.13** is _NOT_ necessary if directly run docker image.  Thanks /Jing

**Comment by rahulbatra85** [comment] 2023-08-17 18:11
Correct, but you are building singularity image from the docker image. May be during this build something is installing jax/jaxlib 0.4.1. 

Also, you should install the correct version of jax wheel also(can be from ROCm release page or PyPI directly since there isn't any ROCm specific piece in JAX itself, but jaxlib only).

**Comment by jigo3635** [comment] 2023-08-18 07:57
@rahulbatra85 

This is really issue:

`source: /.singularity.d/env/10-docker2singularity.sh:2:8: invalid var name
`

```
cat /.singularity.d/env/10-docker2singularity.sh:2:8

export XLA_CLONE_DIR:/workspace/jax-xla-repo="${XLA_CLONE_DIR:/workspace/jax-xla-repo:-}"
export XLA_REPO="${XLA_REPO:-"https://github.com/ROCmSoftwarePlatform/xla.git"}"
...
export XLA_CLONE_DIR="${XLA_CLONE_DIR:-"/workspace/jax-xla-repo"}"

```

So, to remove the fist line with _sudo_ and recreate new .sif  image works fine now.
```

$ singularity shell jax0.4.13_rocm5.5.0_python3.9.0 --rocm 
Singularity> python
>>> import jax
>>> print(jax.devices())
[gpu(id=0), gpu(id=1), gpu(id=2), gpu(id=3), gpu(id=4), gpu(id=5), gpu(id=6), gpu(id=7)]
```

Thanks a lot for the help. /Jing

**Comment by rahulbatra85** [comment] 2023-08-18 14:09
@hawkinsp @jakevdp We can close this issue now. Thanks!

**Comment by hawkinsp** [comment] 2023-08-18 14:17
Thanks!

**Closed by hawkinsp** 2023-08-18 14:17 UTC
Labels: bug, needs info, AMD GPU

**Comment by reachtarunhere** [comment] 2024-01-21 16:31
> @rahulbatra85
> 
> This is the really issue:
> 
> `source: /.singularity.d/env/10-docker2singularity.sh:2:8: invalid var name `
> 
> ```
> cat /.singularity.d/env/10-docker2singularity.sh
> 
> export XLA_CLONE_DIR:/workspace/jax-xla-repo="${XLA_CLONE_DIR:/workspace/jax-xla-repo:-}"
> export XLA_REPO="${XLA_REPO:-"https://github.com/ROCmSoftwarePlatform/xla.git"}"
> ...
> export XLA_CLONE_DIR="${XLA_CLONE_DIR:-"/workspace/jax-xla-repo"}"
> ```
> 
> So, to remove the fist line with _sudo_ and recreate new .sif image works fine now.
> 
> ```
> 
> $ singularity shell jax0.4.13_rocm5.5.0_python3.9.0 --rocm 
> Singularity> python
> >>> import jax
> >>> print(jax.devices())
> [gpu(id=0), gpu(id=1), gpu(id=2), gpu(id=3), gpu(id=4), gpu(id=5), gpu(id=6), gpu(id=7)]
> ```
> 
> Thanks a lot for the help. /Jing

Hi @jigo3635 I am facing the exact issue as you. Can you make it more clear what file do I need to modify? I am not sure where exactly 10-docker2singularity.sh file is

**Comment by jigo3635** [comment] 2024-01-21 17:39
Hi @reachtarunhere,

> I am not sure where exactly 10-docker2singularity.sh file is
I suppose that you have a singularity sandbox. So you can do likes
```

> sudo singularity shell -w <singularity.box>

# within the sandbox, the files is located in  /.singularity.d/env/10-docker2singularity.sh
singularity$ ls /.singularity.d/env/10-docker2singularity.sh
...
(use one text editor to remove or comment the first line of this file, i.e.

export XLA_CLONE_DIR:/workspace/jax-xla-repo="${XLA_CLONE_DIR:/workspace/jax-xla-repo:-}"

```
