### ISSUE TITLE
What is ComplexWarning?

### ISSUE THREAD

**Issue by XiaotongNi** [google/jax#2050] opened 2020-01-23 14:12 UTC
I get "ComplexWarning: Casting complex values to real discards the imaginary part
lambda t, new_dtype, old_dtype: [convert_element_type(t, old_dtype)])", but I don't know how does it happen or whether I should do anything about this.
I noticed that in the document https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#Complex-numbers-and-differentiation , input[28] also contains this warning, but there's no explanation around it. 
(Sorry if this doesn't deserve an issue. I'm not an experienced Github user.)

**Comment by hawkinsp** [comment] 2020-01-23 14:18
The warning means that a complex number was cast to a real number, which discards the imaginary part of the number. That could happen for many reasons.

As to *why* that is happening, I'd suggest using `pdb` or similar to set a breakpoint at that warning, and then look at the call stack and find out what code called the conversion.

Alternatively, you could share a self-contained runnable example and we might then be able to suggest what the problem is.

Hope that helps!

**Comment by XiaotongNi** [comment] 2020-01-24 03:11
> Alternatively, you could share a self-contained runnable example and we might then be able to suggest what the problem is.

Thanks for replying. For an example, I mentioned that the warning also happened in the document of Jax https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#Complex-numbers-and-differentiation  (input[28])

(I haven't done any serious Python debugging before. So I would appreciate if you can point me to a good guide about python debugging. For example, I tried to
(Pdb) b /miniconda3/lib/python3.7/site-packages/jax/lax/lax.py:1905
which is where the ComplexWarning happens.
But when I (Pdb) c  later, it doesn't stop at any point.)

**Comment by hawkinsp** [comment] 2020-04-16 20:58
The fix for this is to call `jax.numpy.real` explicitly instead of doing a type conversion from complex to real.

I personally am not a `pdb` user so I can't give you tips on using it, but one way I personally would debug this is to check out JAX from source and add code like:

```
import traceback
traceback.print_stack()
```
right before the code that raises the `ComplexWarning` to figure out where it came from. 

(I am mostly a `print` debugger, and I'm sure some Python experts will chime in and tell me that this is easy with `pdb`!)

Hope that helps!

**Closed by hawkinsp** 2020-04-16 20:58 UTC
Labels: question
