### ISSUE TITLE
"cudaErrorMemoryAllocation : out of memory" when more than one program involving JAX and cuDNN

### ISSUE THREAD

**Issue by CHYjeremy** [google/jax#17217] opened 2023-08-22 07:47 UTC
### Description

Hi,

The thing is, when i first create a code involving JAX and cuDNN, everything works just as fine. But if i start running a completely same code, the second will instantly crash and report the following information:

```E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:413] There was an error before creating cudnn handle (2): cudaErrorMemoryAllocation : out of memory```

Note that the code involve JAX.JIT and i did put these two code into seperate GPUs. 

May i know what happened? thanks~

### What jax/jaxlib version are you using?

I install via the following command: pip install --upgrade "jax[cuda12_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux Ubuntu 22.04

### NVIDIA GPU info

```
Tue Aug 22 15:45:38 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090         On | 00000000:4F:00.0 Off |                  N/A |
| 79%   80C    P2              328W / 350W|  23808MiB / 24576MiB |     95%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090         On | 00000000:52:00.0 Off |                  N/A |
| 79%   87C    P2              355W / 350W|   9588MiB / 24576MiB |     90%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce RTX 3090         On | 00000000:56:00.0 Off |                  N/A |
| 79%   82C    P2              347W / 350W|   9588MiB / 24576MiB |     92%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce RTX 3090         On | 00000000:57:00.0 Off |                  N/A |
| 33%   44C    P8               31W / 350W|    972MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce RTX 3090         On | 00000000:CE:00.0 Off |                  N/A |
| 64%   65C    P2              370W / 350W|  19206MiB / 24576MiB |     51%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce RTX 3090         On | 00000000:D1:00.0 Off |                  N/A |
| 32%   41C    P8               27W / 350W|    972MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA GeForce RTX 3090         On | 00000000:D5:00.0 Off |                  N/A |
| 57%   59C    P2              149W / 350W|   1980MiB / 24576MiB |     37%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA GeForce RTX 3090         On | 00000000:D6:00.0 Off |                  N/A |
| 79%   86C    P2              331W / 350W|   4438MiB / 24576MiB |     93%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by erfanzar** [comment] 2023-08-23 08:04
are you using any special array sharding methods like pjit ,pmap or anything like that?



The error message "cudaErrorMemoryAllocation : out of memory"  can happen for a few reasons:

1. The code is trying to allocate too much memory.
2. The GPU is already running low on memory due to other processes.
3. There is a memory leak in the code.

To troubleshoot this issue, you can try the following:

1. Check the code to make sure that it is not trying to allocate too much memory.
2. Close any other processes that are using the GPU.
3. Use the gdb debugger to find memory leaks in the code.


You can also try setting the environment variable XLA_PYTHON_CLIENT_PREALLOCATE=false. This will disable the preallocation behavior, which can sometimes help to reduce memory usage.
```python
import os
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
os.environ['XLA_PYTHON_CLIENT_ALLOCATOR'] = 'gpu'
```

and if you want to have a better look at the detail of the processing code and know exactly about the size of the buffer or executable you can use Jax-smi or my code
```shell
pip install fjutils
```

```python
from fjutils.tracker import initialise_tracking, threaded_log, get_mem

if __name__ == "__main__":
    initialise_tracking()
    threaded_log().start()
    # or
    print(get_mem())
```

**Comment by Micky774** [comment] 2024-04-18 23:50
Closing as a duplicate of https://github.com/google/jax/issues/12461

The gist of it is as mentioned above: JAX pre-allocates memory, and on systems with less VRAM this can be enough to lead to memory starvation which renders CUDA initialization impossible. See [this comment](https://github.com/google/jax/issues/12461#issuecomment-1256284886) from the linked issue, as well as [this section](https://jax.readthedocs.io/en/latest/faq.html#why-do-some-cuda-libraries-fail-to-load-initialize) of the FAQ.

**Closed by Micky774** 2024-04-18 23:50 UTC
Labels: bug
