### ISSUE TITLE
jax.lax.while_loop unnecessary comparison

### ISSUE THREAD

**Issue by Amir-Mehrpanah** [google/jax#18187] opened 2023-10-19 15:03 UTC
### Description

This is a MWE to reproduce the error.
Note that `while_loop(cond_fun=cond_fun, body_fun=body_fun, init_val=init_val)` works just fine, and I expect `while_loop(cond_fun=cond_fun_buggy, body_fun=body_fun_buggy, init_val=init_val_buggy)` to work exactly the same.

```
import jax
from collections import namedtuple

Stream = namedtuple("Stream", ["name"])
init_val = {Stream("x"): 0, Stream("y"): 0, Stream("i"): 0}
init_val_buggy = {Stream("x"): 0, Stream("y"): 0, "i": 0}

def body_fun(s):
    s[Stream("i")] += 1
    return s

def body_fun_buggy(s):
    s["i"] += 1
    return s

def cond_fun(s):
    return s[Stream("i")] < 10

def cond_fun_buggy(s):
    return s["i"] < 10

jax.lax.while_loop(cond_fun=cond_fun, body_fun=body_fun, init_val=init_val)
jax.lax.while_loop(cond_fun=cond_fun_buggy, body_fun=body_fun_buggy, init_val=init_val_buggy)
```
The last line leads to this error: 
```
Traceback (most recent call last):
  File "/outputs/jax_bug_mwe.py", line 23, in <module>
    jax.lax.while_loop(cond_fun=cond_fun_buggy, body_fun=cond_fun_buggy, init_val=init_val_buggy)
  File "/miniconda3/envs/jaxbugs/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/miniconda3/envs/jaxbugs/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 1150, in while_loop
    init_vals, init_avals, body_jaxpr, in_tree, *rest = _create_jaxpr(init_val)
  File "/miniconda3/envs/jaxbugs/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 1129, in _create_jaxpr
    init_vals, in_tree = tree_flatten((init_val,))
  File "/miniconda3/envs/jaxbugs/lib/python3.9/site-packages/jax/_src/tree_util.py", line 61, in tree_flatten
    return pytree.flatten(tree, is_leaf)
jax._src.traceback_util.UnfilteredStackTrace: TypeError: '<' not supported between instances of 'str' and 'Stream'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/outputs/jax_bug_mwe.py", line 23, in <module>
    jax.lax.while_loop(cond_fun=cond_fun_buggy, body_fun=body_fun_buggy, init_val=init_val_buggy)
TypeError: '<' not supported between instances of 'str' and 'Stream'
```

### What jax/jaxlib version are you using?

jax 0.4.13, jaxlib 0.4.13+cuda12.cudnn89

### Which accelerator(s) are you using?

CPU

### Additional system info

python 3.9 debian

**Comment by jakevdp** [comment] 2023-10-19 16:28
Thanks for the report!

The issue is that JAX transformations are not compatible with arbitrary dicts, but only dicts whose keys are sortable (See #15358 for details).

I'm going to close this because it's essentially a duplicate of #15358

**Closed by jakevdp** 2023-10-19 16:28 UTC
Labels: bug, duplicate

**Comment by jakevdp** [comment] 2023-10-19 16:30
Also related is #4085, where there is some discussion of how pytree dict handling might be re-designed in a way that would relax this sort-compatible key requirement.
