### ISSUE TITLE
AttributeError: _ARRAY_API not found in Numpy 2.0.0

### ISSUE THREAD

**Issue by WhiteSymmetry** [google/jax#21937] opened 2024-06-17 23:06 UTC
### Description

 File "/home/*/lib/python3.11/site-packages/jax/_src/lib/__init__.py", line 87, in <module>
    import jaxlib.xla_client as xla_client
  File "/home/*/lib/python3.11/site-packages/jaxlib/xla_client.py", line 32, in <module>
    from . import xla_extension as _xla
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: _ARRAY_API not found

Numpy: 1.x
It doesn’t give an error in numpy 1.x.

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.27
jaxlib: 0.4.23.dev20240125 & 0.4.23.dev20240522
numpy:  2.0.0
python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:53:30) [GCC 12.3.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='mk', release='6.9.3-060903-generic', version='#202405300957 SMP PREEMPT_DYNAMIC Thu May 30 11:39:13 UTC 2024', machine='x86_64')

**Comment by superbobry** [comment] 2024-06-18 08:46
I cannot reproduce this in a fresh virtualenv. Can you confirm that doing

```
python -m venv env
source env/bin/activate
pip install jax==0.4.27 jaxlib==0.4.27 numpy==2.0
python -c "import jax"
```

reproduces the issue for you?

**Comment by WhiteSymmetry** [comment] 2024-06-18 11:17
Since my computer only supports the CPU feature, I can install jaxlib's conda and mamba. I tried again today, and it gave the same error. 

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<string>", line 1, in <module>
  File "/home/*/miniconda3/envs/x11/lib/python3.11/site-packages/jax/__init__.py", line 37, in <module>
    import jax.core as _core
  File "/home/*/miniconda3/envs/x11/lib/python3.11/site-packages/jax/core.py", line 18, in <module>
    from jax._src.core import (
  File "/home/*/miniconda3/envs/x11/lib/python3.11/site-packages/jax/_src/core.py", line 39, in <module>
    from jax._src import dtypes
  File "/home/*/miniconda3/envs/x11/lib/python3.11/site-packages/jax/_src/dtypes.py", line 33, in <module>
    from jax._src import config
  File "/home/*/miniconda3/envs/x11/lib/python3.11/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/*/miniconda3/envs/x11/lib/python3.11/site-packages/jax/_src/lib/__init__.py", line 87, in <module>
    import jaxlib.xla_client as xla_client
  File "/home/*/miniconda3/envs/x11/lib/python3.11/site-packages/jaxlib/xla_client.py", line 32, in <module>
    from . import xla_extension as _xla
AttributeError: _ARRAY_API not found  
![Screenshot from 2024-06-18 14-12-57](https://github.com/google/jax/assets/5471497/ac070232-ff58-45d1-b3fe-d2e0866f1fc7)

**Comment by superbobry** [comment] 2024-06-18 11:21
It look like the `jaxlib` package in Conda was compiled for NumPy 1.X? I would recommend to either install JAX from PyPI via `pip` or open an issue in https://github.com/conda-forge/jaxlib-feedstock.

**Comment by hawkinsp** [comment] 2024-06-18 11:29
Closing. We don't provide the conda packages for JAX: please file issues for those against the conda-forge feedstock linked above. The pip packages we ship will work with NumPy 2.0, and we recommend you use those if you want NumPy 2.0 support, even if you're otherwise using conda-forge.

**Closed by hawkinsp** 2024-06-18 11:29 UTC
Labels: bug, needs info
