### ISSUE TITLE
'out_buf' is not defined when jax_debug_nans is True

### ISSUE THREAD

**Issue by matthewdhoffman** [google/jax#1327] opened 2019-09-09 17:20 UTC
In jax/interpreters/xla.py,
`if FLAGS.jax_debug_nans: check_nans(xla_call_p, out_buf)`
gives me
`NameError: name 'out_buf' is not defined`
when `jax_debug_nans` is True.

**Comment by romanngg** [comment] 2019-09-09 20:49
Hit the same issue and sent a pull request here
https://github.com/google/jax/pull/1324

**Comment by mattjj** [comment] 2019-09-10 14:16
I think this might be a duplicate of #1258, which #1324 should have fixed. Unfortunately, #1324 didn't add a test, so it's hard to be sure! (@romanngg want to add one?)

**Closed by mattjj** 2019-09-10 14:16 UTC

**Comment by romanngg** [comment] 2019-09-10 22:16
Thanks Matt, will look into it, but probably next week!
