### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by alexbw** [google/jax#104] opened 2018-12-13 16:28 UTC
In Autograd, we had https://github.com/airspeed-velocity/asv

**Comment by gnecula** [comment] 2019-11-19 22:06
We really need such tests, and they should be able to check for memory usage regressions. E.,g. #1710

**Comment by hawkinsp** [comment] 2022-08-12 19:48
We have a number of performance benchmarks. Closing because we should just add more as needed.

**Closed by hawkinsp** 2022-08-12 19:48 UTC
Labels: enhancement
