### ISSUE TITLE
`triangular_solve` does not work well with batching

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#4888] opened 2020-11-12 21:54 UTC
Currently, the following script
```python
from jax.scipy.linalg import solve_triangular
import jax.numpy as jnp

dim = 130
x = jnp.broadcast_to(jnp.eye(dim), (2, dim, dim))
solve_triangular(x, x)  # error
```
raises the issue: `RuntimeError: Invalid argument: The rank of the operand and the padding configuration do not match: f32[126,126] vs dimensions { } dimensions { edge_padding_low: 2 } dimensions { }.: `

This does not fail when
+ `dim <= 128`
+ no batching (`(2,)` in the above script)

**Comment by hawkinsp** [comment] 2020-11-12 22:16
I think this is a duplicate of https://github.com/google/jax/issues/4773 and already fixed in jaxlib head.

(We're also in the process of pushing new wheels, so hopefully the deployed wheels also.)

Please reopen if that turns out not to be true!

**Closed by hawkinsp** 2020-11-12 22:16 UTC
Labels: bug

**Comment by fehiepsi** [comment] 2020-11-12 22:19
Oh, thanks @hawkinsp! What a coincidence. :)

**Comment by mattjj** [comment] 2020-11-12 22:25
I think jaxlib 0.1.57 may already be available on pypi, so try a `pip install --upgrade jaxlib` and see if the issue persists.

**Comment by fehiepsi** [comment] 2020-11-12 22:27
Thanks, Matt! I can confirm that the issue has been resolved.
