### ISSUE TITLE
jax, jaxlib versions 0.4.32 and 0.4.33 causing errors

### ISSUE THREAD

**Issue by dkweiss31** [google/jax#23690] opened 2024-09-17 11:22 UTC
### Description

It seems that packages such as equinox and diffrax (and probably others) are broken by the latest versions 0.4.32 and 0.4.33 of jax and jaxlib. Here is example code that throws the error I keep seeing (and runs with 0.4.31), apologies that it includes internal equinox code
```python
import equinox.internal as eqxi
import jax
import jax.lax as lax
import jax.numpy as jnp
import jax.random as jr
import jax.tree_util as jtu


init = (0, 2)
xs = (jnp.arange(4.0), jnp.arange(8.0).reshape(4, 2))


def lax_run(init, xs):
    final, ys = lax.scan(lambda car, x: (car, x), init, xs)
    return ys, final


def run(init, xs):
    final, ys = eqxi.scan(
        lambda car, x: (car, x), init, xs, length=4, kind="checkpointed"
    )
    return ys, final


lax_out, lax_vjp_fn, lax_aux = jax.vjp(lax_run, init, xs, has_aux=True)
ct_out = jtu.tree_map(
    lambda x: jr.normal(jax.random.PRNGKey(0), x.shape, x.dtype), lax_out
)


@jax.jit
def vjp_run(init, xs, ct_out):
    out, vjp_fn, aux = jax.vjp(run, init, xs, has_aux=True)
    out = (out, aux)
    grad = vjp_fn(ct_out)
    return out, grad

out, grad = vjp_run(init, xs, ct_out)

```
This code is modified from equinox's tests/test_scan.py, just to have a standalone example. The error is 
```python
ValueError: Closure-converted function called with different dynamic arguments to the example arguments provided.
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.33
jaxlib: 0.4.33
numpy:  2.1.1
python: 3.10.14 (main, May  6 2024, 14:42:37) [Clang 14.0.6 ]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Darwin', node='MacBook-Pro-62.local', release='23.6.0', version='Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000', machine='arm64')
```

**Comment by jakevdp** [comment] 2024-09-17 13:14
Hi, thanks for the report! This error seems to be coming from equinox (see this search: https://github.com/search?q=repo%3Apatrick-kidger%2Fequinox%20%22Closure-converted%20function%20called%20with%22&type=code)

If you're able to reproduce this error without equinox, then there's problably something we can fix here. If the error only occurs with equinox, then I suspect you'd make more progress reporting it at https://github.com/patrick-kidger/equinox/

**Comment by dkweiss31** [comment] 2024-09-17 13:49
Understood, and thanks for the quick reply! Tagging @patrick-kidger for visibility, as he might be better suited than I for producing a possible jax-only MWE.

**Comment by hawkinsp** [comment] 2024-09-17 15:43
I bisected this to commit [dd6f0e2e2ed13869eb7641ebff854ff5e8077e82](https://github.com/google/jax/commit/dd6f0e2e2ed13869eb7641ebff854ff5e8077e82), with the released jaxlib.

Perhaps that helps?

**Comment by lockwo** [comment] 2024-09-17 18:56
> I bisected this to commit [dd6f0e2e2ed13869eb7641ebff854ff5e8077e82](https://github.com/google/jax/commit/dd6f0e2e2ed13869eb7641ebff854ff5e8077e82), with the released jaxlib.
> 
> Perhaps that helps?

When I experimented with this, it is possible it is related to a comparison in which Structs have differing weak types (which I assume wasn't a problem before that commit, because there was not weak type attribute to compare): https://github.com/patrick-kidger/equinox/issues/854#issuecomment-2356666036.

**Comment by hawkinsp** [comment] 2024-09-17 19:27
My current belief is that there's no action needed from JAX here: we're simply providing additional information as part of shape evaluation, and equinox needs an update to handle that.

**Comment by hawkinsp** [comment] 2024-09-18 15:04
Closing, this needs a fix in equinox.

**Closed by hawkinsp** 2024-09-18 15:04 UTC
Labels: bug
