### ISSUE TITLE
Jax throws internal XLA error for sufficiently large batched outer product on GPU

### ISSUE THREAD

**Issue by Chillee** [google/jax#5733] opened 2021-02-16 01:17 UTC
Code:
```
import jax.numpy as jnp


A = jnp.ones((4, 1024*1024, 1))
B = jnp.ones((4, 1024*1024, 1))

tot = 0
def f(A, B):
  return  A[:,:,None,:] * B[:,None, :, :]
f(A, B)
```

throws

```
/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py in _execute_compiled_primitive(prim, compiled, result_handler, *args)
    355   device, = compiled.local_devices()
    356   input_bufs = list(it.chain.from_iterable(device_put(x, device) for x in args if x is not token))
--> 357   out_bufs = compiled.execute(input_bufs)
    358   check_special(prim, out_bufs)
    359   return result_handler(*out_bufs)

RuntimeError: Resource exhausted: Out of memory while trying to allocate 4398046511104 bytes.: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
```

Using GPU runtime

https://colab.research.google.com/drive/11MPml8hIU9aeIfuTn8ns7GitYffRjsGv?authuser=2#scrollTo=tjDEbMizZdg_

If you decrease the size it doesn't throw this error, so it may be simply a bad error.

@mattjj

**Comment by hawkinsp** [comment] 2021-02-16 13:59
That isn't an internal error, it's a user-facing error, although perhaps it could be worded better.

Your program requires a lot of memory, in particular it would require at least 4*1024*1024*1024*1024*4 bytes = 16TiB for its output, and you most likely do not have 16TiB of GPU memory. The particular allocation quantity in the error message is probably for one of the intermediate values, which is why it is only 4TiB.

If you have suggestions on how to make the error clearer, we'd welcome them. But this is otherwise working as intended.

(I guess the part of the error about replicated computations is irrelevant to this particular error; we should probably fix that.)

**Comment by hawkinsp** [comment] 2021-02-16 19:58
I updated the error a little bit in the PR linked above. When deployed as part of a jaxlib, the error will be:
```
RuntimeError: Resource exhausted: Out of memory while trying to allocate 4398046511104 bytes.
```
which seems pretty self-explanatory to me!

Closing, but feel free to suggest further improvements.

**Comment by Chillee** [comment] 2021-02-16 22:48
Wait, sorry, I copied the wrong error.

This is the actual error I get.

```
/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py in backend_compile(backend, built_c, options)
    350   # we use a separate function call to ensure that XLA compilation appears
    351   # separately in Python profiling results
--> 352   return backend.compile(built_c, compile_options=options)
    353 
    354 def _execute_compiled_primitive(prim, compiled, result_handler, *args):

RuntimeError: Internal: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:698) !llvm::verifyModule(*llvm_module, &err_stream) Invalid LLVM IR before optimizations:
Range must not be empty!
!2 = !{i32 0, i32 0}

This probably indicates a bug in the HLO -> LLVM IR lowering. Rerun with --xla_dump_to to get the IR and looks for files with name containing: *module_0000.*
```

**Comment by hawkinsp** [comment] 2021-02-17 02:39
I agree, that's a bad error. I filed a bug with the XLA folks.

**Comment by hawkinsp** [comment] 2021-02-19 14:57
With a jaxlib built including #5787, we now get:
```
RuntimeError: Unimplemented: Kernel launch needs more blocks (4294967296) than allowed by hardware (2147483647).
```
which is a slightly better error.

**Closed** 2021-02-19 17:56 UTC
Labels: bug, xla_issue

**Comment by Chillee** [comment] 2021-02-19 17:57
Nice :)
