### ISSUE TITLE
pmap could support multiple worker

### ISSUE THREAD

**Issue by qqsun8819** [google/jax#6904] opened 2021-06-06 09:50 UTC
now for spmd, pmap can only support run parallel running in one process multi devices ,like one worker for multiple gpu/cpu devices, just like MirroredStrategy do
I know that for pmap, it'll translated into ops in hlo like kAllReduce. 
so any plan or any possibility  to support pmap in multi process and using collective ops like allreduce to parallelize  model running , like MultiWorkerMirroredStrategy distributed strategy ,using grpc or nccl for collective communication

It anyone can give me some tips, I can also implement this poc myself

**Comment by hawkinsp** [comment] 2021-06-08 17:59
We already support multiple processes on TPU. For GPU, this is a duplicate of https://github.com/google/jax/issues/1009 .

**Closed by hawkinsp** 2021-06-08 17:59 UTC
Labels: enhancement
