### ISSUE TITLE
Hi I got an error when importing jax, like the screenshots. I have installed the jax and jax.lib but I have no idea ahout where is the problem. so do you have any suggestions ? Thank you in advance 

### ISSUE THREAD

**Issue by carinawmy1** [google/jax#11438] opened 2022-07-11 07:54 UTC
Hi I got the same error when import jax, like the screenshot:
<img width="1018" alt="WechatIMG288" src="https://user-images.githubusercontent.com/109046108/178164833-412d1d12-0f53-4d9a-bc7c-8a1553287f24.png">

<img width="1049" alt="WechatIMG289" src="https://user-images.githubusercontent.com/109046108/178164835-c7a8199e-7113-4054-9234-f301492473e3.png">
<img width="534" alt="WechatIMG290" src="https://user-images.githubusercontent.com/109046108/178164842-35812dc1-7c0d-4670-8eaf-71e86eebfad7.png">
thank you very much for your advice!

_Originally posted by @carinawmy1 in https://github.com/google/jax/issues/10605#issuecomment-1179814591_

**Comment by hawkinsp** [comment] 2022-07-29 14:28
Closing because we don't have reproduction instructions. Feel free to reopen the bug with instructions on how we can reproduce it.

**Closed by hawkinsp** 2022-07-29 14:28 UTC
Labels: needs info

**Comment by sushmit86** [comment] 2022-10-23 04:27
I am having the same issue here. Can we reopen this?
