### ISSUE TITLE
copy to `dlpack` twice

### ISSUE THREAD

**Issue by yuanqing-wang** [google/jax#4636] opened 2020-10-18 17:31 UTC
Hello!

I encountered an interesting behavior of JAX when I was trying to implement a JAX backend for DGL:
https://github.com/dmlc/dgl/issues/2260

It seems that copying a Jax device array to DLPack twice is not supported:

```
import jax
from jax import numpy as jnp
from jax import dlpack
x = jnp.array([1.0, 1.0])
jax.dlpack.to_dlpack(x)
jax.dlpack.to_dlpack(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wangy1/anaconda3/envs/pinot/lib/python3.7/site-packages/jax/dlpack.py", line 34, in to_dlpack
    return xla_client._xla.buffer_to_dlpack_managed_tensor(buf)
RuntimeError: Invalid argument: Cannot convert deleted/invalid buffer to DLPack tensor.
```

This is not surprising since copying to DLPack should be a zerocopy.

But it seems that this doesn't throw error:

```
import jax
from jax import numpy as jnp
from jax import dlpack
x = jnp.ones(2)
jax.dlpack.to_dlpack(x)
jax.dlpack.to_dlpack(x)
```

I'm guessing this is because the lazy tensor is not yet being evaluated?

So for non-lazy device array, is there a way that it can be copied to `dlpack` more than once?

**Comment by hawkinsp** [comment] 2020-10-19 20:07
This is by design: because DLPack has no concept of a read-only tensor, so for safety, converting a buffer to DLPack consumes it.

We could probably add a mode where you promise faithfully that you will not touch the buffer and then exporting it to dlpack would not necessarily need to consume it.

**Comment by yuanqing-wang** [comment] 2020-10-19 21:40
Thanks for the clarification.

> We could probably add a mode where you promise faithfully that you will not touch the buffer and then exporting it to dlpack would not necessarily need to consume it.
That would be tremendously helpful! But before that, is there a work around?

**Comment by hawkinsp** [comment] 2020-10-20 18:16
The workaround until the fix is checked in and deployed is to copy the array before exporting it with dlpack. We don't have a device-side copy method (we really should) but you can fake one by computing something like `x + 0`.

**Comment by yuanqing-wang** [comment] 2020-10-20 18:34
Ah! Thanks! How can I never have thought of that!

**Comment by hawkinsp** [comment] 2020-10-20 19:50
#4659 contains the fix. However, you'll need to build jaxlib from source or wait until we make a jaxlib release.

`to_dlpack` now takes a new `take_ownership` argument, which defaults to `False`.

**Closed** 2020-10-20 20:07 UTC

**Comment by yuanqing-wang** [comment] 2020-10-20 20:41
Thanks!

**Comment by hawkinsp** [comment] 2020-11-13 02:47
This feature has been deployed in jaxlib 0.1.57. Hope that helps!
