### ISSUE TITLE
BUG: module 'jaxlib.pocketfft' has no attribute 'pocketfft'

### ISSUE THREAD

**Issue by sxiii** [google/jax#11980] opened 2022-08-18 13:08 UTC
### Description

Hi Jax developers! Tried 2 GPT-J colab playbooks, neither worked.

At some point, whatever I do, I get:
```python
AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'
```

### What jax/jaxlib version are you using?

jax==0.2.12

### Which accelerator(s) are you using?

TPU

### Additional System Info

Google Colab

**Comment by hawkinsp** [comment] 2022-08-18 13:33
What `jaxlib` version do you have installed?

(Also note `jax` 0.2.12 is quite old.)

**Comment by hawkinsp** [comment] 2022-08-18 19:36
Closing because I'm pretty confident this will not reproduce with a `jax` and `jaxlib` from head.

**Closed by hawkinsp** 2022-08-18 19:36 UTC
Labels: bug

**Comment by d-diaz** [comment] 2022-10-13 19:54
I had this error pop up with `jax` 0.2.22 (installed via pip) and `jaxlib` 0.3.15 (build cuda112py310hd0b79ce_203) installed from conda-forge.

**Comment by laddg95** [comment] 2022-10-21 12:11
jaxlib 0.3.10 , jax 0.3.23 , now I have the same issue, and I need your help,please!Thanks!

**Comment by hawkinsp** [comment] 2022-10-21 13:39
@laddg95 You are using incompatible versions of `jax` and `jaxlib`. Update your jaxlib release. In fact I'm not quite sure how you saw this error because if you try the versions you have you should get the following error when importing `jax`:

```
RuntimeError: jaxlib is version 0.3.10, but this version of jax requires version >= 0.3.15.
```

**Comment by cmosguy** [comment] 2023-02-14 21:56
@hawkinsp I am getting this error with `jaxlib` `0.4.3` and see this error:

```
ImportError: cannot import name 'pocketfft' from 'jaxlib' (./miniconda3/envs/coursera-nlp/lib/python3.9/site-packages/jaxlib/__init__.py
```
