### ISSUE TITLE
Exception has occurred: FloatingPointError invalid value (nan) encountered in jit(convert_element_type). Because jax_config.debug_nans.value and/or config.jax_debug_infs is set, the de-optimized function (i.e., the function as if the `jit` decorator were removed) was called in an attempt to get a more precise error message. However, the de-optimized function did not produce invalid values during its execution.

### ISSUE THREAD

**Issue by tobiaswuerth** [google/jax#22291] opened 2024-07-05 17:57 UTC
### Description

I noticed NANs in my values and was able to close in on the issue. I'm not sure if I'm doing something wrong or this is an issue with jax. I'm relatively new to jax and might not understand the methodology completly correctly.

Exception:
```
Exception has occurred: FloatingPointError
invalid value (nan) encountered in jit(convert_element_type). Because jax_config.debug_nans.value and/or config.jax_debug_infs is set, the de-optimized function (i.e., the function as if the `jit` decorator were removed) was called in an attempt to get a more precise error message. However, the de-optimized function did not produce invalid values during its execution. This behavior can result from `jit` optimizations causing the invalid value to be produced. It may also arise from having nan/inf constants as outputs, like `jax.jit(lambda ...: jax.numpy.nan)(...)`. 

It may be possible to avoid the invalid value by removing the `jit` decorator, at the cost of losing optimizations. 

If you see this error, consider opening a bug report at https://github.com/google/jax.
  File "/home/tobias/dev_linux/acrylic-plotter-cobiax-copy/ngu.py", line 25, in update
    b_var = jnp.var(values, axis=0)
  File "/home/tobias/dev_linux/acrylic-plotter-cobiax-copy/ngu.py", line 62, in update_step
    running_rnd.update(rnd_err)
  File "/home/tobias/dev_linux/acrylic-plotter-cobiax-copy/ngu.py", line 68, in train
    jax.lax.scan(update_step, runner_state, None, length=1000)
  File "/home/tobias/dev_linux/acrylic-plotter-cobiax-copy/ngu.py", line 84, in main
    outs = jax.block_until_ready(train_vjit(rngs))
  File "/home/tobias/dev_linux/acrylic-plotter-cobiax-copy/ngu.py", line 87, in <module>
    main()
FloatingPointError: invalid value (nan) encountered in jit(convert_element_type). Because jax_config.debug_nans.value and/or config.jax_debug_infs is set, the de-optimized function (i.e., the function as if the `jit` decorator were removed) was called in an attempt to get a more precise error message. However, the de-optimized function did not produce invalid values during its execution. This behavior can result from `jit` optimizations causing the invalid value to be produced. It may also arise from having nan/inf constants as outputs, like `jax.jit(lambda ...: jax.numpy.nan)(...)`. 

It may be possible to avoid the invalid value by removing the `jit` decorator, at the cost of losing optimizations. 

If you see this error, consider opening a bug report at https://github.com/google/jax.
```

Minimal code to reproduce:
```python
import jax
import chex
import jax.numpy as jnp
from typing import Optional

jax.config.update("jax_debug_nans", True)
jax.config.update("jax_disable_jit", True)

class RunningTracker:
    def __init__(self):
        self.r_mean: Optional[jnp.ndarray] = None
        self.r_var: Optional[jnp.ndarray] = None
        self.count: int = 0

    def update(self, values: jnp.ndarray) -> None:
        if self.r_mean is None:
            self.r_mean = jnp.zeros((1, *values.shape[1:]), dtype=jnp.float32)
            self.r_var = jnp.ones((1, *values.shape[1:]), dtype=jnp.float32)

        B = values.shape[0]
        self.count += B

        b_mean = jnp.mean(values, axis=0)
        jax.debug.print('values: {x}', x=values)
        b_var = jnp.var(values, axis=0)
        
        delta = b_mean - self.r_mean
        self.r_mean += delta * B / self.count

        m_a = self.r_var * (self.count - B)
        m_b = b_var * B
        M2 = m_a + m_b + (delta**2) * self.count * B / self.count
        self.r_var = M2 / self.count

    def get_running_mean(self) -> jnp.ndarray:
        return self.r_mean.copy()
    
    def get_running_std_dev(self) -> jnp.ndarray:
        return jnp.sqrt(self.r_var).copy()
    
    def reset(self) -> None:
        self.r_mean = None
        self.r_var = None
        self.count = 0

@chex.dataclass
class RunnerState:
    rng: chex.PRNGKey

def make_train(config):
    N = config["NUM_POLICIES"]

    def train(rng):
        running_rnd = RunningTracker()
        rng, _rng = jax.random.split(rng)

        def update_step(runner_state:RunnerState, unused):
            rng1, rng2 = jax.random.split(runner_state.rng)
            rnd = jax.random.uniform(rng1, (N, 128))
            rndT = jax.random.uniform(rng2, (N, 128))
            rnd_err = ((rnd - rndT) ** 2).mean(axis=-1)
            running_rnd.update(rnd_err)

        rng, _rng = jax.random.split(rng)
        runner_state = RunnerState(
            rng=_rng,
        )
        jax.lax.scan(update_step, runner_state, None, length=1000)

    return train


def main():

    config = {
        "SEED": 0,
        "NUM_POLICIES": 16,
    }

    rng = jax.random.PRNGKey(config["SEED"])
    rngs = jax.random.split(rng, 1)
    # train_vjit = jax.jit(jax.vmap(make_train(config)))
    train_vjit = jax.vmap(make_train(config))
    outs = jax.block_until_ready(train_vjit(rngs))

if __name__ == "__main__":
    main()
```

The line on which the exception is triggered is:
```
b_var = jnp.var(values, axis=0)
```

The logged values are:
```
values: [0.147233   0.16015422 0.15756994 0.15886027 0.17155224 0.14763154
 0.15769038 0.15949456 0.18642683 0.15243328 0.15063865 0.17908339
 0.15743712 0.16170152 0.1348365  0.16695803]
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.30
jaxlib: 0.4.30
numpy:  2.0.0
python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
jax.devices (1 total, 1 local): [cuda(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='WS-Z790Nova', release='5.15.153.1-microsoft-standard-WSL2', version='#1 SMP Fri Mar 29 23:14:13 UTC 2024', machine='x86_64')


$ nvidia-smi
Fri Jul  5 19:55:09 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.52.01              Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        On  |   00000000:01:00.0 Off |                  Off |
|  0%   44C    P2              9W /  450W |     382MiB /  24564MiB |     11%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     38934      C   /python3.10                                 N/A      |
+-----------------------------------------------------------------------------------------+
```

If this is an actual issue, is there a temporary fix I can use?

Thanks for looking into it!

**Comment by superbobry** [comment] 2024-07-08 11:14
This looks like a duplicate of #22291, which has a smaller reproducer.

**Closed** 2024-07-08 12:23 UTC
Labels: bug
