### ISSUE TITLE
No GPU/TPU found

### ISSUE THREAD

**Issue by nestordemeure** [google/jax#7867] opened 2021-09-09 21:26 UTC
I am using Jax (`jaxlib==0.1.70+cuda101`) on an `Ubuntu 18.04.5` with `Cuda 10.1` installed. Things were working fine until about a week ago when it stopped detecting the GPU and displayed the following error message:

```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```

I don't know what caused it to stop working as I did not touch my Python / nvidia / cuda / cudnn instalation between the time it worked and the time it failed to detect the GPU (the only thing that happened is an Ubuntu update which might have impacted the Cuda or cudnn instalation behind the scene).

I have tried fully reinstalling cuda, cudnn, jax and jaxlib (following the instructions in the readme) but without any impact on the problem.

Cuda is installed in the `/usr/local/cuda-10.1` folder, there is a `/usr/local/cuda` folder pointing to the previous one and cublas appears to be (alone) in a `/usr/local/cuda-10.2` folder.  I found cudnn (`v8.0.5 for CUDA 10.1`) installed in the `/usr/lib/x86_64-linux-gnu` folder. My nvcc version is:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

`nvidia-smi` works fine and give me the following information:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P3    N/A /  N/A |    557MiB /  4040MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by zhangqiaorjc** [comment] 2021-09-14 17:18
@yashk2810 could this be related to some cuda build changes we have recently?

**Comment by yashk2810** [comment] 2021-09-14 17:28
I don't think so. This is with jaxlib 0.1.70 with Cuda 10.1 (we don't support that anymore).

Plus there were no breaking build changes.

**Comment by hawkinsp** [comment] 2021-12-02 13:35
I don't think we have enough information to make progress on this bug, but my guess is "you have the non-GPU jaxlib wheel installed".

For us to be able to debug this, we'd need to be able to reproduce it. Perhaps you can reproduce it in a VM or in a docker image or something like that?

Closing because I don't think there's any action we can take without more information, but please feel free to reopen with more details!

**Closed by hawkinsp** 2021-12-02 13:35 UTC
Labels: bug

**Comment by nestordemeure** [comment] 2021-12-02 16:17
Thank you, I will reopen if I find a way to make it reproduceable.
