### ISSUE TITLE
Building from source failed test

### ISSUE THREAD

**Issue by ysagon** [google/jax#8590] opened 2021-11-18 11:16 UTC
Hi,

I'm trying to build jax 0.2.19 using EasyBuild. During the test phase, I have two failed tests:

```
jax/test_util.py:146: AssertionError
========================================================================================================== short test summary info ==========================================================================================================
FAILED tests/lax_numpy_einsum_test.py::EinsumTest::test_einsum_kpmurphy_example - AssertionError:
FAILED tests/lax_test.py::LaxTest::testOpAgainstNumpyDigamma_float32[2,3,4] - AssertionError:
========================================================================================= 2 failed, 13216 passed, 684 skipped in 3672.05s (1:01:12) =========================================================================================
```

https://gist.github.com/ysagon/afc9ce91060c8fd1872452e86d74a0a0
https://gist.github.com/ysagon/3b2d3d445d74b6a04aa8b0654e22e435

Any clue?

**Comment by hawkinsp** [comment] 2021-11-18 14:50
I think both of these indicate that the test tolerances are a bit too tight and changes in vectorization, etc. might be perturbing the output. Do you want to send a PR relaxing the test tolerances for those two tests?

**Comment by hawkinsp** [comment] 2021-11-18 14:51
Although I note that v0.2.19 is old: v0.2.25 is current for `jax`.

**Comment by ysagon** [comment] 2022-04-08 06:30
Hi, sorry for not following. In fact, I'm trying to build AlphaFold and this version of Jax is a dependency. I don't know if I can upgrade it. I may give a try.

About increasing the tolerance: can you please let me know which file should I modify? I must admit I have no clue at all how jax is working.

**Comment by apaszke** [comment] 2022-04-08 14:23
You could try bumping up the `atol` and `rtol` arguments [here](https://github.com/google/jax/blob/main/tests/lax_numpy_einsum_test.py#L314) and adding e.g. `float32: 1e-3` [here](https://github.com/google/jax/blob/main/tests/lax_test.py#L133-L134).

**Comment by hawkinsp** [comment] 2022-08-13 16:21
Closing because we can't reproduce. If you can, please send a PR increasing the tolerances!

**Closed by hawkinsp** 2022-08-13 16:21 UTC
Labels: bug, needs info
