### ISSUE TITLE
BUG: Issue detecting platform as cuda or Rocm

### ISSUE THREAD

**Issue by w1redch4d** [google/jax#11901] opened 2022-08-13 03:02 UTC
### Description

Found another issue
```py
>>from jax import random
>>random.split(random.PRNGKey(2**32-1))
```
returns
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/random.py", line 193, in split
    key, wrapped = _check_prng_key(key)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/random.py", line 180, in _split
    return key._split(num)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 200, in _split
    return PRNGKeyArray(self.impl, self.impl.split(self._keys, num))
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 462, in threefry_split
    return _threefry_split(key, int(num))  # type: ignore
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 466, in _threefry_split
    counts = lax.iota(np.uint32, num * 2)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 445, in threefry_2x32
    except core.InconclusiveDimensionOperation as e:
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AttributeError: 'NoneType' object has no attribute 'threefry2x32_descriptor'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/random.py", line 194, in split
    return _return_prng_keys(wrapped, _split(key, num))
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/random.py", line 180, in _split
    return key._split(num)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 200, in _split
    return PRNGKeyArray(self.impl, self.impl.split(self._keys, num))
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 462, in threefry_split
    return _threefry_split(key, int(num))  # type: ignore
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/api.py", line 527, in cache_miss
    out_flat = xla.xla_call(
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/core.py", line 1937, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/core.py", line 1953, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/core.py", line 687, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/dispatch.py", line 208, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/dispatch.py", line 257, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/profiler.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/dispatch.py", line 385, in lower_xla_callable
    lowering_result = mlir.lower_jaxpr_to_module(
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 618, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 881, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/interpreters/mlir.py", line 1008, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 401, in _threefry2x32_gpu_lowering
    return threefry2x32_lowering(
  File "/home/doomer/.local/lib/python3.10/site-packages/jaxlib/gpu_prng.py", line 57, in _threefry2x32_lowering
    opaque = prng.threefry2x32_descriptor(_prod(dims))
jax._src.traceback_util.UnfilteredStackTrace: AttributeError: 'NoneType' object has no attribute 'threefry2x32_descriptor'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/random.py", line 194, in split
    return _return_prng_keys(wrapped, _split(key, num))
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/random.py", line 180, in _split
    return key._split(num)
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 200, in _split
    return PRNGKeyArray(self.impl, self.impl.split(self._keys, num))
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 462, in threefry_split
    return _threefry_split(key, int(num))  # type: ignore
  File "/home/doomer/.local/lib/python3.10/site-packages/jax/_src/prng.py", line 401, in _threefry2x32_gpu_lowering
    return threefry2x32_lowering(
  File "/home/doomer/.local/lib/python3.10/site-packages/jaxlib/gpu_prng.py", line 57, in _threefry2x32_lowering
    opaque = prng.threefry2x32_descriptor(_prod(dims))
AttributeError: 'NoneType' object has no attribute 'threefry2x32_descriptor'
```
by which i thought i would see if its getting the same error while i try to manually follow the function calls stack as in:
```py
>>from jaxlib import gpu_prng
>>print(gpu_prng._hip_prng.threefry2x32_descriptor(2**32-1))
b'\xff\xff\xff\xff\x00\x00\x00\x00'
```
but while i try to do the same thing with _cuda_prng it returns None, seems like an issue on detecting if the platform is cuda or ROCM

### What jax/jaxlib version are you using?

jaxlib 0.3.16 (source compiled for rocm)

### Which accelerator(s) are you using?

RX580

### Additional System Info

Linux (5.19.0-arch1-1)

**Comment by brettkoonce** [comment] 2022-08-19 15:29
I was seeing this error as well, using 0abbdd064846817e97ca751d1c7ee5f4a933789c (see https://github.com/google/jax/issues/11972) made the problem go away!

**Comment by mattjj** [comment] 2022-08-22 20:45
Closing this because I _think_ it's effectively a duplicate of #11972. Please reopen/complain if I am wrong!

**Comment by mattjj** [comment] 2022-08-22 20:47
Actually I think I misunderstood.

**Comment by mattjj** [comment] 2022-08-22 20:52
@UwUeeb I wasn't able to repro this on a CUDA cloud machine. Is this a rocm-specific issue? Do you think #11972 is related?

**Comment by mattjj** [comment] 2022-08-22 20:53
Assigning to @UwUeeb to follow up with more info.

**Comment by UwUeeb** [comment] 2022-08-27 15:14
Hi sorry i have changed my workstation along with that i have shiftd from ROCM to CUDA so cant get more info about this issue , sorry for that

**Comment by w1redch4d** [comment] 2023-02-13 07:28
@mattjj hi im back on a rocm platform, and i guess i have the patch for the issue, if this is still a problem i can create a PR

**Comment by hawkinsp** [comment] 2023-10-04 01:55
I'm guessing this issue is stale. Please let us know if I'm wrong and there's still something for us to do here.

**Closed by hawkinsp** 2023-10-04 01:55 UTC
Labels: bug, duplicate, needs info
