### ISSUE TITLE
"Unexpectedly high number of iterations in HLO passes, exiting fixed point loop." in odeint

### ISSUE THREAD

**Issue by jacobjinkelly** [google/jax#2691] opened 2020-04-12 19:31 UTC
I get the warning message 
`W external/org_tensorflow/tensorflow/compiler/xla/service/hlo_pass_fix.h:49] Unexpectedly high number of iterations in HLO passes, exiting fixed point loop.` 
each time I evaluate `grad(odeint)` in the following [code](https://github.com/jessebett/jax/blob/hk-nodes/examples/nodes_cifar_hk.py). The forward system has `4 * 4 * 64 = 1024` dimensions, and the dynamics function has `1 * 1 * 64 * 64 = 4096` parameters (so the adjoint system would have about `5121` dimensions). I also [modified](https://github.com/jessebett/jax/blob/hk-nodes/jax/experimental/ode.py) `odeint` to count NFE on the forward pass (which in this case is only `7`). 

Not really sure what this warning message means, but I suspect it might be affecting the performance of my code. Any insights into this would be greatly appreciate, and I'm happy to create a more stripped down example (e.g. without the haiku dependency) if needed.

[XLA dump](https://drive.google.com/open?id=13Zck0wpfd57ZtoaKfpLfZIMw5UITsIH4)

**Comment by mattjj** [comment] 2020-04-13 02:18
This might be a duplicate of #2639. We think it's harmless (and will disappear when we update XLA by releasing a new jaxlib wheel) unless you've noticed any separate performance changes.

I think I'm going to close in favor of consolidating the discussion at #2639, but let's follow up there as needed!

**Closed by mattjj** 2020-04-13 02:18 UTC
