### ISSUE TITLE
Gradient(s) and Hessian(s) of functions with higher order tensors as input

### ISSUE THREAD

**Issue by bhaveshshrimali** [google/jax#3880] opened 2020-07-28 06:59 UTC
Hi Jax community, 

I recently came across `jax` and wanted to explore AD of functions that take as input higher order (>1) tensors. Note that I refer to a vector as an order-1 tensor.  Let's start with a scalar function

```python3

from jax import jit, grad
from jax.numpy import vectorize, sqrt, zeros

# function to minimize
def psi(gw0, gw1, gw2):
    return sqrt(1 + gw0** 2 + gw1** 2 + gw2**2)

# gradient
def dpsi(gw0, gw1, gw2):
    out = zeros((3,) + gw0.shape)
    for i in range(3):
        out[i] = vectorize(grad(psi, i))(gw0, gw1, gw2)
    return out

# hessian
def ddpsi(gw0, gw1, gw2):
    out = np.zeros((3, 3) + gw0.shape)
    for i in range(3):
        for j in range(3):
            out[i, j] = vectorize(grad(grad(psi, i), j))(gw0, gw1, gw2)
    return out

```

I can now very well pass a vector as input to `dpsi` and `ddpsi` and get the gradient and hessian as output. 

Now, what if instead my function `psi` took as input not a vector but a second order tensor. How would I go about calculating `dpsi` and `ddpsi` which in that case would be (`3,3`) and (`3,3,3,3`) tensors.  

The below snippet is an idealisation of what I want to achieve. 

```python3

from jax.numpy import zeros_like, einsum

# gradU is a (3,3,...) tensor : 
def psi(gradU):
    F = zeros_like(gradU)
    F[0,0] += 1.
    F[1,1] += 1.
    F[2,2] += 1.
    
    F += gradU
    I1 = einsum("ij...,ij...", F, F)
    return I1

# gradient 
def dpsi(gradU):
    out = zeros_like(gradU.shape)
    ...

# hessian
def ddpsi(gradU):
    out = zeros_like((3,3,3,3) + gradU.shape[2:])
    ...
```

I know this may be a naive question, but any pointers would be helpful. Also if this is already discussed somewhere, feel free to redirect (I'd be happy to learn :) )

**Comment by shoyer** [comment] 2020-07-29 18:25
Gradients and Hessians of functions with higher order tensors (or even nested lists/tuples/dicts of tensors) as input should just work out of the box with `grad`. Have you encountered any specific errors or unexpected behavior when you try this?

Note that inplace assignment to variables doesn't work in JAX -- you have to write something like `F = F.at[0,0].add(1.)` instead of `F[0,0] += 1.`, which should result in an error. So I'm guessing you may not have actually run this code with JAX yet? :)

**Comment by bhaveshshrimali** [comment] 2020-07-30 01:07
Hi @shoyer ,

Thanks a lot for your reply!

> `F = F.at[0,0].add(1.)` instead of `F[0,0] += 1.`, which should result in an error. So I'm guessing you may not have actually run this code with JAX yet? :)

Yes. Indeed, I hadn't run the code with `jax` as I wasn't sure how to pass the arguments to the functions, so that grad understands how to take derivatives properly. Now after experimenting a bit with Jax, I could come up with a MWE to illustrate my problem. Consider the following snippets

### Runs fine 

```python3
def F(du0, du1):
    return jnp.sqrt(1 + du0 ** 2 + du1 ** 2)

def jac_eval(du0, du1):
    out = np.zeros((2,) + du0.shape)
    for i in range(2):
        out[i] = vectorize(grad(F, i))(du0, du1)
    return out

def hess_eval(du0, du1):
    out = np.zeros((2, 2) + du0.shape)
    for i in range(2):
        for j in range(2):
            out[i, j] = vectorize(grad(grad(F, i), j))(du0, du1)
    return out

trialu = np.sin(np.random.random((2,250,4)))

print(jac_eval(*trialu))

``` 



### Fails
```python3
from jax import grad
from jax.numpy import vectorize, einsum
import numpy as np

def psi(gradU):
    F = np.zeros_like(gradU)
    F[0, 0] += 1.
    F[1, 1] += 1.
    F[2, 2] += 1.
    
    F += gradU

    I1 = einsum("ij...,ij...", F, F)
    return I1

def dpsi(gradU):
    out = np.zeros_like(gradU.shape)
    for i in range(gradU.shape[0]):
        for j in range(gradU.shape[1]):
            out[i, j] = vectorize(grad(grad(psi, i), j))(gradU)
    return out

def ddpsi(gradU):
    out = np.zeros_like((3,3) + gradU.shape)
    for i in range(out.shape[0]):
        for j in range(out.shape[1]):
            for k in range(out.shape[2]):
                for l in range(out.shape[3]):
                    out[i, j, k, l] = vectorize(grad(grad(grad(grad(psi, i), j), k), l))(gradU)
    return out

trialgrad = np.sin(np.random.random((3,3,250,4)))
dpsi(trialgrad)
```

raises (not posting the entire traceback)

```
This error can occur when a JAX Tracer object is passed to a raw numpy function, or a method on a numpy.ndarray object. 
You might want to check that you are using `jnp` together with `import jax.numpy as jnp` rather than using `np` via `import numpy as np`. 
If this error arises on a line that involves array indexing, 
like `x[idx]`, it may be that the array being indexed `x` is a raw numpy.ndarray while
the indices `idx` are a JAX Tracer instance; in that case, you can instead write `jax.device_put(x)[idx]`.
```

Following this, I also tried

```python3
device_put(out)[i,j] = vectorize(grad(grad(psi, i), j))(gradU)
```

But it still raises the same error. 


Thanks in advance. I know the error might just be due to my incomplete understanding of how `grad` works but I appreciate if you could provide any pointers.

**Comment by shoyer** [comment] 2020-07-30 01:15
JAX's transformations like `grad` don't work on functions that use NumPy, like your `psi()` and `dpsi()` functions (this is exactly what the error message says). You will need to need to rewrite them entirely in terms of `jax.numpy` operations before you can expect `grad` to work.

**Comment by bhaveshshrimali** [comment] 2020-07-30 04:42
> JAX's transformations like `grad` don't work on functions that use NumPy, like your `psi()` and `dpsi()` functions (this is exactly what the error message says)

Agreed, but then

```python3

from jax import grad, device_put, jacrev, jacfwd
from jax.numpy import vectorize, einsum, zeros_like, sin, zeros, array
import numpy as np

def psi(gradU):
    I1 = einsum("ij...,ij...", gradU, gradU)
    return I1

def dpsi(gradU):
    out = zeros(gradU.shape)
    for i in range(gradU.shape[0]):
        for j in range(gradU.shape[1]):
            # device_put(out)[i,j] = vectorize(grad(grad(psi, i), j))(gradU)
            out.at[i, j].add(vectorize(grad(grad(psi, i), j))(gradU))
    return out

trialgrad = sin(np.random.random((3,3,250,4)))
print(psi(trialgrad))
dpsi(trialgrad) # fails

```

fails too with

```python3
ValueError: Einstein sum subscript 'ij' does not contain the correct number of indices for operand 0.
```

I guess I failed to mention the first time around, what I want to compute the derivative of `psi` wrt `gradU`. Since `psi` is a scalar, so the derivative should be of shape `gradU.shape`. `psi` evaluates perfectly when supplied with `trialgrad` with the output shaped `(250,4)`

**Comment by shoyer** [comment] 2020-07-30 07:52
".at" needs to be used like "out = out.at[i, j].add(...)". It doesn't
modify values inplace.

**Comment by bhaveshshrimali** [comment] 2020-07-30 14:58
> ".at" needs to be used like "out = out.at[i, j].add(...)". It doesn't modify values inplace.

Ah thanks. Should have read your previous comment more carefully!

It still doesn't change anything though. I will keep looking.

**Comment by shoyer** [comment] 2020-08-05 05:37
I'm going to close this issue since we've drifted pretty far from the original topic.

Feel free to open new issues with specific questions. Please test the code first and provide a _minimal_ example of what doesn't work as expected, including the full stack trace if there is an error.

**Closed by shoyer** 2020-08-05 05:37 UTC

**Comment by bhaveshshrimali** [comment] 2020-08-05 06:53
> Feel free to open new issues with specific questions.

Sure, will do. I thought the last snippet I posted above illustrated my problem well enough and yet minimal to the point where (perhaps) it's just a question of syntax. Anyway, I understand it doesn't contribute to the general community to simply debug issues.  Will try to post something more concrete in the future!

**Comment by shoyer** [comment] 2020-08-05 07:15
There is a lot going on in your example, it would be helpful to simplify

I notice now that you write `grad(grad(psi, i), j)`, but that actually isn't valid in JAX since `grad` is only for functions with a single scalar output.

See the autodiff cookbook for more details on how to calculate Hessians: https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html

**Comment by bhaveshshrimali** [comment] 2020-08-05 07:30
> I notice now that you write `grad(grad(psi, i), j)`, but that actually isn't valid in JAX since `grad` is only for functions with a single scalar output.

Thanks! I will check out any relevant examples in autodiff cookbook. 

> There is a lot going on in your example, it would be helpful to simplify
> 
> I notice now that you write `grad(grad(psi, i), j)`, but that actually isn't valid in JAX since `grad` is only for functions with a single scalar output.

Agreed. Will try to come up with something simpler. I had read the documentation for `grad` and managed to implement it [as described above](https://github.com/google/jax/issues/3880#issuecomment-666014512) for functions that take as input vectors, using `vectorize`.  

I think I should be able to take it from here. Probably thinking a bit more clearly on how to feed things to `vectorize` for this case
