### ISSUE TITLE
Trying to import jax raises ImportError

### ISSUE THREAD

**Issue by raghuramshankar** [google/jax#7796] opened 2021-09-03 09:28 UTC
Trying to import `Jax` raises `ImportError`:

```
import jax
```

This gives me the error:

```
File "/home/user/.local/lib/python3.9/site-packages/jax/_src/api.py", line 52, in <module>
    from ..tree_util import (tree_map, tree_flatten, tree_unflatten, tree_structure,
ImportError: cannot import name 'Partial' from 'jax.tree_util' (/home/user/.local/lib/python3.9/site-packages/jax/tree_util.py)
```

Python and jax version:
```
python --version
Python 3.9.6

pip show jax 
Name: jax
Version: 0.2.19
```

My system info:
Linux Manjaro (Arch Linux) with the latest kernel.
```
uname -r
5.13.12-1-MANJARO
```
Adding `Partial` to the list in `/home/user/.local/lib/python3.9/site-packages/jax/tree_util.py` line 40 solved the issue for me and I am able to successfully `import jax`. 
I also noticed that `partial` is available in the list but replacing `partial` with `Partial` seems to raise more errors for me.

**Comment by jakevdp** [comment] 2021-09-03 13:03
Hi - thanks for the report!

I'm a bit confused about what's going on, because you mention that you're using JAX 0.2.19, and you mention adding `Partial` at line 40 of `jax/tree_util.py`, but if I look at that line within the 0.2.19 source tree `Partial` is already there: https://github.com/google/jax/blob/jax-v0.2.19/jax/tree_util.py#L40

I would do two things: first, check the output of this:
```
$ python -m pip show jax
```
calling `pip` this way assures you're using the `pip` associated with your `python` executable, which is not guaranteed if you just call `pip` alone.

If everything looks good there, then I assume your installation has been corrupted somehow. I'd then run
```
$ python -m pip uninstall jax jaxlib
$ python -m pip install jax[cpu]
```

**Comment by ioannis12** [comment] 2021-09-03 21:30
hello, 
I think I have the same problem, when I try to import jax I get an error message "kernel died, restarting kernel". 
I use spyder 4.1.0.

**Comment by raghuramshankar** [comment] 2021-09-06 04:01
Hi,

Thank you for your reply.
I am using Jax as a solver for [Pybamm](https://github.com/pybamm-team/PyBaMM) simulations. I just found that the issue was with the installation of the Pybamm library, and not with the Jax library. [Here](https://github.com/pybamm-team/PyBaMM/issues/1470) is the issue that was raised over there regarding the same.
Sorry for not catching this earlier, I did not expect it to be this way. 
Thanks!

Regards
Raghuram

**Comment by jakevdp** [comment] 2021-09-13 18:07
Thanks! I'll close the issue then. Feel free to open another if you run into any other problems!

**Closed by jakevdp** 2021-09-13 18:07 UTC
Labels: bug

**Comment by RylanSchaeffer** [comment] 2021-10-07 04:10
I think the problem is with `numpyro` (https://github.com/pyro-ppl/numpyro/issues/1165)

**Comment by yukiweng62** [comment] 2023-09-20 02:32
I received a similar error from jax 0.4.11, could u help me:

  File C:\ProgramData\anaconda3\Lib\site-packages\flax\linen\linear.py:30
    from jax import ShapedArray

ImportError: cannot import name 'ShapedArray' from 'jax' (C:\ProgramData\anaconda3\Lib\site-packages\jax\__init__.py)

**Comment by jakevdp** [comment] 2023-09-20 03:10
`jax.ShapedArray was removed in JAX v0.4.14 after being deprecated for several releases (see the [JAX v0.4.14 changelog](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-14-july-27-2023)).

I would suggest updating flax to a more recent version that is compatible with recent JAX versions.

**Comment by yukiweng62** [comment] 2023-09-20 10:47
Thanks a lot!!!

**Comment by aiyb1314** [comment] 2023-12-18 02:10
ImportError: cannot import name 'abstract_arrays' from 'jax' (/home/xuj/anaconda3/envs/removal/lib/python3.10/site-packages/jax/__init__.py) 
How to solve??

**Comment by jakevdp** [comment] 2023-12-18 02:19
`jax.abstract_arrays` was [deprecated](https://github.com/google/jax/blob/main/CHANGELOG.md#jax-0412-june-8-2023) in jax v0.4.12 and [removed](https://github.com/google/jax/blob/main/CHANGELOG.md#jax-0417-oct-3-2023) in JAX v 0.4.17.

To fis the error you're seeing, you can avoid attempting to import `jax.abstract_arrays`. If you're using another package that imports this deprecated module, you could try updating that other package, or if that's not possible, install JAX v0.4.16 or older.
