### ISSUE TITLE
Build dependency on TensorFlow

### ISSUE THREAD

**Issue by CharlesJQuarra** [google/jax#1804] opened 2019-12-03 14:24 UTC
I tried to build on Mac OS X, but I get this error when running `python3 setup.py`:

```
ERROR: /private/var/tmp/_bazel_cj/de96de179f580494f32631716f8b8a5c/external/org_tensorflow/tensorflow/core/BUILD:2513:1: @org_tensorflow//tensorflow/core:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_cj/de96de179f580494f32631716f8b8a5c/external/org_tensorflow/third_party/git/git_configure.bzl", line 64
		_fail(result.stderr)
	File "/private/var/tmp/_bazel_cj/de96de179f580494f32631716f8b8a5c/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_cj/de96de179f580494f32631716f8b8a5c/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins
```

And the question is: Do I really need to install TensorFlow in order to build Jax?

**Comment by hawkinsp** [comment] 2019-12-03 14:27
You should try the prebuilt Jaxlib packages (from `pip`) first; they are much easier to install. If they don't work for you we should look into that.

JAX uses XLA as its JIT compiler, which is distributed as part of the TensorFlow tree. Hence `jaxlib` builds that part of the TensorFlow tree as a submodule. It does not use most of TensorFlow (e.g., the TF kernels, graph logic, or any of the Python code).

What version of Python do you have and how did you install it?

**Comment by hawkinsp** [comment] 2019-12-03 14:31
Also to be completely clear: you should not have to install TensorFlow yourself. JAX downloads and builds the necessary part as part of its build process.

**Comment by lauradriscoll** [comment] 2019-12-21 01:04
@hawkinsp We're having the same issue. Can't use pip install because we're using the stanford cluster which runs centos 7 (GLIBC issue #854). We specified cuda path and cudnn path with this command:

$CUDA_PATH=/share/software/user/open/cuda/10.0.130/
$CUDNN_PATH=/share/software/user/open/cudnn/7.6.4
$python build/build.py --cuda_path $CUDA_PATH --cudnn_path $CUDNN_PATH --enable_cuda

```python
     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


WARNING: Output base '/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0' is on NFS. This may lead to surprising failures and undetermined behavior.
Starting local Bazel server and connecting to it...
Bazel binary path: ./bazel-0.29.1-linux-x86_64
Python binary path: /share/software/user/open/python/2.7.13/bin/python
MKL-DNN enabled: yes
-march=native: no
CUDA enabled: yes
CUDA toolkit path: /share/software/user/open/cuda/10.0.130/
CUDNN library path: /share/software/user/open/cudnn/7.4.1.5

Building XLA and installing it in the jaxlib source tree...
./bazel-0.29.1-linux-x86_64 run --verbose_failures=true --config=mkl_open_source_only --config=cuda --define=xla_python_enable_gpu=true :install_xla_in_source_tree /home/users/lndrisco/code/jax/build
WARNING: Output base '/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/users/lndrisco/code/jax/.bazelrc:
  Inherited 'build' options: --repo_env PYTHON_BIN_PATH=/share/software/user/open/python/2.7.13/bin/python --python_path=/share/software/user/open/python/2.7.13/bin/python --repo_env TF_NEED_CUDA=1 --distinct_host_configuration=false --copt=-Wno-sign-compare -c opt --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --spawn_strategy=standalone --strategy=Genrule=standalone --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --action_env CUDA_TOOLKIT_PATH=/share/software/user/open/cuda/10.0.130/ --action_env CUDNN_INSTALL_PATH=/share/software/user/open/cudnn/7.4.1.5
INFO: Found applicable config definition build:mkl_open_source_only in file /home/users/lndrisco/code/jax/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/users/lndrisco/code/jax/.bazelrc: --crosstool_top=@local_config_cuda//crosstool:toolchain --define=using_cuda=true --define=using_cuda_nvcc=true
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:5:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Analyzing: target //build:install_xla_in_source_tree (1 packages loaded, 0 targets configured)
Analyzing: target //build:install_xla_in_source_tree (36 packages loaded, 130 targets configured)
WARNING: /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/core/platform/BUILD:52:1: in srcs attribute of cc_library rule @org_tensorflow//tensorflow/core/platform:env_time_impl: please do not import '@org_tensorflow//tensorflow/core/platform/default:env_time.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_instantiate_platform_libraries', the error might have been caused by the macro implementation in /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/core/platform/BUILD:52:1
WARNING: /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/core/platform/BUILD:52:1: in srcs attribute of cc_library rule @org_tensorflow//tensorflow/core/platform:logging_impl: please do not import '@org_tensorflow//tensorflow/core/platform/default:logging.cc' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'tf_instantiate_platform_libraries', the error might have been caused by the macro implementation in /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/core/platform/BUILD:52:1
Traceback (most recent call last):
  File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins
INFO: Call stack for the definition of repository 'local_config_git' which is a git_configure (rule definition at /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl:66:17):
 - /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/workspace.bzl:74:5
 - /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/workspace.bzl:61:5
 - /home/users/lndrisco/code/jax/WORKSPACE:41:1
ERROR: An error occurred during the fetch of repository 'local_config_git':
   Traceback (most recent call last):
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 64
		_fail(result.stderr)
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

INFO: Call stack for the definition of repository 'llvm' which is a tf_http_archive (rule definition at /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/repo.bzl:121:19):
 - /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/workspace.bzl:549:5
 - /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/workspace.bzl:61:5
 - /home/users/lndrisco/code/jax/WORKSPACE:41:1
ERROR: /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/core/util/BUILD:265:1: @org_tensorflow//tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 64
		_fail(result.stderr)
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/core/util/BUILD:265:1: @org_tensorflow//tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/head in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 64
		_fail(result.stderr)
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/core/util/BUILD:265:1: @org_tensorflow//tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/branch_ref in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 64
		_fail(result.stderr)
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: Analysis of target '//build:install_xla_in_source_tree' failed; build aborted: no such package '@local_config_git//': Traceback (most recent call last):
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 64
		_fail(result.stderr)
	File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, in _fail
		fail(("%sGit Configuration Error:%s %...)))
Git Configuration Error: Traceback (most recent call last):
  File "/home/users/lndrisco/.cache/bazel/_bazel_lndrisco/211ff64f4219b1450e0e3c09844491f0/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

INFO: Elapsed time: 271.579s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (95 packages loaded, 1974 targets configured)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (95 packages loaded, 1974 targets configured)
Traceback (most recent call last):
  File "build/build.py", line 351, in <module>
    main()
  File "build/build.py", line 346, in main
    shell(command)
  File "build/build.py", line 50, in shell
    output = subprocess.check_output(cmd)
  File "/share/software/user/open/python/2.7.13/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['./bazel-0.29.1-linux-x86_64', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', '--config=cuda', '--define=xla_python_enable_gpu=true', ':install_xla_in_source_tree', '/home/users/lndrisco/code/jax/build']' returned non-zero exit status 1
```

**Comment by skye** [comment] 2019-12-21 02:22
Can you try `pip install future`? That should include the builtins module.

**Comment by hawkinsp** [comment] 2020-03-09 19:58
This build error pertained to Python 2; we don't support Python 2 any more so it's likely the issue is moot. Closing.

**Closed by hawkinsp** 2020-03-09 19:58 UTC
Labels: build, question
