### ISSUE TITLE
jax2tf polymorphic_shapes with structured input

### ISSUE THREAD

**Issue by sygi** [google/jax#7344] opened 2021-07-21 13:15 UTC
I'm trying to use polymorphic shapes in jax2tf. From the docs it seems that structured inputs are supported:

`It should be a Python object with the same pytree structure as, or a prefix of, the tuple of arguments to the function, but with a shape specification corresponding to each argument.`

yet when I was trying to use it with a NamedTuple I got the error:
`InconclusiveDimensionOperation: Dimension polynomial 'b' is not constant`

Did I do something wrong? Is this supported?

```python
from jax.experimental import jax2tf
import tensorflow.compat.v1 as tf
from typing import Tuple, NamedTuple

class G(NamedTuple):
  a: Tuple[int]
  b: Tuple[int]

def fn(a):
  return a.a[0] + a.b[0]

g = jax2tf.convert(fn, polymorphic_shapes=["(b, ...)"])
h = jax2tf.convert(fn, polymorphic_shapes=[G(a="(b, ...)", b="(b, ...)")])
l = jax2tf.convert(fn, polymorphic_shapes=[G(a="(b, _)", b="(b, _)")])
m = jax2tf.convert(fn, polymorphic_shapes=["(b, _)"])
place = G(a=tf.placeholder(tf.int32, shape=(10, 5)), b=tf.placeholder(tf.int32, shape=(10, 5)))

g(place), h(place), ...
```

**Comment by sygi** [comment] 2021-07-22 07:57
After playing with this example a bit I realised that the problem wasn't with the structured input, as I assumed, but with indexing the polymorphic shape. I don't care about this; the example above was an unfortunate attempt at extracting the problem that I have into a small example. Let me give more context and rephrase my question:

I have some complex jax function `arbitrary_fn`. I would like to expand it by a polimorphic-shape batch with a vmap and then convert to TF. Eg. I would like:

```
def arbitrary_fn(x): pass
arbitrary_fn(regular_arg)  # runs fine
tf_fn = jax2tf.convert(jax.vmap(arbirary_fn), polymorphic_shapes=tree.map_structure("(b, ...)", regular_arg))
place = tree.map_structure(lambda x: tf.placeholder(x.dtype, (1,) + x.shape), regular_arg)
tf_fn(place)  # gives the InconclusiveDimensionOperation error (runs fine if polymorphic shapes are dropped)
```

I tried some small examples with vmap, but they work just fine. Should I expect this kind of application to work on arbitrary jax functions (and I should look for a bug in my code) or rather, depending on a function they may or may not work? I can give more details about the function internally.

Thank you!

**Comment by gnecula** [comment] 2021-07-22 12:26
The first bug you encountered was because the current version of jax2tf does not support indexing a polymorphic dimension. This ought to be fixed in the upcoming PR #7317.

In general, you cannot expect an arbitrary JAX program to be shape polymorphic, e.g., if it does a conditional on the value of the unknown dimension. The [documentation](https://github.com/google/jax/tree/9f8fb243f9d709d9351e12c46b21c5c531abbc15/jax/experimental/jax2tf#coverage-of-shape-polymorphic-tracing) tries to explain this in detail.

Your example with vmap should work, and we have many tests in that spirit. However, we do not really support TF1 and we do not test it (although I suspect you can make it work). I modified your example slightly and it works:

```
    regular_arg = (np.array(0.), np.array(1.))
    def arbitrary_fn(x):
      pass

    res = arbitrary_fn(regular_arg)  # runs fine
    tf_fn = jax2tf.convert(jax.vmap(arbitrary_fn),
                           polymorphic_shapes=tree.map_structure(lambda x: "(b, ...)", regular_arg))
    place = tree.map_structure(lambda x: tf.TensorSpec((1,) + x.shape, x.dtype), regular_arg)
    res_place = tf.function(tf_fn)(place)
```

**Comment by sygi** [comment] 2021-07-22 17:14
Sorry for bothering again. After spending more time on this, I managed to reduce my code to:

```python
def arbitrary_fn(x):
  pass
arbitrary_fn(regular)  # runs fine
extended = tree.map_structure(lambda x: np.expand_dims(x, axis=0), regular)
jax.vmap(arbitrary_fn)(extended)  # runs fine
batched_full_shape = tree.map_structure(lambda x: str(('b',) + x.shape), regular)  # not exactly the implementation, but confirmed the shapes are correct, with 'b' at the front
one_batched_shape = tree.map_structure(lambda x: x.replace('b', '1'), batched_full_shape_of_regular)
one_place = tree.map_structure(lambda x: tf.placeholder(shape=(1,) + x.shape, dtype=x.dtype), regular)
one_spec = tree.map_structure(lambda x: tf.TensorSpec((1,) + x.shape, x.dtype), regular)

tf_one = jax2tf.convert(jax.vmap(arbitrary_fn), polymorphic=one_batched_shape)
tf_batched = jax2tf.convert(jax.vmap(arbitrary_fn), polymorphic=batched_full_shape)

tf.function(tf_one)(one_place)  # runs fine
tf.function(tf_one)(one_spec)  # fails with ValueError: Arguments and signature arguments do not match. got: 0, expected: 10
tf.function(tf_batched)(one_spec)  # fails with InconclusiveDimensionOperation
tf.function(tf_batched)(one_place)  # fails with InconclusiveDimensionOperation
```

Did you, in your message, meant that using `tf.placeholder` is not supported at all? Any idea about the situations in which `tf.placeholder` may work and `tf.TensorSpec` will fail? Or ones where `fn(regular)` and `jax.vmap(fn)(extended)` will run, but `tf_one(one_spec)` won't? Similarly, what could be a reason for `InconclusiveDimensionOp` if substituting `b` with `1` leads to the code running with the same input?

I will greatly appreciate your help here!

**Comment by gnecula** [comment] 2021-07-23 07:10
`tf.placeholder` is a TF1-only concept. Is TF1 a requirement for you? We have not tested `jax2tf` with TF1 and I don't actually know TF1.

Focussing on the TF2-compatible parts of your code (remove all the stuff with placeholders), I am having trouble running your code. First, I add `regular = np.array([0., 1.])` (perhaps the errors are different depending on what you used for `regular`.)

Then, I had to replace `polymorphic=` with `polymorphic_shapes=`. Then I get the error 

```
TypeError: polymorphic_shapes must be a sequence with the same length as the positional argument list (1). Got polymorphic_shapes=('1', 2)
```

This is because `polymorphic_shapes` should be a list or tuple. (This error is confusing, I will improve the error reporting). 
I fix this by `polymorphic_shapes=[one_batched_shape]`. Then I get the error:

```
ValueError: PolyShape '('1', 2)' has invalid syntax (unexpected term ''1'')
```

I fix this by replacing `lambda x: str(('b',) + x.shape)` with `lambda x: 'b, ...'`. 

Now I get the error you reported: `ValueError: Arguments and signature arguments do not match. got: 0, expected: 1`.

The problem here is that it seems TF does not like tf.TensorSpec as arguments to tf.function. You can do: 

```
tf.function(tf_one).get_concrete_function(one_spec)
```

and this runs without errors.

If you have further trouble, please include code that runs in TF 2.

**Comment by gnecula** [comment] 2021-07-23 08:06
I have made some improvements to the error checking and reporting for bad polymorphic_shapes in PR #7356.

**Comment by sygi** [comment] 2021-07-23 08:26
Thanks for taking a look. I'm sorry I didn't make it clear enough, but the example above was not meant to be run. What I am saying there is that I have a function where if I extend the shapes of all the inputs by 'b' (correctly, so eg. I have "(b, 76, 48, 3)" as a shape (which is not super easy due to how tree works)) and vmap the function, I get the `InconclusiveDimensionOperation`. When I map `b` to `1` (so in my example I'd have `(1, 76, 48, 3)`), the code runs with the same input.

The problem is, if I substitute my complex function with a simple one, the code runs again; if I were able to make a small reproduction, I would include it here, but I don't (I can give you access to the code in g3).

I will try to do what you suggested with turning on TF2 and using `get_concrete_function` and report back (on Monday) if I still see the errors, but using TF1 is a requirements for us due to backwards compatibility, so thanks for confirming that's not supported at all.

Thanks for your support and improving the error reporting there; I have, in fact, stumbled upon that before :)

**Comment by gnecula** [comment] 2021-07-25 12:10
It is very possible for code traced with a dimension variable to produce `InconclusiveDimensionOperation` even when the code works when replacing the dimension variable with a constant. This means that your code (or some code inside JAX) tries to compute something that is not supported for dimension variables. This [part of the documentation](https://github.com/google/jax/tree/9f8fb243f9d709d9351e12c46b21c5c531abbc15/jax/experimental/jax2tf#computing-with-dimension-variables) tries to explain this. 

Do you have reasons to believe that your code is shape polymorphic? Does it behaves the same if you replace the dimension variables with any value >= 1? For example code that contains a conditional `if x.shape[0] >= 10: ...` is not obviously shape polymorphic in the first dimension of `x`, because it may do different things for different values of a dimension variable. JAX is very conservative: if it sees that you are trying to cast a dimension size to an integer, it will throw that exception. However, JAX will allow addition, subtraction, multiplication and some limited forms of division. 

Is the offending operation on shapes in your code or in JAX? Perhaps if you can include the stack trace I can guess.

**Comment by sygi** [comment] 2021-07-26 09:50
I ran the code you suggested (with concretization) in tf2 and got the same behavior as in tf1: when running with an extra `(1,` dimension, it runs fine, when running with `(b` it gives the same error. I include stacktrace since entering `lax.scan` below.

I'm slightly confused by your question "why do you think your code is shape polymorphic". Isn't this property guaranteed (over the first dimension) for functions of the form `jax.vmap(arbitrary_fn)` that I have here? The docs you linked [suggest](https://github.com/google/jax/tree/9f8fb243f9d709d9351e12c46b21c5c531abbc15/jax/experimental/jax2tf#coverage-of-shape-polymorphic-tracing) that this is supported.

```
core_out, state = core_fns.unroll((core_in, should_reset), state)
  File "/google/src/cloud/sygi/xland_wfh/google3/blaze-out/haswell-opt/bin/learning/deepmind/research/xland/jaxland/agents/snapshotting_test.runfiles/google3/third_party/py/haiku/_src/recurrent.py", line 183, in dynamic_unroll
    input_sequence)
  File ".../third_party/py/haiku/_src/stateful.py", line 508, in scan
    stateful_fun, init, xs, length, reverse, unroll=unroll)
  File ".../third_party/py/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 1304, in scan
    unroll=unroll)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 1876, in scan_bind
    return core.Primitive.bind(scan_p, *args, **params)
  File ".../third_party/py/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File ".../third_party/py/jax/interpreters/batching.py", line 145, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 1791, in _scan_batching_rule
    num_consts=num_consts, num_carry=num_carry, linear=linear, unroll=unroll)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 1876, in scan_bind
    return core.Primitive.bind(scan_p, *args, **params)
  File ".../third_party/py/jax/core.py", line 264, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 877, in process_primitive
    val_out = invoke_impl()
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 858, in invoke_impl
    **params)
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 490, in wrapped
    extra_name_stack)
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 455, in _interpret_fun
    fun.call_wrapped(*in_vals)
  File ".../third_party/py/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 485, in jax_impl_jax_args
    jax_results = jax_impl(*jax_args, **kwargs)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 1390, in _scan_impl
    y_avals=y_avals)
  File "...third_party/py/jax/_src/lax/control_flow.py", line 1348, in _scan_impl_loop
    _, *outs = while_loop(cond_fun, body_fun, init_val)
  File ".../third_party/py/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 300, in while_loop
    init_vals, init_avals, body_jaxpr, in_tree, *rest = _create_jaxpr(init_val)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 284, in _create_jaxpr
    body_fun, in_tree, init_avals, "while_loop")
  File ".../third_party/py/jax/_src/util.py", line 186, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File ".../third_party/py/jax/_src/util.py", line 179, in cached
    return f(*args, **kwargs)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 77, in _initial_style_jaxpr
    fun, in_tree, in_avals, primitive_name)
  File ".../third_party/py/jax/_src/util.py", line 186, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File ".../third_party/py/jax/_src/util.py", line 179, in cached
    return f(*args, **kwargs)
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 70, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File ".../third_party/py/jax/interpreters/partial_eval.py", line 1253, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File ".../third_party/py/jax/interpreters/partial_eval.py", line 1263, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File ".../third_party/py/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 1337, in body_fun
    x = _map(partial(_dynamic_index_array, i_), x_avals, xs)
  File ".../third_party/py/jax/_src/util.py", line 41, in safe_map
    return list(map(f, *args))
  File ".../third_party/py/jax/_src/lax/control_flow.py", line 1449, in _dynamic_index_array
    return lax.dynamic_index_in_dim(x, i, keepdims=False)
  File ".../third_party/py/jax/_src/lax/lax.py", line 1968, in dynamic_index_in_dim
    result = dynamic_slice_in_dim(operand, index, 1, axis)
  File ".../third_party/py/jax/_src/lax/lax.py", line 1962, in dynamic_slice_in_dim
    return dynamic_slice(operand, start_indices, slice_sizes)
  File ".../third_party/py/jax/_src/lax/lax.py", line 888, in dynamic_slice
    start_indices = _dynamic_slice_indices(operand, start_indices)
  File ".../third_party/py/jax/_src/lax/lax.py", line 6739, in _dynamic_slice_indices
    for i, d in zip(start_indices, operand.shape)]
  File ".../third_party/py/jax/_src/lax/lax.py", line 6739, in <listcomp>
    for i, d in zip(start_indices, operand.shape)]
  File ".../third_party/py/jax/_src/lax/lax.py", line 6745, in _const
    val = dtypes.scalar_type_of(example)(val)
  File ".../third_party/py/jax/experimental/jax2tf/shape_poly.py", line 333, in __int__
    raise InconclusiveDimensionOperation(f"Dimension polynomial '{self}' is not constant")

The above exception was the direct cause of the following exception:
...
    core_out, state = core_fns.unroll((core_in, should_reset), state)
  File ".../third_party/py/haiku/_src/recurrent.py", line 183, in dynamic_unroll
    input_sequence)
  File ".../third_party/py/haiku/_src/stateful.py", line 508, in scan
    stateful_fun, init, xs, length, reverse, unroll=unroll)
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 877, in process_primitive
    val_out = invoke_impl()
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 858, in invoke_impl
    **params)
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 490, in wrapped
    extra_name_stack)
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 455, in _interpret_fun
    fun.call_wrapped(*in_vals)
  File ".../third_party/py/jax/experimental/jax2tf/jax2tf.py", line 485, in jax_impl_jax_args
    jax_results = jax_impl(*jax_args, **kwargs)
  File ".../third_party/py/jax/experimental/jax2tf/shape_poly.py", line 333, in __int__
    raise InconclusiveDimensionOperation(f"Dimension polynomial '{self}' is not constant")
jax.experimental.jax2tf.shape_poly.InconclusiveDimensionOperation: Dimension polynomial 'b' is not constant
```

**Comment by gnecula** [comment] 2021-07-26 10:47
I asked "why do you think your code is shape polymorphic" because I did not not remember that your function is the result of `jax.vmap`. In that case we aim to extend JAX to recognise that shape polymorphism. It is possible that we are not there yet, as you seem to be encountering.

From the stack trace, it seems that the problem is in the invocation of `lax.dynamic_slice` (line 888). Can you get the shapes of the arguments of `lax.dynamic_slice`? I can try in parallel to construct a repro example.

**Comment by gnecula** [comment] 2021-07-26 10:49
I strongly suspect that fixing this requires merging PR #7317.

**Comment by sygi** [comment] 2021-07-26 11:17
The sapes entering `dynamic slice` are:
```
operand: (1, b, 1, 64)
start_indices: [(), (), (), ()]
slice_shapes: [1, b, 1, 64]
```

Do you know whether is there an easy way for me to patch this PR internally?

**Comment by gnecula** [comment] 2021-07-26 11:54
I was able to reproduce your use case, and indeed PR #7317 should solve this issue. 

I think that you should be able to patch this PR locally if you clone the JAX sources, then patch the PR  and then run `pip install -e .` in the JAX directory.

**Comment by sygi** [comment] 2021-07-26 16:18
Thanks for preparing a fix. I tested it like this:

```python
tensor_spec = tree.map_structure(
    lambda x: tf.TensorSpec((None,) + x.shape, x.dtype),
    regular_input)
expanded_one = tree.map_structure(lambda x: np.expand_dims(x, axis=0), regular_input)
expanded_three = tree.map_structure(lambda x: np.repeat(np.expand_dims(x, axis=0), 3, axis=0), regular_input)

concrete = tf.function(tf_step, autograph=False).get_concrete_function(tensor_spec)
concrete(expanded_one)
concrete(expanded_three)
```
and can confirm it runs in tf2. However, in tf1 I get the following error (when calling on `expanded_three`), suggesting that, despite marking shapes polymorphic and concretinizing the function with (None, .., the resulting function considers its inputs to be of shape (1,...:

```
ValueError: Cannot reshape a tensor with 192 elements to shape [1,1,64] (64 elements) for '{{node Reshape_11}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](jax2tf_arg_12, Reshape_11/shape)' with input shapes: [3,64], [3] and with input tensors computed as partial shapes: input[1] = [1,1,64].
```

I get the same error when using tf.placeholders. I tried using a placeholder of shape (1,... instead of (None, but this gives me:
```
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Input tensor 'BroadcastTo_10:0' enters the loop with shape (1, 1, 64), but has shape (?, 1, 64) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.
```

**Comment by gnecula** [comment] 2021-07-27 12:45
PR #7317 has been merged. Please try it out.

**Comment by sygi** [comment] 2021-07-27 12:47
Thank you! As I said above (I patched it in before it was merged), it indeed works in tf2, but fails in tf1.

**Comment by gnecula** [comment] 2021-07-27 12:47
I am sorry, but I am very reluctant to start debugging TF1. We don't really intend to support TF1 for jax2tf, but I would be happy to take in contributions.

**Comment by gnecula** [comment] 2021-07-27 12:49
Perhaps I could debug this if you prepare a branch in your repo with a pytest that fails. I could then try to setup a virtualenv with your dependencies and see if I can reproduce it.

**Comment by sygi** [comment] 2021-07-27 12:51
That's fair, thanks a lot for taking a look. Did I understand correctly that for testing this, you were able to reproduce the issue I had with a small example? Would you be able to provide that for our own investigations? I was trying to play with different combinations of while/scan, etc. but everything simple that I got worked fine. I also investigated the graph and indeed it had some nodes where it seems the polymorphic shape didn't propagate, but with the big complex example that I have it's impossible to know what exactly is causing the issue.

**Comment by gnecula** [comment] 2021-07-27 18:05
I recognized from the stack trace that the issue had to do with just dynamic_slice when passed a list of indices as argument. The test case is [this](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/tests/shape_poly_test.py#L1326-L1338)

**Comment by sygi** [comment] 2021-07-28 14:08
Thank you. I managed to reduce the breaking example to:
```python
import tensorflow.compat.v2 as tf_v2
#tf_v2.enable_v2_behavior()  # commenting this line breaks it
import jax
from jax.experimental import jax2tf
import numpy as np
import jax.numpy as jnp

def fn(x):
  return jnp.expand_dims(x, axis=0)

h = tf_v2.function(jax2tf.convert(jax.vmap(fn), polymorphic_shapes=["(b, 5)"], with_gradient=False), autograph=False)
concrete = h.get_concrete_function(tf_v2.TensorSpec([None, 5], tf_v2.float32))
concrete(np.random.random((3, 5)).astype(np.float32))
```

**Comment by gnecula** [comment] 2021-07-29 08:04
I actually do not see any error, whether or not I comment out the line. In both cases the output shape of concrete is [None, 1, 5], which is as expected.

What error are you seeing?

BTW, I am using tf-nightly.

**Comment by sygi** [comment] 2021-07-29 09:15
I shared a colab with you. The error I'm seeing is:
```
ValueError: Cannot reshape a tensor with 15 elements to shape [1,1,5] (5 elements) for '{{node Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](jax2tf_arg_0, Reshape/shape)' with input shapes: [3,5], [3] and with input tensors computed as partial shapes: input[1] = [1,1,5].
```

I believe what I was missing in the example is a call to `tf_v2.disable_v2_behavior()`.

**Comment by gnecula** [comment] 2021-07-30 11:16
I can reproduce this with (explicitly forcing TF1 behavior):
```
 import tensorflow.compat.v1 as tf_v1
tf_v1.disable_v2_behavior()
```

Both lines are important in my installation.

I will fix this soon.

**Closed** 2021-07-30 14:42 UTC
Labels: bug
