### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable

### ISSUE THREAD

**Issue by April-ppigg** [google/jax#18514] opened 2023-11-14 05:54 UTC
### Description

jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/prng_kernels.cc:33: operation gpuGetLastError() failed: no kernel image is available for execution on the device; current tracing scope: custom-call.11; current profiling annotation: XlaModule:#hlo_module=jit__threefry_split_original,program_id=28#.

pip list:
absl-py                  1.4.0
attrs                    23.1.0
blosc2                   2.0.0
chex                     0.1.7
cloudpickle              2.2.1
conda-pack               0.7.1
contextlib2              21.6.0
contourpy                1.1.0
cycler                   0.11.0
Cython                   0.29.36
decorator                5.1.1
distrax                  0.1.3
dm-tree                  0.1.8
fonttools                4.42.0
gast                     0.5.4
h5py                     3.9.0
immutabledict            2.2.4
importlib-metadata       6.7.0
importlib-resources      6.0.1
jax                      0.4.12
jaxlib                   0.4.12+cuda11.cudnn86
kfac-jax                 0.0.5
kiwisolver               1.4.4
matplotlib               3.7.2
ml-collections           0.1.1
ml-dtypes                0.2.0
msgpack                  1.0.5
numexpr                  2.8.4
numpy                    1.22.4
nvidia-cublas-cu11       11.11.3.6
nvidia-cuda-cupti-cu11   11.8.87
nvidia-cuda-nvrtc-cu11   11.8.89
nvidia-cuda-runtime-cu11 11.8.89
nvidia-cudnn-cu11        8.6.0.163
nvidia-cufft-cu11        10.9.0.58
nvidia-cusolver-cu11     11.4.1.48
nvidia-cusparse-cu11     11.7.5.86
opt-einsum               3.3.0
optax                    0.1.5
packaging                23.1
pandas                   2.0.3
Pillow                   10.0.0
pip                      23.1.2
py-cpuinfo               9.0.0
pyblock                  0.6
pyparsing                3.0.9
pyscf                    2.2.1
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0
scipy                    1.10.1
setuptools               67.8.0
six                      1.16.0
tables                   3.8.0
tensorflow-probability   0.20.1
toolz                    0.12.0
typing_extensions        4.6.3
tzdata                   2023.3
wheel                    0.38.4
zipp                     3.15.0

### What jax/jaxlib version are you using?

jax 0.4.12 jaxlib 0.4.12+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU (k80)

### Additional system info

python3.9 linux

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:06:00.0 Off |                    0 |
| N/A   38C    P0   128W / 149W |  10506MiB / 11441MiB |     88%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:07:00.0 Off |                    0 |
| N/A   46C    P0   143W / 149W |  10541MiB / 11441MiB |     87%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     14429      C   ...R011/anaconda3/bin/python    10501MiB |
|    1   N/A  N/A     14429      C   ...R011/anaconda3/bin/python    10536MiB |
+-----------------------------------------------------------------------------+

**Comment by hawkinsp** [comment] 2023-11-14 14:48
The issue is you are using a K80 GPU. Kepler-series GPUs are no longer supported by JAX. NVIDIA has dropped support for them in CUDA 12.

https://jax.readthedocs.io/en/latest/installation.html#nvidia-gpu

We should issue a better error in this case; closing because that issue is tracked by https://github.com/google/jax/issues/993 .

Hope that helps!

**Closed by hawkinsp** 2023-11-14 14:48 UTC
Labels: bug
