### ISSUE TITLE
Implementing np.eig in JAX

### ISSUE THREAD

**Issue by stanislavfort** [google/jax#2776] opened 2020-04-20 22:20 UTC
tl;dr: Please implement np.eig in JAX, in particular its forward-mode differentiation

I am working on a quantum project that is currently written in TensorFlow but would greatly benefit from JAX. The main roadblock is that the np.eig function does not have its forward-mode differentiation rule implemented in JAX.

Thanks a lot!

**Comment by froystig** [comment] 2020-04-20 22:44
Duplicate of #2748

**Closed by froystig** 2020-04-20 22:44 UTC
