### ISSUE TITLE
Dimension is lost when indexing numpy with singleton jax.numpy

### ISSUE THREAD

**Issue by MichaelMathieu** [google/jax#3607] opened 2020-06-30 11:59 UTC
Hi,

When indexing a numpy array with a jax.numpy array, and the jax array has a singleton dimension, the dimension is lost. This behaviour is different if both are numpy arrays, or both are jax arrays.

```
array_jnp = jnp.zeros((50, 5))
array_np = np.zeros((50, 5))
idx_jnp = jnp.array([2])
idx_np = np.array([2])
print(array_jnp[idx_jnp])  # prints [[0. 0. 0. 0. 0.]]
print(array_np[idx_jnp])  # prints [0. 0. 0. 0. 0.]    <--------- this is different!
print(array_jnp[idx_np])  # prints [[0. 0. 0. 0. 0.]]
print(array_np[idx_np])  # prints [[0. 0. 0. 0. 0.]]
```

**Comment by jakevdp** [comment] 2020-06-30 13:51
Thanks for the report and the clear repro!

**Comment by jakevdp** [comment] 2020-06-30 16:34
The code emits a warning that gives some clues about what's happening:
```
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
```
That warning is raised here: https://github.com/numpy/numpy/blob/cb98ad400c701f189d4e4043ee2cb44857733df4/numpy/core/src/multiarray/mapping.c#L309-L325

The reason it gets here is because jax device arrays fail this check, which is where standard array indices are handled: https://github.com/numpy/numpy/blob/cb98ad400c701f189d4e4043ee2cb44857733df4/numpy/core/src/multiarray/mapping.c#L228-L237
```
/* Obvious single-entry cases */
    if (0  /* to aid macros below */
            || PyLong_CheckExact(index)
            || index == Py_None
            || PySlice_Check(index)
            || PyArray_Check(index)
            || !PySequence_Check(index)
            || PyBaseString_Check(index)) {

        return unpack_scalar(index, result, result_n);
    }
```
Apparently, jax arrays do not present themselves to numpys C-API as arrays, and so `PyArray_Check` returns `False`. The fix here would be to figure out why this is the case, and check whether there's something we could do on the jax side to change the result of `PyArray_Check` on jax arrays.

**Comment by shoyer** [comment] 2020-06-30 16:34
This has come up before: https://github.com/google/jax/issues/620

Unfortunately it doesn't seem like there's much we can do to fix this on the JAX side because NumPy finishes the deprecation cycle for this behavior -- which should hopefully be very soon, if anyone gets around to it!

**Comment by jakevdp** [comment] 2020-06-30 16:51
Thanks, I'll close it as a duplicate of #620 then.

**Closed by jakevdp** 2020-06-30 16:51 UTC
Labels: bug
