### ISSUE TITLE
Destructing DeviceArray produces Numpy arrays

### ISSUE THREAD

**Issue by cgarciae** [google/jax#8017] opened 2021-09-27 18:17 UTC
Don't know if this is a new feature or a bug. Destructing a DeviceArray is resulting in its pieces being converted to Numpy arrays:
```python
import jax
import jax.numpy as jnp

key = jax.random.PRNGKey(0)
key1, key2 = jax.random.split(key)

assert not isintance(key1, jnp.ndarray)
assert not isintance(key2, jnp.ndarray)
```
This is surprising given this pattern with `split` is used extensively in the docs. Now it seems you have to do this:
```python
key = jax.random.PRNGKey(0)
splits = jax.random.split(key)
key1, key2 = splits[0], splits[1]

assert isintance(key1, jnp.ndarray)
assert isintance(key2, jnp.ndarray)
```
Which is less nice.

Versions:
```
name = "jax"
version = "0.2.21"

name = "jaxlib"
version = "0.1.71"
```

**Comment by cgarciae** [comment] 2021-09-27 18:25
I can confirm this doesn't happen in `jax==0.2.20`.

**Comment by jakevdp** [comment] 2021-09-27 18:25
Thanks for the report! This is actually a long-standing issue (See e.g. #1583) There is a potential fix in #3821, but it has not landed yet.

**Comment by cgarciae** [comment] 2021-09-27 18:28
Thanks @jakevdp! 

But why is there a difference in behavior between `jax==0.2.20` and `jax==0.2.21`? 
I believe this is going to break a lot of code.

**Comment by cgarciae** [comment] 2021-09-27 18:30
Examples that might no longer work: https://github.com/google/flax/search?q=random.split

**Comment by jakevdp** [comment] 2021-09-27 18:33
The return type of destructured jax arrays has not changed, but the semantics of `isinstance(x, jnp.ndarray)` have changed between v0.2.20 and v0.2.21. See https://github.com/google/jax/pull/7927

If you check `isinstance(key1, np.ndarray)` the results will be the same from v0.2.20 to v0.2.21.

**Comment by cgarciae** [comment] 2021-09-27 18:44
@jakevdp I've updated the example. I feel the implications are much stronger, here destructured arrays are Numpy array, not just instances of it.

**Comment by cgarciae** [comment] 2021-09-27 18:51
Thanks @jakevdp! I was very confused a second, sorry for all the noise in the thread.
I will post an issue in Flax repo.

**Comment by cgarciae** [comment] 2021-09-27 19:00
As I am fixing code, sadly the practical solution has been to avoid de-structuring on my side so I can interface with external code:

```python
splits = jax.random.split(key)
key1, key2 = splits[0], splits[1]
```

**Comment by jakevdp** [comment] 2021-09-27 19:07
Yeah, the issue is much larger than `split`, unfortunately. We really need to get #3821 or something like it in, but it has been challenging for various reasons.

**Closed** 2022-06-03 17:26 UTC
Labels: bug, duplicate
