### ISSUE TITLE
non-Python type signatures in docs are confusing for a Python package

### ISSUE THREAD

**Issue by grahamgower** [google/jax#8355] opened 2021-10-24 13:14 UTC
The docs include confusing type signatures, using what I assume is Haskell syntax (please correct me if I'm wrong---I never learned Haskell). Two examples I found are:
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html#jax.lax.scan
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.fori_loop.html#jax.lax.fori_loop

PS: sorry, I didn't see an option to report an issue with the docs, so just used the "bugs" issue template.

**Comment by jakevdp** [comment] 2021-10-29 18:06
Does anyone know a good reference for this haskell signature syntax?

**Comment by soraros** [comment] 2021-10-29 18:56
I think the problem is not "type signature syntax" per se, but automatic currying. So a reference might be [this](https://wiki.haskell.org/Currying).

**Comment by jakevdp** [comment] 2022-05-16 17:44
Re-opening and assigning to @mattjj in case we want to add more info (cf. https://github.com/google/jax/pull/10700#pullrequestreview-973028228)

**Closed** 2022-05-23 21:04 UTC
Labels: documentation
