### ISSUE TITLE
XLARunTime Error: Cannot remove instruction %all-reduce while sharding with convolutions

### ISSUE THREAD

**Issue by anuragithub** [google/jax#17431] opened 2023-09-05 09:19 UTC
### Description

Hi team, I have been using jax with equinox for some time, and was excited by the new AutoParallelism feature using sharding. Unfortunately, there's a bug I have encountered while using sharding using convolutions. XLA with sharding and convolutions just breaks. 

With all other operations with FC layers and other, sharding works, but fails with convolution.

See the below error: 
![image](https://github.com/google/jax/assets/8970660/245c42ce-db96-4d46-bdd2-a40b7338b455)

MWE for the replication of code is below:
```python
import equinox as eqx
import jax
import jax.experimental.mesh_utils as mesh_utils
import jax.numpy as jnp
import jax.random as jr
import jax.sharding as sharding
import numpy as np
import optax  # https://github.com/deepmind/optax

# Hyperparameters
dataset_size = 64
channel_size = 4
hidden_size = 32
depth = 1
learning_rate = 3e-4
num_steps = 10
batch_size = 16  # must be a multiple of our number of devices.

# Generate some synthetic data
xs = np.random.normal(size=(dataset_size, channel_size))
ys = np.sin(xs)

num_samples = 100
image_height = 64
image_width = 64
num_channels = 3

# Generate random image data with values between 0 and 255
images = np.random.randint(0, 256, size=(num_samples, num_channels, image_height, image_width ), dtype=np.uint8)

# Generate corresponding random labels from 0 to 5
labels = np.random.randint(0, 6, size=num_samples)


class SimpleConv(eqx.Module):
    conv_layer: eqx.nn.Conv2d
    linear : eqx.nn.Linear
    def __init__(self, key):
        key1, key2 = jr.split(key, 2)
        self.conv_layer = eqx.nn.Conv2d(3, 5, 5, 1, padding=2, key=key1)
        self.linear = eqx.nn.Linear(20480, 1, key=key2)

    def __call__(self, x):
        x = self.conv_layer(x)
        return self.linear(x.flatten())

model = SimpleConv(key=jr.PRNGKey(6789))
optim = optax.adam(learning_rate)
opt_state = optim.init(eqx.filter(model, eqx.is_inexact_array))




def compute_loss(model, x, y):
    pred_y = jax.vmap(model)(x)
    return jnp.mean((y - pred_y) ** 2)


@eqx.filter_jit
def make_step(model, opt_state, x, y):
    grads = eqx.filter_grad(compute_loss)(model, x, y)
    updates, opt_state = optim.update(grads, opt_state)
    model = eqx.apply_updates(model, updates)
    return model, opt_state

def dataloader(arrays, batch_size):
    dataset_size = arrays[0].shape[0]
    assert all(array.shape[0] == dataset_size for array in arrays)
    indices = np.arange(dataset_size)
    while True:
        perm = np.random.permutation(indices)
        start = 0
        end = batch_size
        while end != dataset_size:
            batch_perm = perm[start:end]
            yield tuple(array[batch_perm] for array in arrays)
            start = end
            end = start + batch_size


num_devices = len(jax.devices())
devices_x = mesh_utils.create_device_mesh((num_devices, 1, 1, 1))
devices_y = mesh_utils.create_device_mesh((num_devices,))
shard_x = sharding.PositionalSharding(devices_x)
shard_y = sharding.PositionalSharding(devices_y)
print(f"Devices being used {num_devices}") 

for step, (x, y) in zip(range(num_steps), dataloader((images, labels), batch_size)):
    x = jnp.asarray(x, dtype="float32")
    x, y = jax.device_put(x, shard_x), jax.device_put(y, shard_y)
    model, opt_state = make_step(model, opt_state, x, y)


```

### What jax/jaxlib version are you using?

jax==0.4.13, jaxlib==0.4.13+cuda12.cudnn89

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux

### NVIDIA GPU info

NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1

**Comment by hawkinsp** [comment] 2023-09-11 21:23
I can't reproduce this at head on 2 GPUs. Can you say more about your GPU setup? How many GPUs are you using and what kinds?

If you're so inclined, if you build `jaxlib` from source at head does the problem reproduce?

**Comment by hawkinsp** [comment] 2023-11-17 14:39
Closing because no further details were provided. I'd be happy to look into this if you can still reproduce this with the latest jax and jaxlib!

**Closed by hawkinsp** 2023-11-17 14:39 UTC
Labels: bug, XLA, needs info, NVIDIA GPU
