### ISSUE TITLE
Can't jit `view` with reinterpret from int32 to int64

### ISSUE THREAD

**Issue by jenkspt** [google/jax#11092] opened 2022-06-14 14:24 UTC
```python
import jax
import jax.numpy as jnp
from jax.experimental import enable_x64

@jax.jit
def f(x):
    with enable_x64():
        return x.view(jnp.int64)

f(jnp.arange(10).reshape(5,2))
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
main.py in <module>
----> 1 pack_fragments(jnp.array(-10.01), jnp.array(-1))

    [... skipping hidden 14 frame]

.../python3.9/site-packages/jax/_src/util.py in safe_map(f, *args)
     42   for arg in args[1:]:
     43     assert len(arg) == n, 'length mismatch: {}'.format(list(map(len, args)))
---> 44   return list(map(f, *args))
     45 
     46 def unzip2(xys):

RuntimeError: INVALID_ARGUMENT: Binary op shift-left with different element types: u64[1,2] and u32[1,2].
```

**Comment by hawkinsp** [comment] 2022-06-14 15:14
Using the `experimental` `enable_x64` scope is buggy. (It is tagged `experimental` for a reason.)

For now, try enabling x64 mode globally at the start of the program, like this:
```
jax.config.update('jax_enable_x64', True)
```

**Comment by jenkspt** [comment] 2022-06-14 16:13
Thanks! that works -- I suppose this should be a feature request.

**Comment by jakevdp** [comment] 2022-06-14 16:23
This feature is something that we're not going to implement, because to do so would require a deep restructure of how JAX transforms work. The issue you raised here is one of the motivating reasons for our goal to excise the X64 modalism entirely from JAX; you can see https://github.com/google/jax/issues/8178 for more.

**Comment by jakevdp** [comment] 2022-06-14 16:24
I'm going to close this as a duplicate of https://github.com/google/jax/issues/5982; thanks for the report!

**Closed by jakevdp** 2022-06-14 16:24 UTC
Labels: bug
