### ISSUE TITLE
Dot of dn=((0,),(0,)) for a=[100, 100] b=[100, 1] crashes on GPU with latest JAX release

### ISSUE THREAD

**Issue by tomhennigan** [google/jax#7752] opened 2021-08-29 18:24 UTC
Trivial dot crashes on GPU with latest JAX release (reported at deepmind/dm-haiku#204).

Changing the last dim of `b` to anything other than `1` seems to fix things.

```python
import jax
import jax.numpy as jnp

a = jnp.ones([100, 100])
b = jnp.ones([100, 1])
c = jax.lax.dot_general(a, b, dimension_numbers=(((0,), (0,)), ((), ())))
c.block_until_ready()
# RuntimeError: Internal: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

Full reproducer at https://colab.research.google.com/gist/tomhennigan/ae29278953f4637b085765f5aeabe5f8/copy-of-dm-haiku.ipynb

I tested in Colab with the latest JAX/jaxlib installed using:

```
!pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.7/dist-packages (21.2.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

!pip install --upgrade "jax[cuda111]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
Looking in links: https://storage.googleapis.com/jax-releases/jax_releases.html
Requirement already satisfied: jax[cuda111] in /usr/local/lib/python3.7/dist-packages (0.2.19)
Requirement already satisfied: numpy>=1.18 in /usr/local/lib/python3.7/dist-packages (from jax[cuda111]) (1.19.5)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.7/dist-packages (from jax[cuda111]) (3.3.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.7/dist-packages (from jax[cuda111]) (0.12.0)
Requirement already satisfied: jaxlib==0.1.70+cuda111 in /usr/local/lib/python3.7/dist-packages (from jax[cuda111]) (0.1.70+cuda111)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from jaxlib==0.1.70+cuda111->jax[cuda111]) (1.4.1)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in /usr/local/lib/python3.7/dist-packages (from jaxlib==0.1.70+cuda111->jax[cuda111]) (1.12)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from absl-py->jax[cuda111]) (1.15.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Tested on a T4 GPU:

```
!nvidia-smi
Sun Aug 29 17:57:16 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by hawkinsp** [comment] 2021-08-31 17:45
This appears to reproduce on CUDA 11.0 only, as best I can tell.

**Comment by hawkinsp** [comment] 2021-08-31 18:27
I am now mostly confident this is a `ptxas` bug.

* It reproduces under CUDA 11.0 but not under CUDA 11.2.
* JAX/XLA produce identical PTX code under both versions.
* It does not reproduce if I use the `ptxas` version from CUDA 11.2 with an otherwise CUDA 11.0 installation.

I conclude this is likely a `ptxas` bug. Since it already seems to be fixed, I doubt it's worth asking NVidia about it; probably the right thing to do would be to get Colab to update its installed copy of CUDA to something newer. We want that for other reasons also (namely: we'd like to drop CUDA 11.0 support).

Closing because I don't think there's an action we can take here.

**Closed by hawkinsp** 2021-08-31 18:27 UTC
Labels: bug
