### ISSUE TITLE
single function which subsumes different vmapped functions

### ISSUE THREAD

**Issue by SaitejaUtpala** [google/jax#12392] opened 2022-09-16 18:33 UTC
assume we have written a function which work when a, b are single instances

```
def f(a,b):
   #some computation  
   return result
```

using **vmap** we can repeat same computation for different instances of a and single instance of b as follows

```
v = partial(vmap, in_axes=(0, None))
af = v(f)
```

now similarly, we can repeat same computation for single instances of a and multiple instances of b as follows

```
v = partial(vmap, in_axes=(None, 0))
bf = v(f)
```

we have different functions `af`, `bf`. Is there way to combine this into single function and handle automatically ? If input is batched over **a** use `af` and if it is batched over **b** use `bf`.

Thanks in advance.

**Comment by mattjj** [comment] 2022-09-16 18:47
Thanks for the question!

I may not understand it though. It seems like the issue is independent of JAX and vmap, and just has to do with the caller. Shouldn't this look just like e.g.

```python
if a.ndim > 1:
  return af(a, b)
elif b.ndim > 1:
  return bf(a, b)
```

where I've just assumed you check for "if the input is batched" by checking the rank of `a` and `b` somehow.

**Comment by mattjj** [comment] 2022-09-16 18:52
Is this a duplicate of #12391? Let's consolidate there.

**Closed by mattjj** 2022-09-16 18:52 UTC
Labels: question
