### ISSUE TITLE
jnp.ndarray unpacking yields onp.ndarray results

### ISSUE THREAD

**Issue by romanngg** [google/jax#7204] opened 2021-07-07 15:49 UTC
Example:
```python
import jax.numpy as jnp
import numpy as np
a = jnp.arange(10).reshape((2, 5))

type(a)
```
```
jaxlib.xla_extension.DeviceArray
```

But if we do:
```
b, c = a
```
We get
```
type(b), type(c)
```
```
(numpy.ndarray, numpy.ndarray)
```
https://colab.research.google.com/gist/romanngg/bc4197d71a404f28224914a2b0dc4481/jnp-np-coversion-when-unpacking.ipynb

**Comment by jakevdp** [comment] 2021-07-07 16:05
Hi - thanks for the issue! I think this is a duplicate of #1583, which has a potential fix in #3821

I can't quite recall why that fix stalled – but I recall there were some subtle aspects of this that made it a tricky fix.

**Comment by jakevdp** [comment] 2021-07-07 16:06
I'll assign this to @mattjj as a light ping on the issue :grin:

**Comment by jakevdp** [comment] 2022-06-29 16:55
This has been fixed

**Closed by jakevdp** 2022-06-29 16:55 UTC
Labels: bug, duplicate
