### ISSUE TITLE
Capturing gradients with respect to intermediate activations

### ISSUE THREAD

**Issue by jpuigcerver** [google/jax#6668] opened 2021-05-06 17:47 UTC
Hi!

I'm trying to access gradients of a loss with respect to intermediate activations from a Linen module. 

For that, I created a function that wraps the call to a given function with a custom backward function (using `jax.custom_vjp`), that uses `jax.experimental.host_callback.id_tap` to add the gradients to a list.

```python
def with_gradient_log(func):

  log = []

  def tap_func(args, transforms):
    log.append(args)
    return args  

  @jax.custom_vjp
  def f(*args):
    return func(*args)

  def f_fwd(*args):
    return jax.vjp(func, *args)

  def f_bwd(vjp_fun, input_cotangents):
    out_cotangents = vjp_fun(input_cotangents)
    return host_callback.id_tap(tap_func, out_cotangents)

  f.defvjp(f_fwd, f_bwd)
  return f, log
```

Then, I use this function to wrap the call to the module whose gradients I need to track:

```python
class A(nn.Module):

  @nn.compact
  def __call__(self, inputs):
    x = nn.Dense(features=32, name='dense1')(inputs)
    dense2 = nn.Dense(features=2, name='dense2')
    fn, log = with_gradient_log(dense2)
    y = fn(x)
    return y, log
```

However, when I try to use `jax.value_and_grad`, I get the following exception:
```
NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-b480e1302bb6> in <module>()
     21   return -jnp.sum(logits * jax.nn.one_hot(y, 2)), log
     22 
---> 23 (loss, log), grad = jax.value_and_grad(loss_fn, has_aux=True)(variables)

/usr/local/lib/python3.7/dist-packages/jax/_src/traceback_util.py in reraise_with_filtered_traceback(*args, **kwargs)
    169 
    170             # Fallback case for older jaxlibs; includes the current frame.
--> 171             raise e.with_traceback(filtered_tb)
    172         finally:
    173           del filtered_tb

<ipython-input-3-b480e1302bb6> in loss_fn(variables)
     16 
     17 def loss_fn(variables):
---> 18   logits, log = a.apply(variables, x)
     19   logits = jax.nn.log_softmax(logits)
     20   y = jax.nn.one_hot(y, 2)

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in apply(self, variables, rngs, method, mutable, capture_intermediates, *args, **kwargs)
    937         method, self,
    938         mutable=mutable, capture_intermediates=capture_intermediates
--> 939     )(variables, *args, **kwargs, rngs=rngs)
    940 
    941   def init_with_output(self,

/usr/local/lib/python3.7/dist-packages/flax/core/scope.py in wrapper(variables, rngs, *args, **kwargs)
    685               **kwargs) -> Union[Any, Tuple[Any, VariableDict]]:
    686     with bind(variables, rngs=rngs, mutable=mutable).temporary() as root:
--> 687       y = fn(root, *args, **kwargs)
    688     if mutable is not False:
    689       return y, root.mutable_variables()

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in scope_fn(scope, *args, **kwargs)
   1176     _context.capture_stack.append(capture_intermediates)
   1177     try:
-> 1178       return fn(module.clone(parent=scope), *args, **kwargs)
   1179     finally:
   1180       _context.capture_stack.pop()

/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in wrapped_module_method(*args, **kwargs)
    273     _context.module_stack.append(self)
    274     try:
--> 275       y = fun(self, *args, **kwargs)
    276       if _context.capture_stack:
    277         filter_fn = _context.capture_stack[-1]

<ipython-input-3-b480e1302bb6> in __call__(self, inputs)
      6     dense2 = nn.Dense(features=2, name='dense2')
      7     fn, log = with_gradient_log(dense2)
----> 8     y = fn(x)
      9     return y, log
     10 

NotImplementedError: Differentiation rule for 'custom_lin' not implemented
```

The [following colab](https://colab.research.google.com/drive/12jei-0I4036p-Yd3mjQc7G27GFaJyrem?usp=sharing) includes things that I've tried:
A) The previous example.
B) Not tracking the gradients (i.e. not using id_tap), simply wrapping the function's fwd/bwd. Produces the same exception.
C) Instead of wrapping the call to the FLAX module, I wrap a lambda implementing the identity function. 
```python
x = ...
lin, log = with_gradient_log(lambda x: x)
return dense2(lin(x)), log
```
This doesn't cause an exception, but the `log` list is empty even after computing gradients.

**Comment by mattjj** [comment] 2024-07-24 03:58
Thanks for the question! Please see [this thread](https://github.com/google/jax/discussions/5336#discussioncomment-269983). There are a few others, like [this one](https://github.com/google/flax/discussions/1152). Someday we'll make this more ergonomic, but for now I think we should link to those standard methods and close this issue (lest we lose track of it again, as we did for the past... 3 years).

**Closed by mattjj** 2024-07-24 03:58 UTC
Labels: bug

**Comment by rivershah** [comment] 2025-06-07 14:11
@mattjj Thanks so much for the links and I have tried to get some insight from but I am still struggling.

I have ported over most code from `keras` using `tensorflow` to `jax` backend. In the `keras with tensorflow` based layer I am doing something like:

```
class GradientLayer(Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, inputs, response):
        g = tf.gradients(response, inputs, unconnected_gradients="zero")

        return g
```

How can I do something similar using `jax` please without radical refactors in my code. Is there any grad tracers for `jax` such that when `jax.jit` is called on my `keras` model / callable, I can grab the gradients like I currently do in the layer with `tensorflow`?

The `flax` perturb api is interesting but I am unsure how I proceed for the `keras` case. Thanks for any guidance; apologies as the issue is closed but still think this most appropriate to post here.
