### ISSUE TITLE
Behavior-documentation inconsistency for `jax.numpy.linalg.cholesky`

### ISSUE THREAD

**Issue by yhtang** [google/jax#12516] opened 2022-09-26 18:40 UTC
### Description

The [docstring](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.cholesky.html) for `jax.numpy.linalg.cholesky` seems to be copied from its [NumPy counterpart](https://numpy.org/doc/stable/reference/generated/numpy.linalg.cholesky.html), where it states:
> ... No checking is performed to verify whether a is Hermitian or not. ...

However, the [actual implementation](https://github.com/google/jax/blob/e034432872545c68c91f598e84c20ffd4c7c6cea/jax/_src/lax/linalg.py#L104) in `jax/_src/lax/linalg.py` does indeed always symmetrize the input matrix. Its argument `symmetrize_input`, which controls whether symmetrization happens, defaults to `True` and is **not** exposed to the end user.

IMHO this has two consequences:
1. Users can be misled and confused by the behavior of the method.
2. Symmetrization may introduce unnecessary overhead when the input matrix is already Hermitian.

### What jax/jaxlib version are you using?

upstream

**Comment by mattjj** [comment] 2022-09-26 19:00
Thanks for bringing this up! Actually, I think you're raising a few questions:
* whether the `jnp.linalg.cholesky` implementation is consistent with its docstring;
* whether `symmetrize_input` is exposed to the end user;
* whether there's some confusing behavior that can result from the current implementation;
* whether there's unnecessary overhead.

IIUC, the implementation is consistent with the docstring (many jax.numpy docstrings are at runtime dynamically populated from the numpy module); the jax.numpy.cholesky implementation does not do any checking to verify if the input is (already) Hermitian. Instead of checking, it always does a projection onto the symmetric matrices!

The `symmetrize_input` option [is exposed in the `jax.lax.linalg.cholesky` function](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.linalg.cholesky.html). Our general policy is to make the `jax.numpy` functions track very closely to their `numpy` counterparts, usually not changing their signature (e.g. by adding arguments), with good defaults. In this case, we didn't add the `symmetrize_input` argument at the `jax.numpy.linalg` level and instead set it to `True` because we think that's a good default for automatic differentiation purposes; see e.g. [this discussion](https://github.com/google/jax/issues/10815). With any choice of defaults, it's important for the user to be able to override them as needed. That's how we intend lower-level functions, in this case like `jax.lax.linalg.cholesky`, to be used.

For overheads, I'm not sure how often those will matter in practice (since the overhead is like O(N^2) compared to Cholesky's O(N^3). But I'm sure there are regimes where that behavior is undesirable.

Other than performance overhead, is there some other kind of user confusion you had in mind?

Given all that, I can think of at least two courses of action:
1. add a mention of `jax.lax.linalg.cholesky` in the `jax.numpy.linalg.cholesky` docstring, and/or
2. add the `symmetrize_input` to the `jax.numpy.linalg.cholesky` function.

I don't think removing the default of `symmetrize_input=True` from `jax.numpy.linalg.cholesky` is a viable option though.

WDYT? Any other options we should consider?

**Comment by yhtang** [comment] 2022-09-26 19:46
Hi Matthew, many thanks for your explanations! That is very helpful.

I agree that the behavior is not strictly-speaking going against the docstring, but I think more clarification would be even better. When I first read the docstring, my mind automatically (although incorrectly) assumed that the method might not either check or fix any asymmetries in the input matrix. Having the matrix automatically symmetrized then turned out to be a surprise for me. As you have pointed out, perhaps we could modify the docstring to say something like:
> ... No checking is performed to verify whether a is Hermitian or not. Rather, the input matrix will be automatically symmetrized by averaging with its conjugate tranpose. To explicit control whether symmetrization happens, please use the lower-level method `jax.lax.linalg.cholesky` ...

Performance-wise, the transposition/symmetrization operation is quadratic in cost but memory-bound. This is only in theory so I can't say without doing experiments if this will matter in a practical scenario. But at least having an option to turn symmetrization on or off (as `lax.linalg.cholesky` already does) would be great.

What do you think?

**Comment by jakevdp** [comment] 2023-11-03 18:21
Closing as a duplicate of #9473

**Closed by jakevdp** 2023-11-03 18:21 UTC
Labels: bug
