### ISSUE TITLE
Float16 behavior affect by jax_enable_x64

### ISSUE THREAD

**Issue by coreyjadams** [google/jax#12145] opened 2022-08-29 15:50 UTC
### Description

When the flag for float 64 enabling is ON, the behavior of float16 operations changes - unexpectedly, in at least one case.  Here is a function that reproduces:

```python
def multi_uniform_slow(_keys, shape, dtype):
    out_uniform = []
    for _k in _keys:
        _uniform = random.uniform(_k, shape=shape, dtype=dtype)
        out_uniform.append(_uniform)
    return numpy.stack(out_uniform)
```

That is a slower version of something like this, vmap'ing the random.normal function:
```python
@partial(jit, static_argnums=(1,2))
def multi_uniform(keys, shape, dtype):
    l = jit(vmap(lambda x : random.uniform(x, shape=shape, dtype=dtype)))
    return l(keys)
```

I discovered this bug because I wrote a unit test for the "real" function above (`multi_uniform`) that looks like this:
```python
@pytest.mark.parametrize("n_keys", [10])
@pytest.mark.parametrize("dtype", [numpy.float64,numpy.float32,numpy.float16, numpy.bfloat16])
def test_multi_uniform(n_keys, seed, dtype):

    key = random.PRNGKey(int(seed))

    shape = ()

    def multi_uniform_slow(_keys, shape, dtype):
        out_uniform = []
        for _k in _keys:
            _uniform = random.uniform(_k, shape=shape, dtype=dtype)
            out_uniform.append(_uniform)
            print(_uniform)
        return numpy.stack(out_uniform)

    multikeys = random.split(key, n_keys)

    slow_uniform = multi_uniform_slow(multikeys, shape, dtype)

    fast_uniform = multi_uniform(multikeys, shape, dtype)

    assert (slow_uniform == fast_uniform).all()
```

This unit test passes for fp16 when fp64 enabling is OFF.  It fails for fp16 when fp64 enabling is ON.  The uniform function returns all 0s when used in the "slow" version in the case that fp64 is ON, though notably they JIT'd function returns sensible (but unchecked by unit testing) values.

Expected behavior: fp64 flags shouldn't affect fp16 operations.

### What jax/jaxlib version are you using?

jax 0.3.15, jaxlib 0.3.15

### Which accelerator(s) are you using?

CPU

### Additional System Info

Mac OSX

**Comment by coreyjadams** [comment] 2022-08-29 15:50
Oh, one other point of data: the `random.normal` function is NOT affected by this.  I have not tested any other random generators.

**Comment by jakevdp** [comment] 2022-08-29 16:26
What is `numpy` in this code snippet?

**Comment by coreyjadams** [comment] 2022-08-29 16:43
Yes, sorry, that's a pretty important piece of information I left out.... `numpy` is `jax.numpy` exclusively here.

Here's a standalone reproducer that fails on my mac for fp16 only.  If I remove line 23 (`from jax.config import config; config.update("jax_enable_x64", True")` if fails.

https://gist.github.com/coreyjadams/c6bf63ab52154988fd343f20bec4563c

I went ahead and tested on nvidia A100 and the failure is not present on GPU; perhaps isolated to CPU.  On GPU, jax and jaxlib were both 0.3.15

**Comment by jakevdp** [comment] 2022-08-29 16:48
Thanks for the info. For future reference, it would be more helpful if you could edit your initial post to add a complete example rather than linking to an external example.

**Comment by jakevdp** [comment] 2022-08-29 17:25
Here's a reproduction that narrows-in on the core issue here:
```python
import jax

key = jax.random.PRNGKey(0)

for dtype in ['float16', 'float32']:
  print("dtype =", dtype)
  with jax.experimental.enable_x64(True):
    print("  x64=True: ", jax.random.uniform(key, (), dtype))
  with jax.experimental.enable_x64(False):
    print("  x64=False:", jax.random.uniform(key, (), dtype))
```
```
dtype = float16
  x64=True:  0.0
  x64=False: 0.004883
dtype = float32
  x64=True:  0.41845703
  x64=False: 0.41845703
```
Assigning to @froystig because he's been working on PRNG stuff lately, and this issue does not reproduce with the most recent release of JAX

**Comment by rajasekharporeddy** [comment] 2024-02-28 18:04
Hi @coreyjadams 

Looks like this issue has been resolved. I executed the minimal reproducer provided by @jakevdp on colab CPU with JAX version 0.4.23. It resulted the expected (same) output with and without the `x64` enabled for `float16` also.

```python
import jax
print(f"JAX versioin: {jax.__version__}")

key = jax.random.PRNGKey(0)

for dtype in ['float16', 'float32']:
  print("dtype =", dtype)
  with jax.experimental.enable_x64(True):
    print("  x64=True: ", jax.random.uniform(key, (), dtype))
  with jax.experimental.enable_x64(False):
    print("  x64=False:", jax.random.uniform(key, (), dtype))
```

Output:

```
JAX versioin: 0.4.23
dtype = float16
  x64=True:  0.004883
  x64=False: 0.004883
dtype = float32
  x64=True:  0.41845703
  x64=False: 0.41845703
```
Attaching the [gist](https://colab.research.google.com/gist/rajasekharporeddy/d44b76946ace58a9fb5a42672566ded8/-12145.ipynb) for reference. Also verified its behavior on mac with JAX version 0.4.25 and it produced the same result for `float16` with both `x64 = True` and `x64=False`. Please find the screenshot on mac.
<img width="1286" alt="image" src="https://github.com/google/jax/assets/153593711/d60b36ea-2ace-4fbf-85aa-237bb4563738">

Could you please verify with the latest JAX versions and let us know if the issue still persists.

Thank you

**Comment by jakevdp** [comment] 2024-02-28 18:58
Thanks for following up!

**Closed by jakevdp** 2024-02-28 18:58 UTC
Labels: bug

**Comment by coreyjadams** [comment] 2024-03-07 16:53
Thanks for following up, looks like it is working for me too!
