### ISSUE TITLE
guidance on how to properly use lax.reduce on an multi-dimension array.

### ISSUE THREAD

**Issue by linzzzzzz** [google/jax#22320] opened 2024-07-08 16:32 UTC
I want to perform reduce operation on an array in a slightly different way than `jnp.argmax`.

I have an array `A` with shape `(2,5)`. I wanted to reduce `A` in the below way: for a pair of index `(i, j)`, calculate `z = A[0][i]*A[1][j]-A[0][j]*A[1][i]`, if `z>0`, then pick `i` otherwise pick `j`. Continue this computation until getting the final index. 

What's the best way for me to perform this in JAX?

Below is my code on trying to implement this reduce operation, which threw error `IndexError: Too many indices for array: 1 non-None/Ellipsis indices for dim 0.`.

```
A = np.random.randn(2, 5)

def my_compare(x0, x1):
    y0 = x0[0]*x1[1]
    y1 = x0[1]*x1[0]
    z = y0 > y1
    return jax.lax.select(z, x0, x1)

res = jax.lax.reduce(A, A[0][0], my_compare, [0,1])

```

**Comment by jakevdp** [comment] 2024-07-08 16:56
This looks to be a duplicate of #22319 – I'm going to close this one because the discussion format is probably better for this question!

**Closed by jakevdp** 2024-07-08 16:56 UTC
Labels: enhancement
