### ISSUE TITLE
jax.numpy.argmin/jax.numpy.argmax fail with nans

### ISSUE THREAD

**Issue by danielsuo** [google/jax#3193] opened 2020-05-23 21:55 UTC
Noticed odd behavior (colab [repro](https://colab.research.google.com/drive/1ZDiyjfyyK8CGgPfVwFUw2q9SRjqWhYkP?authuser=1#scrollTo=j7MRVZFShYP7)) and was about to fix/submit a PR when I saw [this](https://github.com/google/jax/blob/master/jax/numpy/lax_numpy.py#L2986) comment:

> `# TODO(mattjj): redo this lowering with a call to variadic lax.reduce`

Wasn't sure what @mattjj had in mind, but happy to have a look at that as well.

**Comment by jakevdp** [comment] 2020-05-24 14:35
I get a notebook load error when l click on your repro link. Can you paste a short repro into this issue?

**Comment by danielsuo** [comment] 2020-05-25 15:03
Ah, terrible! For some reason, I keep getting auth errors now. I'll just paste here:

```python
import jax.numpy as jnp
import numpy as np

nans = {
    "all": jnp.array([jnp.nan] * 100),
    "pre": jnp.array([jnp.nan] * 50 + [0] * 50),
    "post": jnp.array([0] * 50 + [jnp.nan] * 50)
}

for key, nan in nans.items():
  print("jnp.argmin({}):".format(key), jnp.argmin(nan))
  print("jnp.argmax({}):".format(key), jnp.argmax(nan))
  print("np.argmin({}):".format(key), np.argmin(nan))
  print("np.argmax({}):".format(key), np.argmax(nan))
```

And output:

```bash
jnp.argmin(all): 2147483647
jnp.argmax(all): 2147483647
np.argmin(all): 0
np.argmax(all): 0
jnp.argmin(pre): 2147483647
jnp.argmax(pre): 2147483647
np.argmin(pre): 0
np.argmax(pre): 0
jnp.argmin(post): 2147483647
jnp.argmax(post): 2147483647
np.argmin(post): 50
np.argmax(post): 50
```

**Comment by jakevdp** [comment] 2020-05-26 16:29
Thanks - I think a fix to this without addressing the TODO would be valuable. Feel free to submit the PR, or let us know if you're not able to tackle this right now.

**Comment by hawkinsp** [comment] 2020-05-26 20:30
I think the thought was that we could use this approach:
https://github.com/tensorflow/tensorflow/blob/e7cc47384f4d57cc04ec550dbc2c08e467e42a4a/tensorflow/compiler/xla/client/lib/arithmetic.cc#L143

(i.e., a one-pass algorithm using a variadic `Reduce`)

**Comment by hawkinsp** [comment] 2020-05-27 13:31
Although I'm wondering if this is even a bug. As far as I can tell, NumPy doesn't define its semantics for NaNs, and it's not clear what they should be, given that NaNs aren't ordered with respect to non-NaNs.

Note numpy and JAX both have `np.nanargmin` which does define semantics in the presence of NaN values.

**Comment by danielsuo** [comment] 2020-05-27 13:34
Yeah, after I started looking into the scope of a PR / all the variations on `min`/`max`, it wasn't clear to me that this is an issue besides not matching (apparent) `numpy` behavior.

Let me know what you guys want to do since this now seems more a judgement call.

**Comment by hawkinsp** [comment] 2020-05-27 13:49
Unless we can think of a good reason to mimic NumPy's behavior (e.g., it is well-motivated and folks are likely to care about the behavior in this case), I think we can consider this working as intended.

**Comment by Baschdl** [comment] 2021-05-27 11:53
> Although I'm wondering if this is even a bug. As far as I can tell, NumPy doesn't define its semantics for NaNs, and it's not clear what they should be, given that NaNs aren't ordered with respect to non-NaNs.

Having `jnp.argmin` return an index which is out of bounds of the original array feels like a bug for me. Especially as it probably results in an `IndexError` in most cases. A `ValueError` (with a hint to `np.nanargmin`) would probably be more what a user would expect.

**Comment by jakevdp** [comment] 2021-05-27 16:32
Hi @Baschdl – I think the issue has been fixed. In the current version of JAX, the output of the script above is the following:
```
jnp.argmin(all): 0
jnp.argmax(all): 0
np.argmin(all): 0
np.argmax(all): 0
jnp.argmin(pre): 0
jnp.argmax(pre): 0
np.argmin(pre): 0
np.argmax(pre): 0
jnp.argmin(post): 50
jnp.argmax(post): 50
np.argmin(post): 50
np.argmax(post): 50
```

**Comment by Baschdl** [comment] 2021-05-31 23:49
It's still happening for me with version 0.2.13 (Python 3.7.4, jaxlib 0.1.67+cuda110):
```
import jax
jax.__version__
## '0.2.13'
import jax.numpy as jnp
jnp.argmin(jnp.array([0, float('nan'), 1]))
## DeviceArray(2147483647, dtype=int32)
```

**Comment by jakevdp** [comment] 2021-06-01 00:25
Thanks - looks like it's only a problem on GPU, not on CPU or TPU. This suggests it may be an XLA issue.

**Comment by hawkinsp** [comment] 2021-06-01 13:32
I think this was already fixed by https://github.com/google/jax/pull/6764 . That PR isn't in a `jax` release yet, though, so to see the fix you'd need to use `jax` from Github head.

(This both was and was not an XLA issue. It's an XLA issue that GPU acts differently, because XLA/GPU lacks support for variadic reductions, forcing us to use a different code path on GPU. The fallback path handling NaNs differently was a JAX issue.)

**Closed by hawkinsp** 2021-06-01 13:32 UTC
Labels: xla_issue
