### ISSUE TITLE
No tools in profiler

### ISSUE THREAD

**Issue by tancik** [google/jax#4427] opened 2020-09-30 21:33 UTC
Ever since I upgraded jax, the profiler no longer works for me. It is able to capture a trace but there are no tools to investigate the trace.

![image](https://user-images.githubusercontent.com/3310961/94741785-8384e800-0329-11eb-895e-4f5d73499f47.png)

I start the profiler with:
```
import jax.profiler
server = jax.profiler.start_server(9999)
```

jax - 0.2.0
jaxlib - 0.1.55
tensorboard - 2.3.0
tensorboard-plugin-profile - 2.3.0

**Comment by DannyKong12** [comment] 2020-10-06 14:37
I can confirm this happens with latest tensorboard as well as v2.2.0

**Comment by DannyKong12** [comment] 2020-10-06 15:04
Downgrading back to jax==0.1.75 and jaxlib==0.1.52 everything works as expected. Tools dropdown has (5) options including trace_viewer. Any idea on what the timeline is for bringing tensorboard support back/anything we can do to help?

**Comment by tancik** [comment] 2020-10-07 04:21
Interesting, I downgraded back to jax==0.1.75 and jaxlib==0.1.52 and I still have zero tools available.

**Comment by DannyKong12** [comment] 2020-10-07 08:18
I had to capture profile again, but the same code works as expected on 0.1.75 for me. Checking the logdir directory I also see different files, certain files are just not produced after upgrading.

**Comment by shoyer** [comment] 2020-10-21 20:37
@tfrerix is struggling with the same issue here

**Comment by zhangqiaorjc** [comment] 2020-10-22 00:39
I'm able to repro this issue. I may have found a root cause. This may require a fix from tensorflow/profiler folks.

**Comment by AnimatedRNG** [comment] 2020-10-22 00:41
I also ran into this issue with the latest jax/jaxlib; downgrading to jax==0.1.75 and jaxlib==0.1.52 (CUDA 10.1; cuDNN 7.6.5) and capturing a new profile fixed things on my end

**Comment by qiuminxu** [comment] 2020-10-22 01:30
Profiler recently moved the data processing from TensorFlow data collection side into the TensorBoard. Data collection will generate a single .xplane.pb file, and TensorBoard will process and visualize the trace. These all lands in the recent nightly, the reported issue is caused by old version of profile plugin not able to visualize the new .xplane.pb format.

Can you try: `pip3 install -U tf-nightly tbp-nightly` and see if this works?

**Comment by zhangqiaorjc** [comment] 2020-10-27 23:38
I just verified that by upgrading tf-nightly to 2.5.0-dev20201027, you will get a backwards compatible profiler client that handles existing jaxlib versions.

Could people try `pip3 install -U tf-nightly`? 

Note that tf-nightly on mac isn't yet at 2.5.0-dev20201027.

**Comment by hawkinsp** [comment] 2020-11-13 02:49
@zhangqiaorjc can we close this bug now a new jaxlib has been released?

**Comment by zhangqiaorjc** [comment] 2020-11-20 18:38
I just tried this again on my Linux workstation. It does seem to work.

tb-nightly                    2.4.0a20201027
tbp-nightly                   2.4.0a20201027
tensorboard-plugin-wit        1.7.0
tf-nightly                    2.5.0.dev20201028

<img width="1257" alt="Screen Shot 2020-11-20 at 10 29 17 AM" src="https://user-images.githubusercontent.com/328992/99837454-75c73400-2b1c-11eb-8bac-cd1ed3ee4299.png">

**Closed** 2020-11-20 18:38 UTC
