### ISSUE TITLE
jax.numpy autocomplete not working in vscode cause of PEP 561 problems

### ISSUE THREAD

**Issue by machineko** [google/jax#7762] opened 2021-08-30 19:31 UTC
More about this in -> https://github.com/microsoft/pylance-release/issues/1737#issuecomment-908574952

vscode autocompletion
![131223662-3ce951c3-9b59-41d9-b617-6f3a010bedfe](https://user-images.githubusercontent.com/42299606/131394457-106902a0-8665-4e68-bc72-645b0ecf1d07.png)

**Comment by jakevdp** [comment] 2021-08-30 19:33
Possible duplicate of #7570?

**Closed** 2021-08-30 19:35 UTC
Labels: bug
