### ISSUE TITLE
No implicit conversions from *int4 to int8

### ISSUE THREAD

**Issue by jewillco** [google/jax#16704] opened 2023-07-13 04:32 UTC
### Description

When JAX's `int4` support is enabled, there are no implicit conversions from `int4` and `uint4` to larger integer types. There are conversions defined for `i4` and `u4` and those are explicitly removed for `int4` and `uint4`.

**Comment by jakevdp** [comment] 2023-07-13 13:34
Hi - thanks for the report. This is the expected behavior: the idea is that if you are working with `int4`, you are doing it quite intentionally, and implicit casting would be surprising. If you want the values to be cast for an operation, you can do it explicitly with e.g. `arr.astype('int8')`.

**Comment by jakevdp** [comment] 2023-11-03 20:54
I'm going to close this, because I don't think there are plans to add implicit conversion for 4-bit integers.

**Closed by jakevdp** 2023-11-03 20:54 UTC
Labels: question
