### ISSUE TITLE
BCOO.todense() fails for bool data

### ISSUE THREAD

**Issue by terryykoo** [google/jax#18427] opened 2023-11-07 19:57 UTC
### Description

Calling BCOO.todense() fails if the matrix contains bool data.  I have a repro here:
cl/580254220
sponge/18981f47-17fc-4291-83d4-36eb1f06112d

The error is

TypeError: add does not accept dtype bool at position 0. Accepted dtypes at position 0 are subtypes of integer, complexfloating, floating.

you can see the full stack trace at the sponge link or re-run the test yourself.

### What jax/jaxlib version are you using?

jax v0.4.21 (//third_party/py/jax)

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10.13

**Comment by jakevdp** [comment] 2023-11-07 20:18
Thanks for the report – BCOO was designed for numerical data.

If you're using it for boolean data, what semantics would you expect in the case of duplicate indices?

**Comment by jakevdp** [comment] 2023-11-07 20:20
I think we'll probably not fix this (we're not planning to put more development effort into BCOO) but I think the best workaround would be to store your data in `uint8` rather than `boolean` format, and then cast to bool when needed. Since bools are backed by 8-bit buffers, this will not require much overhead.

**Comment by terryykoo** [comment] 2023-11-08 01:45
For my use case, I can take responsibility for avoiding duplicate indices.

If you need an answer, I see that for numeric types duplicate indices are handled by summing the corresponding data.  I think the closest analogue for addition with booleans is to OR them---for example, the boolean semiring defines `+` as OR and `x` as AND.

Just checking, if I use `uint8` and cast to `bool`, are they able to share space?  Or is it just the path of least overhead given that I'll end up with two dense arrays.

**Comment by jakevdp** [comment] 2023-11-08 02:28
Casting from uint8 to bool will invoke a copy, but since you're concerned with converting to dense I didn't think a copy of the sparse buffer would be all that significant.

**Comment by hawkinsp** [comment] 2023-11-20 16:06
Seems like the resolution is "won't fix".

**Closed** 2023-11-20 16:06 UTC
Labels: bug, wontfix
