### ISSUE TITLE
Tracing error when using cumsum inside xla.lower_fun

### ISSUE THREAD

**Issue by ekelsen** [google/jax#2820] opened 2020-04-24 13:29 UTC
Repro:

```import jax.numpy as jnp
from jax import api
from jax import core
from jax import abstract_arrays
import jax.ops as jops
from jax import xla

v = jnp.reshape(jnp.array([1, 0, -1], dtype=jnp.float32), [3, 1])

a = jnp.array([0, 2, 2, 0, 1, 2], dtype=jnp.int32)
b = jnp.array([0, 2, 3, 6], dtype=jnp.int32)

repro_p = core.Primitive("repro")

def repro_prim(v, a, b):
  return repro_p.bind(v, a=a, b=b)
  
def repro_abstract_eval(v, a, b):
  out_m = a.shape[0]
  return abstract_arrays.ShapedArray( (out_m, ), dtype=v.dtype)

repro_p.def_abstract_eval(repro_abstract_eval)

def _get_foo(a, b):
  foo = jops.index_update(jnp.zeros_like(a), b, jnp.ones(b.shape[0]))
  return jnp.cumsum(foo)

def repro_translation(c, v, a, b):
  foo = xla.lower_fun(_get_foo)(c, a=a, b=b)
  return foo

xla.translations[repro_p] = repro_translation

api.jit(repro_prim)(v, a, b)
```

Error is:

```UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
The functions being transformed should not save traced values to global state.
Details: Tracer from a higher level: Traced<AbstractUnit():JaxprTrace(level=-1/2)> in trace JaxprTrace(level=-1/2).
```

**Comment by mattjj** [comment] 2020-04-26 18:49
The issue is setting up `a` and `b` as primitive parameters here (by passing them as kwargs, which is our convention for separating value-level inputs from metadata-like parameters):

```python
  return repro_p.bind(v, a=a, b=b)
```

That's inconsistent with treating `a` and `b` as values, e.g. when you write `api.jit(repro_prim)(v, a, b)`.

This runs:

```python
import jax.numpy as jnp
from jax import api
from jax import core
from jax import abstract_arrays
import jax.ops as jops
from jax import xla

v = jnp.reshape(jnp.array([1, 0, -1], dtype=jnp.float32), [3, 1])

a = jnp.array([0, 2, 2, 0, 1, 2], dtype=jnp.int32)
b = jnp.array([0, 2, 3, 6], dtype=jnp.int32)

repro_p = core.Primitive("repro")

def repro_prim(v, a, b):
  return repro_p.bind(v, a, b)  # changed!

def repro_abstract_eval(v, a, b):
  out_m = a.shape[0]
  return abstract_arrays.ShapedArray( (out_m, ), dtype=v.dtype)

repro_p.def_abstract_eval(repro_abstract_eval)

def _get_foo(a, b):
  foo = jops.index_update(jnp.zeros_like(a), b, jnp.ones(b.shape[0]))
  return jnp.cumsum(foo)

def repro_translation(c, v, a, b):
  foo = xla.lower_fun(_get_foo)(c, a, b)  # changed!
  return foo

xla.translations[repro_p] = repro_translation

api.jit(repro_prim)(v, a, b)
```

**Comment by mattjj** [comment] 2020-04-26 18:50
I think we've got this sorted, so in the spirit of minimizing our active issues, I'm going to close this.

**Closed by mattjj** 2020-04-26 18:50 UTC
Labels: question

**Comment by mattjj** [comment] 2020-04-26 18:52
You should think of primitive params, which are identified by being passed via keyword arguments to Primitive.bind, as things like strings (e.g. "VALID" or "SAME") or shapes (e.g. (2, 3)) which can be construed of as part of the primitive's name or in some cases type-level arguments. Things that are array-like tend to be value-level arguments and must be passed to `Primitive.bind` as positional arguments (by the same convention).
