### ISSUE TITLE
`jax.config.update("jax_enable_x64", True); jnp.array(..., dtype=int)` produces 32-bit instead of 64-bit result on Windows

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#9574] opened 2022-02-15 15:02 UTC
So I realise Windows isn't properly supported. I'm raising this really just so that something is availble if people search for it, or as a bug to fix when/if Windows support ever happens.

This:
```python
import jax
jax.config.update("jax_enable_x64", True)
jax.numpy.array(1, dtype=int)
```
produces an `int64` array on Linux but an `int32` array on Windows. I'm assuming the Linux behaviour is the correct one.

(I'm using jaxlib built from https://github.com/cloudhan/jax-windows-builder; in https://github.com/patrick-kidger/diffrax/issues/67 a user reports the same behaviour when building jaxlib from source.)

**Comment by hawkinsp** [comment] 2022-02-15 15:25
Not having access to a Windows box, are you sure that `np.array(1, dtype=int)` does not do the same?

**Comment by patrick-kidger** [comment] 2022-02-15 15:39
NumPy has the same Windows->int32; Linux->int64 behaviour. e.g. https://github.com/numpy/numpy/issues/17640 discusses this. It looks like `dtype=int` gives a C `long` which is 32-bit on Windows and 64-bit everywhere else. (And that maybe they'd like to change this behaviour at some point?)

JAX already handles dtypes differently to NumPy (a la  the existence of `JAX_ENABLE_X64`) though of course.

**Comment by jakevdp** [comment] 2022-02-15 16:59
JAX currently uses NumPy's dtype system, so when faced with `dtype=int`, it employs numpy's dtype constructor to convert it to a dtype object. I believe this is why its behavior is the same as NumPy for this case.

**Comment by dhirschfeld** [comment] 2022-02-15 23:10
Isn't using `dtype=int` a code-smell on *any* platform? I think it's recommended to be explicit - e.g. `dtype=np.int64`.

i.e. code should never be using `dtype=int` so there's nothing to fix here... unless it's used internally in `jax`?

**Comment by Micky774** [comment] 2024-05-02 18:17
Ultimately this is an issue with the semantics of ctypes (in particular, Windows vs Linux `long`), but **within the scope of JAX**, this behavior is consistent with expectations in the ecosystem, and in general `dtype=int` is an anti-pattern that should be avoided whenever possible. I'm going to go ahead and close this as intended behavior.

**Closed by Micky774** 2024-05-02 18:17 UTC
Labels: bug, Windows
