### ISSUE TITLE
Impossible to have static kwargs with vmap

### ISSUE THREAD

**Issue by Conchylicultor** [google/jax#5617] opened 2021-02-03 18:01 UTC
It doesn't seems possible to forward static kwargs when a function is wrapped with vmap.

```python
@jax.vmap
def f(x, y, **kwarg):
  return jax.scipy.ndimage.map_coordinates(x, y, **kwarg)

f(x, y, order=1)  #TypeError: batched_fun() got an unexpected keyword argument 'order'
```

`jax.vmap` doesn't seems to have an `excluded =` (like in `jnp.vectorize`), or `static_argnums=`, or similar.

Currently, the only solution is to wrap the function is some higher function, like:

```python
def f(x, y, **kwarg):
  f_inner = functools.partial(jax.scipy.ndimage.map_coordinates, **kwargs)
  f_inner = jax.vmap(f_inner)
  return f_inner(y, y)

f(x, y, order=1)  # works
```

**Comment by jakevdp** [comment] 2021-02-03 18:49
You're correct that static keyword arguments are not supported in `vmap`. The recommended approach is to use closeres along the lines of your second example, or if you want something more compact:
```python
f = jax.vmap(lambda x, y: jax.scipy.ndimage.map_coordinates(x, y, order=1))
f(x, y)
```

**Comment by froystig** [comment] 2021-02-06 02:12
If the notion of "static" here means "do not map", as the example suggests, then there is an analogue of `static_argnums`: it is the presence of `None` in the corresponding position among `in_axes`.

A remaining issue is that keyword arguments can be supplied by callers in varying order or not at all. When applying `vmap` before knowing how the result will be called, as in this example, one cannot set up a position-based `in_axes` spec that aligns with calls downstream.

It might make sense to extend the `in_axes` spec to better support keyword arguments somehow. #1936 has related discussion in the context of `jit`. I'm closing this since it is working as intended, but please feel free to reopen with a more specific feature request, especially if it differs from the discussion in the linked issue.

**Closed by froystig** 2021-02-06 02:12 UTC

**Comment by jekbradbury** [comment] 2021-02-07 06:36
Does it maybe make sense for keyword arguments to assume in_axes=None?

**Comment by NightMachinary** [comment] 2021-11-25 16:49
I want to `vmap` this function:
```py
def books_next_bytes(rng, index, books_bytes):
  bytes = books_bytes[index]
  return bytes_next(rng, bytes)
```
The `index` is between 0 and the number of classification classes I have, so I want to make it static.
---

```
def books2batch(rng, books_bytes, batch_size):
  k, sk = jrnd.split(rng)
  target = jrnd.randint(sk, (batch_size, ), minval=0, maxval=len(books_bytes))
  
  keys = jrnd.split(k, batch_size)
  input_batch = jax.vmap(books_next_bytes, in_axes=(0, 0, None)) \
    (keys, target, books_bytes)
  
  return input_batch, jax.nn.one_hot(target, len(books_bytes)
```

**Comment by mattjj** [comment] 2021-11-26 23:00
@NightMachinary could you open a new issue?
