### ISSUE TITLE
sparse sparse matmul exhausts memory; even when dense version works fine

### ISSUE THREAD

**Issue by awehrs** [google/jax#18249] opened 2023-10-24 03:25 UTC
### Description

Given two BCOO matrices:
```
a = jax.experimental.sparse.random_bcoo(jax.random.PRNGKey(42), shape=(256, 1024)).astype(jnp.int16)
b = jax.experimental.sparse.random_bcoo(jax.random.PRNGKey(43), shape=(256, 1024)).astype(jnp.int16)
````
Sparse matmul, implemented with the generalized dot operation 

```
jax.experimental.sparse.bcoo_dot_general(a, b, dimension_numbers=(((1,), (1,)), ((), ())))
````
runs out of memory: 

```
XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 175922363761 bytes.
```

Similarly, implementing the matmul by sparsifying (sp?) the infix operator, 

```
jax.experimental.sparse.sparsify(lambda x, y: x @ y.T)(a, b)
```
crashes the interpreter.

Multiplying the dense version of these matrices, with 
```
jax.lax.dot_general(a.todense(), b.todense(), (((1,), (1,)), ((), ())))
```
or, 
```
a.todense() @ b.todense().T
```
goes through just fine (the former is fast, too; kudos). 

Any idea why the sparse version isn't working? Maybe I've constructed the BCOOs improperly (I'm still confused by the n_batch property, so maybe toggling it would help?). 

EDIT: Tried straight up sparse sparse matmul via, 

```
a @ b.T
```
but got, 

```
XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 175922363761 bytes.
```

### What jax/jaxlib version are you using?

jax v0.4.18

### Which accelerator(s) are you using?

CPU 

### Additional system info

python 3.10.13, ubuntu 20.04

**Comment by jakevdp** [comment] 2023-10-24 04:32
Hi - thanks for the report. This is a duplicate of #14642 – there is some discussion of the issue there.

**Comment by awehrs** [comment] 2023-10-24 04:33
Oops. My bad.

**Closed** 2023-10-25 19:44 UTC
Labels: bug
