### ISSUE TITLE
Unexpected JIT error for operations on static arguments

### ISSUE THREAD

**Issue by spenrich** [google/jax#5208] opened 2020-12-16 16:45 UTC
The code below gets through the call to `grid1`, but then throws `jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.` when trying to call `grid2`. In `grid1`, the number of points for `jnp.linspace` is specified explicitly, while in `grid2` it is computed from a few other local constants.

```python
import jax
import jax.numpy as jnp

@jax.jit
def grid1():
    print('re-compiling ...')
    t0, tf, num_steps = 0., 1., 10
    ts = jnp.linspace(t0, tf, num_steps + 1)
    return ts

@jax.jit
def grid2():
    print('re-compiling ...')
    t0, tf, dt = 0., 1., 1e-1
    num_steps = jnp.maximum(jnp.abs((tf - t0)/dt), 1)
    ts = jnp.linspace(t0, tf, num_steps + 1)
    return ts

print(grid1())
print(grid2())
```

A similar error occurs with the following code, where the values passed to `jnp.linspace` are either static arguments or the result of operations on static arguments. According to the docs on `jax.jit` (https://jax.readthedocs.io/en/latest/jax.html#jax.jit), such operations should be "constant-folded in Python (during tracing)", so I'm confused about why an error is happening here as well.

```python
import jax
import jax.numpy as jnp
from functools import partial

@partial(jax.jit, static_argnums=(0,))
def grid3(grid_spec):
    print('re-compiling ...')
    t0, tf, dt = grid_spec
    num_steps = jnp.maximum(jnp.abs((tf - t0)/dt), 1)
    ts = jnp.linspace(t0, tf, num_steps + 1)
    return ts

grid_spec = (0., 1., 1e-1)
print(grid3(grid_spec))
```

Can someone let me know where I'm going wrong here, perhaps in my understanding of `jax.jit`? Thank you!

**Comment by jakevdp** [comment] 2020-12-16 18:29
This is intended behavior: starting in JAX 0.2.0, all `jnp` operations are staged for compilation, even if the inputs are static values (see #3370 for information). Since the size of a `linspace` must be static, the result is this error.

The current recommendation is that if you want values to be computed statically, you should use `numpy` routines rather than `jax.numpy` routines. So, for example, you could change your `grid2` function to look like this:
```python
import numpy as np

@jax.jit
def grid2():
    print('re-compiling ...')
    t0, tf, dt = 0., 1., 1e-1
    num_steps = np.maximum(abs((tf - t0)/dt), 1)
    ts = jnp.linspace(t0, tf, num_steps + 1)
    return ts
```
then it will work as expected.

It may be that the `jax.jit` documentation should be updated to reflect how things work under omnistaging.

**Comment by jakevdp** [comment] 2021-01-13 01:03
I'm going to close this, as the documenation issue here is tracked in #4643. Thanks for the report!

**Closed by jakevdp** 2021-01-13 01:03 UTC
Labels: documentation

**Comment by jecampagne** [comment] 2024-05-17 08:40
Hi, I reopen this thread as with the `grid2` code above using jax '0.4.24'
```python
@jax.jit
def grid2():
    print('re-compiling ...')
    t0, tf, dt = 0., 1., 1e-1
    num_steps = np.maximum(abs((tf - t0)/dt), 1)
    ts = jnp.linspace(t0, tf, num_steps + 1)
    return ts
```
I get


```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[294], line 1
----> 1 grid2()

    [... skipping hidden 12 frame]

Cell In[292], line 6, in grid2()
      4 t0, tf, dt = 0., 1., 1e-1
      5 num_steps = np.maximum(abs((tf - t0)[/](https://jupyterhub.idris.fr/dt)[dt](https://jupyterhub.idris.fr/dt)), 1)
----> 6 ts = jnp.linspace(t0, tf, num_steps + 1)
      7 return ts

File [/gpfslocalsup/pub/anaconda-py3/2023.09/envs/jax-0.4.24](https://jupyterhub.idris.fr/gpfslocalsup/pub/anaconda-py3/2023.09/envs/jax-0.4.24)+py3.11.7+cuda-12.2[/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py:2573](https://jupyterhub.idris.fr/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py#line=2572), in linspace(start, stop, num, endpoint, retstep, dtype, axis)
   2568 @util.implements(np.linspace)
   2569 def linspace(start: ArrayLike, stop: ArrayLike, num: int = 50,
   2570              endpoint: bool = True, retstep: bool = False,
   2571              dtype: DTypeLike | None = None,
   2572              axis: int = 0) -> Array | tuple[Array, Array]:
-> 2573   num = core.concrete_or_error(operator.index, num, "'num' argument of jnp.linspace")
   2574   axis = core.concrete_or_error(operator.index, axis, "'axis' argument of jnp.linspace")
   2575   return _linspace(start, stop, num, endpoint, retstep, dtype, axis)

File [/gpfslocalsup/pub/anaconda-py3/2023.09/envs/jax-0.4.24](https://jupyterhub.idris.fr/gpfslocalsup/pub/anaconda-py3/2023.09/envs/jax-0.4.24)+py3.11.7+cuda-12.2[/lib/python3.11/site-packages/jax/_src/core.py:1529](https://jupyterhub.idris.fr/lib/python3.11/site-packages/jax/_src/core.py#line=1528), in concrete_or_error(force, val, context)
   1527     raise ConcretizationTypeError(val, context)
   1528 else:
-> 1529   return force(val)

TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

**Comment by jakevdp** [comment] 2024-05-17 11:34
Try this:
```python
ts = jnp.linspace(t0, tf, int(num_steps) + 1)
```
