### ISSUE TITLE
JAX CUDA 12 wheel is outdated

### ISSUE THREAD

**Issue by mehdiataei** [google/jax#16412] opened 2023-06-14 16:56 UTC
### Description

I am unable to install the latest version of JAX 0.4.12 through the command:

```
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
Version 0.4.11 is installed instead.

### NVIDIA GPU info

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX 6000 Ada Gener...    Off| 00000000:41:00.0 Off |                  Off |
| 30%   44C    P8               26W / 300W|      6MiB / 49140MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX 6000 Ada Gener...    Off| 00000000:61:00.0 Off |                  Off |
| 30%   39C    P8               22W / 300W|    226MiB / 49140MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1925      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A      1925      G   /usr/lib/xorg/Xorg                          135MiB |
|    1   N/A  N/A      2061      G   /usr/bin/gnome-shell                         52MiB |
+---------------------------------------------------------------------------------------+

**Comment by jakevdp** [comment] 2023-06-15 08:03
Thanks for the report! I think this is a duplicate of #16362.

**Closed by jakevdp** 2023-06-15 08:03 UTC
Labels: bug
