### ISSUE TITLE
 cannot import name 'ShapedArray' from 'jax'

### ISSUE THREAD

**Issue by AliAlhasan2** [google/jax#17286] opened 2023-08-25 08:56 UTC
### Description

Hi, i am working on Poject mipnerf and train to run but i got a problem with jax
ImportError: cannot import name 'ShapedArray' from 'jax' (/home/alhasan.ali/anaconda3/lib/python3.9/site-packages/jax/__init__.py)

### What jax/jaxlib version are you using?

jax 0.4.14

**Comment by hawkinsp** [comment] 2023-08-25 14:56
That's correct: `jax.ShapedArray` was removed from the API in JAX 0.4.14: https://github.com/google/jax/blob/main/CHANGELOG.md#jax-0414-july-27-2023

Which package is using it? Perhaps that package needs an update? If you say more we might be able to help.

**Comment by AliAlhasan2** [comment] 2023-08-25 15:09
i think flax i tried to update but i got Error: AttributeError: module 'flax' has no attribute 'nn'
i use flax=0.5.1 to avoid this Error and this the Error with jax

**Comment by hawkinsp** [comment] 2023-08-25 16:36
I suggest you might need to update the user of `flax`, as well, then.

Closing because JAX is working as intended: you need to update the JAX-using code.

**Closed by hawkinsp** 2023-08-25 16:36 UTC
Labels: bug, needs info

**Comment by HuChen9218** [comment] 2024-03-14 15:56
> That's correct: `jax.ShapedArray` was removed from the API in JAX 0.4.14: https://github.com/google/jax/blob/main/CHANGELOG.md#jax-0414-july-27-2023
> 
> Which package is using it? Perhaps that package needs an update? If you say more we might be able to help.

Jax-cfd is still using it in "jax_cfd\base". And it is using "jnp.DeciveArray" as well.
