### ISSUE TITLE
jax.numpy.linalg.eigh produces different results for full vs triangular matrices 

### ISSUE THREAD

**Issue by deasmhumhna** [google/jax#12687] opened 2022-10-06 20:22 UTC
### Description

```python
import numpy as np
import jax.numpy as jnp 

A = jax.random.normal(jax.random.PRNGKey(0), (100, 100))
H = A + A.T

lam1, y1 = jnp.linalg.eigh(H)
lam2, y2 = jnp.linalg.eigh(jnp.tril(H))
print(jnp.linalg.norm(lam1 - lam2)) # 70.34676

lam1, y1 = jnp.linalg.eigh(H, UPLO="U")
lam2, y2 = jnp.linalg.eigh(jnp.triu(H), UPLO="U")
print(jnp.linalg.norm(lam1 - lam2)) # 70.34677

lam1, y1 = np.linalg.eigh(H)
lam2, y2 = np.linalg.eigh(np.tril(H))
print(np.linalg.norm(lam1 - lam2)) # 0.0

lam1, y1 = np.linalg.eigh(H, UPLO="U")
lam2, y2 = np.linalg.eigh(np.triu(H), UPLO="U")
print(np.linalg.norm(lam1 - lam2)) # 0.0
```

### What jax/jaxlib version are you using?

jax v0.3.21, jaxlib 0.3.20+cuda11.cudnn805

### Which accelerator(s) are you using?

CPU

### Additional system info

Google colab

**Comment by deasmhumhna** [comment] 2022-10-06 20:32
Never mind, I see the `symmetrize_input=True` parameter now...though it doesn't have a description in the docs and is easily overlooked. Why is the default to symmetrize when BLAS only uses the lower/upper part and it's common practice to only evaluate one of these halves?

**Comment by jakevdp** [comment] 2022-10-06 21:42
Thanks for the report – the issue is also reported in #9473

**Comment by jakevdp** [comment] 2022-10-06 21:48
We should make sure to document this behavior if we're not going to match numpy's

**Comment by mattjj** [comment] 2022-10-07 06:55
[This comment](https://github.com/google/jax/issues/10815#issuecomment-1136491254) about `jax.numpy.linalg.cholesky` pretty much explains it. I agree we should document it, though I think this may then be a duplicate of #12516. We might even want to consider changing the default, though a reason I like the current default is that`grad(lambda x: f(jax.numpy.linalg.eigh(x)))(symmetric_x)` is itself symmetric, while with `symmetrize_input=False` it would not be.

**Comment by jakevdp** [comment] 2023-11-03 18:20
Closing as a duplicate of #9473

**Closed by jakevdp** 2023-11-03 18:20 UTC
Labels: documentation
