### ISSUE TITLE
Partial/vmap crashes when partial overrides first argument.

### ISSUE THREAD

**Issue by Thenerdstation** [google/jax#2010] opened 2020-01-16 01:00 UTC
This code.

```python
import jax
import jax.numpy as jnp

def f(x, y):
  return x + y

g = partial(f, x=1)
jax.vmap(g)(jnp.arange(10))
```

Causes this error.

```
TypeError                                 Traceback (most recent call last)
<ipython-input-18-7a70bb6ecd3d> in <module>()
      6 
      7 g = partial(f, x=1)
----> 8 jax.vmap(g)(jnp.arange(10))

3 frames
jax/api.py in batched_fun(*args)
    692     _check_axis_sizes(in_tree, args_flat, in_axes_flat)
    693     out_flat = batching.batch(flat_fun, args_flat, in_axes_flat,
--> 694                               lambda: _flatten_axes(out_tree(), out_axes))
    695     return tree_unflatten(out_tree(), out_flat)
    696 

jax/interpreters/batching.py in batch(fun, in_vals, in_dims, out_dim_dests)
     38 def batch(fun, in_vals, in_dims, out_dim_dests):
     39   size, = {x.shape[d] for x, d in zip(in_vals, in_dims) if d is not not_mapped}
---> 40   out_vals, out_dims = batch_fun(fun, in_vals, in_dims)
     41   return map(partial(matchaxis, size), out_dims, out_dim_dests(), out_vals)
     42 

jax/interpreters/batching.py in batch_fun(fun, in_vals, in_dims)
     44   with new_master(BatchTrace) as master:
     45     fun, out_dims = batch_subtrace(fun, master, in_dims)
---> 46     out_vals = fun.call_wrapped(*in_vals)
     47     del master
     48   return out_vals, out_dims()

jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    150     gen = None
    151 
--> 152     ans = self.f(*args, **dict(self.params, **kwargs))
    153     del args
    154     while stack:

TypeError: f() got multiple values for argument 'x'
```

Changing the last line to `jax.vmap(g)(y=jnp.arange(10))` (just adding `y=`) causes a different crash.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-004ee0618fce> in <module>()
      6 
      7 g = partial(f, x=1)
----> 8 jax.vmap(g)(y=jnp.arange(10))

TypeError: batched_fun() got an unexpected keyword argument 'y'
```

**Comment by Thenerdstation** [comment] 2020-01-16 01:01
Note, swapping `y` and `x` in the function def works just fine (using `y=` in the vmap call still crashes tho)

```python
import jax
import jax.numpy as jnp

def f(y, x):
  return x + y

g = partial(f, x=1)
jax.vmap(g)(jnp.arange(10))
```

Prints out
```
DeviceArray([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)
```

**Comment by shoyer** [comment] 2020-01-16 23:26
This is feature of how Python's `partial` works, not JAX. You can reproduce the exact same behavior with `g(2)` on top of your example, without using JAX at all:
```python

def f(x, y):
  return x + y

g = partial(f, x=1)
g(2)
```

When you call `g(2)` it gets translated into `f(2, x=1)`, which is ambiguous.

If you want to pass in the second argument, you can use `g = partial(f, 1)`. Both `g(2)` and `g(y=2)` work in that case.

> Changing the last line to `jax.vmap(g)(y=jnp.arange(10))` (just adding `y=`) causes a different crash.

This is a separate issue -- `vmap` doesn't support keyword arguments.

**Comment by Thenerdstation** [comment] 2020-01-16 23:51
Is there a strong blocker as to why vmap can't support keyword args?

**Comment by mattjj** [comment] 2020-01-16 23:53
Not that I can remember. It'd be a little bit annoying given how `in_axes` are specified, but i'm sure doable with enough motivation.

**Comment by mattjj** [comment] 2020-01-17 00:26
Since we already have #912 for vmap keyword arguments, I'm going to close this particular issue.

**Closed by mattjj** 2020-01-17 00:26 UTC
