### ISSUE TITLE
Jaxlib 0.1.52 binary crashes on Mac OS 10.13.16

### ISSUE THREAD

**Issue by C-J-Cundy** [google/jax#3982] opened 2020-08-06 19:59 UTC
Running `import jax` with jaxlib 0.1.52 and jax 0.1.75 on mac osx 13.16 crashes and gives this error:
```
python
Python 3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 17:55:48)
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jax/__init__.py", line 22, in <module>
    from .api import (
  File "/Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jax/api.py", line 38, in <module>
    from . import core
  File "/Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jax/core.py", line 31, in <module>
    from . import dtypes
  File "/Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jax/dtypes.py", line 31, in <module>
    from .lib import xla_client
  File "/Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jax/lib/__init__.py", line 52, in <module>
    from jaxlib import xla_client
  File "/Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jaxlib/xla_client.py", line 39, in <module>
    from . import xla_extension as _xla
ImportError: dlopen(/Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jaxlib/xla_extension.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jaxlib/xla_extension.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/Chris/miniconda3/envs/python3/lib/python3.8/site-packages/jaxlib/xla_extension.so
>>>
```
Jax 0.1.75 and jaxlib 0.1.51 together work fine, so this bug seems like it's been introduced in jaxlib 0.1.51.

**Comment by hawkinsp** [comment] 2020-08-06 20:00
Duplicate of #3867

**Closed by hawkinsp** 2020-08-06 20:00 UTC
