### ISSUE TITLE
Trying to use Objax on Jax-metal

### ISSUE THREAD

**Issue by silvialpz** [google/jax#18674] opened 2023-11-26 01:48 UTC
### Description

I am trying to use objax.nn.Conv2D and I keep getting an XlaRuntimeError :( 
[xlaruntimeerror.txt](https://github.com/google/jax/files/13465695/xlaruntimeerror.txt)
[offendingline.txt](https://github.com/google/jax/files/13465702/offendingline.txt)

### What jax/jaxlib version are you using?

Jax v0.4.11, Jax-metal 0.0.4, jaxlib v0.4.11

### Which accelerator(s) are you using?

GPU

### Additional system info?

Python 3.10.12, MacOS M1

**Comment by shuhand0** [comment] 2024-05-28 17:59
The issue is fixed in jax-metal 0.0.7. Pls reopen the issue if otherwise.

**Closed by shuhand0** 2024-05-28 17:59 UTC
Labels: bug, Apple GPU (Metal) plugin
