### ISSUE TITLE
Apple Silicon: behaviour of array updates

### ISSUE THREAD

**Issue by smao-astro** [google/jax#16326] opened 2023-06-08 23:47 UTC
### Description

I successfully installed jax-metal by meticulously following the instructions step by step. The process involved:
```
# obtain JAX source code
git clone https://github.com/google/jax.git --branch jaxlib-v0.4.10 --single-branch
cd jax
# build jaxlib from source, with capability to load plugin
python build/build.py --bazel_options=--@xla//xla/python:enable_tpu=true
# install jaxlib
python -m pip install dist/*.whl
# install jax
python -m pip install jax

python -m pip install jax-metal
```
Despite not encountering any clear error messages throughout this process, I did observe a certain behavior related to array updates that didn't match the output when the same code was run on a CPU. I have provided a minimal reproduction code snippet below for further examination:
```
import jax
import jax.numpy as jnp


@jax.jit
def f(x, r):
    x = x.at[:, 0].set(x[:, 0] / r)
    return x


x = jnp.array([[1.0, 2.0], [3.0, 4.0]])
fx = f(x, jnp.array([10.0]))
print(fx)
```

Outputs on GPU (Metal)
```
Metal device set to: Apple M1 Max

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

[[0.1 0.3]
 [3.  4. ]]
```

Outputs on CPU
```
[[0.1 2. ]
 [0.3 4. ]]
```

### What jax/jaxlib version are you using?

jax v0.4.11, jaxlib 0.4.10 (built from source)

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9.13, MacOS 13.4

**Comment by hawkinsp** [comment] 2023-06-09 13:23
@shuhand0 @kulinseth

**Comment by martin-marek** [comment] 2023-06-10 15:39
I was able to simplify the example slightly. I think JIT is not required. Instead, it seems to me that Metal indexes the wrong dimension in `.at`.

Metal:
```python
import jax.numpy as jnp
x = jnp.array([[1, 2], [3, 4]])
print(x.at[:, 0].mul(10)) # [[10, 20], [3, 4]]
```
CPU:
```python
import jax.numpy as jnp
x = jnp.array([[1, 2], [3, 4]])
print(x.at[:, 0].mul(10)) # [[10, 2], [30, 4]]
```

**Comment by mattjj** [comment] 2023-06-13 20:04
@shuhand0 @kulinseth what's the status of running the full JAX test suite on Metal?

Could you add a disclaimer to [the jax-metal page](https://developer.apple.com/metal/jax/) that says the plugin doesn't pass the test suite (and perhaps give some additional info about how far along it is)?

I ask because I'm a bit concerned that [users might otherwise be surprised when things don't work](https://twitter.com/thomasahle/status/1668028482390220804), and if they ascribe the bugs to JAX itself (across platforms), rather than a new and understandably incomplete backend, they might get the wrong impression about JAX. That could ultimately be harmful to both JAX and, by extension, jax-metal!

**Comment by kulinseth** [comment] 2023-06-15 19:01
> @shuhand0 @kulinseth what's the status of running the full JAX test suite on Metal?
> 
> Could you add a disclaimer to [the jax-metal page](https://developer.apple.com/metal/jax/) that says the plugin doesn't pass the test suite (and perhaps give some additional info about how far along it is)?
> 
> 
> I ask because I'm a bit concerned that [users might otherwise be surprised when things don't work](https://twitter.com/thomasahle/status/1668028482390220804), and if they ascribe the bugs to JAX itself (across platforms), rather than a new and understandably incomplete backend, they might get the wrong impression about JAX. That could ultimately be harmful to both JAX and, by extension, jax-metal!

Hi @mattjj, 

> EDIT: and maybe also print a warning when the plugin is loaded?

```
Metal device set to: Apple M1 Max

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB
```
This is an indication that Plugin is loaded and we are running on Metal device. Please let us know if you want to enhance this in anyway.

> I ask because I'm a bit concerned that [users might otherwise be surprised when things don't work](https://twitter.com/thomasahle/status/1668028482390220804), and if they ascribe the bugs to JAX itself (across platforms), rather than a new and understandably incomplete backend, they might get the wrong impression about JAX. 

Agreed, we will update our Website to provide a link to the Github Issue tracker where we will track the current JAX metal issues. We are going to discuss with @hawkinsp and @skye to come up with list of tests we want to add to the tracker.

**Comment by jakevdp** [comment] 2023-06-16 04:01
Until you can pass the JAX test suite, I'd recommend something like this:
```
Metal device set to: Apple M1 Max

WARNING: Apple M1 support is experimental and not all JAX functionality is correctly supported!

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB
```

**Comment by smao-astro** [comment] 2023-07-01 17:56
Dear developers,

No rush, but any updates on this issue? Has it been fixed?

Thanks.

**Comment by marcelroed** [comment] 2023-07-01 17:59
@smao-astro Not sure exactly where the issue is, but the [PyPI package Apple released has not been updated](https://pypi.org/project/jax-metal/#history), so I think the answer is no.

**Comment by p-i-** [comment] 2023-09-22 21:36
Can someone nudge Apple? Nearly 4 months now...

**Comment by shuhand0** [comment] 2023-09-27 00:07
The issue was in the conversion from Stablehlo to Metal backend, for the coordinates of the advanced indexing. The fix will be included in the next release.

**Comment by hawkinsp** [comment] 2023-09-27 00:08
Thanks @shuhand0 !

**Comment by gdragotto** [comment] 2023-10-24 00:41
Thanks for the great work. Are there any updates on the bufgix?

**Comment by benjaminvatterj** [comment] 2024-01-01 19:51
Hi, @shuhand0 @kulinseth, are there any updates on this and related bugs in jax-metal? like https://github.com/google/jax/issues/17490, https://github.com/google/jax/issues/18678
I just tested with the new 0.0.5 version and things are still broken.

**Comment by marcelroed** [comment] 2024-01-02 17:51
It seems like Apple wants people to use [MLX](https://github.com/ml-explore/mlx) instead. I would definitely much prefer them to properly support Jax since it already has such a rich ecosystem.

**Comment by shuhand0** [comment] 2024-01-02 19:06
> I just tested with 0.0.5 and this original issue is fixed. The right output is provided. There are still, however, some basic functionalities like cholesky decompositions that are broken.

Thx @benjaminvatterj. Going to close the issue. jax-metal is committed to continually improve and expand support to JAX functionalities.  The unsupported feature of op cholesky is tracked here #16321.

**Closed by shuhand0** 2024-01-02 19:06 UTC
Labels: bug, Apple GPU (Metal) plugin

**Comment by kulinseth** [comment] 2024-01-02 19:24
> It seems like Apple wants people to use [MLX](https://github.com/ml-explore/mlx) instead. I would definitely much prefer them to properly support Jax since it already has such a rich ecosystem.

We are going to continue to support and provide updates in terms of new features, performance improvements and bug fixes for the JAX Metal backend. There is no change in direction from that stand point.
