### ISSUE TITLE
Please provide Windows WHLs for jax and jaxlib

### ISSUE THREAD

**Issue by SoftologyPro** [google/jax#15939] opened 2023-05-09 20:37 UTC
That would help all Windows users immensely.

**Comment by froystig** [comment] 2023-05-10 02:14
This remains out of scope for us currently. You can read more about Windows build/installation in the [installation section of the project readme](https://github.com/google/jax/#installation) and in discussion on issue #5795.

**Closed by froystig** 2023-05-10 02:14 UTC
Labels: enhancement

**Comment by SoftologyPro** [comment] 2023-05-10 03:23
But aren't the jax devs the best ones to be able to supply wheels?  If anything it should be totally "in scope" for you guys?
Building locally for Windows has been a constant problem for myself and others on Windows.

**Comment by froystig** [comment] 2023-05-10 16:34
My reason for closing this is that it is a duplicate of #5795, and it's best to track things in one place. Your feedback is useful, and it might invite more discussion. I'm mainly trying to redirect it to the right place.
