### ISSUE TITLE
Segmentation fault on jax.random.PRNGKey

### ISSUE THREAD

**Issue by andyElking** [google/jax#18033] opened 2023-10-10 10:37 UTC
### Description

When running the following code:
```
import jax
import jax.numpy as jnp

x1 = jnp.zeros((2, 4))
print(x1)
y1 = jnp.zeros((2, 3))
print(y1)
print("tut")

key1 = jax.random.PRNGKey(0).block_until_ready()

print("blub")
print(key1)
```
I get:
```
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
tut

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Oddly, if I remove the lines
```
y1 = jnp.zeros((2, 3))
print(y1)
```
the program works as required (i.e. prints "blub" and the key [0, 0]).

Most other things work as required as long as no key needs to be generated.

### What jax/jaxlib version are you using?

jaxlib 0.4.18+cuda11.cudnn86, Python3.11

### Which accelerator(s) are you using?

GPU

### Additional system info

Ubuntu 22.04.3 LTS

### NVIDIA GPU info

NVIDIA driver metapackage from nvidia-driver-535
GTX 1650 Mobile/Max-Q

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650 ...    Off | 00000000:02:00.0 Off |                  N/A |
| N/A   42C    P0               6W /  35W |      5MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1693      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+

**Comment by hawkinsp** [comment] 2023-10-10 13:13
I can't reproduce this, unfortunately. I'm wondering if it's perhaps related to this being a mobile GPU without much memory available.

Can you try with `XLA_PYTHON_CLIENT_ALLOCATOR=platform`? This will hurt performance, but it might indicate whether this is the problem or not.

**Comment by hawkinsp** [comment] 2023-11-17 21:53
I didn't get a response to my question; closing. Please feel free to comment with more information and I'd be happy to take a look.

**Closed by hawkinsp** 2023-11-17 21:53 UTC
Labels: bug, NVIDIA GPU
