### ISSUE TITLE
Numerical error in jax.vjp computation

### ISSUE THREAD

**Issue by duchao0726** [google/jax#13348] opened 2022-11-22 08:19 UTC
### Description

Hi, 

I am trying to produce the vector-Jacobian products of a linear function but the numerical error can not be fully eliminated. 
The following code can reproduce the numerical error:

```python
import numpy as np
import jax
import jax.numpy as jnp
import torch

np.random.seed(0)
w = np.random.randn(5, 3).astype(np.float32)
x = np.random.randn(3, 2).astype(np.float32)

# JAX vjp results
w_jax = jnp.array(w)
x_jax = jnp.array(x)


def f(z):
    return jnp.matmul(w_jax, z)  # a linear function w.r.t. x, whose Jacobian should be w


value, f_vjp = jax.vjp(f, x_jax)
vjp_by_jax = f_vjp(value)[0]
vjp_manual = jnp.matmul(w_jax.T, value)
print(jnp.mean(jnp.abs(vjp_by_jax - vjp_manual)))  # Should be zero


# Pytorch vjp results
w_torch = torch.from_numpy(w)
x_torch = torch.from_numpy(x)


def g(z):
    return torch.matmul(w_torch, z)  # a linear function w.r.t. x, whose Jacobian should be w


value = g(x_torch)
vjp_by_torch = torch.autograd.functional.vjp(g, x_torch, value)[1]
vjp_manual = torch.matmul(w_torch.T, value)
print(torch.mean(torch.abs(vjp_by_torch - vjp_manual)))  # Should be zero
```

The code prints the difference between the VJP from JAX and the VJP computed manually. The expected output is zero.

Running the code produces the following results, where a severe numerical error is encountered:
> 0.0032820504
> tensor(0.)

A recent issue #11628 suggests that the error is caused by internal float16 conversion and `NVIDIA_TF32_OVERRIDE=0` can avoid it. But with `NVIDIA_TF32_OVERRIDE=0` the above code still produce a (though much smaller) numerical error:
>1.5894572e-07
>tensor(0.)

As a reference, an equivalent implementation in Pytorch can precisely produce zero.

### What jax/jaxlib version are you using?

jax==0.3.24, jaxlib==0.3.24+cuda11.cudnn805

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.8.10; Ubuntu 20.04.3 LTS

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 470.42.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   31C    P0    59W / 400W |  37279MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:4C:00.0 Off |                    0 |
| N/A   33C    P0    60W / 400W |   1653MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:C8:00.0 Off |                    0 |
| N/A   31C    P0    66W / 400W |   1653MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:CB:00.0 Off |                    0 |
| N/A   31C    P0    60W / 400W |   1653MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by apaszke** [comment] 2022-11-23 17:55
1e-7 is pretty much at the limit of precision for `float32`, so I would treat that as working as intended. If you want to find out what JAX is really doing in the VJP, you can wrap it in `jax.make_jaxpr` and print the result. If you inspect your case, you'll see that the VJP gets expanded as `jnp.tensordot(value, w_jax, axes=([0], [0])).T`. That is, a matrix multiply with a lhs transpose fused in, followed by another transposition. I suspect that this equivalent, but slightly different reformulation might cause e.g. cuBLAS to use different kernels and that would explain the numerical differences. When I tried your example on CPU it gave exactly the same results.

I'm closing this, since I don't think this is a bug, but feel free to reopen if you feel otherwise!

**Closed by apaszke** 2022-11-23 17:55 UTC
Labels: bug
