### ISSUE TITLE
The side-effect omnistaging example is broken

### ISSUE THREAD

**Issue by sbodenstein** [google/jax#5206] opened 2020-12-16 12:14 UTC
The example illustrating a possible issue with omnistaging and global state (https://github.com/google/jax/blob/master/design_notes/omnistaging.md#example-1) no longer leads to an escaped tracer:
```
from jax import jit
from jax import random

print('omnistaging enabled', jax.config.omnistaging_enabled)
print(jax.__version__)

key = random.PRNGKey(0)
def init():
  global key
  key, subkey = random.split(key)
  print(key)
  return random.normal(subkey, ())
print(init())  # -1.2515389
print(init())  # -0.58665067
init = jit(init)
print(init())  # 0.48648298
print(init())  # 0.48648298  !!
print(key) # Traced<ShapedArray(uint32[2])>with<DynamicJaxprTrace(level=0/1)>
print(random.normal(key, ()))

# omnistaging enabled True
# 0.2.7
# [4146024105  967050713]
# -1.2515285
# [2384771982 3928867769]
# -0.5866531
# [3382499631 3878610767]
# 0.48647928
# 0.48647928
# [3382499631 3878610767]
# Buffer(-0.4876217, dtype=float32)
```
Has this omnistaging behaviour been changed?

**Comment by jakevdp** [comment] 2020-12-16 18:22
Thanks for flagging this - I tried back as far as jax 0.2.0 when omnistaging was first turned on by default, and could not reproduce the expected escaped tracer error. I'm going to assign to @mattjj because he might know what's going on.

**Comment by mattjj** [comment] 2020-12-16 18:38
Hrm, curious. This repros for me:

```python
import jax
from jax import jit
from jax import random

key = random.PRNGKey(0)
def init():
  global key
  key, subkey = random.split(key)
  return random.normal(subkey, ())
init = jit(init)
print(init())  # -1.2515389
print(init())  # -1.2515389
print(key) # Traced<ShapedArray(uint32[2])>with<DynamicJaxprTrace(level=0/1)>
```

If we put a single `print(init())` before jitting, then we also get the escaped tracer. But if we put two, we don't! Very curious.

I think the reason why @jakevdp wasn't able to reproduce is that he didn't rewind jaxlib as well as jax. The funny actor here is the C++ jit. If we run the original version with `JAX_CPP_JIT=0` then we get the behavior as expected:

```
$ cat 5206.py
import jax
from jax import jit
from jax import random

key = random.PRNGKey(0)
def init():
  global key
  key, subkey = random.split(key)
  return random.normal(subkey, ())
print(init())
print(init())
init = jit(init)
print(init())  # -1.2515389
print(init())  # -1.2515389
print(key) # Traced<ShapedArray(uint32[2])>with<DynamicJaxprTrace(level=0/1)>

$ python 5206.py
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
-1.2515389
-0.58665067
0.48648298
0.48648298
[3382499631 3878610767]

$ env JAX_CPP_JIT=0 python 5206.py
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
-1.2515389
-0.58665067
0.48648298
0.48648298
Traced<ShapedArray(uint32[2])>with<DynamicJaxprTrace(level=0/1)>
```

I was tipped off because in the last line of the OP we see a `Buffer` printed out, and that smelled like a C++ issue.

I don't understand this in full yet though. cc @jblespiau in case he has ideas.

**Comment by mattjj** [comment] 2020-12-16 18:51
Just to underscore, I really don't know what's going on here, and I don't mean to imply that any particular code has a bug. Setting `JAX_CPP_JIT` affects the behavior, but I don't actually know if there's an issue in the C++ code, or related Python code, or if actually this is somehow intended behavior as a consequence of some of our caching decisions related to the C++ jit behavior.

**Comment by jblespiau** [comment] 2020-12-16 19:27
```
key = random.PRNGKey(0)
def init(a):
  global key
  import pdb; pdb.set_trace()
  key, subkey = random.split(key)
  return random.normal(subkey, ())
print(init(1))
print(init(2))
init = jit(init)
print(init(3))
print(init(4))
print(key)
```

What happens?

print(init()) << This compiles `random.split`. at this moment, random.split is provided with a tracer, it compiles, run the execution and return concrete keys.
print(key) --> prints  [4146024105  967050713]
print(init()) << Here, we hit the cache for these, it returns a real value, as expected
print(key) --> [2384771982 3928867769]
init = jit(init)
print(init()) <-- This triggers the compilation of `init`. `ramdom.split` is provided with a concrete key so, it will return a concrete type
print(key) >> [3382499631 3878610767]
print(init()) <-- No longer executing Python anyway. key won't change.
print(key) >> [3382499631 3878610767]


It you want to get an abstract type, you need to store it when there is one (e.g. if you add an argument "a", and you save it, it will work:

```
global_v = None
def f(a):
  global global_v
  global_v = a
  return a + 1

jit(f)(1)
print(global_v)
```

So for the C++, I can explain.

However, for the Python I cannot.

When we start tracing, do we set a global variable somewhere, to tell to compiled function they should trace?

i.e. when we jit `init`, and we get into `random.split`, it it tracing, even though we passed concrete types.

**Comment by mattjj** [comment] 2020-12-16 20:09
Ah yes, this is the nature of omnistaging, namely that with omnistaging things like `jit` change the behavior of operations based on global context, not just on their input arguments. That's the goal: not to rely solely on data dependence, so that we can stage out more, like constant creation and RNG operations. The cost is that JAX's tracing behavior itself isn't purely functional, in that that whether a function produces a tracer or not cannot be decided based on whether the inputs are traced.

We shouldn't get a cache hit on the `print(init())` line after applying `jit`. The reason is that it results in a worse program being staged out, at least if we imagine the random constant being arbitrarily large: there's a potentially-large random value staged out into the jitted version of `init`, as opposed to the intended behavior of staging out the PRNG generation itself (based on the small key as a constant).

But I see now why we are getting that behavior: it's because, by design, with the C++ jit we've moved the cache to the api.py level, whereas with the Python version we have it in the jit impl (i.e. the xla_call impl). In the Python version, when running the jitted version of `init`, we never hit the impl rule for `random.split` at all, so there's no risk of hitting the cache. That is, the Python version is already sensitive to the necessary global context.

I think we need to make the C++ jit sensitive to the global context. Otherwise, we're not getting the full benefits of omnistaging.

**Comment by mattjj** [comment] 2020-12-16 20:17
(Thanks for catching this and letting us know, @sbodenstein ! Otherwise the ill effects are subtle, like increased memory fragmentation.)

**Comment by Amirnateghi1** [comment] 2020-12-19 09:50
> مثالی که یک مسئله احتمالی با وضعیت جهانی و جهانی را نشان می دهد ( https://github.com/google/jax/blob/master/design_notes/omnistaging.md#example-1 ) دیگر منجر به ردیابی فرار نمی شود:
> 
> ```
> from jax import jit
> from jax import random
> 
> print('omnistaging enabled', jax.config.omnistaging_enabled)
> print(jax.__version__)
> 
> key = random.PRNGKey(0)
> def init():
>   global key
>   key, subkey = random.split(key)
>   print(key)
>   return random.normal(subkey, ())
> print(init())  # -1.2515389
> print(init())  # -0.58665067
> init = jit(init)
> print(init())  # 0.48648298
> print(init())  # 0.48648298  !!
> print(key) # Traced<ShapedArray(uint32[2])>with<DynamicJaxprTrace(level=0/1)>
> print(random.normal(key, ()))
> 
> # omnistaging enabled True
> # 0.2.7
> # [4146024105  967050713]
> # -1.2515285
> # [2384771982 3928867769]
> # -0.5866531
> # [3382499631 3878610767]
> # 0.48647928
> # 0.48647928
> # [3382499631 3878610767]
> # Buffer(-0.4876217, dtype=float32)
> ```
> 
> آیا این رفتار همه کاره تغییر کرده است؟

Ok

**Closed** 2021-01-08 04:50 UTC
Labels: bug
