### ISSUE TITLE
BUG: Jitted function produces wrong results

### ISSUE THREAD

**Issue by andriusstank** [google/jax#11979] opened 2022-08-18 13:07 UTC
### Description

Code to reproduce the issue:

```python
import jax
import jax.random
import jax.numpy as jnp

def myfun(x, key):
    n = 20
    zeros = jnp.full((n,), 0)
    ones = jnp.full((n,), 1)
    maxval = x[ones] - 1
    return jax.random.randint(key, (n,), zeros, maxval)

key = jax.random.PRNGKey(1)
x = jnp.array([0, 2])
y1 = myfun(x, key)
y2 = jax.jit(myfun)(x, key)
print(y1)
print(y2)
```

Output:

```
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 1 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1]
```

Here `maxval` is an array full of ones, hence `randint` should produce zeros only. This is the case with non-jitted version of `myfun`, while jitted `myfun` incorrectly produces a mixture of ones and zeros.

### What jax/jaxlib version are you using?

jax 0.3.16, jaxlib 0.3.15

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment] 2022-08-18 14:38
Thanks for the report – I believe this is a duplicate of #11510; unfortunately the XLA team has not yet arrived on a fix.

**Comment by andriusstank** [comment] 2022-08-18 15:17
Right, looks pretty much the same. Sorry for the duplicate.

**Comment by hawkinsp** [comment] 2022-08-19 20:53
This is now fixed when `jaxlib` is built from XLA head:

```
In [11]: import jax
    ...: import jax.random
    ...: import jax.numpy as jnp
    ...:
    ...: def myfun(x, key):
    ...:     n = 20
    ...:     zeros = jnp.full((n,), 0)
    ...:     ones = jnp.full((n,), 1)
    ...:     maxval = x[ones] - 1
    ...:     return jax.random.randint(key, (n,), zeros, maxval)
    ...:
    ...: key = jax.random.PRNGKey(1)
    ...: x = jnp.array([0, 2])
    ...: y1 = myfun(x, key)
    ...: y2 = jax.jit(myfun)(x, key)
    ...: print(y1)
    ...: print(y2)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

**Closed by hawkinsp** 2022-08-19 20:53 UTC
Labels: bug, duplicate
