### ISSUE TITLE
Conda installations

### ISSUE THREAD

**Issue by alexbw** [google/jax#66] opened 2018-12-11 15:59 UTC
Conda is a great package distribution system, especially for those with binary dependencies. It'd be good to have some ourselves.

**Comment by hawkinsp** [comment] 2020-12-02 16:20
Anaconda and miniconda do not permit commercial users, so we as a team cannot work on this. But we welcome community contributions!

**Comment by hawkinsp** [comment] 2020-12-02 16:21
Closing as a duplicate of #189

**Closed by hawkinsp** 2020-12-02 16:21 UTC
Labels: build, contributions welcome
