### ISSUE TITLE
"Very slow compile?  If you want to file a bug, run..."

### ISSUE THREAD

**Issue by PgLoLo** [google/jax#8229] opened 2021-10-15 06:48 UTC
I started to experience issue [7797](https://github.com/google/jax/issues/7797) randomly in the same code while rerunning it with different seeds.

Behaviour is very annoying: at some point in code, during jit-compiling, the code just deadlocks itself with the message:
```
2021-10-15 02:51:03.767536: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:55]
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
Compiling module jit__threefry_split__3.20
********************************
```
Currently, I do experiments in juypter notebook, during this deadlock I can not stop the execution of the jupyter cell, the only way out is to restart the jupyter kernel.

In many cases I feel that it somehow connected with `jax.random` module and especially `jax.random.split`, but that can be only wrong impression.

This ill-posed behaviour consistently reproduces on the same machine with different cuda versions. In my personal case it reproduces on my several workstations (with different nvidia drivers). But find it hard to reproduce on other systems: the same code does not do the trick so you should just randomly encounter it.

I don't know why issues are not overwhelmed with this problem: literally just heavy using of flax + jax would eventually and steadily introduce you to this behaviour.

Is there any debug mode in which I can run my code to collect more information about the bug? As far as I can tell it only happens under GPU execution, thus maybe it is heavily related to some bugs in NVIDIA cuda/driver/smth else?

**Comment by nouiz** [comment] 2022-09-27 13:25
We can't reproduce this, so I'll close this issue.
If you are able to give us a reproduction, reopen it.

**Closed by nouiz** 2022-09-27 13:25 UTC
Labels: bug, P2 (eventual), needs info, NVIDIA GPU
